using CodeStage.AntiCheat.ObscuredTypes;
using UnityEngine;

namespace EveEngine
{
	public static class ANEFBDIDHMM
	{
		public static void CAHACMKBJMI(this KCIGFAHFHCH OGJFDNEEDCP, out Vector2 ICENKPDOHBK)
		{
			ICENKPDOHBK.x = OGJFDNEEDCP.GCFOKBADLFB();
			ICENKPDOHBK.y = OGJFDNEEDCP.GCFOKBADLFB();
		}

		public static void CAHACMKBJMI(this KCIGFAHFHCH OGJFDNEEDCP, out Vector3 ICENKPDOHBK)
		{
			ICENKPDOHBK.x = OGJFDNEEDCP.GCFOKBADLFB();
			ICENKPDOHBK.y = OGJFDNEEDCP.GCFOKBADLFB();
			ICENKPDOHBK.z = OGJFDNEEDCP.GCFOKBADLFB();
		}

		public static void CAHACMKBJMI(this KCIGFAHFHCH OGJFDNEEDCP, out Quaternion ICENKPDOHBK)
		{
			ICENKPDOHBK.x = OGJFDNEEDCP.GCFOKBADLFB();
			ICENKPDOHBK.y = OGJFDNEEDCP.GCFOKBADLFB();
			ICENKPDOHBK.z = OGJFDNEEDCP.GCFOKBADLFB();
			ICENKPDOHBK.w = OGJFDNEEDCP.GCFOKBADLFB();
		}

		public static void CAHACMKBJMI(this KCIGFAHFHCH OGJFDNEEDCP, out ObscuredBool ICENKPDOHBK)
		{
			ICENKPDOHBK = OGJFDNEEDCP.JCGKFEPEJPO();
		}

		public static void CAHACMKBJMI(this KCIGFAHFHCH OGJFDNEEDCP, out ObscuredByte ICENKPDOHBK)
		{
			ICENKPDOHBK = OGJFDNEEDCP.KFAGPDGHEBK();
		}

		public static void CAHACMKBJMI(this KCIGFAHFHCH OGJFDNEEDCP, out ObscuredUShort ICENKPDOHBK)
		{
			ICENKPDOHBK = OGJFDNEEDCP.AJPFAAFLHEB();
		}

		public static void CAHACMKBJMI(this KCIGFAHFHCH OGJFDNEEDCP, out ObscuredInt ICENKPDOHBK)
		{
			ICENKPDOHBK = OGJFDNEEDCP.PNBKOPGIHDI();
		}

		public static void CAHACMKBJMI(this KCIGFAHFHCH OGJFDNEEDCP, out ObscuredUInt ICENKPDOHBK)
		{
			ICENKPDOHBK = OGJFDNEEDCP.BMKOKHGAHEC();
		}

		public static void CAHACMKBJMI(this KCIGFAHFHCH OGJFDNEEDCP, out ObscuredFloat ICENKPDOHBK)
		{
			ICENKPDOHBK = OGJFDNEEDCP.GCFOKBADLFB();
		}

		public static void CAHACMKBJMI(this KCIGFAHFHCH OGJFDNEEDCP, out ObscuredVector2 ICENKPDOHBK)
		{
			ICENKPDOHBK = OGJFDNEEDCP.HAFNCLBFCLK();
		}

		public static void CAHACMKBJMI(this KCIGFAHFHCH OGJFDNEEDCP, out ObscuredVector3 ICENKPDOHBK)
		{
			ICENKPDOHBK = OGJFDNEEDCP.MCGFBNKNFJG();
		}

		public static Vector2 HAFNCLBFCLK(this KCIGFAHFHCH OGJFDNEEDCP)
		{
			Vector2 zero = Vector2.zero;
			zero.x = OGJFDNEEDCP.GCFOKBADLFB();
			zero.y = OGJFDNEEDCP.GCFOKBADLFB();
			return zero;
		}

		public static Vector3 MCGFBNKNFJG(this KCIGFAHFHCH OGJFDNEEDCP)
		{
			Vector3 zero = Vector3.zero;
			zero.x = OGJFDNEEDCP.GCFOKBADLFB();
			zero.y = OGJFDNEEDCP.GCFOKBADLFB();
			zero.z = OGJFDNEEDCP.GCFOKBADLFB();
			return zero;
		}

		public static Quaternion HLOCKIKBGOM(this KCIGFAHFHCH OGJFDNEEDCP)
		{
			Quaternion identity = Quaternion.identity;
			identity.x = OGJFDNEEDCP.GCFOKBADLFB();
			identity.y = OGJFDNEEDCP.GCFOKBADLFB();
			identity.z = OGJFDNEEDCP.GCFOKBADLFB();
			identity.w = OGJFDNEEDCP.GCFOKBADLFB();
			return identity;
		}

		public static void GBMJNFOEACC(this KCIGFAHFHCH OGJFDNEEDCP, Vector2 ICENKPDOHBK)
		{
			OGJFDNEEDCP.GBMJNFOEACC(ICENKPDOHBK.x);
			OGJFDNEEDCP.GBMJNFOEACC(ICENKPDOHBK.y);
		}

		public static void GBMJNFOEACC(this KCIGFAHFHCH OGJFDNEEDCP, Vector3 ICENKPDOHBK)
		{
			OGJFDNEEDCP.GBMJNFOEACC(ICENKPDOHBK.x);
			OGJFDNEEDCP.GBMJNFOEACC(ICENKPDOHBK.y);
			OGJFDNEEDCP.GBMJNFOEACC(ICENKPDOHBK.z);
		}

		public static void GBMJNFOEACC(this KCIGFAHFHCH OGJFDNEEDCP, Quaternion ICENKPDOHBK)
		{
			OGJFDNEEDCP.GBMJNFOEACC(ICENKPDOHBK.x);
			OGJFDNEEDCP.GBMJNFOEACC(ICENKPDOHBK.y);
			OGJFDNEEDCP.GBMJNFOEACC(ICENKPDOHBK.z);
			OGJFDNEEDCP.GBMJNFOEACC(ICENKPDOHBK.w);
		}

		public static void GBMJNFOEACC(this KCIGFAHFHCH OGJFDNEEDCP, ObscuredBool ICENKPDOHBK)
		{
			OGJFDNEEDCP.GBMJNFOEACC(ICENKPDOHBK);
		}

		public static void GBMJNFOEACC(this KCIGFAHFHCH OGJFDNEEDCP, ObscuredByte ICENKPDOHBK)
		{
			OGJFDNEEDCP.GBMJNFOEACC(ICENKPDOHBK);
		}

		public static void GBMJNFOEACC(this KCIGFAHFHCH OGJFDNEEDCP, ObscuredUShort ICENKPDOHBK)
		{
			OGJFDNEEDCP.GBMJNFOEACC(ICENKPDOHBK);
		}

		public static void GBMJNFOEACC(this KCIGFAHFHCH OGJFDNEEDCP, ObscuredInt ICENKPDOHBK)
		{
			OGJFDNEEDCP.GBMJNFOEACC(ICENKPDOHBK);
		}

		public static void GBMJNFOEACC(this KCIGFAHFHCH OGJFDNEEDCP, ObscuredUInt ICENKPDOHBK)
		{
			OGJFDNEEDCP.GBMJNFOEACC(ICENKPDOHBK);
		}

		public static void GBMJNFOEACC(this KCIGFAHFHCH OGJFDNEEDCP, ObscuredFloat ICENKPDOHBK)
		{
			OGJFDNEEDCP.GBMJNFOEACC(ICENKPDOHBK);
		}

		public static void GBMJNFOEACC(this KCIGFAHFHCH OGJFDNEEDCP, ObscuredVector2 ICENKPDOHBK)
		{
			OGJFDNEEDCP.GBMJNFOEACC((Vector2)ICENKPDOHBK);
		}

		public static void GBMJNFOEACC(this KCIGFAHFHCH OGJFDNEEDCP, ObscuredVector3 ICENKPDOHBK)
		{
			OGJFDNEEDCP.GBMJNFOEACC((Vector3)ICENKPDOHBK);
		}
	}
}
