namespace CommunityServer
{
	public enum HGBGJMIFCEP : byte
	{
		Success = 0,
		InvalidProtocolVersion = 1,
		InvalidUserID = 2,
		InvalidNickname = 3,
		AlreadyConnect = 4,
		InvalidCharacter = 5,
		InvalidAdventure = 6,
		InvalidMission = 7,
		InvalidGuild = 8,
		NotEnoughLevel = 9,
		NotEnoughCoin = 10,
		NotEnoughCash = 11,
		NotEnoughHeart = 12,
		NotEnoughFood = 13,
		NotEnoughSkillPoint = 14,
		MaxLevel = 15,
		MaxCount = 16,
		AlreadyEnterRoom = 17,
		NotEnoughItem = 18,
		AlreadyEquipItem = 19,
		AlreadyExistHero = 20,
		AlreadyClear = 21,
		AlreadyResultChat = 22,
		AlreadyExistGuild = 23,
		BlockUser = 24,
		MaxTodayRecommendCount = 25,
		MaxTotalRecommendCount = 26,
		AlreadyRecommendUser = 27,
		InvalidCoupon = 28,
		ExpireCoupon = 29,
		AlreadyUseCoupon = 30,
		AlreadyConnectAccount = 31,
		CantUseToday = 32,
		TooManyEscape = 33,
		AlreadyRequestFriend = 34,
		AlreadyFriend = 35,
		AlreadyRequestGuild = 36,
		AlreadyJoinGuild = 37,
		NoPermission = 38,
		CantGuildMaster = 39,
		CantRemoveGuildOnlyOne = 40,
		DisconnectUser = 41,
		Unknown = 42
	}
}
