using EveEngine;
using MongoDB.Bson.Serialization.Attributes;

namespace CommunityServer
{
	[JBFHBIFPIBM]
	public class PBOOPPEPAIK : IBHMLPMENFJ
	{
		public uint PNJKANMGGBA;

		public uint FJECKCCPAKE;

		public long GLEPPIMMELK;

		public uint HCECKOLDNDF;

		public uint BCBKMKDPHHF;

		public uint AEIFABFFEBH;

		public uint OFLEBCIMPMD;

		public int MEKAGPLGMCM;

		public bool DCAICFODLPH;

		public uint CFEIDKKONGL;

		public uint LPCFHCENKAF;

		public ulong AFEPOHNJEIB;

		public override void JCOLMPJMMEB(PJEMPFEIOAK EFDLFNPAKGO)
		{
			base.JCOLMPJMMEB(EFDLFNPAKGO);
			PNJKANMGGBA = EFDLFNPAKGO.BMKOKHGAHEC();
			FJECKCCPAKE = EFDLFNPAKGO.BMKOKHGAHEC();
			GLEPPIMMELK = EFDLFNPAKGO.GAGNPBAMJLE();
			MEKAGPLGMCM = EFDLFNPAKGO.PNBKOPGIHDI();
			OFLEBCIMPMD = EFDLFNPAKGO.BMKOKHGAHEC();
			DCAICFODLPH = EFDLFNPAKGO.JCGKFEPEJPO();
			HCECKOLDNDF = EFDLFNPAKGO.BMKOKHGAHEC();
			BCBKMKDPHHF = EFDLFNPAKGO.BMKOKHGAHEC();
		}

		public virtual void EIMLGHFBJAB(CMNIABEFLBJ EFDLFNPAKGO)
		{
			base.CFGEKKHOKKE(EFDLFNPAKGO);
			EFDLFNPAKGO.GBMJNFOEACC(PNJKANMGGBA);
			EFDLFNPAKGO.BHAFGILIOCN(FJECKCCPAKE);
			EFDLFNPAKGO.GBMJNFOEACC(GLEPPIMMELK);
			EFDLFNPAKGO.GBMJNFOEACC(MEKAGPLGMCM);
			EFDLFNPAKGO.BHAFGILIOCN(OFLEBCIMPMD);
			EFDLFNPAKGO.KHEGDBFKNMB(DCAICFODLPH);
			EFDLFNPAKGO.BHAFGILIOCN(HCECKOLDNDF);
			EFDLFNPAKGO.GBMJNFOEACC(BCBKMKDPHHF);
		}

		public virtual void NNELCJABFPA(CMNIABEFLBJ EFDLFNPAKGO)
		{
			base.CFGEKKHOKKE(EFDLFNPAKGO);
			EFDLFNPAKGO.GBMJNFOEACC(PNJKANMGGBA);
			EFDLFNPAKGO.GBMJNFOEACC(FJECKCCPAKE);
			EFDLFNPAKGO.GBMJNFOEACC(GLEPPIMMELK);
			EFDLFNPAKGO.GBMJNFOEACC(MEKAGPLGMCM);
			EFDLFNPAKGO.GBMJNFOEACC(OFLEBCIMPMD);
			EFDLFNPAKGO.GBMJNFOEACC(DCAICFODLPH);
			EFDLFNPAKGO.GBMJNFOEACC(HCECKOLDNDF);
			EFDLFNPAKGO.BHAFGILIOCN(BCBKMKDPHHF);
		}

		public virtual void COGEJPHIAKE()
		{
			base.LDNEFFHJNPL();
			PNJKANMGGBA = 1u;
			FJECKCCPAKE = 0u;
			GLEPPIMMELK = 1L;
			HMHEDBOAADF = 1;
			OFLEBCIMPMD = 1u;
			CFEIDKKONGL = 1u;
		}

		public virtual void INOKJCKAONB()
		{
			base.LDNEFFHJNPL();
			PNJKANMGGBA = 0u;
			FJECKCCPAKE = 1u;
			GLEPPIMMELK = 1L;
			HMHEDBOAADF = 1;
			OFLEBCIMPMD = 0u;
			CFEIDKKONGL = 1u;
		}

		public virtual void APBPBAPJJNL(CMNIABEFLBJ EFDLFNPAKGO)
		{
			base.CFGEKKHOKKE(EFDLFNPAKGO);
			EFDLFNPAKGO.BHAFGILIOCN(PNJKANMGGBA);
			EFDLFNPAKGO.GBMJNFOEACC(FJECKCCPAKE);
			EFDLFNPAKGO.GBMJNFOEACC(GLEPPIMMELK);
			EFDLFNPAKGO.GBMJNFOEACC(MEKAGPLGMCM);
			EFDLFNPAKGO.GBMJNFOEACC(OFLEBCIMPMD);
			EFDLFNPAKGO.KHEGDBFKNMB(DCAICFODLPH);
			EFDLFNPAKGO.BHAFGILIOCN(HCECKOLDNDF);
			EFDLFNPAKGO.BHAFGILIOCN(BCBKMKDPHHF);
		}

		public virtual void GAPECFHNEJC(PJEMPFEIOAK EFDLFNPAKGO)
		{
			base.JCOLMPJMMEB(EFDLFNPAKGO);
			PNJKANMGGBA = EFDLFNPAKGO.BMKOKHGAHEC();
			FJECKCCPAKE = EFDLFNPAKGO.BMKOKHGAHEC();
			GLEPPIMMELK = EFDLFNPAKGO.GAGNPBAMJLE();
			MEKAGPLGMCM = EFDLFNPAKGO.PNBKOPGIHDI();
			OFLEBCIMPMD = EFDLFNPAKGO.BMKOKHGAHEC();
			DCAICFODLPH = EFDLFNPAKGO.JCGKFEPEJPO();
			HCECKOLDNDF = EFDLFNPAKGO.BMKOKHGAHEC();
			BCBKMKDPHHF = EFDLFNPAKGO.BMKOKHGAHEC();
		}

		public virtual void NNBHCBPELPG()
		{
			base.LDNEFFHJNPL();
			PNJKANMGGBA = 0u;
			FJECKCCPAKE = 0u;
			GLEPPIMMELK = 0L;
			HMHEDBOAADF = 0;
			OFLEBCIMPMD = 1u;
			CFEIDKKONGL = 0u;
		}

		public virtual void OFDLEJFADCN()
		{
			base.LDNEFFHJNPL();
			PNJKANMGGBA = 0u;
			FJECKCCPAKE = 0u;
			GLEPPIMMELK = 1L;
			HMHEDBOAADF = 0;
			OFLEBCIMPMD = 0u;
			CFEIDKKONGL = 1u;
		}

		public virtual void BCGICPOKOHO()
		{
			base.LDNEFFHJNPL();
			PNJKANMGGBA = 0u;
			FJECKCCPAKE = 1u;
			GLEPPIMMELK = 1L;
			HMHEDBOAADF = 0;
			OFLEBCIMPMD = 0u;
			CFEIDKKONGL = 1u;
		}

		public virtual void MEKNGDKEKKO(PJEMPFEIOAK EFDLFNPAKGO)
		{
			base.JCOLMPJMMEB(EFDLFNPAKGO);
			PNJKANMGGBA = EFDLFNPAKGO.BMKOKHGAHEC();
			FJECKCCPAKE = EFDLFNPAKGO.BMKOKHGAHEC();
			GLEPPIMMELK = EFDLFNPAKGO.GAGNPBAMJLE();
			MEKAGPLGMCM = EFDLFNPAKGO.PNBKOPGIHDI();
			OFLEBCIMPMD = EFDLFNPAKGO.BMKOKHGAHEC();
			DCAICFODLPH = EFDLFNPAKGO.JCGKFEPEJPO();
			HCECKOLDNDF = EFDLFNPAKGO.BMKOKHGAHEC();
			BCBKMKDPHHF = EFDLFNPAKGO.BMKOKHGAHEC();
		}

		public override void LDNEFFHJNPL()
		{
			base.LDNEFFHJNPL();
			PNJKANMGGBA = 0u;
			FJECKCCPAKE = 0u;
			GLEPPIMMELK = 0L;
			HMHEDBOAADF = 0;
			OFLEBCIMPMD = 0u;
			CFEIDKKONGL = 0u;
		}

		public virtual void CPPAAILEDJO(CMNIABEFLBJ EFDLFNPAKGO)
		{
			base.CFGEKKHOKKE(EFDLFNPAKGO);
			EFDLFNPAKGO.BHAFGILIOCN(PNJKANMGGBA);
			EFDLFNPAKGO.GBMJNFOEACC(FJECKCCPAKE);
			EFDLFNPAKGO.GBMJNFOEACC(GLEPPIMMELK);
			EFDLFNPAKGO.GBMJNFOEACC(MEKAGPLGMCM);
			EFDLFNPAKGO.GBMJNFOEACC(OFLEBCIMPMD);
			EFDLFNPAKGO.GBMJNFOEACC(DCAICFODLPH);
			EFDLFNPAKGO.GBMJNFOEACC(HCECKOLDNDF);
			EFDLFNPAKGO.BHAFGILIOCN(BCBKMKDPHHF);
		}

		public virtual void JANBGPFAFJF(CMNIABEFLBJ EFDLFNPAKGO)
		{
			base.CFGEKKHOKKE(EFDLFNPAKGO);
			EFDLFNPAKGO.GBMJNFOEACC(PNJKANMGGBA);
			EFDLFNPAKGO.GBMJNFOEACC(FJECKCCPAKE);
			EFDLFNPAKGO.GBMJNFOEACC(GLEPPIMMELK);
			EFDLFNPAKGO.GBMJNFOEACC(MEKAGPLGMCM);
			EFDLFNPAKGO.GBMJNFOEACC(OFLEBCIMPMD);
			EFDLFNPAKGO.GBMJNFOEACC(DCAICFODLPH);
			EFDLFNPAKGO.GBMJNFOEACC(HCECKOLDNDF);
			EFDLFNPAKGO.GBMJNFOEACC(BCBKMKDPHHF);
		}

		public override void CFGEKKHOKKE(CMNIABEFLBJ EFDLFNPAKGO)
		{
			base.CFGEKKHOKKE(EFDLFNPAKGO);
			EFDLFNPAKGO.GBMJNFOEACC(PNJKANMGGBA);
			EFDLFNPAKGO.GBMJNFOEACC(FJECKCCPAKE);
			EFDLFNPAKGO.GBMJNFOEACC(GLEPPIMMELK);
			EFDLFNPAKGO.GBMJNFOEACC(MEKAGPLGMCM);
			EFDLFNPAKGO.GBMJNFOEACC(OFLEBCIMPMD);
			EFDLFNPAKGO.GBMJNFOEACC(DCAICFODLPH);
			EFDLFNPAKGO.GBMJNFOEACC(HCECKOLDNDF);
			EFDLFNPAKGO.GBMJNFOEACC(BCBKMKDPHHF);
		}

		public virtual void OENLLEKFJHM()
		{
			base.LDNEFFHJNPL();
			PNJKANMGGBA = 0u;
			FJECKCCPAKE = 0u;
			GLEPPIMMELK = 1L;
			HMHEDBOAADF = 1;
			OFLEBCIMPMD = 1u;
			CFEIDKKONGL = 1u;
		}

		public virtual void GANHNFADIJO(PJEMPFEIOAK EFDLFNPAKGO)
		{
			base.JCOLMPJMMEB(EFDLFNPAKGO);
			PNJKANMGGBA = EFDLFNPAKGO.BMKOKHGAHEC();
			FJECKCCPAKE = EFDLFNPAKGO.BMKOKHGAHEC();
			GLEPPIMMELK = EFDLFNPAKGO.GAGNPBAMJLE();
			MEKAGPLGMCM = EFDLFNPAKGO.PNBKOPGIHDI();
			OFLEBCIMPMD = EFDLFNPAKGO.BMKOKHGAHEC();
			DCAICFODLPH = EFDLFNPAKGO.JCGKFEPEJPO();
			HCECKOLDNDF = EFDLFNPAKGO.BMKOKHGAHEC();
			BCBKMKDPHHF = EFDLFNPAKGO.BMKOKHGAHEC();
		}
	}
}
