using System.Collections.Generic;
using EveEngine;

namespace GameServer
{
	public class AAIGMCHPHLA : EOPOBHFNFPA
	{
		protected List<LKDLDEPEAHO> AGPKODDPAOL;

		public LKDLDEPEAHO JDBMANOLMDE(LKDLDEPEAHO.ACPICCBBPHF FBAGNJILEGD)
		{
			if ((int)FBAGNJILEGD < 0 || (int)FBAGNJILEGD >= AGPKODDPAOL.Count)
			{
				return null;
			}
			return AGPKODDPAOL[(int)FBAGNJILEGD];
		}

		public AAIGMCHPHLA()
		{
			AGPKODDPAOL = new List<LKDLDEPEAHO>(30);
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Dog, "Dog", 100, 1f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.SwordCat, "Sword Cat", 200, 1.2f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.BombMan, "Bomb Man", 150, 1f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.NinjaCat, "Ninja Cat", 400, 3f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Observer, "Observer", 500, 10f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Butterfly, "Butterfly", 600, 3f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.FireCat, "Fire Cat", 700, 3f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.FishCat, "Fish Cat", 1500, 10f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Healer, "Healer", 800, 10f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Lamb, "Lamb", 1200, 6f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.LongCat, "Long Cat", 1500, 8f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Squirrel, "Squirrel", 2000, 10f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.UFO, "UFO", 800, 4f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Firebat, "Firebat", 400, 4f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.BlackCat, "BlackCat", 600, 4f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.HeadShip, "HeadShip", 2500, 15f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Reserved1, "Reserved", 0, 1f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Reserved2, "Reserved", 0, 1f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Boss, "Boss", 0, 0f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Reserved10, "Reserved", 0, 0f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Reserved11, "Reserved", 0, 0f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Reserved12, "Reserved", 0, 0f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Reserved13, "Reserved", 0, 0f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Reserved14, "Reserved", 0, 0f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Sword, "Sword", 0, 0f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Missile, "Missile", 0, 0f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.FireMissile, "FireMissile", 0, 0f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.Nuclear, "Nuclear", 0, 0f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.BlackMissile, "BlackMissile", 0, 0f));
			AGPKODDPAOL.Add(new LKDLDEPEAHO(LKDLDEPEAHO.ACPICCBBPHF.DropBomb, "DropBomb", 0, 0f));
		}

		public void HNGINOBLION(CMNIABEFLBJ EFDLFNPAKGO)
		{
			foreach (LKDLDEPEAHO item in AGPKODDPAOL)
			{
				item.CFGEKKHOKKE(EFDLFNPAKGO);
			}
		}

		public void CKBCOALJMJB(PJEMPFEIOAK EFDLFNPAKGO)
		{
			foreach (LKDLDEPEAHO item in AGPKODDPAOL)
			{
				item.MEKNGDKEKKO(EFDLFNPAKGO);
			}
		}

		public void JHDBNOHACNB(CMNIABEFLBJ EFDLFNPAKGO)
		{
			foreach (LKDLDEPEAHO item in AGPKODDPAOL)
			{
				item.JDGMFOEPJME(EFDLFNPAKGO);
			}
		}

		public LKDLDEPEAHO JMAEODDKAHD(LKDLDEPEAHO.ACPICCBBPHF FBAGNJILEGD)
		{
			if ((int)FBAGNJILEGD < 1 || (int)FBAGNJILEGD >= AGPKODDPAOL.Count)
			{
				return null;
			}
			return AGPKODDPAOL[(int)FBAGNJILEGD];
		}

		public void JCOLMPJMMEB(PJEMPFEIOAK EFDLFNPAKGO)
		{
			foreach (LKDLDEPEAHO item in AGPKODDPAOL)
			{
				item.JCOLMPJMMEB(EFDLFNPAKGO);
			}
		}

		public void CFGEKKHOKKE(CMNIABEFLBJ EFDLFNPAKGO)
		{
			foreach (LKDLDEPEAHO item in AGPKODDPAOL)
			{
				item.CFGEKKHOKKE(EFDLFNPAKGO);
			}
		}

		public void LEDLMGNKOJA(PJEMPFEIOAK EFDLFNPAKGO)
		{
			foreach (LKDLDEPEAHO item in AGPKODDPAOL)
			{
				item.GANHNFADIJO(EFDLFNPAKGO);
			}
		}

		public LKDLDEPEAHO LEHJBCOMJHN(LKDLDEPEAHO.ACPICCBBPHF FBAGNJILEGD)
		{
			if ((int)FBAGNJILEGD < 0 || (int)FBAGNJILEGD >= AGPKODDPAOL.Count)
			{
				return null;
			}
			return AGPKODDPAOL[(int)FBAGNJILEGD];
		}

		public void MIBDDAAECMC(CMNIABEFLBJ EFDLFNPAKGO)
		{
			foreach (LKDLDEPEAHO item in AGPKODDPAOL)
			{
				item.JDGMFOEPJME(EFDLFNPAKGO);
			}
		}

		public LKDLDEPEAHO CMHJLFDAIJM(LKDLDEPEAHO.ACPICCBBPHF FBAGNJILEGD)
		{
			if ((int)FBAGNJILEGD < 0 || (int)FBAGNJILEGD >= AGPKODDPAOL.Count)
			{
				return null;
			}
			return AGPKODDPAOL[(int)FBAGNJILEGD];
		}

		public LKDLDEPEAHO FGKPHJKKDMO(LKDLDEPEAHO.ACPICCBBPHF FBAGNJILEGD)
		{
			if ((int)FBAGNJILEGD < 1 || (int)FBAGNJILEGD >= AGPKODDPAOL.Count)
			{
				return null;
			}
			return AGPKODDPAOL[(int)FBAGNJILEGD];
		}

		public LKDLDEPEAHO ICAPBKPKKHN(LKDLDEPEAHO.ACPICCBBPHF FBAGNJILEGD)
		{
			if ((int)FBAGNJILEGD < 0 || (int)FBAGNJILEGD >= AGPKODDPAOL.Count)
			{
				return null;
			}
			return AGPKODDPAOL[(int)FBAGNJILEGD];
		}
	}
}
