using System.Collections.Generic;
using System.Runtime.CompilerServices;
using EveEngine;

namespace GameServer
{
	public class AKDIMHNDAIH : EOPOBHFNFPA
	{
		private object JOEHMANNDJK;

		private int LFMCAMFIHEJ;

		private Dictionary<ushort, CLJOMPBCNOE> LDDHNIFBPII;

		public int PKKDIMODALC
		{
			get
			{
				return LJKLAIGNIKB();
			}
			protected set
			{
				ACIBDAANJLI(value);
			}
		}

		public Dictionary<ushort, CLJOMPBCNOE> LAFAGPFAFNC
		{
			get
			{
				return GLBKCGACIHK();
			}
			protected set
			{
				DOMDCJMEEGM(value);
			}
		}

		public void CFGEKKHOKKE(CMNIABEFLBJ EFDLFNPAKGO)
		{
			lock (JOEHMANNDJK)
			{
				EFDLFNPAKGO.GBMJNFOEACC((ushort)GLBKCGACIHK().Count);
				foreach (KeyValuePair<ushort, CLJOMPBCNOE> item in GLBKCGACIHK())
				{
					item.Value.CFGEKKHOKKE(EFDLFNPAKGO);
				}
			}
		}

		[SpecialName]
		public Dictionary<ushort, CLJOMPBCNOE> KGMEPGEFIBF()
		{
			return LDDHNIFBPII;
		}

		public CLJOMPBCNOE PFGPGGNDAAL(ushort OHGOBGOIECH)
		{
			lock (JOEHMANNDJK)
			{
				CLJOMPBCNOE value;
				if (!GLBKCGACIHK().TryGetValue(OHGOBGOIECH, out value))
				{
					return null;
				}
				return value;
			}
		}

		public int LJKLAIGNIKB()
		{
			return LFMCAMFIHEJ;
		}

		[SpecialName]
		protected void GPOKJNLOGCF(int ICENKPDOHBK)
		{
			LFMCAMFIHEJ = ICENKPDOHBK;
		}

		public bool AMBOPDLLCCP()
		{
			if (LJKLAIGNIKB() == GetHashCode())
			{
				return true;
			}
			return false;
		}

		public CLJOMPBCNOE KFKMFHLOHCM(ushort OHGOBGOIECH)
		{
			lock (JOEHMANNDJK)
			{
				CLJOMPBCNOE value;
				if (!KGMEPGEFIBF().TryGetValue(OHGOBGOIECH, out value))
				{
					return null;
				}
				return value;
			}
		}

		public override int GetHashCode()
		{
			int num = 0;
			foreach (KeyValuePair<ushort, CLJOMPBCNOE> item in GLBKCGACIHK())
			{
				num ^= item.Value.GetHashCode();
			}
			return num;
		}

		public bool CANIKFNCHLC()
		{
			if (LFCIGPFCGGP() == IMNEMDFAINP())
			{
				return false;
			}
			return true;
		}

		public bool FKMLNNEMDIO()
		{
			if (LFCIGPFCGGP() == HMOHANFJAGG())
			{
				return true;
			}
			return false;
		}

		public void PEFJOMFAOJI()
		{
			CLJOMPBCNOE cLJOMPBCNOE = new CLJOMPBCNOE(11001, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE.GAFNNDHJDAE = "하급 공격력 표식";
			cLJOMPBCNOE.MGGCDFHFMKK = 150;
			cLJOMPBCNOE.FLNFNOEDLFN = 1;
			cLJOMPBCNOE.LHEKBMLAJMA = 0.53f;
			GLBKCGACIHK().Add(cLJOMPBCNOE.KGHMFHDGNEO(), cLJOMPBCNOE);
			CLJOMPBCNOE cLJOMPBCNOE2 = new CLJOMPBCNOE(11002, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE2.GAFNNDHJDAE = "하급 성장 공격력 표식";
			cLJOMPBCNOE2.MGGCDFHFMKK = 300;
			cLJOMPBCNOE2.FLNFNOEDLFN = 1;
			cLJOMPBCNOE2.JGPIIFFIAIG = 0.08f;
			GLBKCGACIHK().Add(cLJOMPBCNOE2.KGHMFHDGNEO(), cLJOMPBCNOE2);
			CLJOMPBCNOE cLJOMPBCNOE3 = new CLJOMPBCNOE(11003, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE3.GAFNNDHJDAE = "하급 공격속도 표식";
			cLJOMPBCNOE3.MGGCDFHFMKK = 300;
			cLJOMPBCNOE3.FLNFNOEDLFN = 1;
			cLJOMPBCNOE3.NMFDEKCMJAH = 0.0094f;
			GLBKCGACIHK().Add(cLJOMPBCNOE3.KGHMFHDGNEO(), cLJOMPBCNOE3);
			CLJOMPBCNOE cLJOMPBCNOE4 = new CLJOMPBCNOE(11004, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE4.GAFNNDHJDAE = "하급 주문력 표식";
			cLJOMPBCNOE4.MGGCDFHFMKK = 300;
			cLJOMPBCNOE4.FLNFNOEDLFN = 1;
			cLJOMPBCNOE4.KBMBFHHNDPE = 0.33f;
			GLBKCGACIHK().Add(cLJOMPBCNOE4.KGHMFHDGNEO(), cLJOMPBCNOE4);
			CLJOMPBCNOE cLJOMPBCNOE5 = new CLJOMPBCNOE(11005, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE5.GAFNNDHJDAE = "하급 성장 주문력 표식";
			cLJOMPBCNOE5.MGGCDFHFMKK = 300;
			cLJOMPBCNOE5.FLNFNOEDLFN = 1;
			cLJOMPBCNOE5.OOJHKLBFHED = 0.06f;
			GLBKCGACIHK().Add(cLJOMPBCNOE5.KGHMFHDGNEO(), cLJOMPBCNOE5);
			CLJOMPBCNOE cLJOMPBCNOE6 = new CLJOMPBCNOE(11006, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE6.GAFNNDHJDAE = "하급 대기시간감소 표식";
			cLJOMPBCNOE6.MGGCDFHFMKK = 300;
			cLJOMPBCNOE6.FLNFNOEDLFN = 1;
			cLJOMPBCNOE6.BDKLLIMAGPP = 0.0011f;
			GLBKCGACIHK().Add(cLJOMPBCNOE6.KGHMFHDGNEO(), cLJOMPBCNOE6);
			CLJOMPBCNOE cLJOMPBCNOE7 = new CLJOMPBCNOE(11007, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE7.GAFNNDHJDAE = "하급 마나 표식";
			cLJOMPBCNOE7.MGGCDFHFMKK = 300;
			cLJOMPBCNOE7.FLNFNOEDLFN = 1;
			cLJOMPBCNOE7.BELPBCDOPBA = 3.28f;
			GLBKCGACIHK().Add(cLJOMPBCNOE7.KGHMFHDGNEO(), cLJOMPBCNOE7);
			CLJOMPBCNOE cLJOMPBCNOE8 = new CLJOMPBCNOE(11008, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE8.GAFNNDHJDAE = "하급 성장 마나 표식";
			cLJOMPBCNOE8.MGGCDFHFMKK = 300;
			cLJOMPBCNOE8.FLNFNOEDLFN = 1;
			cLJOMPBCNOE8.BJHADLMCNJO = 0.65f;
			GLBKCGACIHK().Add(cLJOMPBCNOE8.KGHMFHDGNEO(), cLJOMPBCNOE8);
			CLJOMPBCNOE cLJOMPBCNOE9 = new CLJOMPBCNOE(11009, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE9.GAFNNDHJDAE = "하급 마나 재생 표식";
			cLJOMPBCNOE9.MGGCDFHFMKK = 150;
			cLJOMPBCNOE9.FLNFNOEDLFN = 1;
			cLJOMPBCNOE9.MGLIOBDEJLF = 0.15f;
			GLBKCGACIHK().Add(cLJOMPBCNOE9.KGHMFHDGNEO(), cLJOMPBCNOE9);
			CLJOMPBCNOE cLJOMPBCNOE10 = new CLJOMPBCNOE(11010, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE10.GAFNNDHJDAE = "하급 체력 표식";
			cLJOMPBCNOE10.MGGCDFHFMKK = 300;
			cLJOMPBCNOE10.FLNFNOEDLFN = 1;
			cLJOMPBCNOE10.NCBAGGNLLLK = 1.93f;
			GLBKCGACIHK().Add(cLJOMPBCNOE10.KGHMFHDGNEO(), cLJOMPBCNOE10);
			CLJOMPBCNOE cLJOMPBCNOE11 = new CLJOMPBCNOE(11011, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE11.GAFNNDHJDAE = "하급 성장 체력 표식";
			cLJOMPBCNOE11.MGGCDFHFMKK = 650;
			cLJOMPBCNOE11.FLNFNOEDLFN = 1;
			cLJOMPBCNOE11.MDAGHJFEODE = 0.3f;
			GLBKCGACIHK().Add(cLJOMPBCNOE11.KGHMFHDGNEO(), cLJOMPBCNOE11);
			CLJOMPBCNOE cLJOMPBCNOE12 = new CLJOMPBCNOE(11012, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE12.GAFNNDHJDAE = "하급 치명타 확률 표식";
			cLJOMPBCNOE12.MGGCDFHFMKK = 300;
			cLJOMPBCNOE12.FLNFNOEDLFN = 1;
			cLJOMPBCNOE12.CJALIPCFCLA = 0.0052f;
			GLBKCGACIHK().Add(cLJOMPBCNOE12.KGHMFHDGNEO(), cLJOMPBCNOE12);
			CLJOMPBCNOE cLJOMPBCNOE13 = new CLJOMPBCNOE(11013, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE13.GAFNNDHJDAE = "하급 방어력 표식";
			cLJOMPBCNOE13.MGGCDFHFMKK = 150;
			cLJOMPBCNOE13.FLNFNOEDLFN = 1;
			cLJOMPBCNOE13.FBEBCNEPHJD = 0.51f;
			GLBKCGACIHK().Add(cLJOMPBCNOE13.KGHMFHDGNEO(), cLJOMPBCNOE13);
			CLJOMPBCNOE cLJOMPBCNOE14 = new CLJOMPBCNOE(11014, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE14.GAFNNDHJDAE = "하급 마법저항력 표식";
			cLJOMPBCNOE14.MGGCDFHFMKK = 150;
			cLJOMPBCNOE14.FLNFNOEDLFN = 1;
			cLJOMPBCNOE14.NLMHKBGDKLA = 0.43f;
			GLBKCGACIHK().Add(cLJOMPBCNOE14.KGHMFHDGNEO(), cLJOMPBCNOE14);
			CLJOMPBCNOE cLJOMPBCNOE15 = new CLJOMPBCNOE(12001, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE15.GAFNNDHJDAE = "중급 공격력 표식";
			cLJOMPBCNOE15.MGGCDFHFMKK = 800;
			cLJOMPBCNOE15.FLNFNOEDLFN = 10;
			cLJOMPBCNOE15.LHEKBMLAJMA = 0.74f;
			GLBKCGACIHK().Add(cLJOMPBCNOE15.KGHMFHDGNEO(), cLJOMPBCNOE15);
			CLJOMPBCNOE cLJOMPBCNOE16 = new CLJOMPBCNOE(12002, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE16.GAFNNDHJDAE = "중급 성장 공격력 표식";
			cLJOMPBCNOE16.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE16.FLNFNOEDLFN = 10;
			cLJOMPBCNOE16.JGPIIFFIAIG = 0.1f;
			GLBKCGACIHK().Add(cLJOMPBCNOE16.KGHMFHDGNEO(), cLJOMPBCNOE16);
			CLJOMPBCNOE cLJOMPBCNOE17 = new CLJOMPBCNOE(12003, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE17.GAFNNDHJDAE = "중급 공격속도 표식";
			cLJOMPBCNOE17.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE17.FLNFNOEDLFN = 10;
			cLJOMPBCNOE17.NMFDEKCMJAH = 0.0132f;
			GLBKCGACIHK().Add(cLJOMPBCNOE17.KGHMFHDGNEO(), cLJOMPBCNOE17);
			CLJOMPBCNOE cLJOMPBCNOE18 = new CLJOMPBCNOE(12004, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE18.GAFNNDHJDAE = "중급 주문력 표식";
			cLJOMPBCNOE18.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE18.FLNFNOEDLFN = 10;
			cLJOMPBCNOE18.KBMBFHHNDPE = 0.46f;
			GLBKCGACIHK().Add(cLJOMPBCNOE18.KGHMFHDGNEO(), cLJOMPBCNOE18);
			CLJOMPBCNOE cLJOMPBCNOE19 = new CLJOMPBCNOE(12005, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE19.GAFNNDHJDAE = "중급 성장 주문력 표식";
			cLJOMPBCNOE19.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE19.FLNFNOEDLFN = 10;
			cLJOMPBCNOE19.OOJHKLBFHED = 0.08f;
			GLBKCGACIHK().Add(cLJOMPBCNOE19.KGHMFHDGNEO(), cLJOMPBCNOE19);
			CLJOMPBCNOE cLJOMPBCNOE20 = new CLJOMPBCNOE(12006, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE20.GAFNNDHJDAE = "중급 대기시간감소 표식";
			cLJOMPBCNOE20.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE20.FLNFNOEDLFN = 10;
			cLJOMPBCNOE20.BDKLLIMAGPP = 0.0016f;
			GLBKCGACIHK().Add(cLJOMPBCNOE20.KGHMFHDGNEO(), cLJOMPBCNOE20);
			CLJOMPBCNOE cLJOMPBCNOE21 = new CLJOMPBCNOE(12007, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE21.GAFNNDHJDAE = "중급 마나 표식";
			cLJOMPBCNOE21.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE21.FLNFNOEDLFN = 10;
			cLJOMPBCNOE21.BELPBCDOPBA = 4.59f;
			GLBKCGACIHK().Add(cLJOMPBCNOE21.KGHMFHDGNEO(), cLJOMPBCNOE21);
			CLJOMPBCNOE cLJOMPBCNOE22 = new CLJOMPBCNOE(12008, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE22.GAFNNDHJDAE = "중급 성장 마나 표식";
			cLJOMPBCNOE22.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE22.FLNFNOEDLFN = 10;
			cLJOMPBCNOE22.BJHADLMCNJO = 0.91f;
			GLBKCGACIHK().Add(cLJOMPBCNOE22.KGHMFHDGNEO(), cLJOMPBCNOE22);
			CLJOMPBCNOE cLJOMPBCNOE23 = new CLJOMPBCNOE(12009, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE23.GAFNNDHJDAE = "중급 마나 재생 표식";
			cLJOMPBCNOE23.MGGCDFHFMKK = 800;
			cLJOMPBCNOE23.FLNFNOEDLFN = 10;
			cLJOMPBCNOE23.MGLIOBDEJLF = 0.2f;
			GLBKCGACIHK().Add(cLJOMPBCNOE23.KGHMFHDGNEO(), cLJOMPBCNOE23);
			CLJOMPBCNOE cLJOMPBCNOE24 = new CLJOMPBCNOE(12010, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE24.GAFNNDHJDAE = "중급 체력 표식";
			cLJOMPBCNOE24.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE24.FLNFNOEDLFN = 10;
			cLJOMPBCNOE24.NCBAGGNLLLK = 2.7f;
			GLBKCGACIHK().Add(cLJOMPBCNOE24.KGHMFHDGNEO(), cLJOMPBCNOE24);
			CLJOMPBCNOE cLJOMPBCNOE25 = new CLJOMPBCNOE(12011, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE25.GAFNNDHJDAE = "중급 성장 체력 표식";
			cLJOMPBCNOE25.MGGCDFHFMKK = 3300;
			cLJOMPBCNOE25.FLNFNOEDLFN = 10;
			cLJOMPBCNOE25.MDAGHJFEODE = 0.42f;
			GLBKCGACIHK().Add(cLJOMPBCNOE25.KGHMFHDGNEO(), cLJOMPBCNOE25);
			CLJOMPBCNOE cLJOMPBCNOE26 = new CLJOMPBCNOE(12012, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE26.GAFNNDHJDAE = "중급 치명타 확률 표식";
			cLJOMPBCNOE26.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE26.FLNFNOEDLFN = 10;
			cLJOMPBCNOE26.CJALIPCFCLA = 0.0072f;
			GLBKCGACIHK().Add(cLJOMPBCNOE26.KGHMFHDGNEO(), cLJOMPBCNOE26);
			CLJOMPBCNOE cLJOMPBCNOE27 = new CLJOMPBCNOE(12013, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE27.GAFNNDHJDAE = "중급 방어력 표식";
			cLJOMPBCNOE27.MGGCDFHFMKK = 800;
			cLJOMPBCNOE27.FLNFNOEDLFN = 10;
			cLJOMPBCNOE27.FBEBCNEPHJD = 0.71f;
			GLBKCGACIHK().Add(cLJOMPBCNOE27.KGHMFHDGNEO(), cLJOMPBCNOE27);
			CLJOMPBCNOE cLJOMPBCNOE28 = new CLJOMPBCNOE(12014, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE28.GAFNNDHJDAE = "중급 마법저항력 표식";
			cLJOMPBCNOE28.MGGCDFHFMKK = 800;
			cLJOMPBCNOE28.FLNFNOEDLFN = 10;
			cLJOMPBCNOE28.NLMHKBGDKLA = 0.6f;
			GLBKCGACIHK().Add(cLJOMPBCNOE28.KGHMFHDGNEO(), cLJOMPBCNOE28);
			CLJOMPBCNOE cLJOMPBCNOE29 = new CLJOMPBCNOE(13001, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE29.GAFNNDHJDAE = "상급 공격력 표식";
			cLJOMPBCNOE29.MGGCDFHFMKK = 2050;
			cLJOMPBCNOE29.FLNFNOEDLFN = 20;
			cLJOMPBCNOE29.LHEKBMLAJMA = 0.95f;
			GLBKCGACIHK().Add(cLJOMPBCNOE29.KGHMFHDGNEO(), cLJOMPBCNOE29);
			CLJOMPBCNOE cLJOMPBCNOE30 = new CLJOMPBCNOE(13002, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE30.GAFNNDHJDAE = "상급 성장 공격력 표식";
			cLJOMPBCNOE30.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE30.FLNFNOEDLFN = 20;
			cLJOMPBCNOE30.JGPIIFFIAIG = 0.13f;
			GLBKCGACIHK().Add(cLJOMPBCNOE30.KGHMFHDGNEO(), cLJOMPBCNOE30);
			CLJOMPBCNOE cLJOMPBCNOE31 = new CLJOMPBCNOE(13003, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE31.GAFNNDHJDAE = "상급 공격속도 표식";
			cLJOMPBCNOE31.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE31.FLNFNOEDLFN = 20;
			cLJOMPBCNOE31.NMFDEKCMJAH = 0.017f;
			GLBKCGACIHK().Add(cLJOMPBCNOE31.KGHMFHDGNEO(), cLJOMPBCNOE31);
			CLJOMPBCNOE cLJOMPBCNOE32 = new CLJOMPBCNOE(13004, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE32.GAFNNDHJDAE = "상급 주문력 표식";
			cLJOMPBCNOE32.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE32.FLNFNOEDLFN = 20;
			cLJOMPBCNOE32.KBMBFHHNDPE = 0.59f;
			GLBKCGACIHK().Add(cLJOMPBCNOE32.KGHMFHDGNEO(), cLJOMPBCNOE32);
			CLJOMPBCNOE cLJOMPBCNOE33 = new CLJOMPBCNOE(13005, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE33.GAFNNDHJDAE = "상급 성장 주문력 표식";
			cLJOMPBCNOE33.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE33.FLNFNOEDLFN = 20;
			cLJOMPBCNOE33.OOJHKLBFHED = 0.1f;
			GLBKCGACIHK().Add(cLJOMPBCNOE33.KGHMFHDGNEO(), cLJOMPBCNOE33);
			CLJOMPBCNOE cLJOMPBCNOE34 = new CLJOMPBCNOE(13006, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE34.GAFNNDHJDAE = "상급 대기시간감소 표식";
			cLJOMPBCNOE34.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE34.FLNFNOEDLFN = 20;
			cLJOMPBCNOE34.BDKLLIMAGPP = 0.002f;
			GLBKCGACIHK().Add(cLJOMPBCNOE34.KGHMFHDGNEO(), cLJOMPBCNOE34);
			CLJOMPBCNOE cLJOMPBCNOE35 = new CLJOMPBCNOE(13007, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE35.GAFNNDHJDAE = "상급 마나 표식";
			cLJOMPBCNOE35.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE35.FLNFNOEDLFN = 20;
			cLJOMPBCNOE35.BELPBCDOPBA = 5.91f;
			GLBKCGACIHK().Add(cLJOMPBCNOE35.KGHMFHDGNEO(), cLJOMPBCNOE35);
			CLJOMPBCNOE cLJOMPBCNOE36 = new CLJOMPBCNOE(13008, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE36.GAFNNDHJDAE = "상급 성장 마나 표식";
			cLJOMPBCNOE36.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE36.FLNFNOEDLFN = 20;
			cLJOMPBCNOE36.BJHADLMCNJO = 1.17f;
			GLBKCGACIHK().Add(cLJOMPBCNOE36.KGHMFHDGNEO(), cLJOMPBCNOE36);
			CLJOMPBCNOE cLJOMPBCNOE37 = new CLJOMPBCNOE(13009, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE37.GAFNNDHJDAE = "상급 마나 재생 표식";
			cLJOMPBCNOE37.MGGCDFHFMKK = 2050;
			cLJOMPBCNOE37.FLNFNOEDLFN = 20;
			cLJOMPBCNOE37.MGLIOBDEJLF = 0.26f;
			GLBKCGACIHK().Add(cLJOMPBCNOE37.KGHMFHDGNEO(), cLJOMPBCNOE37);
			CLJOMPBCNOE cLJOMPBCNOE38 = new CLJOMPBCNOE(13010, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE38.GAFNNDHJDAE = "상급 체력 표식";
			cLJOMPBCNOE38.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE38.FLNFNOEDLFN = 20;
			cLJOMPBCNOE38.NCBAGGNLLLK = 3.47f;
			GLBKCGACIHK().Add(cLJOMPBCNOE38.KGHMFHDGNEO(), cLJOMPBCNOE38);
			CLJOMPBCNOE cLJOMPBCNOE39 = new CLJOMPBCNOE(13011, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE39.GAFNNDHJDAE = "상급 성장 체력 표식";
			cLJOMPBCNOE39.MGGCDFHFMKK = 8200;
			cLJOMPBCNOE39.FLNFNOEDLFN = 20;
			cLJOMPBCNOE39.MDAGHJFEODE = 0.54f;
			GLBKCGACIHK().Add(cLJOMPBCNOE39.KGHMFHDGNEO(), cLJOMPBCNOE39);
			CLJOMPBCNOE cLJOMPBCNOE40 = new CLJOMPBCNOE(13012, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE40.GAFNNDHJDAE = "상급 치명타 확률 표식";
			cLJOMPBCNOE40.MGGCDFHFMKK = 8200;
			cLJOMPBCNOE40.FLNFNOEDLFN = 20;
			cLJOMPBCNOE40.CJALIPCFCLA = 0.0092f;
			GLBKCGACIHK().Add(cLJOMPBCNOE40.KGHMFHDGNEO(), cLJOMPBCNOE40);
			CLJOMPBCNOE cLJOMPBCNOE41 = new CLJOMPBCNOE(13013, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE41.GAFNNDHJDAE = "상급 방어력 표식";
			cLJOMPBCNOE41.MGGCDFHFMKK = 2050;
			cLJOMPBCNOE41.FLNFNOEDLFN = 20;
			cLJOMPBCNOE41.FBEBCNEPHJD = 0.91f;
			GLBKCGACIHK().Add(cLJOMPBCNOE41.KGHMFHDGNEO(), cLJOMPBCNOE41);
			CLJOMPBCNOE cLJOMPBCNOE42 = new CLJOMPBCNOE(13014, CLJOMPBCNOE.ACPICCBBPHF.Mark, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE42.GAFNNDHJDAE = "상급 마법저항력 표식";
			cLJOMPBCNOE42.MGGCDFHFMKK = 2050;
			cLJOMPBCNOE42.FLNFNOEDLFN = 20;
			cLJOMPBCNOE42.NLMHKBGDKLA = 0.77f;
			GLBKCGACIHK().Add(cLJOMPBCNOE42.KGHMFHDGNEO(), cLJOMPBCNOE42);
			CLJOMPBCNOE cLJOMPBCNOE43 = new CLJOMPBCNOE(21001, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE43.GAFNNDHJDAE = "하급 공격력 인장";
			cLJOMPBCNOE43.MGGCDFHFMKK = 150;
			cLJOMPBCNOE43.FLNFNOEDLFN = 1;
			cLJOMPBCNOE43.LHEKBMLAJMA = 0.24f;
			GLBKCGACIHK().Add(cLJOMPBCNOE43.KGHMFHDGNEO(), cLJOMPBCNOE43);
			CLJOMPBCNOE cLJOMPBCNOE44 = new CLJOMPBCNOE(21002, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE44.GAFNNDHJDAE = "하급 성장 공격력 인장";
			cLJOMPBCNOE44.MGGCDFHFMKK = 150;
			cLJOMPBCNOE44.FLNFNOEDLFN = 1;
			cLJOMPBCNOE44.JGPIIFFIAIG = 0.03f;
			GLBKCGACIHK().Add(cLJOMPBCNOE44.KGHMFHDGNEO(), cLJOMPBCNOE44);
			CLJOMPBCNOE cLJOMPBCNOE45 = new CLJOMPBCNOE(21003, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE45.GAFNNDHJDAE = "하급 공격속도 인장";
			cLJOMPBCNOE45.MGGCDFHFMKK = 300;
			cLJOMPBCNOE45.FLNFNOEDLFN = 1;
			cLJOMPBCNOE45.NMFDEKCMJAH = 0.0042f;
			GLBKCGACIHK().Add(cLJOMPBCNOE45.KGHMFHDGNEO(), cLJOMPBCNOE45);
			CLJOMPBCNOE cLJOMPBCNOE46 = new CLJOMPBCNOE(21004, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE46.GAFNNDHJDAE = "하급 주문력 인장";
			cLJOMPBCNOE46.MGGCDFHFMKK = 300;
			cLJOMPBCNOE46.FLNFNOEDLFN = 1;
			cLJOMPBCNOE46.KBMBFHHNDPE = 0.33f;
			GLBKCGACIHK().Add(cLJOMPBCNOE46.KGHMFHDGNEO(), cLJOMPBCNOE46);
			CLJOMPBCNOE cLJOMPBCNOE47 = new CLJOMPBCNOE(21005, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE47.GAFNNDHJDAE = "하급 성장 주문력 인장";
			cLJOMPBCNOE47.MGGCDFHFMKK = 300;
			cLJOMPBCNOE47.FLNFNOEDLFN = 1;
			cLJOMPBCNOE47.OOJHKLBFHED = 0.06f;
			GLBKCGACIHK().Add(cLJOMPBCNOE47.KGHMFHDGNEO(), cLJOMPBCNOE47);
			CLJOMPBCNOE cLJOMPBCNOE48 = new CLJOMPBCNOE(21006, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE48.GAFNNDHJDAE = "하급 대기시간감소 인장";
			cLJOMPBCNOE48.MGGCDFHFMKK = 300;
			cLJOMPBCNOE48.FLNFNOEDLFN = 1;
			cLJOMPBCNOE48.BDKLLIMAGPP = 0.002f;
			GLBKCGACIHK().Add(cLJOMPBCNOE48.KGHMFHDGNEO(), cLJOMPBCNOE48);
			CLJOMPBCNOE cLJOMPBCNOE49 = new CLJOMPBCNOE(21007, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE49.GAFNNDHJDAE = "하급 마나 인장";
			cLJOMPBCNOE49.MGGCDFHFMKK = 300;
			cLJOMPBCNOE49.FLNFNOEDLFN = 1;
			cLJOMPBCNOE49.BELPBCDOPBA = 3.83f;
			GLBKCGACIHK().Add(cLJOMPBCNOE49.KGHMFHDGNEO(), cLJOMPBCNOE49);
			CLJOMPBCNOE cLJOMPBCNOE50 = new CLJOMPBCNOE(21008, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE50.GAFNNDHJDAE = "하급 성장 마나 인장";
			cLJOMPBCNOE50.MGGCDFHFMKK = 300;
			cLJOMPBCNOE50.FLNFNOEDLFN = 1;
			cLJOMPBCNOE50.BJHADLMCNJO = 0.65f;
			GLBKCGACIHK().Add(cLJOMPBCNOE50.KGHMFHDGNEO(), cLJOMPBCNOE50);
			CLJOMPBCNOE cLJOMPBCNOE51 = new CLJOMPBCNOE(21009, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE51.GAFNNDHJDAE = "하급 마나 재생 인장";
			cLJOMPBCNOE51.MGGCDFHFMKK = 150;
			cLJOMPBCNOE51.FLNFNOEDLFN = 1;
			cLJOMPBCNOE51.MGLIOBDEJLF = 0.23f;
			GLBKCGACIHK().Add(cLJOMPBCNOE51.KGHMFHDGNEO(), cLJOMPBCNOE51);
			CLJOMPBCNOE cLJOMPBCNOE52 = new CLJOMPBCNOE(21010, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE52.GAFNNDHJDAE = "하급 체력 인장";
			cLJOMPBCNOE52.MGGCDFHFMKK = 650;
			cLJOMPBCNOE52.FLNFNOEDLFN = 1;
			cLJOMPBCNOE52.NCBAGGNLLLK = 4.48f;
			GLBKCGACIHK().Add(cLJOMPBCNOE52.KGHMFHDGNEO(), cLJOMPBCNOE52);
			CLJOMPBCNOE cLJOMPBCNOE53 = new CLJOMPBCNOE(21011, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE53.GAFNNDHJDAE = "하급 성장 체력 인장";
			cLJOMPBCNOE53.MGGCDFHFMKK = 300;
			cLJOMPBCNOE53.FLNFNOEDLFN = 1;
			cLJOMPBCNOE53.MDAGHJFEODE = 0.7467f;
			GLBKCGACIHK().Add(cLJOMPBCNOE53.KGHMFHDGNEO(), cLJOMPBCNOE53);
			CLJOMPBCNOE cLJOMPBCNOE54 = new CLJOMPBCNOE(21012, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE54.GAFNNDHJDAE = "하급 치명타 확률 인장";
			cLJOMPBCNOE54.MGGCDFHFMKK = 650;
			cLJOMPBCNOE54.FLNFNOEDLFN = 1;
			cLJOMPBCNOE54.CJALIPCFCLA = 0.001f;
			GLBKCGACIHK().Add(cLJOMPBCNOE54.KGHMFHDGNEO(), cLJOMPBCNOE54);
			CLJOMPBCNOE cLJOMPBCNOE55 = new CLJOMPBCNOE(21013, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE55.GAFNNDHJDAE = "하급 방어력 인장";
			cLJOMPBCNOE55.MGGCDFHFMKK = 150;
			cLJOMPBCNOE55.FLNFNOEDLFN = 1;
			cLJOMPBCNOE55.FBEBCNEPHJD = 0.56f;
			GLBKCGACIHK().Add(cLJOMPBCNOE55.KGHMFHDGNEO(), cLJOMPBCNOE55);
			CLJOMPBCNOE cLJOMPBCNOE56 = new CLJOMPBCNOE(21014, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE56.GAFNNDHJDAE = "하급 마법저항력 인장";
			cLJOMPBCNOE56.MGGCDFHFMKK = 150;
			cLJOMPBCNOE56.FLNFNOEDLFN = 1;
			cLJOMPBCNOE56.NLMHKBGDKLA = 0.41f;
			GLBKCGACIHK().Add(cLJOMPBCNOE56.KGHMFHDGNEO(), cLJOMPBCNOE56);
			CLJOMPBCNOE cLJOMPBCNOE57 = new CLJOMPBCNOE(22001, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE57.GAFNNDHJDAE = "중급 공격력 인장";
			cLJOMPBCNOE57.MGGCDFHFMKK = 800;
			cLJOMPBCNOE57.FLNFNOEDLFN = 10;
			cLJOMPBCNOE57.LHEKBMLAJMA = 0.33f;
			GLBKCGACIHK().Add(cLJOMPBCNOE57.KGHMFHDGNEO(), cLJOMPBCNOE57);
			CLJOMPBCNOE cLJOMPBCNOE58 = new CLJOMPBCNOE(22002, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE58.GAFNNDHJDAE = "중급 성장 공격력 인장";
			cLJOMPBCNOE58.MGGCDFHFMKK = 800;
			cLJOMPBCNOE58.FLNFNOEDLFN = 10;
			cLJOMPBCNOE58.JGPIIFFIAIG = 0.05f;
			GLBKCGACIHK().Add(cLJOMPBCNOE58.KGHMFHDGNEO(), cLJOMPBCNOE58);
			CLJOMPBCNOE cLJOMPBCNOE59 = new CLJOMPBCNOE(22003, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE59.GAFNNDHJDAE = "중급 공격속도 인장";
			cLJOMPBCNOE59.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE59.FLNFNOEDLFN = 10;
			cLJOMPBCNOE59.NMFDEKCMJAH = 0.0059f;
			GLBKCGACIHK().Add(cLJOMPBCNOE59.KGHMFHDGNEO(), cLJOMPBCNOE59);
			CLJOMPBCNOE cLJOMPBCNOE60 = new CLJOMPBCNOE(22004, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE60.GAFNNDHJDAE = "중급 주문력 인장";
			cLJOMPBCNOE60.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE60.FLNFNOEDLFN = 10;
			cLJOMPBCNOE60.KBMBFHHNDPE = 0.46f;
			GLBKCGACIHK().Add(cLJOMPBCNOE60.KGHMFHDGNEO(), cLJOMPBCNOE60);
			CLJOMPBCNOE cLJOMPBCNOE61 = new CLJOMPBCNOE(22005, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE61.GAFNNDHJDAE = "중급 성장 주문력 인장";
			cLJOMPBCNOE61.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE61.FLNFNOEDLFN = 10;
			cLJOMPBCNOE61.OOJHKLBFHED = 0.08f;
			GLBKCGACIHK().Add(cLJOMPBCNOE61.KGHMFHDGNEO(), cLJOMPBCNOE61);
			CLJOMPBCNOE cLJOMPBCNOE62 = new CLJOMPBCNOE(22006, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE62.GAFNNDHJDAE = "중급 대기시간감소 인장";
			cLJOMPBCNOE62.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE62.FLNFNOEDLFN = 10;
			cLJOMPBCNOE62.BDKLLIMAGPP = 0.0029f;
			GLBKCGACIHK().Add(cLJOMPBCNOE62.KGHMFHDGNEO(), cLJOMPBCNOE62);
			CLJOMPBCNOE cLJOMPBCNOE63 = new CLJOMPBCNOE(22007, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE63.GAFNNDHJDAE = "중급 마나 인장";
			cLJOMPBCNOE63.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE63.FLNFNOEDLFN = 10;
			cLJOMPBCNOE63.BELPBCDOPBA = 5.36f;
			GLBKCGACIHK().Add(cLJOMPBCNOE63.KGHMFHDGNEO(), cLJOMPBCNOE63);
			CLJOMPBCNOE cLJOMPBCNOE64 = new CLJOMPBCNOE(22008, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE64.GAFNNDHJDAE = "중급 성장 마나 인장";
			cLJOMPBCNOE64.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE64.FLNFNOEDLFN = 10;
			cLJOMPBCNOE64.BJHADLMCNJO = 0.91f;
			GLBKCGACIHK().Add(cLJOMPBCNOE64.KGHMFHDGNEO(), cLJOMPBCNOE64);
			CLJOMPBCNOE cLJOMPBCNOE65 = new CLJOMPBCNOE(22009, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE65.GAFNNDHJDAE = "중급 마나 재생 인장";
			cLJOMPBCNOE65.MGGCDFHFMKK = 800;
			cLJOMPBCNOE65.FLNFNOEDLFN = 10;
			cLJOMPBCNOE65.MGLIOBDEJLF = 0.32f;
			GLBKCGACIHK().Add(cLJOMPBCNOE65.KGHMFHDGNEO(), cLJOMPBCNOE65);
			CLJOMPBCNOE cLJOMPBCNOE66 = new CLJOMPBCNOE(22010, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE66.GAFNNDHJDAE = "중급 체력 인장";
			cLJOMPBCNOE66.MGGCDFHFMKK = 3300;
			cLJOMPBCNOE66.FLNFNOEDLFN = 10;
			cLJOMPBCNOE66.NCBAGGNLLLK = 6.24f;
			GLBKCGACIHK().Add(cLJOMPBCNOE66.KGHMFHDGNEO(), cLJOMPBCNOE66);
			CLJOMPBCNOE cLJOMPBCNOE67 = new CLJOMPBCNOE(22011, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE67.GAFNNDHJDAE = "중급 성장 체력 인장";
			cLJOMPBCNOE67.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE67.FLNFNOEDLFN = 10;
			cLJOMPBCNOE67.MDAGHJFEODE = 1.04f;
			GLBKCGACIHK().Add(cLJOMPBCNOE67.KGHMFHDGNEO(), cLJOMPBCNOE67);
			CLJOMPBCNOE cLJOMPBCNOE68 = new CLJOMPBCNOE(22012, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE68.GAFNNDHJDAE = "중급 치명타 확률 인장";
			cLJOMPBCNOE68.MGGCDFHFMKK = 3300;
			cLJOMPBCNOE68.FLNFNOEDLFN = 10;
			cLJOMPBCNOE68.CJALIPCFCLA = 0.0021f;
			GLBKCGACIHK().Add(cLJOMPBCNOE68.KGHMFHDGNEO(), cLJOMPBCNOE68);
			CLJOMPBCNOE cLJOMPBCNOE69 = new CLJOMPBCNOE(22013, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE69.GAFNNDHJDAE = "중급 방어력 인장";
			cLJOMPBCNOE69.MGGCDFHFMKK = 800;
			cLJOMPBCNOE69.FLNFNOEDLFN = 10;
			cLJOMPBCNOE69.FBEBCNEPHJD = 0.78f;
			GLBKCGACIHK().Add(cLJOMPBCNOE69.KGHMFHDGNEO(), cLJOMPBCNOE69);
			CLJOMPBCNOE cLJOMPBCNOE70 = new CLJOMPBCNOE(22014, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE70.GAFNNDHJDAE = "중급 마법저항력 인장";
			cLJOMPBCNOE70.MGGCDFHFMKK = 800;
			cLJOMPBCNOE70.FLNFNOEDLFN = 10;
			cLJOMPBCNOE70.NLMHKBGDKLA = 0.58f;
			GLBKCGACIHK().Add(cLJOMPBCNOE70.KGHMFHDGNEO(), cLJOMPBCNOE70);
			CLJOMPBCNOE cLJOMPBCNOE71 = new CLJOMPBCNOE(23001, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE71.GAFNNDHJDAE = "상급 공격력 인장";
			cLJOMPBCNOE71.MGGCDFHFMKK = 2050;
			cLJOMPBCNOE71.FLNFNOEDLFN = 20;
			cLJOMPBCNOE71.LHEKBMLAJMA = 0.43f;
			GLBKCGACIHK().Add(cLJOMPBCNOE71.KGHMFHDGNEO(), cLJOMPBCNOE71);
			CLJOMPBCNOE cLJOMPBCNOE72 = new CLJOMPBCNOE(23002, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE72.GAFNNDHJDAE = "상급 성장 공격력 인장";
			cLJOMPBCNOE72.MGGCDFHFMKK = 2050;
			cLJOMPBCNOE72.FLNFNOEDLFN = 20;
			cLJOMPBCNOE72.JGPIIFFIAIG = 0.06f;
			GLBKCGACIHK().Add(cLJOMPBCNOE72.KGHMFHDGNEO(), cLJOMPBCNOE72);
			CLJOMPBCNOE cLJOMPBCNOE73 = new CLJOMPBCNOE(23003, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE73.GAFNNDHJDAE = "상급 공격속도 인장";
			cLJOMPBCNOE73.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE73.FLNFNOEDLFN = 20;
			cLJOMPBCNOE73.NMFDEKCMJAH = 0.0076f;
			GLBKCGACIHK().Add(cLJOMPBCNOE73.KGHMFHDGNEO(), cLJOMPBCNOE73);
			CLJOMPBCNOE cLJOMPBCNOE74 = new CLJOMPBCNOE(23004, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE74.GAFNNDHJDAE = "상급 주문력 인장";
			cLJOMPBCNOE74.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE74.FLNFNOEDLFN = 20;
			cLJOMPBCNOE74.KBMBFHHNDPE = 0.59f;
			GLBKCGACIHK().Add(cLJOMPBCNOE74.KGHMFHDGNEO(), cLJOMPBCNOE74);
			CLJOMPBCNOE cLJOMPBCNOE75 = new CLJOMPBCNOE(23005, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE75.GAFNNDHJDAE = "상급 성장 주문력 인장";
			cLJOMPBCNOE75.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE75.FLNFNOEDLFN = 20;
			cLJOMPBCNOE75.OOJHKLBFHED = 0.1f;
			GLBKCGACIHK().Add(cLJOMPBCNOE75.KGHMFHDGNEO(), cLJOMPBCNOE75);
			CLJOMPBCNOE cLJOMPBCNOE76 = new CLJOMPBCNOE(23006, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE76.GAFNNDHJDAE = "상급 대기시간감소 인장";
			cLJOMPBCNOE76.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE76.FLNFNOEDLFN = 20;
			cLJOMPBCNOE76.BDKLLIMAGPP = 0.0036f;
			GLBKCGACIHK().Add(cLJOMPBCNOE76.KGHMFHDGNEO(), cLJOMPBCNOE76);
			CLJOMPBCNOE cLJOMPBCNOE77 = new CLJOMPBCNOE(23007, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE77.GAFNNDHJDAE = "상급 마나 인장";
			cLJOMPBCNOE77.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE77.FLNFNOEDLFN = 20;
			cLJOMPBCNOE77.BELPBCDOPBA = 6.89f;
			GLBKCGACIHK().Add(cLJOMPBCNOE77.KGHMFHDGNEO(), cLJOMPBCNOE77);
			CLJOMPBCNOE cLJOMPBCNOE78 = new CLJOMPBCNOE(23008, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE78.GAFNNDHJDAE = "상급 성장 마나 인장";
			cLJOMPBCNOE78.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE78.FLNFNOEDLFN = 20;
			cLJOMPBCNOE78.BJHADLMCNJO = 1.17f;
			GLBKCGACIHK().Add(cLJOMPBCNOE78.KGHMFHDGNEO(), cLJOMPBCNOE78);
			CLJOMPBCNOE cLJOMPBCNOE79 = new CLJOMPBCNOE(23009, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE79.GAFNNDHJDAE = "상급 마나 재생 인장";
			cLJOMPBCNOE79.MGGCDFHFMKK = 2050;
			cLJOMPBCNOE79.FLNFNOEDLFN = 20;
			cLJOMPBCNOE79.MGLIOBDEJLF = 0.41f;
			GLBKCGACIHK().Add(cLJOMPBCNOE79.KGHMFHDGNEO(), cLJOMPBCNOE79);
			CLJOMPBCNOE cLJOMPBCNOE80 = new CLJOMPBCNOE(23010, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE80.GAFNNDHJDAE = "상급 체력 인장";
			cLJOMPBCNOE80.MGGCDFHFMKK = 8200;
			cLJOMPBCNOE80.FLNFNOEDLFN = 20;
			cLJOMPBCNOE80.NCBAGGNLLLK = 8f;
			GLBKCGACIHK().Add(cLJOMPBCNOE80.KGHMFHDGNEO(), cLJOMPBCNOE80);
			CLJOMPBCNOE cLJOMPBCNOE81 = new CLJOMPBCNOE(23011, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE81.GAFNNDHJDAE = "상급 성장 체력 인장";
			cLJOMPBCNOE81.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE81.FLNFNOEDLFN = 20;
			cLJOMPBCNOE81.MDAGHJFEODE = 1.34f;
			GLBKCGACIHK().Add(cLJOMPBCNOE81.KGHMFHDGNEO(), cLJOMPBCNOE81);
			CLJOMPBCNOE cLJOMPBCNOE82 = new CLJOMPBCNOE(23012, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE82.GAFNNDHJDAE = "상급 치명타 확률 인장";
			cLJOMPBCNOE82.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE82.FLNFNOEDLFN = 20;
			cLJOMPBCNOE82.CJALIPCFCLA = 0.0042f;
			GLBKCGACIHK().Add(cLJOMPBCNOE82.KGHMFHDGNEO(), cLJOMPBCNOE82);
			CLJOMPBCNOE cLJOMPBCNOE83 = new CLJOMPBCNOE(23013, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE83.GAFNNDHJDAE = "상급 방어력 인장";
			cLJOMPBCNOE83.MGGCDFHFMKK = 2050;
			cLJOMPBCNOE83.FLNFNOEDLFN = 20;
			cLJOMPBCNOE83.FBEBCNEPHJD = 1f;
			GLBKCGACIHK().Add(cLJOMPBCNOE83.KGHMFHDGNEO(), cLJOMPBCNOE83);
			CLJOMPBCNOE cLJOMPBCNOE84 = new CLJOMPBCNOE(23014, CLJOMPBCNOE.ACPICCBBPHF.Seal, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE84.GAFNNDHJDAE = "상급 마법저항력 인장";
			cLJOMPBCNOE84.MGGCDFHFMKK = 2050;
			cLJOMPBCNOE84.FLNFNOEDLFN = 20;
			cLJOMPBCNOE84.NLMHKBGDKLA = 0.74f;
			GLBKCGACIHK().Add(cLJOMPBCNOE84.KGHMFHDGNEO(), cLJOMPBCNOE84);
			CLJOMPBCNOE cLJOMPBCNOE85 = new CLJOMPBCNOE(31001, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE85.GAFNNDHJDAE = "하급 공격력 문양";
			cLJOMPBCNOE85.MGGCDFHFMKK = 150;
			cLJOMPBCNOE85.FLNFNOEDLFN = 1;
			cLJOMPBCNOE85.LHEKBMLAJMA = 0.16f;
			GLBKCGACIHK().Add(cLJOMPBCNOE85.KGHMFHDGNEO(), cLJOMPBCNOE85);
			CLJOMPBCNOE cLJOMPBCNOE86 = new CLJOMPBCNOE(31002, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE86.GAFNNDHJDAE = "하급 성장 공격력 문양";
			cLJOMPBCNOE86.MGGCDFHFMKK = 150;
			cLJOMPBCNOE86.FLNFNOEDLFN = 1;
			cLJOMPBCNOE86.JGPIIFFIAIG = 0.02f;
			GLBKCGACIHK().Add(cLJOMPBCNOE86.KGHMFHDGNEO(), cLJOMPBCNOE86);
			CLJOMPBCNOE cLJOMPBCNOE87 = new CLJOMPBCNOE(31003, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE87.GAFNNDHJDAE = "하급 공격속도 문양";
			cLJOMPBCNOE87.MGGCDFHFMKK = 300;
			cLJOMPBCNOE87.FLNFNOEDLFN = 1;
			cLJOMPBCNOE87.NMFDEKCMJAH = 0.0035f;
			GLBKCGACIHK().Add(cLJOMPBCNOE87.KGHMFHDGNEO(), cLJOMPBCNOE87);
			CLJOMPBCNOE cLJOMPBCNOE88 = new CLJOMPBCNOE(31004, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE88.GAFNNDHJDAE = "하급 주문력 문양";
			cLJOMPBCNOE88.MGGCDFHFMKK = 300;
			cLJOMPBCNOE88.FLNFNOEDLFN = 1;
			cLJOMPBCNOE88.KBMBFHHNDPE = 0.66f;
			GLBKCGACIHK().Add(cLJOMPBCNOE88.KGHMFHDGNEO(), cLJOMPBCNOE88);
			CLJOMPBCNOE cLJOMPBCNOE89 = new CLJOMPBCNOE(31005, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE89.GAFNNDHJDAE = "하급 성장 주문력 문양";
			cLJOMPBCNOE89.MGGCDFHFMKK = 300;
			cLJOMPBCNOE89.FLNFNOEDLFN = 1;
			cLJOMPBCNOE89.OOJHKLBFHED = 0.1f;
			GLBKCGACIHK().Add(cLJOMPBCNOE89.KGHMFHDGNEO(), cLJOMPBCNOE89);
			CLJOMPBCNOE cLJOMPBCNOE90 = new CLJOMPBCNOE(31006, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE90.GAFNNDHJDAE = "하급 대기시간감소 문양";
			cLJOMPBCNOE90.MGGCDFHFMKK = 650;
			cLJOMPBCNOE90.FLNFNOEDLFN = 1;
			cLJOMPBCNOE90.BDKLLIMAGPP = 0.0047f;
			GLBKCGACIHK().Add(cLJOMPBCNOE90.KGHMFHDGNEO(), cLJOMPBCNOE90);
			CLJOMPBCNOE cLJOMPBCNOE91 = new CLJOMPBCNOE(31007, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE91.GAFNNDHJDAE = "하급 마나 문양";
			cLJOMPBCNOE91.MGGCDFHFMKK = 300;
			cLJOMPBCNOE91.FLNFNOEDLFN = 1;
			cLJOMPBCNOE91.BELPBCDOPBA = 6.25f;
			GLBKCGACIHK().Add(cLJOMPBCNOE91.KGHMFHDGNEO(), cLJOMPBCNOE91);
			CLJOMPBCNOE cLJOMPBCNOE92 = new CLJOMPBCNOE(31008, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE92.GAFNNDHJDAE = "하급 성장 마나 문양";
			cLJOMPBCNOE92.MGGCDFHFMKK = 300;
			cLJOMPBCNOE92.FLNFNOEDLFN = 1;
			cLJOMPBCNOE92.BJHADLMCNJO = 0.79f;
			GLBKCGACIHK().Add(cLJOMPBCNOE92.KGHMFHDGNEO(), cLJOMPBCNOE92);
			CLJOMPBCNOE cLJOMPBCNOE93 = new CLJOMPBCNOE(31009, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE93.GAFNNDHJDAE = "하급 마나 재생 문양";
			cLJOMPBCNOE93.MGGCDFHFMKK = 300;
			cLJOMPBCNOE93.FLNFNOEDLFN = 1;
			cLJOMPBCNOE93.MGLIOBDEJLF = 0.19f;
			GLBKCGACIHK().Add(cLJOMPBCNOE93.KGHMFHDGNEO(), cLJOMPBCNOE93);
			CLJOMPBCNOE cLJOMPBCNOE94 = new CLJOMPBCNOE(31010, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE94.GAFNNDHJDAE = "하급 체력 문양";
			cLJOMPBCNOE94.MGGCDFHFMKK = 300;
			cLJOMPBCNOE94.FLNFNOEDLFN = 1;
			cLJOMPBCNOE94.NCBAGGNLLLK = 1.49f;
			GLBKCGACIHK().Add(cLJOMPBCNOE94.KGHMFHDGNEO(), cLJOMPBCNOE94);
			CLJOMPBCNOE cLJOMPBCNOE95 = new CLJOMPBCNOE(31011, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE95.GAFNNDHJDAE = "하급 성장 체력 문양";
			cLJOMPBCNOE95.MGGCDFHFMKK = 650;
			cLJOMPBCNOE95.FLNFNOEDLFN = 1;
			cLJOMPBCNOE95.MDAGHJFEODE = 0.3f;
			GLBKCGACIHK().Add(cLJOMPBCNOE95.KGHMFHDGNEO(), cLJOMPBCNOE95);
			CLJOMPBCNOE cLJOMPBCNOE96 = new CLJOMPBCNOE(31012, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE96.GAFNNDHJDAE = "하급 치명타 확률 문양";
			cLJOMPBCNOE96.MGGCDFHFMKK = 650;
			cLJOMPBCNOE96.FLNFNOEDLFN = 1;
			cLJOMPBCNOE96.CJALIPCFCLA = 0.0015f;
			GLBKCGACIHK().Add(cLJOMPBCNOE96.KGHMFHDGNEO(), cLJOMPBCNOE96);
			CLJOMPBCNOE cLJOMPBCNOE97 = new CLJOMPBCNOE(31013, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE97.GAFNNDHJDAE = "하급 방어력 문양";
			cLJOMPBCNOE97.MGGCDFHFMKK = 150;
			cLJOMPBCNOE97.FLNFNOEDLFN = 1;
			cLJOMPBCNOE97.FBEBCNEPHJD = 0.39f;
			GLBKCGACIHK().Add(cLJOMPBCNOE97.KGHMFHDGNEO(), cLJOMPBCNOE97);
			CLJOMPBCNOE cLJOMPBCNOE98 = new CLJOMPBCNOE(31014, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE98.GAFNNDHJDAE = "하급 마법저항력 문양";
			cLJOMPBCNOE98.MGGCDFHFMKK = 150;
			cLJOMPBCNOE98.FLNFNOEDLFN = 1;
			cLJOMPBCNOE98.NLMHKBGDKLA = 0.74f;
			GLBKCGACIHK().Add(cLJOMPBCNOE98.KGHMFHDGNEO(), cLJOMPBCNOE98);
			CLJOMPBCNOE cLJOMPBCNOE99 = new CLJOMPBCNOE(32001, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE99.GAFNNDHJDAE = "중급 공격력 문양";
			cLJOMPBCNOE99.MGGCDFHFMKK = 800;
			cLJOMPBCNOE99.FLNFNOEDLFN = 10;
			cLJOMPBCNOE99.LHEKBMLAJMA = 0.22f;
			GLBKCGACIHK().Add(cLJOMPBCNOE99.KGHMFHDGNEO(), cLJOMPBCNOE99);
			CLJOMPBCNOE cLJOMPBCNOE100 = new CLJOMPBCNOE(32002, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE100.GAFNNDHJDAE = "중급 성장 공격력 문양";
			cLJOMPBCNOE100.MGGCDFHFMKK = 800;
			cLJOMPBCNOE100.FLNFNOEDLFN = 10;
			cLJOMPBCNOE100.JGPIIFFIAIG = 0.03f;
			GLBKCGACIHK().Add(cLJOMPBCNOE100.KGHMFHDGNEO(), cLJOMPBCNOE100);
			CLJOMPBCNOE cLJOMPBCNOE101 = new CLJOMPBCNOE(32003, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE101.GAFNNDHJDAE = "중급 공격속도 문양";
			cLJOMPBCNOE101.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE101.FLNFNOEDLFN = 10;
			cLJOMPBCNOE101.NMFDEKCMJAH = 0.005f;
			GLBKCGACIHK().Add(cLJOMPBCNOE101.KGHMFHDGNEO(), cLJOMPBCNOE101);
			CLJOMPBCNOE cLJOMPBCNOE102 = new CLJOMPBCNOE(32004, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE102.GAFNNDHJDAE = "중급 주문력 문양";
			cLJOMPBCNOE102.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE102.FLNFNOEDLFN = 10;
			cLJOMPBCNOE102.KBMBFHHNDPE = 0.92f;
			GLBKCGACIHK().Add(cLJOMPBCNOE102.KGHMFHDGNEO(), cLJOMPBCNOE102);
			CLJOMPBCNOE cLJOMPBCNOE103 = new CLJOMPBCNOE(32005, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE103.GAFNNDHJDAE = "중급 성장 주문력 문양";
			cLJOMPBCNOE103.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE103.FLNFNOEDLFN = 10;
			cLJOMPBCNOE103.OOJHKLBFHED = 0.13f;
			GLBKCGACIHK().Add(cLJOMPBCNOE103.KGHMFHDGNEO(), cLJOMPBCNOE103);
			CLJOMPBCNOE cLJOMPBCNOE104 = new CLJOMPBCNOE(32006, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE104.GAFNNDHJDAE = "중급 대기시간감소 문양";
			cLJOMPBCNOE104.MGGCDFHFMKK = 3300;
			cLJOMPBCNOE104.FLNFNOEDLFN = 10;
			cLJOMPBCNOE104.BDKLLIMAGPP = 0.0067f;
			GLBKCGACIHK().Add(cLJOMPBCNOE104.KGHMFHDGNEO(), cLJOMPBCNOE104);
			CLJOMPBCNOE cLJOMPBCNOE105 = new CLJOMPBCNOE(32007, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE105.GAFNNDHJDAE = "중급 마나 문양";
			cLJOMPBCNOE105.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE105.FLNFNOEDLFN = 10;
			cLJOMPBCNOE105.BELPBCDOPBA = 8.75f;
			GLBKCGACIHK().Add(cLJOMPBCNOE105.KGHMFHDGNEO(), cLJOMPBCNOE105);
			CLJOMPBCNOE cLJOMPBCNOE106 = new CLJOMPBCNOE(32008, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE106.GAFNNDHJDAE = "중급 성장 마나 문양";
			cLJOMPBCNOE106.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE106.FLNFNOEDLFN = 10;
			cLJOMPBCNOE106.BJHADLMCNJO = 1.1f;
			GLBKCGACIHK().Add(cLJOMPBCNOE106.KGHMFHDGNEO(), cLJOMPBCNOE106);
			CLJOMPBCNOE cLJOMPBCNOE107 = new CLJOMPBCNOE(32009, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE107.GAFNNDHJDAE = "중급 마나 재생 문양";
			cLJOMPBCNOE107.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE107.FLNFNOEDLFN = 10;
			cLJOMPBCNOE107.MGLIOBDEJLF = 0.26f;
			GLBKCGACIHK().Add(cLJOMPBCNOE107.KGHMFHDGNEO(), cLJOMPBCNOE107);
			CLJOMPBCNOE cLJOMPBCNOE108 = new CLJOMPBCNOE(32010, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE108.GAFNNDHJDAE = "중급 체력 문양";
			cLJOMPBCNOE108.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE108.FLNFNOEDLFN = 10;
			cLJOMPBCNOE108.NCBAGGNLLLK = 2.08f;
			GLBKCGACIHK().Add(cLJOMPBCNOE108.KGHMFHDGNEO(), cLJOMPBCNOE108);
			CLJOMPBCNOE cLJOMPBCNOE109 = new CLJOMPBCNOE(32011, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE109.GAFNNDHJDAE = "중급 성장 체력 문양";
			cLJOMPBCNOE109.MGGCDFHFMKK = 3300;
			cLJOMPBCNOE109.FLNFNOEDLFN = 10;
			cLJOMPBCNOE109.MDAGHJFEODE = 0.42f;
			GLBKCGACIHK().Add(cLJOMPBCNOE109.KGHMFHDGNEO(), cLJOMPBCNOE109);
			CLJOMPBCNOE cLJOMPBCNOE110 = new CLJOMPBCNOE(32012, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE110.GAFNNDHJDAE = "중급 치명타 확률 문양";
			cLJOMPBCNOE110.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE110.FLNFNOEDLFN = 10;
			cLJOMPBCNOE110.CJALIPCFCLA = 0.0022f;
			GLBKCGACIHK().Add(cLJOMPBCNOE110.KGHMFHDGNEO(), cLJOMPBCNOE110);
			CLJOMPBCNOE cLJOMPBCNOE111 = new CLJOMPBCNOE(32013, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE111.GAFNNDHJDAE = "중급 방어력 문양";
			cLJOMPBCNOE111.MGGCDFHFMKK = 800;
			cLJOMPBCNOE111.FLNFNOEDLFN = 10;
			cLJOMPBCNOE111.FBEBCNEPHJD = 0.55f;
			GLBKCGACIHK().Add(cLJOMPBCNOE111.KGHMFHDGNEO(), cLJOMPBCNOE111);
			CLJOMPBCNOE cLJOMPBCNOE112 = new CLJOMPBCNOE(32014, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE112.GAFNNDHJDAE = "중급 마법저항력 문양";
			cLJOMPBCNOE112.MGGCDFHFMKK = 800;
			cLJOMPBCNOE112.FLNFNOEDLFN = 10;
			cLJOMPBCNOE112.NLMHKBGDKLA = 1.04f;
			GLBKCGACIHK().Add(cLJOMPBCNOE112.KGHMFHDGNEO(), cLJOMPBCNOE112);
			CLJOMPBCNOE cLJOMPBCNOE113 = new CLJOMPBCNOE(33001, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE113.GAFNNDHJDAE = "상급 공격력 문양";
			cLJOMPBCNOE113.MGGCDFHFMKK = 2050;
			cLJOMPBCNOE113.FLNFNOEDLFN = 20;
			cLJOMPBCNOE113.LHEKBMLAJMA = 0.28f;
			GLBKCGACIHK().Add(cLJOMPBCNOE113.KGHMFHDGNEO(), cLJOMPBCNOE113);
			CLJOMPBCNOE cLJOMPBCNOE114 = new CLJOMPBCNOE(33002, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE114.GAFNNDHJDAE = "상급 성장 공격력 문양";
			cLJOMPBCNOE114.MGGCDFHFMKK = 2050;
			cLJOMPBCNOE114.FLNFNOEDLFN = 20;
			cLJOMPBCNOE114.JGPIIFFIAIG = 0.04f;
			GLBKCGACIHK().Add(cLJOMPBCNOE114.KGHMFHDGNEO(), cLJOMPBCNOE114);
			CLJOMPBCNOE cLJOMPBCNOE115 = new CLJOMPBCNOE(33003, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE115.GAFNNDHJDAE = "상급 공격속도 문양";
			cLJOMPBCNOE115.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE115.FLNFNOEDLFN = 20;
			cLJOMPBCNOE115.NMFDEKCMJAH = 0.0064f;
			GLBKCGACIHK().Add(cLJOMPBCNOE115.KGHMFHDGNEO(), cLJOMPBCNOE115);
			CLJOMPBCNOE cLJOMPBCNOE116 = new CLJOMPBCNOE(33004, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE116.GAFNNDHJDAE = "상급 주문력 문양";
			cLJOMPBCNOE116.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE116.FLNFNOEDLFN = 20;
			cLJOMPBCNOE116.KBMBFHHNDPE = 1.19f;
			GLBKCGACIHK().Add(cLJOMPBCNOE116.KGHMFHDGNEO(), cLJOMPBCNOE116);
			CLJOMPBCNOE cLJOMPBCNOE117 = new CLJOMPBCNOE(33005, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE117.GAFNNDHJDAE = "상급 성장 주문력 문양";
			cLJOMPBCNOE117.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE117.FLNFNOEDLFN = 20;
			cLJOMPBCNOE117.OOJHKLBFHED = 0.17f;
			GLBKCGACIHK().Add(cLJOMPBCNOE117.KGHMFHDGNEO(), cLJOMPBCNOE117);
			CLJOMPBCNOE cLJOMPBCNOE118 = new CLJOMPBCNOE(33006, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE118.GAFNNDHJDAE = "상급 대기시간감소 문양";
			cLJOMPBCNOE118.MGGCDFHFMKK = 8200;
			cLJOMPBCNOE118.FLNFNOEDLFN = 20;
			cLJOMPBCNOE118.BDKLLIMAGPP = 0.0083f;
			GLBKCGACIHK().Add(cLJOMPBCNOE118.KGHMFHDGNEO(), cLJOMPBCNOE118);
			CLJOMPBCNOE cLJOMPBCNOE119 = new CLJOMPBCNOE(33007, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE119.GAFNNDHJDAE = "상급 마나 문양";
			cLJOMPBCNOE119.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE119.FLNFNOEDLFN = 20;
			cLJOMPBCNOE119.BELPBCDOPBA = 11.25f;
			GLBKCGACIHK().Add(cLJOMPBCNOE119.KGHMFHDGNEO(), cLJOMPBCNOE119);
			CLJOMPBCNOE cLJOMPBCNOE120 = new CLJOMPBCNOE(33008, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE120.GAFNNDHJDAE = "상급 성장 마나 문양";
			cLJOMPBCNOE120.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE120.FLNFNOEDLFN = 20;
			cLJOMPBCNOE120.BJHADLMCNJO = 1.42f;
			GLBKCGACIHK().Add(cLJOMPBCNOE120.KGHMFHDGNEO(), cLJOMPBCNOE120);
			CLJOMPBCNOE cLJOMPBCNOE121 = new CLJOMPBCNOE(33009, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE121.GAFNNDHJDAE = "상급 마나 재생 문양";
			cLJOMPBCNOE121.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE121.FLNFNOEDLFN = 20;
			cLJOMPBCNOE121.MGLIOBDEJLF = 0.33f;
			GLBKCGACIHK().Add(cLJOMPBCNOE121.KGHMFHDGNEO(), cLJOMPBCNOE121);
			CLJOMPBCNOE cLJOMPBCNOE122 = new CLJOMPBCNOE(33010, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE122.GAFNNDHJDAE = "상급 체력 문양";
			cLJOMPBCNOE122.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE122.FLNFNOEDLFN = 20;
			cLJOMPBCNOE122.NCBAGGNLLLK = 2.67f;
			GLBKCGACIHK().Add(cLJOMPBCNOE122.KGHMFHDGNEO(), cLJOMPBCNOE122);
			CLJOMPBCNOE cLJOMPBCNOE123 = new CLJOMPBCNOE(33011, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE123.GAFNNDHJDAE = "상급 성장 체력 문양";
			cLJOMPBCNOE123.MGGCDFHFMKK = 8200;
			cLJOMPBCNOE123.FLNFNOEDLFN = 20;
			cLJOMPBCNOE123.MDAGHJFEODE = 0.54f;
			GLBKCGACIHK().Add(cLJOMPBCNOE123.KGHMFHDGNEO(), cLJOMPBCNOE123);
			CLJOMPBCNOE cLJOMPBCNOE124 = new CLJOMPBCNOE(33012, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE124.GAFNNDHJDAE = "상급 치명타 확률 문양";
			cLJOMPBCNOE124.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE124.FLNFNOEDLFN = 20;
			cLJOMPBCNOE124.CJALIPCFCLA = 0.0028f;
			GLBKCGACIHK().Add(cLJOMPBCNOE124.KGHMFHDGNEO(), cLJOMPBCNOE124);
			CLJOMPBCNOE cLJOMPBCNOE125 = new CLJOMPBCNOE(33013, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE125.GAFNNDHJDAE = "상급 방어력 문양";
			cLJOMPBCNOE125.MGGCDFHFMKK = 2050;
			cLJOMPBCNOE125.FLNFNOEDLFN = 20;
			cLJOMPBCNOE125.FBEBCNEPHJD = 0.7f;
			GLBKCGACIHK().Add(cLJOMPBCNOE125.KGHMFHDGNEO(), cLJOMPBCNOE125);
			CLJOMPBCNOE cLJOMPBCNOE126 = new CLJOMPBCNOE(33014, CLJOMPBCNOE.ACPICCBBPHF.Glyph, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE126.GAFNNDHJDAE = "상급 마법저항력 문양";
			cLJOMPBCNOE126.MGGCDFHFMKK = 2050;
			cLJOMPBCNOE126.FLNFNOEDLFN = 20;
			cLJOMPBCNOE126.NLMHKBGDKLA = 1.34f;
			GLBKCGACIHK().Add(cLJOMPBCNOE126.KGHMFHDGNEO(), cLJOMPBCNOE126);
			CLJOMPBCNOE cLJOMPBCNOE127 = new CLJOMPBCNOE(41001, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE127.GAFNNDHJDAE = "하급 공격력 정수";
			cLJOMPBCNOE127.MGGCDFHFMKK = 800;
			cLJOMPBCNOE127.FLNFNOEDLFN = 10;
			cLJOMPBCNOE127.LHEKBMLAJMA = 1.25f;
			GLBKCGACIHK().Add(cLJOMPBCNOE127.KGHMFHDGNEO(), cLJOMPBCNOE127);
			CLJOMPBCNOE cLJOMPBCNOE128 = new CLJOMPBCNOE(41002, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE128.GAFNNDHJDAE = "하급 성장 공격력 정수";
			cLJOMPBCNOE128.MGGCDFHFMKK = 400;
			cLJOMPBCNOE128.FLNFNOEDLFN = 10;
			cLJOMPBCNOE128.JGPIIFFIAIG = 0.14f;
			GLBKCGACIHK().Add(cLJOMPBCNOE128.KGHMFHDGNEO(), cLJOMPBCNOE128);
			CLJOMPBCNOE cLJOMPBCNOE129 = new CLJOMPBCNOE(41003, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE129.GAFNNDHJDAE = "하급 공격속도 정수";
			cLJOMPBCNOE129.MGGCDFHFMKK = 800;
			cLJOMPBCNOE129.FLNFNOEDLFN = 10;
			cLJOMPBCNOE129.NMFDEKCMJAH = 0.0252f;
			GLBKCGACIHK().Add(cLJOMPBCNOE129.KGHMFHDGNEO(), cLJOMPBCNOE129);
			CLJOMPBCNOE cLJOMPBCNOE130 = new CLJOMPBCNOE(41004, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE130.GAFNNDHJDAE = "하급 주문력 정수";
			cLJOMPBCNOE130.MGGCDFHFMKK = 800;
			cLJOMPBCNOE130.FLNFNOEDLFN = 10;
			cLJOMPBCNOE130.KBMBFHHNDPE = 2.75f;
			GLBKCGACIHK().Add(cLJOMPBCNOE130.KGHMFHDGNEO(), cLJOMPBCNOE130);
			CLJOMPBCNOE cLJOMPBCNOE131 = new CLJOMPBCNOE(41005, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE131.GAFNNDHJDAE = "하급 성장 주문력 정수";
			cLJOMPBCNOE131.MGGCDFHFMKK = 800;
			cLJOMPBCNOE131.FLNFNOEDLFN = 10;
			cLJOMPBCNOE131.OOJHKLBFHED = 0.24f;
			GLBKCGACIHK().Add(cLJOMPBCNOE131.KGHMFHDGNEO(), cLJOMPBCNOE131);
			CLJOMPBCNOE cLJOMPBCNOE132 = new CLJOMPBCNOE(41006, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE132.GAFNNDHJDAE = "하급 대기시간감소 정수";
			cLJOMPBCNOE132.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE132.FLNFNOEDLFN = 10;
			cLJOMPBCNOE132.BDKLLIMAGPP = 0.014f;
			GLBKCGACIHK().Add(cLJOMPBCNOE132.KGHMFHDGNEO(), cLJOMPBCNOE132);
			CLJOMPBCNOE cLJOMPBCNOE133 = new CLJOMPBCNOE(41007, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE133.GAFNNDHJDAE = "하급 마나 정수";
			cLJOMPBCNOE133.MGGCDFHFMKK = 800;
			cLJOMPBCNOE133.FLNFNOEDLFN = 10;
			cLJOMPBCNOE133.BELPBCDOPBA = 20.83f;
			GLBKCGACIHK().Add(cLJOMPBCNOE133.KGHMFHDGNEO(), cLJOMPBCNOE133);
			CLJOMPBCNOE cLJOMPBCNOE134 = new CLJOMPBCNOE(41008, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE134.GAFNNDHJDAE = "하급 성장 마나 정수";
			cLJOMPBCNOE134.MGGCDFHFMKK = 400;
			cLJOMPBCNOE134.FLNFNOEDLFN = 10;
			cLJOMPBCNOE134.BJHADLMCNJO = 2.31f;
			GLBKCGACIHK().Add(cLJOMPBCNOE134.KGHMFHDGNEO(), cLJOMPBCNOE134);
			CLJOMPBCNOE cLJOMPBCNOE135 = new CLJOMPBCNOE(41009, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE135.GAFNNDHJDAE = "하급 마나 재생 정수";
			cLJOMPBCNOE135.MGGCDFHFMKK = 800;
			cLJOMPBCNOE135.FLNFNOEDLFN = 10;
			cLJOMPBCNOE135.MGLIOBDEJLF = 0.69f;
			GLBKCGACIHK().Add(cLJOMPBCNOE135.KGHMFHDGNEO(), cLJOMPBCNOE135);
			CLJOMPBCNOE cLJOMPBCNOE136 = new CLJOMPBCNOE(41010, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE136.GAFNNDHJDAE = "하급 체력 정수";
			cLJOMPBCNOE136.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE136.FLNFNOEDLFN = 10;
			cLJOMPBCNOE136.NCBAGGNLLLK = 14.5f;
			GLBKCGACIHK().Add(cLJOMPBCNOE136.KGHMFHDGNEO(), cLJOMPBCNOE136);
			CLJOMPBCNOE cLJOMPBCNOE137 = new CLJOMPBCNOE(41011, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE137.GAFNNDHJDAE = "하급 성장 체력 정수";
			cLJOMPBCNOE137.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE137.FLNFNOEDLFN = 10;
			cLJOMPBCNOE137.MDAGHJFEODE = 1.5f;
			GLBKCGACIHK().Add(cLJOMPBCNOE137.KGHMFHDGNEO(), cLJOMPBCNOE137);
			CLJOMPBCNOE cLJOMPBCNOE138 = new CLJOMPBCNOE(41012, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE138.GAFNNDHJDAE = "하급 치명타 확률 정수";
			cLJOMPBCNOE138.MGGCDFHFMKK = 800;
			cLJOMPBCNOE138.FLNFNOEDLFN = 10;
			cLJOMPBCNOE138.CJALIPCFCLA = 0.0103f;
			GLBKCGACIHK().Add(cLJOMPBCNOE138.KGHMFHDGNEO(), cLJOMPBCNOE138);
			CLJOMPBCNOE cLJOMPBCNOE139 = new CLJOMPBCNOE(41013, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE139.GAFNNDHJDAE = "하급 방어력 정수";
			cLJOMPBCNOE139.MGGCDFHFMKK = 800;
			cLJOMPBCNOE139.FLNFNOEDLFN = 10;
			cLJOMPBCNOE139.FBEBCNEPHJD = 2.37f;
			GLBKCGACIHK().Add(cLJOMPBCNOE139.KGHMFHDGNEO(), cLJOMPBCNOE139);
			CLJOMPBCNOE cLJOMPBCNOE140 = new CLJOMPBCNOE(41014, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE140.GAFNNDHJDAE = "하급 마법저항력 정수";
			cLJOMPBCNOE140.MGGCDFHFMKK = 800;
			cLJOMPBCNOE140.FLNFNOEDLFN = 10;
			cLJOMPBCNOE140.NLMHKBGDKLA = 2.22f;
			GLBKCGACIHK().Add(cLJOMPBCNOE140.KGHMFHDGNEO(), cLJOMPBCNOE140);
			CLJOMPBCNOE cLJOMPBCNOE141 = new CLJOMPBCNOE(41015, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE141.GAFNNDHJDAE = "하급 생명력흡수 정수";
			cLJOMPBCNOE141.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE141.FLNFNOEDLFN = 10;
			cLJOMPBCNOE141.PPNKFFAHHBB = 0.0084f;
			GLBKCGACIHK().Add(cLJOMPBCNOE141.KGHMFHDGNEO(), cLJOMPBCNOE141);
			CLJOMPBCNOE cLJOMPBCNOE142 = new CLJOMPBCNOE(41016, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Low);
			cLJOMPBCNOE142.GAFNNDHJDAE = "하급 주문흡혈 정수";
			cLJOMPBCNOE142.MGGCDFHFMKK = 1650;
			cLJOMPBCNOE142.FLNFNOEDLFN = 10;
			cLJOMPBCNOE142.MOHEOOEFLNK = 0.0112f;
			GLBKCGACIHK().Add(cLJOMPBCNOE142.KGHMFHDGNEO(), cLJOMPBCNOE142);
			CLJOMPBCNOE cLJOMPBCNOE143 = new CLJOMPBCNOE(42001, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE143.GAFNNDHJDAE = "중급 공격력 정수";
			cLJOMPBCNOE143.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE143.FLNFNOEDLFN = 20;
			cLJOMPBCNOE143.LHEKBMLAJMA = 1.75f;
			GLBKCGACIHK().Add(cLJOMPBCNOE143.KGHMFHDGNEO(), cLJOMPBCNOE143);
			CLJOMPBCNOE cLJOMPBCNOE144 = new CLJOMPBCNOE(42002, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE144.GAFNNDHJDAE = "중급 성장 공격력 정수";
			cLJOMPBCNOE144.MGGCDFHFMKK = 2050;
			cLJOMPBCNOE144.FLNFNOEDLFN = 20;
			cLJOMPBCNOE144.JGPIIFFIAIG = 0.19f;
			GLBKCGACIHK().Add(cLJOMPBCNOE144.KGHMFHDGNEO(), cLJOMPBCNOE144);
			CLJOMPBCNOE cLJOMPBCNOE145 = new CLJOMPBCNOE(42003, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE145.GAFNNDHJDAE = "중급 공격속도 정수";
			cLJOMPBCNOE145.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE145.FLNFNOEDLFN = 20;
			cLJOMPBCNOE145.NMFDEKCMJAH = 0.0351f;
			GLBKCGACIHK().Add(cLJOMPBCNOE145.KGHMFHDGNEO(), cLJOMPBCNOE145);
			CLJOMPBCNOE cLJOMPBCNOE146 = new CLJOMPBCNOE(42004, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE146.GAFNNDHJDAE = "중급 주문력 정수";
			cLJOMPBCNOE146.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE146.FLNFNOEDLFN = 20;
			cLJOMPBCNOE146.KBMBFHHNDPE = 3.85f;
			GLBKCGACIHK().Add(cLJOMPBCNOE146.KGHMFHDGNEO(), cLJOMPBCNOE146);
			CLJOMPBCNOE cLJOMPBCNOE147 = new CLJOMPBCNOE(42005, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE147.GAFNNDHJDAE = "중급 성장 주문력 정수";
			cLJOMPBCNOE147.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE147.FLNFNOEDLFN = 20;
			cLJOMPBCNOE147.OOJHKLBFHED = 0.34f;
			GLBKCGACIHK().Add(cLJOMPBCNOE147.KGHMFHDGNEO(), cLJOMPBCNOE147);
			CLJOMPBCNOE cLJOMPBCNOE148 = new CLJOMPBCNOE(42006, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE148.GAFNNDHJDAE = "중급 대기시간감소 정수";
			cLJOMPBCNOE148.MGGCDFHFMKK = 8200;
			cLJOMPBCNOE148.FLNFNOEDLFN = 20;
			cLJOMPBCNOE148.BDKLLIMAGPP = 0.0195f;
			GLBKCGACIHK().Add(cLJOMPBCNOE148.KGHMFHDGNEO(), cLJOMPBCNOE148);
			CLJOMPBCNOE cLJOMPBCNOE149 = new CLJOMPBCNOE(42007, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE149.GAFNNDHJDAE = "중급 마나 정수";
			cLJOMPBCNOE149.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE149.FLNFNOEDLFN = 20;
			cLJOMPBCNOE149.BELPBCDOPBA = 29.17f;
			GLBKCGACIHK().Add(cLJOMPBCNOE149.KGHMFHDGNEO(), cLJOMPBCNOE149);
			CLJOMPBCNOE cLJOMPBCNOE150 = new CLJOMPBCNOE(42008, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE150.GAFNNDHJDAE = "중급 성장 마나 정수";
			cLJOMPBCNOE150.MGGCDFHFMKK = 2050;
			cLJOMPBCNOE150.FLNFNOEDLFN = 20;
			cLJOMPBCNOE150.BJHADLMCNJO = 3.24f;
			GLBKCGACIHK().Add(cLJOMPBCNOE150.KGHMFHDGNEO(), cLJOMPBCNOE150);
			CLJOMPBCNOE cLJOMPBCNOE151 = new CLJOMPBCNOE(42009, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE151.GAFNNDHJDAE = "중급 마나 재생 정수";
			cLJOMPBCNOE151.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE151.FLNFNOEDLFN = 20;
			cLJOMPBCNOE151.MGLIOBDEJLF = 0.97f;
			GLBKCGACIHK().Add(cLJOMPBCNOE151.KGHMFHDGNEO(), cLJOMPBCNOE151);
			CLJOMPBCNOE cLJOMPBCNOE152 = new CLJOMPBCNOE(42010, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE152.GAFNNDHJDAE = "중급 체력 정수";
			cLJOMPBCNOE152.MGGCDFHFMKK = 8200;
			cLJOMPBCNOE152.FLNFNOEDLFN = 20;
			cLJOMPBCNOE152.NCBAGGNLLLK = 20f;
			GLBKCGACIHK().Add(cLJOMPBCNOE152.KGHMFHDGNEO(), cLJOMPBCNOE152);
			CLJOMPBCNOE cLJOMPBCNOE153 = new CLJOMPBCNOE(42011, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE153.GAFNNDHJDAE = "중급 성장 체력 정수";
			cLJOMPBCNOE153.MGGCDFHFMKK = 8200;
			cLJOMPBCNOE153.FLNFNOEDLFN = 20;
			cLJOMPBCNOE153.MDAGHJFEODE = 2.1f;
			GLBKCGACIHK().Add(cLJOMPBCNOE153.KGHMFHDGNEO(), cLJOMPBCNOE153);
			CLJOMPBCNOE cLJOMPBCNOE154 = new CLJOMPBCNOE(42012, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE154.GAFNNDHJDAE = "중급 치명타 확률 정수";
			cLJOMPBCNOE154.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE154.FLNFNOEDLFN = 20;
			cLJOMPBCNOE154.CJALIPCFCLA = 0.0144f;
			GLBKCGACIHK().Add(cLJOMPBCNOE154.KGHMFHDGNEO(), cLJOMPBCNOE154);
			CLJOMPBCNOE cLJOMPBCNOE155 = new CLJOMPBCNOE(42013, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE155.GAFNNDHJDAE = "중급 방어력 정수";
			cLJOMPBCNOE155.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE155.FLNFNOEDLFN = 20;
			cLJOMPBCNOE155.FBEBCNEPHJD = 3.32f;
			GLBKCGACIHK().Add(cLJOMPBCNOE155.KGHMFHDGNEO(), cLJOMPBCNOE155);
			CLJOMPBCNOE cLJOMPBCNOE156 = new CLJOMPBCNOE(42014, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE156.GAFNNDHJDAE = "중급 마법저항력 정수";
			cLJOMPBCNOE156.MGGCDFHFMKK = 4100;
			cLJOMPBCNOE156.FLNFNOEDLFN = 20;
			cLJOMPBCNOE156.NLMHKBGDKLA = 3.11f;
			GLBKCGACIHK().Add(cLJOMPBCNOE156.KGHMFHDGNEO(), cLJOMPBCNOE156);
			CLJOMPBCNOE cLJOMPBCNOE157 = new CLJOMPBCNOE(42015, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE157.GAFNNDHJDAE = "중급 생명력흡수 정수";
			cLJOMPBCNOE157.MGGCDFHFMKK = 8200;
			cLJOMPBCNOE157.FLNFNOEDLFN = 20;
			cLJOMPBCNOE157.PPNKFFAHHBB = 0.0117f;
			GLBKCGACIHK().Add(cLJOMPBCNOE157.KGHMFHDGNEO(), cLJOMPBCNOE157);
			CLJOMPBCNOE cLJOMPBCNOE158 = new CLJOMPBCNOE(42016, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.Normal);
			cLJOMPBCNOE158.GAFNNDHJDAE = "중급 주문흡혈 정수";
			cLJOMPBCNOE158.MGGCDFHFMKK = 8200;
			cLJOMPBCNOE158.FLNFNOEDLFN = 20;
			cLJOMPBCNOE158.MOHEOOEFLNK = 0.0156f;
			GLBKCGACIHK().Add(cLJOMPBCNOE158.KGHMFHDGNEO(), cLJOMPBCNOE158);
			CLJOMPBCNOE cLJOMPBCNOE159 = new CLJOMPBCNOE(43001, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE159.GAFNNDHJDAE = "상급 공격력 정수";
			cLJOMPBCNOE159.MGGCDFHFMKK = 10250;
			cLJOMPBCNOE159.FLNFNOEDLFN = 30;
			cLJOMPBCNOE159.LHEKBMLAJMA = 2.25f;
			GLBKCGACIHK().Add(cLJOMPBCNOE159.KGHMFHDGNEO(), cLJOMPBCNOE159);
			CLJOMPBCNOE cLJOMPBCNOE160 = new CLJOMPBCNOE(43002, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE160.GAFNNDHJDAE = "상급 성장 공격력 정수";
			cLJOMPBCNOE160.MGGCDFHFMKK = 5150;
			cLJOMPBCNOE160.FLNFNOEDLFN = 30;
			cLJOMPBCNOE160.JGPIIFFIAIG = 0.25f;
			GLBKCGACIHK().Add(cLJOMPBCNOE160.KGHMFHDGNEO(), cLJOMPBCNOE160);
			CLJOMPBCNOE cLJOMPBCNOE161 = new CLJOMPBCNOE(43003, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE161.GAFNNDHJDAE = "상급 공격속도 정수";
			cLJOMPBCNOE161.MGGCDFHFMKK = 10250;
			cLJOMPBCNOE161.FLNFNOEDLFN = 30;
			cLJOMPBCNOE161.NMFDEKCMJAH = 0.045f;
			GLBKCGACIHK().Add(cLJOMPBCNOE161.KGHMFHDGNEO(), cLJOMPBCNOE161);
			CLJOMPBCNOE cLJOMPBCNOE162 = new CLJOMPBCNOE(43004, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE162.GAFNNDHJDAE = "상급 주문력 정수";
			cLJOMPBCNOE162.MGGCDFHFMKK = 10250;
			cLJOMPBCNOE162.FLNFNOEDLFN = 30;
			cLJOMPBCNOE162.KBMBFHHNDPE = 4.95f;
			GLBKCGACIHK().Add(cLJOMPBCNOE162.KGHMFHDGNEO(), cLJOMPBCNOE162);
			CLJOMPBCNOE cLJOMPBCNOE163 = new CLJOMPBCNOE(43005, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE163.GAFNNDHJDAE = "상급 성장 주문력 정수";
			cLJOMPBCNOE163.MGGCDFHFMKK = 10250;
			cLJOMPBCNOE163.FLNFNOEDLFN = 30;
			cLJOMPBCNOE163.OOJHKLBFHED = 0.43f;
			GLBKCGACIHK().Add(cLJOMPBCNOE163.KGHMFHDGNEO(), cLJOMPBCNOE163);
			CLJOMPBCNOE cLJOMPBCNOE164 = new CLJOMPBCNOE(43006, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE164.GAFNNDHJDAE = "상급 대기시간감소 정수";
			cLJOMPBCNOE164.MGGCDFHFMKK = 20500;
			cLJOMPBCNOE164.FLNFNOEDLFN = 30;
			cLJOMPBCNOE164.BDKLLIMAGPP = 0.025f;
			GLBKCGACIHK().Add(cLJOMPBCNOE164.KGHMFHDGNEO(), cLJOMPBCNOE164);
			CLJOMPBCNOE cLJOMPBCNOE165 = new CLJOMPBCNOE(43007, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE165.GAFNNDHJDAE = "상급 마나 정수";
			cLJOMPBCNOE165.MGGCDFHFMKK = 10250;
			cLJOMPBCNOE165.FLNFNOEDLFN = 30;
			cLJOMPBCNOE165.BELPBCDOPBA = 37.5f;
			GLBKCGACIHK().Add(cLJOMPBCNOE165.KGHMFHDGNEO(), cLJOMPBCNOE165);
			CLJOMPBCNOE cLJOMPBCNOE166 = new CLJOMPBCNOE(43008, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE166.GAFNNDHJDAE = "상급 성장 마나 정수";
			cLJOMPBCNOE166.MGGCDFHFMKK = 5150;
			cLJOMPBCNOE166.FLNFNOEDLFN = 30;
			cLJOMPBCNOE166.BJHADLMCNJO = 4.17f;
			GLBKCGACIHK().Add(cLJOMPBCNOE166.KGHMFHDGNEO(), cLJOMPBCNOE166);
			CLJOMPBCNOE cLJOMPBCNOE167 = new CLJOMPBCNOE(43009, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE167.GAFNNDHJDAE = "상급 마나 재생 정수";
			cLJOMPBCNOE167.MGGCDFHFMKK = 10250;
			cLJOMPBCNOE167.FLNFNOEDLFN = 30;
			cLJOMPBCNOE167.MGLIOBDEJLF = 1.25f;
			GLBKCGACIHK().Add(cLJOMPBCNOE167.KGHMFHDGNEO(), cLJOMPBCNOE167);
			CLJOMPBCNOE cLJOMPBCNOE168 = new CLJOMPBCNOE(43010, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE168.GAFNNDHJDAE = "상급 체력 정수";
			cLJOMPBCNOE168.MGGCDFHFMKK = 20500;
			cLJOMPBCNOE168.FLNFNOEDLFN = 30;
			cLJOMPBCNOE168.NCBAGGNLLLK = 26f;
			GLBKCGACIHK().Add(cLJOMPBCNOE168.KGHMFHDGNEO(), cLJOMPBCNOE168);
			CLJOMPBCNOE cLJOMPBCNOE169 = new CLJOMPBCNOE(43011, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE169.GAFNNDHJDAE = "상급 성장 체력 정수";
			cLJOMPBCNOE169.MGGCDFHFMKK = 20500;
			cLJOMPBCNOE169.FLNFNOEDLFN = 30;
			cLJOMPBCNOE169.MDAGHJFEODE = 2.7f;
			GLBKCGACIHK().Add(cLJOMPBCNOE169.KGHMFHDGNEO(), cLJOMPBCNOE169);
			CLJOMPBCNOE cLJOMPBCNOE170 = new CLJOMPBCNOE(43012, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE170.GAFNNDHJDAE = "상급 치명타 확률 정수";
			cLJOMPBCNOE170.MGGCDFHFMKK = 10250;
			cLJOMPBCNOE170.FLNFNOEDLFN = 30;
			cLJOMPBCNOE170.CJALIPCFCLA = 0.0186f;
			GLBKCGACIHK().Add(cLJOMPBCNOE170.KGHMFHDGNEO(), cLJOMPBCNOE170);
			CLJOMPBCNOE cLJOMPBCNOE171 = new CLJOMPBCNOE(43013, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE171.GAFNNDHJDAE = "상급 방어력 정수";
			cLJOMPBCNOE171.MGGCDFHFMKK = 10250;
			cLJOMPBCNOE171.FLNFNOEDLFN = 30;
			cLJOMPBCNOE171.FBEBCNEPHJD = 4.26f;
			GLBKCGACIHK().Add(cLJOMPBCNOE171.KGHMFHDGNEO(), cLJOMPBCNOE171);
			CLJOMPBCNOE cLJOMPBCNOE172 = new CLJOMPBCNOE(43014, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE172.GAFNNDHJDAE = "상급 마법저항력 정수";
			cLJOMPBCNOE172.MGGCDFHFMKK = 10250;
			cLJOMPBCNOE172.FLNFNOEDLFN = 30;
			cLJOMPBCNOE172.NLMHKBGDKLA = 4f;
			GLBKCGACIHK().Add(cLJOMPBCNOE172.KGHMFHDGNEO(), cLJOMPBCNOE172);
			CLJOMPBCNOE cLJOMPBCNOE173 = new CLJOMPBCNOE(43015, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE173.GAFNNDHJDAE = "상급 생명력흡수 정수";
			cLJOMPBCNOE173.MGGCDFHFMKK = 20500;
			cLJOMPBCNOE173.FLNFNOEDLFN = 30;
			cLJOMPBCNOE173.PPNKFFAHHBB = 0.015f;
			GLBKCGACIHK().Add(cLJOMPBCNOE173.KGHMFHDGNEO(), cLJOMPBCNOE173);
			CLJOMPBCNOE cLJOMPBCNOE174 = new CLJOMPBCNOE(43016, CLJOMPBCNOE.ACPICCBBPHF.Quintessence, CLJOMPBCNOE.HCCCCKPABAO.High);
			cLJOMPBCNOE174.GAFNNDHJDAE = "상급 주문흡혈 정수";
			cLJOMPBCNOE174.MGGCDFHFMKK = 20500;
			cLJOMPBCNOE174.FLNFNOEDLFN = 30;
			cLJOMPBCNOE174.MOHEOOEFLNK = 0.02f;
			GLBKCGACIHK().Add(cLJOMPBCNOE174.KGHMFHDGNEO(), cLJOMPBCNOE174);
			ACIBDAANJLI(GetHashCode());
		}

		public List<CLJOMPBCNOE> GLGLAJBBCCL(CLJOMPBCNOE.ACPICCBBPHF FBAGNJILEGD, CLJOMPBCNOE.HCCCCKPABAO NIHEDOFPLLP)
		{
			List<CLJOMPBCNOE> list = new List<CLJOMPBCNOE>();
			foreach (KeyValuePair<ushort, CLJOMPBCNOE> item in GLBKCGACIHK())
			{
				CLJOMPBCNOE value = item.Value;
				if (value.ONJCKKLOJIA() == FBAGNJILEGD && value.EAPFGGJOPEJ() == NIHEDOFPLLP)
				{
					list.Add(value);
				}
			}
			return list;
		}

		public List<CLJOMPBCNOE> OAKPNJECBCD(CLJOMPBCNOE.ACPICCBBPHF FBAGNJILEGD, CLJOMPBCNOE.HCCCCKPABAO NIHEDOFPLLP)
		{
			List<CLJOMPBCNOE> list = new List<CLJOMPBCNOE>();
			foreach (KeyValuePair<ushort, CLJOMPBCNOE> item in GLBKCGACIHK())
			{
				CLJOMPBCNOE value = item.Value;
				if (value.ONJCKKLOJIA() == FBAGNJILEGD && value.EAPFGGJOPEJ() == NIHEDOFPLLP)
				{
					list.Add(value);
				}
			}
			return list;
		}

		protected void ACIBDAANJLI(int ICENKPDOHBK)
		{
			LFMCAMFIHEJ = ICENKPDOHBK;
		}

		public Dictionary<ushort, CLJOMPBCNOE> GLBKCGACIHK()
		{
			return LDDHNIFBPII;
		}

		public bool OAHPEDHGMOP()
		{
			if (LFCIGPFCGGP() == HMOHANFJAGG())
			{
				return true;
			}
			return true;
		}

		protected void DOMDCJMEEGM(Dictionary<ushort, CLJOMPBCNOE> ICENKPDOHBK)
		{
			LDDHNIFBPII = ICENKPDOHBK;
		}

		public CLJOMPBCNOE FPICNOOFDOA(ushort OHGOBGOIECH)
		{
			lock (JOEHMANNDJK)
			{
				CLJOMPBCNOE value;
				if (!GLBKCGACIHK().TryGetValue(OHGOBGOIECH, out value))
				{
					return null;
				}
				return value;
			}
		}

		public List<CLJOMPBCNOE> BAEOJCDJHKI(CLJOMPBCNOE.ACPICCBBPHF FBAGNJILEGD, CLJOMPBCNOE.HCCCCKPABAO NIHEDOFPLLP)
		{
			List<CLJOMPBCNOE> list = new List<CLJOMPBCNOE>();
			foreach (KeyValuePair<ushort, CLJOMPBCNOE> item in MFEIDGCBNBG())
			{
				CLJOMPBCNOE value = item.Value;
				if (value.ONJCKKLOJIA() == FBAGNJILEGD && value.EAPFGGJOPEJ() == NIHEDOFPLLP)
				{
					list.Add(value);
				}
			}
			return list;
		}

		public virtual int IMNEMDFAINP()
		{
			int num = 1;
			foreach (KeyValuePair<ushort, CLJOMPBCNOE> item in KGMEPGEFIBF())
			{
				num ^= item.Value.GetHashCode();
			}
			return num;
		}

		public bool GLFEGLHLOHD()
		{
			if (LFCIGPFCGGP() == HMOHANFJAGG())
			{
				return true;
			}
			return false;
		}

		[SpecialName]
		public int LFCIGPFCGGP()
		{
			return LFMCAMFIHEJ;
		}

		public List<CLJOMPBCNOE> DBCAFDGKHGC(CLJOMPBCNOE.ACPICCBBPHF FBAGNJILEGD, CLJOMPBCNOE.HCCCCKPABAO NIHEDOFPLLP)
		{
			List<CLJOMPBCNOE> list = new List<CLJOMPBCNOE>();
			foreach (KeyValuePair<ushort, CLJOMPBCNOE> item in GLBKCGACIHK())
			{
				CLJOMPBCNOE value = item.Value;
				if (value.ONJCKKLOJIA() == FBAGNJILEGD && value.EAPFGGJOPEJ() == NIHEDOFPLLP)
				{
					list.Add(value);
				}
			}
			return list;
		}

		public void JCOLMPJMMEB(PJEMPFEIOAK EFDLFNPAKGO)
		{
			lock (JOEHMANNDJK)
			{
				GLBKCGACIHK().Clear();
				ushort num = EFDLFNPAKGO.AJPFAAFLHEB();
				for (ushort num2 = 0; num2 < num; num2++)
				{
					CLJOMPBCNOE cLJOMPBCNOE = new CLJOMPBCNOE();
					cLJOMPBCNOE.JCOLMPJMMEB(EFDLFNPAKGO);
					GLBKCGACIHK().Add(cLJOMPBCNOE.KGHMFHDGNEO(), cLJOMPBCNOE);
				}
			}
		}

		public List<CLJOMPBCNOE> KBLMEDNAECO(CLJOMPBCNOE.ACPICCBBPHF FBAGNJILEGD, CLJOMPBCNOE.HCCCCKPABAO NIHEDOFPLLP)
		{
			List<CLJOMPBCNOE> list = new List<CLJOMPBCNOE>();
			foreach (KeyValuePair<ushort, CLJOMPBCNOE> item in GLBKCGACIHK())
			{
				CLJOMPBCNOE value = item.Value;
				if (value.ONJCKKLOJIA() == FBAGNJILEGD && value.EAPFGGJOPEJ() == NIHEDOFPLLP)
				{
					list.Add(value);
				}
			}
			return list;
		}

		[SpecialName]
		protected void DBADEOADBFG(Dictionary<ushort, CLJOMPBCNOE> ICENKPDOHBK)
		{
			LDDHNIFBPII = ICENKPDOHBK;
		}

		public AKDIMHNDAIH()
		{
			JOEHMANNDJK = new object();
			DOMDCJMEEGM(new Dictionary<ushort, CLJOMPBCNOE>());
		}

		public virtual int HMOHANFJAGG()
		{
			int num = 0;
			foreach (KeyValuePair<ushort, CLJOMPBCNOE> item in KGMEPGEFIBF())
			{
				num ^= item.Value.GetHashCode();
			}
			return num;
		}

		[SpecialName]
		public Dictionary<ushort, CLJOMPBCNOE> MFEIDGCBNBG()
		{
			return LDDHNIFBPII;
		}

		[SpecialName]
		protected void GMCIJKINNEA(int ICENKPDOHBK)
		{
			LFMCAMFIHEJ = ICENKPDOHBK;
		}
	}
}
