using System.Collections.Generic;
using EveEngine;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.Options;

namespace GameServer
{
	[JBFHBIFPIBM]
	public class CMDLJCJNOIO : EOPOBHFNFPA
	{
		[GMMFPFKHGMO]
		public uint OHGOBGOIECH;

		[LKHBCEOBOAD(MEEIBJDAMNH.ArrayOfDocuments)]
		public Dictionary<byte, KPPOLJIKONM> JAILIHOJKPH;

		public JBABEKCDKBM HFLJNJKMGOJ(byte OIGKODPLDJA, HAGFLGHFHPB DEHHBJPKFEC)
		{
			KPPOLJIKONM value;
			JAILIHOJKPH.TryGetValue(OIGKODPLDJA, out value);
			if (value == null)
			{
				return null;
			}
			return value.MDEGPGLKANA(DEHHBJPKFEC);
		}

		public KPPOLJIKONM ONMKKPAAGJA(byte OIGKODPLDJA, HAGFLGHFHPB DEHHBJPKFEC, JBABEKCDKBM FHPFBPNCGOC)
		{
			KPPOLJIKONM value;
			JAILIHOJKPH.TryGetValue(OIGKODPLDJA, out value);
			if (value == null)
			{
				JAILIHOJKPH[OIGKODPLDJA] = new KPPOLJIKONM();
			}
			JAILIHOJKPH[OIGKODPLDJA].ONMKKPAAGJA(DEHHBJPKFEC, FHPFBPNCGOC);
			return JAILIHOJKPH[OIGKODPLDJA];
		}

		public void CFGEKKHOKKE(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(OHGOBGOIECH);
			EFDLFNPAKGO.GBMJNFOEACC((ushort)JAILIHOJKPH.Count);
			foreach (KeyValuePair<byte, KPPOLJIKONM> item in JAILIHOJKPH)
			{
				EFDLFNPAKGO.GBMJNFOEACC(item.Key);
				EFDLFNPAKGO.GBMJNFOEACC(item.Value);
			}
		}

		public void GPBOIHMMDDD(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.BHAFGILIOCN(OHGOBGOIECH);
			EFDLFNPAKGO.HEDNLNDFFCL((ushort)JAILIHOJKPH.Count);
			foreach (KeyValuePair<byte, KPPOLJIKONM> item in JAILIHOJKPH)
			{
				EFDLFNPAKGO.GBMJNFOEACC(item.Key);
				EFDLFNPAKGO.JIAAPEKLFEA(item.Value);
			}
		}

		public void AHHKENDIBND(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.BHAFGILIOCN(OHGOBGOIECH);
			EFDLFNPAKGO.HEDNLNDFFCL((ushort)JAILIHOJKPH.Count);
			foreach (KeyValuePair<byte, KPPOLJIKONM> item in JAILIHOJKPH)
			{
				EFDLFNPAKGO.GBMJNFOEACC(item.Key);
				EFDLFNPAKGO.GBMJNFOEACC(item.Value);
			}
		}

		public JBABEKCDKBM IABJDNKNBNB(byte OIGKODPLDJA, HAGFLGHFHPB DEHHBJPKFEC)
		{
			KPPOLJIKONM value;
			JAILIHOJKPH.TryGetValue(OIGKODPLDJA, out value);
			if (value == null)
			{
				return null;
			}
			return value.OKJLONKONKF(DEHHBJPKFEC);
		}

		public void JCOLMPJMMEB(PJEMPFEIOAK EFDLFNPAKGO)
		{
			JAILIHOJKPH.Clear();
			EFDLFNPAKGO.CAHACMKBJMI(ref OHGOBGOIECH);
			ushort num = EFDLFNPAKGO.AJPFAAFLHEB();
			for (ushort num2 = 0; num2 < num; num2++)
			{
				KPPOLJIKONM kPPOLJIKONM = new KPPOLJIKONM();
				byte key = EFDLFNPAKGO.KFAGPDGHEBK();
				EFDLFNPAKGO.CAHACMKBJMI(kPPOLJIKONM);
				JAILIHOJKPH.Add(key, kPPOLJIKONM);
			}
		}

		public void KIIHJNANIPB(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(OHGOBGOIECH);
			EFDLFNPAKGO.HEDNLNDFFCL((ushort)JAILIHOJKPH.Count);
			foreach (KeyValuePair<byte, KPPOLJIKONM> item in JAILIHOJKPH)
			{
				EFDLFNPAKGO.GBMJNFOEACC(item.Key);
				EFDLFNPAKGO.JIAAPEKLFEA(item.Value);
			}
		}

		public void GHBLCHIJJFD(PJEMPFEIOAK EFDLFNPAKGO)
		{
			JAILIHOJKPH.Clear();
			EFDLFNPAKGO.CAHACMKBJMI(ref OHGOBGOIECH);
			ushort num = EFDLFNPAKGO.AJPFAAFLHEB();
			for (ushort num2 = 1; num2 < num; num2++)
			{
				KPPOLJIKONM kPPOLJIKONM = new KPPOLJIKONM();
				byte key = EFDLFNPAKGO.KFAGPDGHEBK();
				EFDLFNPAKGO.ILFEGIPCAHH(kPPOLJIKONM);
				JAILIHOJKPH.Add(key, kPPOLJIKONM);
			}
		}

		public void DFHOLCGFPIK(PJEMPFEIOAK EFDLFNPAKGO)
		{
			JAILIHOJKPH.Clear();
			EFDLFNPAKGO.CAHACMKBJMI(ref OHGOBGOIECH);
			ushort num = EFDLFNPAKGO.AJPFAAFLHEB();
			for (ushort num2 = 1; num2 < num; num2 += 0)
			{
				KPPOLJIKONM kPPOLJIKONM = new KPPOLJIKONM();
				byte key = EFDLFNPAKGO.KFAGPDGHEBK();
				EFDLFNPAKGO.ILFEGIPCAHH(kPPOLJIKONM);
				JAILIHOJKPH.Add(key, kPPOLJIKONM);
			}
		}

		public KPPOLJIKONM NCEMEKFDKAM(byte OIGKODPLDJA, HAGFLGHFHPB DEHHBJPKFEC, JBABEKCDKBM FHPFBPNCGOC)
		{
			KPPOLJIKONM value;
			JAILIHOJKPH.TryGetValue(OIGKODPLDJA, out value);
			if (value == null)
			{
				JAILIHOJKPH[OIGKODPLDJA] = new KPPOLJIKONM();
			}
			JAILIHOJKPH[OIGKODPLDJA].ONMKKPAAGJA(DEHHBJPKFEC, FHPFBPNCGOC);
			return JAILIHOJKPH[OIGKODPLDJA];
		}

		public JBABEKCDKBM JEGJCLEPANJ(byte OIGKODPLDJA, HAGFLGHFHPB DEHHBJPKFEC)
		{
			KPPOLJIKONM value;
			JAILIHOJKPH.TryGetValue(OIGKODPLDJA, out value);
			if (value == null)
			{
				return null;
			}
			return value.OKJLONKONKF(DEHHBJPKFEC);
		}

		public JBABEKCDKBM CHIPFFEHDDE(byte OIGKODPLDJA, HAGFLGHFHPB DEHHBJPKFEC)
		{
			KPPOLJIKONM value;
			JAILIHOJKPH.TryGetValue(OIGKODPLDJA, out value);
			if (value == null)
			{
				return null;
			}
			return value.KNAEODGAICI(DEHHBJPKFEC);
		}

		public JBABEKCDKBM MDEGPGLKANA(byte OIGKODPLDJA, HAGFLGHFHPB DEHHBJPKFEC)
		{
			KPPOLJIKONM value;
			JAILIHOJKPH.TryGetValue(OIGKODPLDJA, out value);
			if (value == null)
			{
				return null;
			}
			return value.MDEGPGLKANA(DEHHBJPKFEC);
		}

		public KPPOLJIKONM PAGHMBLDIJL(byte OIGKODPLDJA, HAGFLGHFHPB DEHHBJPKFEC, JBABEKCDKBM FHPFBPNCGOC)
		{
			KPPOLJIKONM value;
			JAILIHOJKPH.TryGetValue(OIGKODPLDJA, out value);
			if (value == null)
			{
				JAILIHOJKPH[OIGKODPLDJA] = new KPPOLJIKONM();
			}
			JAILIHOJKPH[OIGKODPLDJA].GBIILKJKBJG(DEHHBJPKFEC, FHPFBPNCGOC);
			return JAILIHOJKPH[OIGKODPLDJA];
		}

		public CMDLJCJNOIO()
		{
			JAILIHOJKPH = new Dictionary<byte, KPPOLJIKONM>();
		}

		public KPPOLJIKONM NFOIIAANLDN(byte OIGKODPLDJA, HAGFLGHFHPB DEHHBJPKFEC, JBABEKCDKBM FHPFBPNCGOC)
		{
			KPPOLJIKONM value;
			JAILIHOJKPH.TryGetValue(OIGKODPLDJA, out value);
			if (value == null)
			{
				JAILIHOJKPH[OIGKODPLDJA] = new KPPOLJIKONM();
			}
			JAILIHOJKPH[OIGKODPLDJA].AEFJBPJJELK(DEHHBJPKFEC, FHPFBPNCGOC);
			return JAILIHOJKPH[OIGKODPLDJA];
		}

		public void HOCIBNCFBLL(PJEMPFEIOAK EFDLFNPAKGO)
		{
			JAILIHOJKPH.Clear();
			EFDLFNPAKGO.CAHACMKBJMI(ref OHGOBGOIECH);
			ushort num = EFDLFNPAKGO.AJPFAAFLHEB();
			for (ushort num2 = 1; num2 < num; num2 += 0)
			{
				KPPOLJIKONM kPPOLJIKONM = new KPPOLJIKONM();
				byte key = EFDLFNPAKGO.KFAGPDGHEBK();
				EFDLFNPAKGO.CAHACMKBJMI(kPPOLJIKONM);
				JAILIHOJKPH.Add(key, kPPOLJIKONM);
			}
		}

		public void LEDLMGNKOJA(PJEMPFEIOAK EFDLFNPAKGO)
		{
			JAILIHOJKPH.Clear();
			EFDLFNPAKGO.CAHACMKBJMI(ref OHGOBGOIECH);
			ushort num = EFDLFNPAKGO.AJPFAAFLHEB();
			for (ushort num2 = 1; num2 < num; num2 += 0)
			{
				KPPOLJIKONM kPPOLJIKONM = new KPPOLJIKONM();
				byte key = EFDLFNPAKGO.KFAGPDGHEBK();
				EFDLFNPAKGO.ILFEGIPCAHH(kPPOLJIKONM);
				JAILIHOJKPH.Add(key, kPPOLJIKONM);
			}
		}
	}
}
