using System.Collections.Generic;
using System.Runtime.CompilerServices;
using EveEngine;

namespace GameServer
{
	public class EPOEICHAAKP : EOPOBHFNFPA
	{
		private object JOEHMANNDJK;

		private int LFMCAMFIHEJ;

		private Dictionary<ushort, HNEBHCMAOAE> ENNEEJMCHGI;

		public int PKKDIMODALC
		{
			get
			{
				return LJKLAIGNIKB();
			}
			protected set
			{
				ACIBDAANJLI(value);
			}
		}

		public Dictionary<ushort, HNEBHCMAOAE> JCKFFCBHMIJ
		{
			get
			{
				return EPEJNKKPCCG();
			}
			protected set
			{
				HDKJGMIAOKN(value);
			}
		}

		public int LJKLAIGNIKB()
		{
			return LFMCAMFIHEJ;
		}

		public bool DDPDAGNNMFL(ushort JLPIFIJBMCD)
		{
			ushort num = JLPIFIJBMCD;
			if (num == 27)
			{
				return true;
			}
			return false;
		}

		protected void HDKJGMIAOKN(Dictionary<ushort, HNEBHCMAOAE> ICENKPDOHBK)
		{
			ENNEEJMCHGI = ICENKPDOHBK;
		}

		public HNEBHCMAOAE FPICNOOFDOA(ushort OHGOBGOIECH)
		{
			HNEBHCMAOAE value;
			if (!EPEJNKKPCCG().TryGetValue(OHGOBGOIECH, out value))
			{
				return null;
			}
			return value;
		}

		public void PEFJOMFAOJI()
		{
			HNEBHCMAOAE hNEBHCMAOAE = new HNEBHCMAOAE();
			hNEBHCMAOAE.FIGLEPBIEEJ(1, "알리스타", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 7000u, 0u, 1, 1, "Alistar");
			hNEBHCMAOAE.IIJMLJCIJFD().LBJMNDBMNAE = 613u;
			hNEBHCMAOAE.IIJMLJCIJFD().EPKGCHPIHEL = 102u;
			hNEBHCMAOAE.IIJMLJCIJFD().JKOEPLLJDKM = 8.675f;
			hNEBHCMAOAE.IIJMLJCIJFD().BKOBAIPJAHP = 0.85f;
			hNEBHCMAOAE.IIJMLJCIJFD().OCOOIOGCOEE = 278u;
			hNEBHCMAOAE.IIJMLJCIJFD().GHCBBJBDNPH = 38u;
			hNEBHCMAOAE.IIJMLJCIJFD().MGLIOBDEJLF = 6f;
			hNEBHCMAOAE.IIJMLJCIJFD().GFGOPIKFOAN = 0.8f;
			hNEBHCMAOAE.IIJMLJCIJFD().IIICODNIMNN = 2.4f;
			hNEBHCMAOAE.IIJMLJCIJFD().LOJEMAMKHFD = 61.112f;
			hNEBHCMAOAE.IIJMLJCIJFD().ELDBGIKHAIO = 3.62f;
			hNEBHCMAOAE.IIJMLJCIJFD().LNKFLFOGCCD = 0.625f;
			hNEBHCMAOAE.IIJMLJCIJFD().FHJCBAOBGPG = 3.125f;
			hNEBHCMAOAE.IIJMLJCIJFD().FBEBCNEPHJD = 26.38f;
			hNEBHCMAOAE.IIJMLJCIJFD().PDAOIGGBLPH = 3.5f;
			hNEBHCMAOAE.IIJMLJCIJFD().NLMHKBGDKLA = 32.1f;
			hNEBHCMAOAE.IIJMLJCIJFD().JFLFAKNHKNP = 1.25f;
			hNEBHCMAOAE.IIJMLJCIJFD().NEPGMKLCMFF = 3.3f;
			hNEBHCMAOAE.FKNPBEJDKGM().Add(8000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE.INGLCFJBNOB(), hNEBHCMAOAE);
			HNEBHCMAOAE hNEBHCMAOAE2 = new HNEBHCMAOAE();
			hNEBHCMAOAE2.FIGLEPBIEEJ(2, "베인", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Range, 9000u, 0u, 1, 1, "Vayne");
			hNEBHCMAOAE2.IIJMLJCIJFD().LBJMNDBMNAE = 515u;
			hNEBHCMAOAE2.IIJMLJCIJFD().EPKGCHPIHEL = 89u;
			hNEBHCMAOAE2.IIJMLJCIJFD().JKOEPLLJDKM = 5.42f;
			hNEBHCMAOAE2.IIJMLJCIJFD().BKOBAIPJAHP = 0.55f;
			hNEBHCMAOAE2.IIJMLJCIJFD().OCOOIOGCOEE = 231u;
			hNEBHCMAOAE2.IIJMLJCIJFD().GHCBBJBDNPH = 35u;
			hNEBHCMAOAE2.IIJMLJCIJFD().MGLIOBDEJLF = 6.97f;
			hNEBHCMAOAE2.IIJMLJCIJFD().GFGOPIKFOAN = 0.4f;
			hNEBHCMAOAE2.IIJMLJCIJFD().IIICODNIMNN = 5.5f;
			hNEBHCMAOAE2.IIJMLJCIJFD().LOJEMAMKHFD = 59.1f;
			hNEBHCMAOAE2.IIJMLJCIJFD().ELDBGIKHAIO = 2.02f;
			hNEBHCMAOAE2.IIJMLJCIJFD().LNKFLFOGCCD = 0.658f;
			hNEBHCMAOAE2.IIJMLJCIJFD().FHJCBAOBGPG = 4f;
			hNEBHCMAOAE2.IIJMLJCIJFD().FBEBCNEPHJD = 22.012f;
			hNEBHCMAOAE2.IIJMLJCIJFD().PDAOIGGBLPH = 3.4f;
			hNEBHCMAOAE2.IIJMLJCIJFD().NLMHKBGDKLA = 30f;
			hNEBHCMAOAE2.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE2.IIJMLJCIJFD().NEPGMKLCMFF = 3.3f;
			hNEBHCMAOAE2.FKNPBEJDKGM().Add(4000u);
			hNEBHCMAOAE2.FKNPBEJDKGM().Add(6000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE2.INGLCFJBNOB(), hNEBHCMAOAE2);
			HNEBHCMAOAE hNEBHCMAOAE3 = new HNEBHCMAOAE();
			hNEBHCMAOAE3.FIGLEPBIEEJ(3, "제드", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 13000u, 0u, 1, 1, "Zed");
			hNEBHCMAOAE3.IIJMLJCIJFD().LBJMNDBMNAE = 584u;
			hNEBHCMAOAE3.IIJMLJCIJFD().EPKGCHPIHEL = 80u;
			hNEBHCMAOAE3.IIJMLJCIJFD().JKOEPLLJDKM = 7.09f;
			hNEBHCMAOAE3.IIJMLJCIJFD().BKOBAIPJAHP = 0.65f;
			hNEBHCMAOAE3.IIJMLJCIJFD().OCOOIOGCOEE = 200u;
			hNEBHCMAOAE3.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE3.IIJMLJCIJFD().MGLIOBDEJLF = 50f;
			hNEBHCMAOAE3.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE3.IIJMLJCIJFD().IIICODNIMNN = 2.4f;
			hNEBHCMAOAE3.IIJMLJCIJFD().LOJEMAMKHFD = 54.712f;
			hNEBHCMAOAE3.IIJMLJCIJFD().ELDBGIKHAIO = 3.8f;
			hNEBHCMAOAE3.IIJMLJCIJFD().LNKFLFOGCCD = 0.658f;
			hNEBHCMAOAE3.IIJMLJCIJFD().FHJCBAOBGPG = 2.1f;
			hNEBHCMAOAE3.IIJMLJCIJFD().FBEBCNEPHJD = 29.88f;
			hNEBHCMAOAE3.IIJMLJCIJFD().PDAOIGGBLPH = 3.5f;
			hNEBHCMAOAE3.IIJMLJCIJFD().NLMHKBGDKLA = 32.1f;
			hNEBHCMAOAE3.IIJMLJCIJFD().JFLFAKNHKNP = 1.25f;
			hNEBHCMAOAE3.IIJMLJCIJFD().NEPGMKLCMFF = 3.45f;
			hNEBHCMAOAE3.FKNPBEJDKGM().Add(12000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE3.INGLCFJBNOB(), hNEBHCMAOAE3);
			HNEBHCMAOAE hNEBHCMAOAE4 = new HNEBHCMAOAE();
			hNEBHCMAOAE4.FIGLEPBIEEJ(4, "아리", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Range, 7000u, 0u, 1, 1, "Ahri");
			hNEBHCMAOAE4.IIJMLJCIJFD().LBJMNDBMNAE = 527u;
			hNEBHCMAOAE4.IIJMLJCIJFD().EPKGCHPIHEL = 93u;
			hNEBHCMAOAE4.IIJMLJCIJFD().JKOEPLLJDKM = 6.505f;
			hNEBHCMAOAE4.IIJMLJCIJFD().BKOBAIPJAHP = 0.6f;
			hNEBHCMAOAE4.IIJMLJCIJFD().OCOOIOGCOEE = 418u;
			hNEBHCMAOAE4.IIJMLJCIJFD().GHCBBJBDNPH = 25u;
			hNEBHCMAOAE4.IIJMLJCIJFD().MGLIOBDEJLF = 8f;
			hNEBHCMAOAE4.IIJMLJCIJFD().GFGOPIKFOAN = 0.8f;
			hNEBHCMAOAE4.IIJMLJCIJFD().IIICODNIMNN = 5.5f;
			hNEBHCMAOAE4.IIJMLJCIJFD().LOJEMAMKHFD = 53.04f;
			hNEBHCMAOAE4.IIJMLJCIJFD().ELDBGIKHAIO = 3f;
			hNEBHCMAOAE4.IIJMLJCIJFD().LNKFLFOGCCD = 0.668f;
			hNEBHCMAOAE4.IIJMLJCIJFD().FHJCBAOBGPG = 2f;
			hNEBHCMAOAE4.IIJMLJCIJFD().FBEBCNEPHJD = 20.88f;
			hNEBHCMAOAE4.IIJMLJCIJFD().PDAOIGGBLPH = 3.5f;
			hNEBHCMAOAE4.IIJMLJCIJFD().NLMHKBGDKLA = 30f;
			hNEBHCMAOAE4.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE4.IIJMLJCIJFD().NEPGMKLCMFF = 3.3f;
			hNEBHCMAOAE4.FKNPBEJDKGM().Add(6000u);
			hNEBHCMAOAE4.FKNPBEJDKGM().Add(8000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE4.INGLCFJBNOB(), hNEBHCMAOAE4);
			HNEBHCMAOAE hNEBHCMAOAE5 = new HNEBHCMAOAE();
			hNEBHCMAOAE5.FIGLEPBIEEJ(5, "그레이브즈", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Range, 9000u, 0u, 1, 1, "Graves");
			hNEBHCMAOAE5.IIJMLJCIJFD().LBJMNDBMNAE = 555u;
			hNEBHCMAOAE5.IIJMLJCIJFD().EPKGCHPIHEL = 92u;
			hNEBHCMAOAE5.IIJMLJCIJFD().JKOEPLLJDKM = 8f;
			hNEBHCMAOAE5.IIJMLJCIJFD().BKOBAIPJAHP = 0.7f;
			hNEBHCMAOAE5.IIJMLJCIJFD().OCOOIOGCOEE = 322u;
			hNEBHCMAOAE5.IIJMLJCIJFD().GHCBBJBDNPH = 40u;
			hNEBHCMAOAE5.IIJMLJCIJFD().MGLIOBDEJLF = 7.925f;
			hNEBHCMAOAE5.IIJMLJCIJFD().GFGOPIKFOAN = 0.7f;
			hNEBHCMAOAE5.IIJMLJCIJFD().IIICODNIMNN = 5.25f;
			hNEBHCMAOAE5.IIJMLJCIJFD().LOJEMAMKHFD = 60.83f;
			hNEBHCMAOAE5.IIJMLJCIJFD().ELDBGIKHAIO = 2.41f;
			hNEBHCMAOAE5.IIJMLJCIJFD().LNKFLFOGCCD = 0.625f;
			hNEBHCMAOAE5.IIJMLJCIJFD().FHJCBAOBGPG = 2.6f;
			hNEBHCMAOAE5.IIJMLJCIJFD().FBEBCNEPHJD = 24.376f;
			hNEBHCMAOAE5.IIJMLJCIJFD().PDAOIGGBLPH = 3.2f;
			hNEBHCMAOAE5.IIJMLJCIJFD().NLMHKBGDKLA = 30f;
			hNEBHCMAOAE5.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE5.IIJMLJCIJFD().NEPGMKLCMFF = 3.3f;
			hNEBHCMAOAE5.FKNPBEJDKGM().Add(8000u);
			hNEBHCMAOAE5.FKNPBEJDKGM().Add(10000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE5.INGLCFJBNOB(), hNEBHCMAOAE5);
			HNEBHCMAOAE hNEBHCMAOAE6 = new HNEBHCMAOAE();
			hNEBHCMAOAE6.FIGLEPBIEEJ(6, "카타리나", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 11000u, 0u, 1, 1, "Katarina");
			hNEBHCMAOAE6.IIJMLJCIJFD().LBJMNDBMNAE = 510u;
			hNEBHCMAOAE6.IIJMLJCIJFD().EPKGCHPIHEL = 83u;
			hNEBHCMAOAE6.IIJMLJCIJFD().JKOEPLLJDKM = 7.5f;
			hNEBHCMAOAE6.IIJMLJCIJFD().BKOBAIPJAHP = 0.71f;
			hNEBHCMAOAE6.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE6.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE6.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE6.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE6.IIJMLJCIJFD().IIICODNIMNN = 2.4f;
			hNEBHCMAOAE6.IIJMLJCIJFD().LOJEMAMKHFD = 56.376f;
			hNEBHCMAOAE6.IIJMLJCIJFD().ELDBGIKHAIO = 3.2f;
			hNEBHCMAOAE6.IIJMLJCIJFD().LNKFLFOGCCD = 0.658f;
			hNEBHCMAOAE6.IIJMLJCIJFD().FHJCBAOBGPG = 2.74f;
			hNEBHCMAOAE6.IIJMLJCIJFD().FBEBCNEPHJD = 26.88f;
			hNEBHCMAOAE6.IIJMLJCIJFD().PDAOIGGBLPH = 3.5f;
			hNEBHCMAOAE6.IIJMLJCIJFD().NLMHKBGDKLA = 32.1f;
			hNEBHCMAOAE6.IIJMLJCIJFD().JFLFAKNHKNP = 1.25f;
			hNEBHCMAOAE6.IIJMLJCIJFD().NEPGMKLCMFF = 3.45f;
			hNEBHCMAOAE6.FKNPBEJDKGM().Add(6000u);
			hNEBHCMAOAE6.FKNPBEJDKGM().Add(8000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE6.INGLCFJBNOB(), hNEBHCMAOAE6);
			HNEBHCMAOAE hNEBHCMAOAE7 = new HNEBHCMAOAE();
			hNEBHCMAOAE7.FIGLEPBIEEJ(7, "이즈리얼", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Range, 15000u, 0u, 1, 1, "Ezreal");
			hNEBHCMAOAE7.IIJMLJCIJFD().LBJMNDBMNAE = 484u;
			hNEBHCMAOAE7.IIJMLJCIJFD().EPKGCHPIHEL = 80u;
			hNEBHCMAOAE7.IIJMLJCIJFD().JKOEPLLJDKM = 6.42f;
			hNEBHCMAOAE7.IIJMLJCIJFD().BKOBAIPJAHP = 0.55f;
			hNEBHCMAOAE7.IIJMLJCIJFD().OCOOIOGCOEE = 360u;
			hNEBHCMAOAE7.IIJMLJCIJFD().GHCBBJBDNPH = 42u;
			hNEBHCMAOAE7.IIJMLJCIJFD().MGLIOBDEJLF = 8.09f;
			hNEBHCMAOAE7.IIJMLJCIJFD().GFGOPIKFOAN = 0.65f;
			hNEBHCMAOAE7.IIJMLJCIJFD().IIICODNIMNN = 5.5f;
			hNEBHCMAOAE7.IIJMLJCIJFD().LOJEMAMKHFD = 55.66f;
			hNEBHCMAOAE7.IIJMLJCIJFD().ELDBGIKHAIO = 3f;
			hNEBHCMAOAE7.IIJMLJCIJFD().LNKFLFOGCCD = 0.625f;
			hNEBHCMAOAE7.IIJMLJCIJFD().FHJCBAOBGPG = 2.8f;
			hNEBHCMAOAE7.IIJMLJCIJFD().FBEBCNEPHJD = 21.88f;
			hNEBHCMAOAE7.IIJMLJCIJFD().PDAOIGGBLPH = 3.5f;
			hNEBHCMAOAE7.IIJMLJCIJFD().NLMHKBGDKLA = 30f;
			hNEBHCMAOAE7.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE7.IIJMLJCIJFD().NEPGMKLCMFF = 3.25f;
			hNEBHCMAOAE7.FKNPBEJDKGM().Add(8000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE7.INGLCFJBNOB(), hNEBHCMAOAE7);
			HNEBHCMAOAE hNEBHCMAOAE8 = new HNEBHCMAOAE();
			hNEBHCMAOAE8.FIGLEPBIEEJ(8, "레넥톤", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 13000u, 0u, 1, 1, "Renekton");
			hNEBHCMAOAE8.IIJMLJCIJFD().LBJMNDBMNAE = 572u;
			hNEBHCMAOAE8.IIJMLJCIJFD().EPKGCHPIHEL = 87u;
			hNEBHCMAOAE8.IIJMLJCIJFD().JKOEPLLJDKM = 7.96f;
			hNEBHCMAOAE8.IIJMLJCIJFD().BKOBAIPJAHP = 0.75f;
			hNEBHCMAOAE8.IIJMLJCIJFD().OCOOIOGCOEE = 100u;
			hNEBHCMAOAE8.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE8.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE8.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE8.IIJMLJCIJFD().IIICODNIMNN = 2.4f;
			hNEBHCMAOAE8.IIJMLJCIJFD().LOJEMAMKHFD = 63.328f;
			hNEBHCMAOAE8.IIJMLJCIJFD().ELDBGIKHAIO = 3.3f;
			hNEBHCMAOAE8.IIJMLJCIJFD().LNKFLFOGCCD = 0.665f;
			hNEBHCMAOAE8.IIJMLJCIJFD().FHJCBAOBGPG = 2.75f;
			hNEBHCMAOAE8.IIJMLJCIJFD().FBEBCNEPHJD = 33.584f;
			hNEBHCMAOAE8.IIJMLJCIJFD().PDAOIGGBLPH = 4f;
			hNEBHCMAOAE8.IIJMLJCIJFD().NLMHKBGDKLA = 32.1f;
			hNEBHCMAOAE8.IIJMLJCIJFD().JFLFAKNHKNP = 1.25f;
			hNEBHCMAOAE8.IIJMLJCIJFD().NEPGMKLCMFF = 3.45f;
			hNEBHCMAOAE8.FKNPBEJDKGM().Add(8000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE8.INGLCFJBNOB(), hNEBHCMAOAE8);
			HNEBHCMAOAE hNEBHCMAOAE9 = new HNEBHCMAOAE();
			hNEBHCMAOAE9.FIGLEPBIEEJ(9, "블리츠크랭크", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 11000u, 0u, 1, 1, "Blitzcrank");
			hNEBHCMAOAE9.IIJMLJCIJFD().LBJMNDBMNAE = 582u;
			hNEBHCMAOAE9.IIJMLJCIJFD().EPKGCHPIHEL = 95u;
			hNEBHCMAOAE9.IIJMLJCIJFD().JKOEPLLJDKM = 8.51f;
			hNEBHCMAOAE9.IIJMLJCIJFD().BKOBAIPJAHP = 0.75f;
			hNEBHCMAOAE9.IIJMLJCIJFD().OCOOIOGCOEE = 267u;
			hNEBHCMAOAE9.IIJMLJCIJFD().GHCBBJBDNPH = 40u;
			hNEBHCMAOAE9.IIJMLJCIJFD().MGLIOBDEJLF = 6f;
			hNEBHCMAOAE9.IIJMLJCIJFD().GFGOPIKFOAN = 0.8f;
			hNEBHCMAOAE9.IIJMLJCIJFD().IIICODNIMNN = 2.4f;
			hNEBHCMAOAE9.IIJMLJCIJFD().LOJEMAMKHFD = 61.54f;
			hNEBHCMAOAE9.IIJMLJCIJFD().ELDBGIKHAIO = 3.5f;
			hNEBHCMAOAE9.IIJMLJCIJFD().LNKFLFOGCCD = 0.625f;
			hNEBHCMAOAE9.IIJMLJCIJFD().FHJCBAOBGPG = 1.13f;
			hNEBHCMAOAE9.IIJMLJCIJFD().FBEBCNEPHJD = 24.38f;
			hNEBHCMAOAE9.IIJMLJCIJFD().PDAOIGGBLPH = 3.5f;
			hNEBHCMAOAE9.IIJMLJCIJFD().NLMHKBGDKLA = 32.1f;
			hNEBHCMAOAE9.IIJMLJCIJFD().JFLFAKNHKNP = 1.25f;
			hNEBHCMAOAE9.IIJMLJCIJFD().NEPGMKLCMFF = 3.25f;
			hNEBHCMAOAE9.FKNPBEJDKGM().Add(8000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE9.INGLCFJBNOB(), hNEBHCMAOAE9);
			HNEBHCMAOAE hNEBHCMAOAE10 = new HNEBHCMAOAE();
			hNEBHCMAOAE10.FIGLEPBIEEJ(10, "리븐", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 13000u, 0u, 1, 1, "Riven");
			hNEBHCMAOAE10.IIJMLJCIJFD().LBJMNDBMNAE = 558u;
			hNEBHCMAOAE10.IIJMLJCIJFD().EPKGCHPIHEL = 86u;
			hNEBHCMAOAE10.IIJMLJCIJFD().JKOEPLLJDKM = 5.34f;
			hNEBHCMAOAE10.IIJMLJCIJFD().BKOBAIPJAHP = 0.5f;
			hNEBHCMAOAE10.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE10.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE10.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE10.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE10.IIJMLJCIJFD().IIICODNIMNN = 2.4f;
			hNEBHCMAOAE10.IIJMLJCIJFD().LOJEMAMKHFD = 56.04f;
			hNEBHCMAOAE10.IIJMLJCIJFD().ELDBGIKHAIO = 3f;
			hNEBHCMAOAE10.IIJMLJCIJFD().LNKFLFOGCCD = 0.625f;
			hNEBHCMAOAE10.IIJMLJCIJFD().FHJCBAOBGPG = 3.5f;
			hNEBHCMAOAE10.IIJMLJCIJFD().FBEBCNEPHJD = 24.376f;
			hNEBHCMAOAE10.IIJMLJCIJFD().PDAOIGGBLPH = 3.5f;
			hNEBHCMAOAE10.IIJMLJCIJFD().NLMHKBGDKLA = 32.1f;
			hNEBHCMAOAE10.IIJMLJCIJFD().JFLFAKNHKNP = 1.25f;
			hNEBHCMAOAE10.IIJMLJCIJFD().NEPGMKLCMFF = 3.45f;
			hNEBHCMAOAE10.FKNPBEJDKGM().Add(10000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE10.INGLCFJBNOB(), hNEBHCMAOAE10);
			HNEBHCMAOAE hNEBHCMAOAE11 = new HNEBHCMAOAE();
			hNEBHCMAOAE11.FIGLEPBIEEJ(11, "렝가", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 11000u, 0u, 0, 0, "Rengar");
			hNEBHCMAOAE11.IIJMLJCIJFD().LBJMNDBMNAE = 484u;
			hNEBHCMAOAE11.IIJMLJCIJFD().EPKGCHPIHEL = 80u;
			hNEBHCMAOAE11.IIJMLJCIJFD().JKOEPLLJDKM = 6.42f;
			hNEBHCMAOAE11.IIJMLJCIJFD().BKOBAIPJAHP = 0.55f;
			hNEBHCMAOAE11.IIJMLJCIJFD().OCOOIOGCOEE = 310u;
			hNEBHCMAOAE11.IIJMLJCIJFD().GHCBBJBDNPH = 45u;
			hNEBHCMAOAE11.IIJMLJCIJFD().MGLIOBDEJLF = 8.09f;
			hNEBHCMAOAE11.IIJMLJCIJFD().GFGOPIKFOAN = 0.65f;
			hNEBHCMAOAE11.IIJMLJCIJFD().IIICODNIMNN = 5.5f;
			hNEBHCMAOAE11.IIJMLJCIJFD().LOJEMAMKHFD = 50.24f;
			hNEBHCMAOAE11.IIJMLJCIJFD().ELDBGIKHAIO = 3f;
			hNEBHCMAOAE11.IIJMLJCIJFD().LNKFLFOGCCD = 0.625f;
			hNEBHCMAOAE11.IIJMLJCIJFD().FHJCBAOBGPG = 2.8f;
			hNEBHCMAOAE11.IIJMLJCIJFD().FBEBCNEPHJD = 21.88f;
			hNEBHCMAOAE11.IIJMLJCIJFD().PDAOIGGBLPH = 3.5f;
			hNEBHCMAOAE11.IIJMLJCIJFD().NLMHKBGDKLA = 30f;
			hNEBHCMAOAE11.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE11.IIJMLJCIJFD().NEPGMKLCMFF = 3.25f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE11.INGLCFJBNOB(), hNEBHCMAOAE11);
			HNEBHCMAOAE hNEBHCMAOAE12 = new HNEBHCMAOAE();
			hNEBHCMAOAE12.FIGLEPBIEEJ(12, "마스터 이", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 17000u, 0u, 1, 1, "MasterYi");
			hNEBHCMAOAE12.IIJMLJCIJFD().LBJMNDBMNAE = 598u;
			hNEBHCMAOAE12.IIJMLJCIJFD().EPKGCHPIHEL = 92u;
			hNEBHCMAOAE12.IIJMLJCIJFD().JKOEPLLJDKM = 7.59f;
			hNEBHCMAOAE12.IIJMLJCIJFD().BKOBAIPJAHP = 0.65f;
			hNEBHCMAOAE12.IIJMLJCIJFD().OCOOIOGCOEE = 250u;
			hNEBHCMAOAE12.IIJMLJCIJFD().GHCBBJBDNPH = 42u;
			hNEBHCMAOAE12.IIJMLJCIJFD().MGLIOBDEJLF = 7.255f;
			hNEBHCMAOAE12.IIJMLJCIJFD().GFGOPIKFOAN = 0.45f;
			hNEBHCMAOAE12.IIJMLJCIJFD().IIICODNIMNN = 2.4f;
			hNEBHCMAOAE12.IIJMLJCIJFD().LOJEMAMKHFD = 60.04f;
			hNEBHCMAOAE12.IIJMLJCIJFD().ELDBGIKHAIO = 3f;
			hNEBHCMAOAE12.IIJMLJCIJFD().LNKFLFOGCCD = 0.679f;
			hNEBHCMAOAE12.IIJMLJCIJFD().FHJCBAOBGPG = 2f;
			hNEBHCMAOAE12.IIJMLJCIJFD().FBEBCNEPHJD = 24.04f;
			hNEBHCMAOAE12.IIJMLJCIJFD().PDAOIGGBLPH = 3f;
			hNEBHCMAOAE12.IIJMLJCIJFD().NLMHKBGDKLA = 32.1f;
			hNEBHCMAOAE12.IIJMLJCIJFD().JFLFAKNHKNP = 1.25f;
			hNEBHCMAOAE12.IIJMLJCIJFD().NEPGMKLCMFF = 3.55f;
			hNEBHCMAOAE12.FKNPBEJDKGM().Add(8000u);
			hNEBHCMAOAE12.FKNPBEJDKGM().Add(10000u);
			hNEBHCMAOAE12.FKNPBEJDKGM().Add(14000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE12.INGLCFJBNOB(), hNEBHCMAOAE12);
			HNEBHCMAOAE hNEBHCMAOAE13 = new HNEBHCMAOAE();
			hNEBHCMAOAE13.FIGLEPBIEEJ(13, "가렌", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 11000u, 0u, 1, 1, "Garen");
			hNEBHCMAOAE13.IIJMLJCIJFD().LBJMNDBMNAE = 616u;
			hNEBHCMAOAE13.IIJMLJCIJFD().EPKGCHPIHEL = 96u;
			hNEBHCMAOAE13.IIJMLJCIJFD().JKOEPLLJDKM = 7.84f;
			hNEBHCMAOAE13.IIJMLJCIJFD().BKOBAIPJAHP = 0.5f;
			hNEBHCMAOAE13.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE13.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE13.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE13.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE13.IIJMLJCIJFD().IIICODNIMNN = 2.4f;
			hNEBHCMAOAE13.IIJMLJCIJFD().LOJEMAMKHFD = 57.88f;
			hNEBHCMAOAE13.IIJMLJCIJFD().ELDBGIKHAIO = 3.5f;
			hNEBHCMAOAE13.IIJMLJCIJFD().LNKFLFOGCCD = 0.625f;
			hNEBHCMAOAE13.IIJMLJCIJFD().FHJCBAOBGPG = 2.9f;
			hNEBHCMAOAE13.IIJMLJCIJFD().FBEBCNEPHJD = 27.536f;
			hNEBHCMAOAE13.IIJMLJCIJFD().PDAOIGGBLPH = 2.7f;
			hNEBHCMAOAE13.IIJMLJCIJFD().NLMHKBGDKLA = 32.1f;
			hNEBHCMAOAE13.IIJMLJCIJFD().JFLFAKNHKNP = 1.25f;
			hNEBHCMAOAE13.IIJMLJCIJFD().NEPGMKLCMFF = 3.45f;
			hNEBHCMAOAE13.FKNPBEJDKGM().Add(8000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE13.INGLCFJBNOB(), hNEBHCMAOAE13);
			HNEBHCMAOAE hNEBHCMAOAE14 = new HNEBHCMAOAE();
			hNEBHCMAOAE14.FIGLEPBIEEJ(14, "시비르", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Range, 11000u, 0u, 1, 1, "Sivir");
			hNEBHCMAOAE14.IIJMLJCIJFD().LBJMNDBMNAE = 532u;
			hNEBHCMAOAE14.IIJMLJCIJFD().EPKGCHPIHEL = 88u;
			hNEBHCMAOAE14.IIJMLJCIJFD().JKOEPLLJDKM = 5.17f;
			hNEBHCMAOAE14.IIJMLJCIJFD().BKOBAIPJAHP = 0.55f;
			hNEBHCMAOAE14.IIJMLJCIJFD().OCOOIOGCOEE = 284u;
			hNEBHCMAOAE14.IIJMLJCIJFD().GHCBBJBDNPH = 50u;
			hNEBHCMAOAE14.IIJMLJCIJFD().MGLIOBDEJLF = 8.01f;
			hNEBHCMAOAE14.IIJMLJCIJFD().GFGOPIKFOAN = 0.9f;
			hNEBHCMAOAE14.IIJMLJCIJFD().IIICODNIMNN = 5.25f;
			hNEBHCMAOAE14.IIJMLJCIJFD().LOJEMAMKHFD = 57.46f;
			hNEBHCMAOAE14.IIJMLJCIJFD().ELDBGIKHAIO = 2.41f;
			hNEBHCMAOAE14.IIJMLJCIJFD().LNKFLFOGCCD = 0.625f;
			hNEBHCMAOAE14.IIJMLJCIJFD().FHJCBAOBGPG = 1.6f;
			hNEBHCMAOAE14.IIJMLJCIJFD().FBEBCNEPHJD = 22.21f;
			hNEBHCMAOAE14.IIJMLJCIJFD().PDAOIGGBLPH = 2.8f;
			hNEBHCMAOAE14.IIJMLJCIJFD().NLMHKBGDKLA = 30f;
			hNEBHCMAOAE14.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE14.IIJMLJCIJFD().NEPGMKLCMFF = 3.35f;
			hNEBHCMAOAE14.FKNPBEJDKGM().Add(6000u);
			hNEBHCMAOAE14.FKNPBEJDKGM().Add(8000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE14.INGLCFJBNOB(), hNEBHCMAOAE14);
			HNEBHCMAOAE hNEBHCMAOAE15 = new HNEBHCMAOAE();
			hNEBHCMAOAE15.FIGLEPBIEEJ(15, "잭스", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 17000u, 0u, 1, 1, "Jax");
			hNEBHCMAOAE15.IIJMLJCIJFD().LBJMNDBMNAE = 592u;
			hNEBHCMAOAE15.IIJMLJCIJFD().EPKGCHPIHEL = 85u;
			hNEBHCMAOAE15.IIJMLJCIJFD().JKOEPLLJDKM = 8.37f;
			hNEBHCMAOAE15.IIJMLJCIJFD().BKOBAIPJAHP = 0.55f;
			hNEBHCMAOAE15.IIJMLJCIJFD().OCOOIOGCOEE = 338u;
			hNEBHCMAOAE15.IIJMLJCIJFD().GHCBBJBDNPH = 32u;
			hNEBHCMAOAE15.IIJMLJCIJFD().MGLIOBDEJLF = 7.575f;
			hNEBHCMAOAE15.IIJMLJCIJFD().GFGOPIKFOAN = 0.7f;
			hNEBHCMAOAE15.IIJMLJCIJFD().IIICODNIMNN = 2.4f;
			hNEBHCMAOAE15.IIJMLJCIJFD().LOJEMAMKHFD = 67.97f;
			hNEBHCMAOAE15.IIJMLJCIJFD().ELDBGIKHAIO = 3.375f;
			hNEBHCMAOAE15.IIJMLJCIJFD().LNKFLFOGCCD = 0.638f;
			hNEBHCMAOAE15.IIJMLJCIJFD().FHJCBAOBGPG = 3.4f;
			hNEBHCMAOAE15.IIJMLJCIJFD().FBEBCNEPHJD = 33.04f;
			hNEBHCMAOAE15.IIJMLJCIJFD().PDAOIGGBLPH = 3f;
			hNEBHCMAOAE15.IIJMLJCIJFD().NLMHKBGDKLA = 32.1f;
			hNEBHCMAOAE15.IIJMLJCIJFD().JFLFAKNHKNP = 1.25f;
			hNEBHCMAOAE15.IIJMLJCIJFD().NEPGMKLCMFF = 3.5f;
			hNEBHCMAOAE15.FKNPBEJDKGM().Add(6000u);
			hNEBHCMAOAE15.FKNPBEJDKGM().Add(8000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE15.INGLCFJBNOB(), hNEBHCMAOAE15);
			HNEBHCMAOAE hNEBHCMAOAE16 = new HNEBHCMAOAE();
			hNEBHCMAOAE16.FIGLEPBIEEJ(16, "탈론", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 17000u, 0u, 1, 1, "Talon");
			hNEBHCMAOAE16.IIJMLJCIJFD().LBJMNDBMNAE = 582u;
			hNEBHCMAOAE16.IIJMLJCIJFD().EPKGCHPIHEL = 85u;
			hNEBHCMAOAE16.IIJMLJCIJFD().JKOEPLLJDKM = 8.51f;
			hNEBHCMAOAE16.IIJMLJCIJFD().BKOBAIPJAHP = 0.75f;
			hNEBHCMAOAE16.IIJMLJCIJFD().OCOOIOGCOEE = 377u;
			hNEBHCMAOAE16.IIJMLJCIJFD().GHCBBJBDNPH = 37u;
			hNEBHCMAOAE16.IIJMLJCIJFD().MGLIOBDEJLF = 7.59f;
			hNEBHCMAOAE16.IIJMLJCIJFD().GFGOPIKFOAN = 0.5f;
			hNEBHCMAOAE16.IIJMLJCIJFD().IIICODNIMNN = 2.4f;
			hNEBHCMAOAE16.IIJMLJCIJFD().LOJEMAMKHFD = 55.208f;
			hNEBHCMAOAE16.IIJMLJCIJFD().ELDBGIKHAIO = 3.1f;
			hNEBHCMAOAE16.IIJMLJCIJFD().LNKFLFOGCCD = 0.668f;
			hNEBHCMAOAE16.IIJMLJCIJFD().FHJCBAOBGPG = 2.7f;
			hNEBHCMAOAE16.IIJMLJCIJFD().FBEBCNEPHJD = 22.88f;
			hNEBHCMAOAE16.IIJMLJCIJFD().PDAOIGGBLPH = 3.7f;
			hNEBHCMAOAE16.IIJMLJCIJFD().NLMHKBGDKLA = 32.1f;
			hNEBHCMAOAE16.IIJMLJCIJFD().JFLFAKNHKNP = 1.25f;
			hNEBHCMAOAE16.IIJMLJCIJFD().NEPGMKLCMFF = 3.5f;
			hNEBHCMAOAE16.FKNPBEJDKGM().Add(8000u);
			hNEBHCMAOAE16.FKNPBEJDKGM().Add(10000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE16.INGLCFJBNOB(), hNEBHCMAOAE16);
			HNEBHCMAOAE hNEBHCMAOAE17 = new HNEBHCMAOAE();
			hNEBHCMAOAE17.FIGLEPBIEEJ(17, "루시안", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Range, 17000u, 0u, 1, 1, "Lucian");
			hNEBHCMAOAE17.IIJMLJCIJFD().LBJMNDBMNAE = 554u;
			hNEBHCMAOAE17.IIJMLJCIJFD().EPKGCHPIHEL = 80u;
			hNEBHCMAOAE17.IIJMLJCIJFD().JKOEPLLJDKM = 6.19f;
			hNEBHCMAOAE17.IIJMLJCIJFD().BKOBAIPJAHP = 0.65f;
			hNEBHCMAOAE17.IIJMLJCIJFD().OCOOIOGCOEE = 348u;
			hNEBHCMAOAE17.IIJMLJCIJFD().GHCBBJBDNPH = 38u;
			hNEBHCMAOAE17.IIJMLJCIJFD().MGLIOBDEJLF = 8.175f;
			hNEBHCMAOAE17.IIJMLJCIJFD().GFGOPIKFOAN = 0.7f;
			hNEBHCMAOAE17.IIJMLJCIJFD().IIICODNIMNN = 5.25f;
			hNEBHCMAOAE17.IIJMLJCIJFD().LOJEMAMKHFD = 57.46f;
			hNEBHCMAOAE17.IIJMLJCIJFD().ELDBGIKHAIO = 2.41f;
			hNEBHCMAOAE17.IIJMLJCIJFD().LNKFLFOGCCD = 0.638f;
			hNEBHCMAOAE17.IIJMLJCIJFD().FHJCBAOBGPG = 3.3f;
			hNEBHCMAOAE17.IIJMLJCIJFD().FBEBCNEPHJD = 24.04f;
			hNEBHCMAOAE17.IIJMLJCIJFD().PDAOIGGBLPH = 3f;
			hNEBHCMAOAE17.IIJMLJCIJFD().NLMHKBGDKLA = 30f;
			hNEBHCMAOAE17.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE17.IIJMLJCIJFD().NEPGMKLCMFF = 3.35f;
			hNEBHCMAOAE17.FKNPBEJDKGM().Add(8000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE17.INGLCFJBNOB(), hNEBHCMAOAE17);
			HNEBHCMAOAE hNEBHCMAOAE18 = new HNEBHCMAOAE();
			hNEBHCMAOAE18.FIGLEPBIEEJ(18, "야스오", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 17000u, 0u, 1, 1, "Yasuo");
			hNEBHCMAOAE18.IIJMLJCIJFD().LBJMNDBMNAE = 517u;
			hNEBHCMAOAE18.IIJMLJCIJFD().EPKGCHPIHEL = 82u;
			hNEBHCMAOAE18.IIJMLJCIJFD().JKOEPLLJDKM = 6.51f;
			hNEBHCMAOAE18.IIJMLJCIJFD().BKOBAIPJAHP = 0.9f;
			hNEBHCMAOAE18.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE18.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE18.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE18.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE18.IIJMLJCIJFD().IIICODNIMNN = 2.4f;
			hNEBHCMAOAE18.IIJMLJCIJFD().LOJEMAMKHFD = 55.376f;
			hNEBHCMAOAE18.IIJMLJCIJFD().ELDBGIKHAIO = 3.2f;
			hNEBHCMAOAE18.IIJMLJCIJFD().LNKFLFOGCCD = 0.658f;
			hNEBHCMAOAE18.IIJMLJCIJFD().FHJCBAOBGPG = 3.2f;
			hNEBHCMAOAE18.IIJMLJCIJFD().FBEBCNEPHJD = 24.712f;
			hNEBHCMAOAE18.IIJMLJCIJFD().PDAOIGGBLPH = 3.4f;
			hNEBHCMAOAE18.IIJMLJCIJFD().NLMHKBGDKLA = 30f;
			hNEBHCMAOAE18.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE18.IIJMLJCIJFD().NEPGMKLCMFF = 3.45f;
			hNEBHCMAOAE18.FKNPBEJDKGM().Add(8000u);
			hNEBHCMAOAE18.FKNPBEJDKGM().Add(14000u);
			hNEBHCMAOAE18.FKNPBEJDKGM().Add(16000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE18.INGLCFJBNOB(), hNEBHCMAOAE18);
			HNEBHCMAOAE hNEBHCMAOAE19 = new HNEBHCMAOAE();
			hNEBHCMAOAE19.FIGLEPBIEEJ(19, "블라디미르", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Range, 19000u, 0u, 1, 1, "Vladimir");
			hNEBHCMAOAE19.IIJMLJCIJFD().LBJMNDBMNAE = 525u;
			hNEBHCMAOAE19.IIJMLJCIJFD().EPKGCHPIHEL = 84u;
			hNEBHCMAOAE19.IIJMLJCIJFD().JKOEPLLJDKM = 7.1f;
			hNEBHCMAOAE19.IIJMLJCIJFD().BKOBAIPJAHP = 0.6f;
			hNEBHCMAOAE19.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE19.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE19.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE19.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE19.IIJMLJCIJFD().IIICODNIMNN = 4.5f;
			hNEBHCMAOAE19.IIJMLJCIJFD().LOJEMAMKHFD = 52f;
			hNEBHCMAOAE19.IIJMLJCIJFD().ELDBGIKHAIO = 3f;
			hNEBHCMAOAE19.IIJMLJCIJFD().LNKFLFOGCCD = 0.658f;
			hNEBHCMAOAE19.IIJMLJCIJFD().FHJCBAOBGPG = 2f;
			hNEBHCMAOAE19.IIJMLJCIJFD().FBEBCNEPHJD = 23f;
			hNEBHCMAOAE19.IIJMLJCIJFD().PDAOIGGBLPH = 3.3f;
			hNEBHCMAOAE19.IIJMLJCIJFD().NLMHKBGDKLA = 30f;
			hNEBHCMAOAE19.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE19.IIJMLJCIJFD().NEPGMKLCMFF = 3.3f;
			hNEBHCMAOAE19.FKNPBEJDKGM().Add(8000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE19.INGLCFJBNOB(), hNEBHCMAOAE19);
			HNEBHCMAOAE hNEBHCMAOAE20 = new HNEBHCMAOAE();
			hNEBHCMAOAE20.FIGLEPBIEEJ(20, "트린다미어", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 17000u, 0u, 1, 1, "Tryndamere");
			hNEBHCMAOAE20.IIJMLJCIJFD().LBJMNDBMNAE = 625u;
			hNEBHCMAOAE20.IIJMLJCIJFD().EPKGCHPIHEL = 98u;
			hNEBHCMAOAE20.IIJMLJCIJFD().JKOEPLLJDKM = 8.51f;
			hNEBHCMAOAE20.IIJMLJCIJFD().BKOBAIPJAHP = 0.9f;
			hNEBHCMAOAE20.IIJMLJCIJFD().OCOOIOGCOEE = 100u;
			hNEBHCMAOAE20.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE20.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE20.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE20.IIJMLJCIJFD().IIICODNIMNN = 2.4f;
			hNEBHCMAOAE20.IIJMLJCIJFD().LOJEMAMKHFD = 61.376f;
			hNEBHCMAOAE20.IIJMLJCIJFD().ELDBGIKHAIO = 3.6f;
			hNEBHCMAOAE20.IIJMLJCIJFD().LNKFLFOGCCD = 0.67f;
			hNEBHCMAOAE20.IIJMLJCIJFD().FHJCBAOBGPG = 2.9f;
			hNEBHCMAOAE20.IIJMLJCIJFD().FBEBCNEPHJD = 24.1f;
			hNEBHCMAOAE20.IIJMLJCIJFD().PDAOIGGBLPH = 3.1f;
			hNEBHCMAOAE20.IIJMLJCIJFD().NLMHKBGDKLA = 32.1f;
			hNEBHCMAOAE20.IIJMLJCIJFD().JFLFAKNHKNP = 1.25f;
			hNEBHCMAOAE20.IIJMLJCIJFD().NEPGMKLCMFF = 3.45f;
			hNEBHCMAOAE20.FKNPBEJDKGM().Add(6000u);
			hNEBHCMAOAE20.FKNPBEJDKGM().Add(8000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE20.INGLCFJBNOB(), hNEBHCMAOAE20);
			HNEBHCMAOAE hNEBHCMAOAE21 = new HNEBHCMAOAE();
			hNEBHCMAOAE21.FIGLEPBIEEJ(21, "티모", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Range, 15000u, 0u, 1, 1, "Teemo");
			hNEBHCMAOAE21.IIJMLJCIJFD().LBJMNDBMNAE = 516u;
			hNEBHCMAOAE21.IIJMLJCIJFD().EPKGCHPIHEL = 82u;
			hNEBHCMAOAE21.IIJMLJCIJFD().JKOEPLLJDKM = 5.74f;
			hNEBHCMAOAE21.IIJMLJCIJFD().BKOBAIPJAHP = 0.65f;
			hNEBHCMAOAE21.IIJMLJCIJFD().OCOOIOGCOEE = 267u;
			hNEBHCMAOAE21.IIJMLJCIJFD().GHCBBJBDNPH = 40u;
			hNEBHCMAOAE21.IIJMLJCIJFD().MGLIOBDEJLF = 7.205f;
			hNEBHCMAOAE21.IIJMLJCIJFD().GFGOPIKFOAN = 0.45f;
			hNEBHCMAOAE21.IIJMLJCIJFD().IIICODNIMNN = 5f;
			hNEBHCMAOAE21.IIJMLJCIJFD().LOJEMAMKHFD = 49.54f;
			hNEBHCMAOAE21.IIJMLJCIJFD().ELDBGIKHAIO = 3f;
			hNEBHCMAOAE21.IIJMLJCIJFD().LNKFLFOGCCD = 0.69f;
			hNEBHCMAOAE21.IIJMLJCIJFD().FHJCBAOBGPG = 3.38f;
			hNEBHCMAOAE21.IIJMLJCIJFD().FBEBCNEPHJD = 24.3f;
			hNEBHCMAOAE21.IIJMLJCIJFD().PDAOIGGBLPH = 3.75f;
			hNEBHCMAOAE21.IIJMLJCIJFD().NLMHKBGDKLA = 30f;
			hNEBHCMAOAE21.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE21.IIJMLJCIJFD().NEPGMKLCMFF = 3.3f;
			hNEBHCMAOAE21.FKNPBEJDKGM().Add(6000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE21.INGLCFJBNOB(), hNEBHCMAOAE21);
			HNEBHCMAOAE hNEBHCMAOAE22 = new HNEBHCMAOAE();
			hNEBHCMAOAE22.FIGLEPBIEEJ(22, "브랜드", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Range, 21000u, 0u, 1, 1, "Brand");
			hNEBHCMAOAE22.IIJMLJCIJFD().LBJMNDBMNAE = 507u;
			hNEBHCMAOAE22.IIJMLJCIJFD().EPKGCHPIHEL = 76u;
			hNEBHCMAOAE22.IIJMLJCIJFD().JKOEPLLJDKM = 5.42f;
			hNEBHCMAOAE22.IIJMLJCIJFD().BKOBAIPJAHP = 0.55f;
			hNEBHCMAOAE22.IIJMLJCIJFD().OCOOIOGCOEE = 375u;
			hNEBHCMAOAE22.IIJMLJCIJFD().GHCBBJBDNPH = 42u;
			hNEBHCMAOAE22.IIJMLJCIJFD().MGLIOBDEJLF = 8.005f;
			hNEBHCMAOAE22.IIJMLJCIJFD().GFGOPIKFOAN = 0.6f;
			hNEBHCMAOAE22.IIJMLJCIJFD().IIICODNIMNN = 5.5f;
			hNEBHCMAOAE22.IIJMLJCIJFD().LOJEMAMKHFD = 57.04f;
			hNEBHCMAOAE22.IIJMLJCIJFD().ELDBGIKHAIO = 3f;
			hNEBHCMAOAE22.IIJMLJCIJFD().LNKFLFOGCCD = 0.625f;
			hNEBHCMAOAE22.IIJMLJCIJFD().FHJCBAOBGPG = 1.36f;
			hNEBHCMAOAE22.IIJMLJCIJFD().FBEBCNEPHJD = 21.88f;
			hNEBHCMAOAE22.IIJMLJCIJFD().PDAOIGGBLPH = 3.5f;
			hNEBHCMAOAE22.IIJMLJCIJFD().NLMHKBGDKLA = 30f;
			hNEBHCMAOAE22.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE22.IIJMLJCIJFD().NEPGMKLCMFF = 3.4f;
			hNEBHCMAOAE22.FKNPBEJDKGM().Add(6000u);
			hNEBHCMAOAE22.FKNPBEJDKGM().Add(8000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE22.INGLCFJBNOB(), hNEBHCMAOAE22);
			HNEBHCMAOAE hNEBHCMAOAE23 = new HNEBHCMAOAE();
			hNEBHCMAOAE23.FIGLEPBIEEJ(23, "다리우스", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 21000u, 0u, 1, 1, "Darius");
			hNEBHCMAOAE23.IIJMLJCIJFD().LBJMNDBMNAE = 582u;
			hNEBHCMAOAE23.IIJMLJCIJFD().EPKGCHPIHEL = 100u;
			hNEBHCMAOAE23.IIJMLJCIJFD().JKOEPLLJDKM = 9.845f;
			hNEBHCMAOAE23.IIJMLJCIJFD().BKOBAIPJAHP = 0.95f;
			hNEBHCMAOAE23.IIJMLJCIJFD().OCOOIOGCOEE = 263u;
			hNEBHCMAOAE23.IIJMLJCIJFD().GHCBBJBDNPH = 40u;
			hNEBHCMAOAE23.IIJMLJCIJFD().MGLIOBDEJLF = 6.585f;
			hNEBHCMAOAE23.IIJMLJCIJFD().GFGOPIKFOAN = 0.35f;
			hNEBHCMAOAE23.IIJMLJCIJFD().IIICODNIMNN = 2.4f;
			hNEBHCMAOAE23.IIJMLJCIJFD().LOJEMAMKHFD = 55.88f;
			hNEBHCMAOAE23.IIJMLJCIJFD().ELDBGIKHAIO = 4.6f;
			hNEBHCMAOAE23.IIJMLJCIJFD().LNKFLFOGCCD = 0.625f;
			hNEBHCMAOAE23.IIJMLJCIJFD().FHJCBAOBGPG = 1f;
			hNEBHCMAOAE23.IIJMLJCIJFD().FBEBCNEPHJD = 29.88f;
			hNEBHCMAOAE23.IIJMLJCIJFD().PDAOIGGBLPH = 4f;
			hNEBHCMAOAE23.IIJMLJCIJFD().NLMHKBGDKLA = 32.1f;
			hNEBHCMAOAE23.IIJMLJCIJFD().JFLFAKNHKNP = 1.25f;
			hNEBHCMAOAE23.IIJMLJCIJFD().NEPGMKLCMFF = 3.4f;
			hNEBHCMAOAE23.FKNPBEJDKGM().Add(10000u);
			hNEBHCMAOAE23.FKNPBEJDKGM().Add(6000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE23.INGLCFJBNOB(), hNEBHCMAOAE23);
			HNEBHCMAOAE hNEBHCMAOAE24 = new HNEBHCMAOAE();
			hNEBHCMAOAE24.FIGLEPBIEEJ(24, "트리스타나", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Range, 21000u, 0u, 1, 1, "Tristana");
			hNEBHCMAOAE24.IIJMLJCIJFD().LBJMNDBMNAE = 559u;
			hNEBHCMAOAE24.IIJMLJCIJFD().EPKGCHPIHEL = 88u;
			hNEBHCMAOAE24.IIJMLJCIJFD().JKOEPLLJDKM = 3.75f;
			hNEBHCMAOAE24.IIJMLJCIJFD().BKOBAIPJAHP = 0.65f;
			hNEBHCMAOAE24.IIJMLJCIJFD().OCOOIOGCOEE = 250u;
			hNEBHCMAOAE24.IIJMLJCIJFD().GHCBBJBDNPH = 32u;
			hNEBHCMAOAE24.IIJMLJCIJFD().MGLIOBDEJLF = 7.2f;
			hNEBHCMAOAE24.IIJMLJCIJFD().GFGOPIKFOAN = 0.45f;
			hNEBHCMAOAE24.IIJMLJCIJFD().IIICODNIMNN = 5.25f;
			hNEBHCMAOAE24.IIJMLJCIJFD().LOJEMAMKHFD = 61f;
			hNEBHCMAOAE24.IIJMLJCIJFD().ELDBGIKHAIO = 3.3f;
			hNEBHCMAOAE24.IIJMLJCIJFD().LNKFLFOGCCD = 0.656f;
			hNEBHCMAOAE24.IIJMLJCIJFD().FHJCBAOBGPG = 1.5f;
			hNEBHCMAOAE24.IIJMLJCIJFD().FBEBCNEPHJD = 26f;
			hNEBHCMAOAE24.IIJMLJCIJFD().PDAOIGGBLPH = 3f;
			hNEBHCMAOAE24.IIJMLJCIJFD().NLMHKBGDKLA = 30f;
			hNEBHCMAOAE24.IIJMLJCIJFD().JFLFAKNHKNP = 0.5f;
			hNEBHCMAOAE24.IIJMLJCIJFD().NEPGMKLCMFF = 3.25f;
			hNEBHCMAOAE24.FKNPBEJDKGM().Add(6000u);
			hNEBHCMAOAE24.FKNPBEJDKGM().Add(8000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE24.INGLCFJBNOB(), hNEBHCMAOAE24);
			HNEBHCMAOAE hNEBHCMAOAE25 = new HNEBHCMAOAE();
			hNEBHCMAOAE25.FIGLEPBIEEJ(25, "소라카", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Range, 19000u, 0u, 1, 1, "Soraka");
			hNEBHCMAOAE25.IIJMLJCIJFD().LBJMNDBMNAE = 530u;
			hNEBHCMAOAE25.IIJMLJCIJFD().EPKGCHPIHEL = 78u;
			hNEBHCMAOAE25.IIJMLJCIJFD().JKOEPLLJDKM = 2.5f;
			hNEBHCMAOAE25.IIJMLJCIJFD().BKOBAIPJAHP = 0.5f;
			hNEBHCMAOAE25.IIJMLJCIJFD().OCOOIOGCOEE = 350u;
			hNEBHCMAOAE25.IIJMLJCIJFD().GHCBBJBDNPH = 60u;
			hNEBHCMAOAE25.IIJMLJCIJFD().MGLIOBDEJLF = 11.5f;
			hNEBHCMAOAE25.IIJMLJCIJFD().GFGOPIKFOAN = 0.4f;
			hNEBHCMAOAE25.IIJMLJCIJFD().IIICODNIMNN = 5.5f;
			hNEBHCMAOAE25.IIJMLJCIJFD().LOJEMAMKHFD = 50.04f;
			hNEBHCMAOAE25.IIJMLJCIJFD().ELDBGIKHAIO = 3f;
			hNEBHCMAOAE25.IIJMLJCIJFD().LNKFLFOGCCD = 0.625f;
			hNEBHCMAOAE25.IIJMLJCIJFD().FHJCBAOBGPG = 2.14f;
			hNEBHCMAOAE25.IIJMLJCIJFD().FBEBCNEPHJD = 32f;
			hNEBHCMAOAE25.IIJMLJCIJFD().PDAOIGGBLPH = 3.8f;
			hNEBHCMAOAE25.IIJMLJCIJFD().NLMHKBGDKLA = 30f;
			hNEBHCMAOAE25.IIJMLJCIJFD().JFLFAKNHKNP = 0.5f;
			hNEBHCMAOAE25.IIJMLJCIJFD().NEPGMKLCMFF = 3.25f;
			hNEBHCMAOAE25.FKNPBEJDKGM().Add(6000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE25.INGLCFJBNOB(), hNEBHCMAOAE25);
			HNEBHCMAOAE hNEBHCMAOAE26 = new HNEBHCMAOAE();
			hNEBHCMAOAE26.FIGLEPBIEEJ(26, "올라프", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 21000u, 0u, 1, 1, "Olaf");
			hNEBHCMAOAE26.IIJMLJCIJFD().LBJMNDBMNAE = 597u;
			hNEBHCMAOAE26.IIJMLJCIJFD().EPKGCHPIHEL = 93u;
			hNEBHCMAOAE26.IIJMLJCIJFD().JKOEPLLJDKM = 8.5f;
			hNEBHCMAOAE26.IIJMLJCIJFD().BKOBAIPJAHP = 0.91f;
			hNEBHCMAOAE26.IIJMLJCIJFD().OCOOIOGCOEE = 315u;
			hNEBHCMAOAE26.IIJMLJCIJFD().GHCBBJBDNPH = 42u;
			hNEBHCMAOAE26.IIJMLJCIJFD().MGLIOBDEJLF = 7.5f;
			hNEBHCMAOAE26.IIJMLJCIJFD().GFGOPIKFOAN = 0.56f;
			hNEBHCMAOAE26.IIJMLJCIJFD().IIICODNIMNN = 2.4f;
			hNEBHCMAOAE26.IIJMLJCIJFD().LOJEMAMKHFD = 61.2f;
			hNEBHCMAOAE26.IIJMLJCIJFD().ELDBGIKHAIO = 3.5f;
			hNEBHCMAOAE26.IIJMLJCIJFD().LNKFLFOGCCD = 0.694f;
			hNEBHCMAOAE26.IIJMLJCIJFD().FHJCBAOBGPG = 2.7f;
			hNEBHCMAOAE26.IIJMLJCIJFD().FBEBCNEPHJD = 35f;
			hNEBHCMAOAE26.IIJMLJCIJFD().PDAOIGGBLPH = 3f;
			hNEBHCMAOAE26.IIJMLJCIJFD().NLMHKBGDKLA = 32.1f;
			hNEBHCMAOAE26.IIJMLJCIJFD().JFLFAKNHKNP = 1.25f;
			hNEBHCMAOAE26.IIJMLJCIJFD().NEPGMKLCMFF = 3.5f;
			hNEBHCMAOAE26.FKNPBEJDKGM().Add(8000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE26.INGLCFJBNOB(), hNEBHCMAOAE26);
			HNEBHCMAOAE hNEBHCMAOAE27 = new HNEBHCMAOAE();
			hNEBHCMAOAE27.FIGLEPBIEEJ(27, "피즈", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 23000u, 0u, 1, 1, "Fizz");
			hNEBHCMAOAE27.IIJMLJCIJFD().LBJMNDBMNAE = 570u;
			hNEBHCMAOAE27.IIJMLJCIJFD().EPKGCHPIHEL = 98u;
			hNEBHCMAOAE27.IIJMLJCIJFD().JKOEPLLJDKM = 8f;
			hNEBHCMAOAE27.IIJMLJCIJFD().BKOBAIPJAHP = 0.71f;
			hNEBHCMAOAE27.IIJMLJCIJFD().OCOOIOGCOEE = 240u;
			hNEBHCMAOAE27.IIJMLJCIJFD().GHCBBJBDNPH = 40u;
			hNEBHCMAOAE27.IIJMLJCIJFD().MGLIOBDEJLF = 6f;
			hNEBHCMAOAE27.IIJMLJCIJFD().GFGOPIKFOAN = 0.8f;
			hNEBHCMAOAE27.IIJMLJCIJFD().IIICODNIMNN = 2.4f;
			hNEBHCMAOAE27.IIJMLJCIJFD().LOJEMAMKHFD = 58.04f;
			hNEBHCMAOAE27.IIJMLJCIJFD().ELDBGIKHAIO = 3f;
			hNEBHCMAOAE27.IIJMLJCIJFD().LNKFLFOGCCD = 0.658f;
			hNEBHCMAOAE27.IIJMLJCIJFD().FHJCBAOBGPG = 3.1f;
			hNEBHCMAOAE27.IIJMLJCIJFD().FBEBCNEPHJD = 22.41f;
			hNEBHCMAOAE27.IIJMLJCIJFD().PDAOIGGBLPH = 3.4f;
			hNEBHCMAOAE27.IIJMLJCIJFD().NLMHKBGDKLA = 32.1f;
			hNEBHCMAOAE27.IIJMLJCIJFD().JFLFAKNHKNP = 1.25f;
			hNEBHCMAOAE27.IIJMLJCIJFD().NEPGMKLCMFF = 3.35f;
			hNEBHCMAOAE27.FKNPBEJDKGM().Add(10000u);
			EPEJNKKPCCG().Add(hNEBHCMAOAE27.INGLCFJBNOB(), hNEBHCMAOAE27);
			HNEBHCMAOAE hNEBHCMAOAE28 = new HNEBHCMAOAE();
			hNEBHCMAOAE28.FIGLEPBIEEJ(10000, "블루 근접미니언", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Minion, HNEBHCMAOAE.HFIHMACFPMM.Melee, 0u, 0u, 1, 0, "BlueMinionMelee");
			hNEBHCMAOAE28.IIJMLJCIJFD().LBJMNDBMNAE = 390u;
			hNEBHCMAOAE28.IIJMLJCIJFD().EPKGCHPIHEL = 20u;
			hNEBHCMAOAE28.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE28.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE28.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE28.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE28.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE28.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE28.IIJMLJCIJFD().IIICODNIMNN = 1.5f;
			hNEBHCMAOAE28.IIJMLJCIJFD().LOJEMAMKHFD = 12f;
			hNEBHCMAOAE28.IIJMLJCIJFD().ELDBGIKHAIO = 0.7f;
			hNEBHCMAOAE28.IIJMLJCIJFD().LNKFLFOGCCD = 1.25f;
			hNEBHCMAOAE28.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE28.IIJMLJCIJFD().FBEBCNEPHJD = 0f;
			hNEBHCMAOAE28.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE28.IIJMLJCIJFD().NLMHKBGDKLA = 0f;
			hNEBHCMAOAE28.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE28.IIJMLJCIJFD().NEPGMKLCMFF = 3.25f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE28.INGLCFJBNOB(), hNEBHCMAOAE28);
			HNEBHCMAOAE hNEBHCMAOAE29 = new HNEBHCMAOAE();
			hNEBHCMAOAE29.FIGLEPBIEEJ(10001, "블루 원거리미니언", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Minion, HNEBHCMAOAE.HFIHMACFPMM.Range, 0u, 0u, 1, 0, "BlueMinionWizard");
			hNEBHCMAOAE29.IIJMLJCIJFD().LBJMNDBMNAE = 250u;
			hNEBHCMAOAE29.IIJMLJCIJFD().EPKGCHPIHEL = 10u;
			hNEBHCMAOAE29.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE29.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE29.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE29.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE29.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE29.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE29.IIJMLJCIJFD().IIICODNIMNN = 4f;
			hNEBHCMAOAE29.IIJMLJCIJFD().LOJEMAMKHFD = 23f;
			hNEBHCMAOAE29.IIJMLJCIJFD().ELDBGIKHAIO = 2.25f;
			hNEBHCMAOAE29.IIJMLJCIJFD().LNKFLFOGCCD = 0.67f;
			hNEBHCMAOAE29.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE29.IIJMLJCIJFD().FBEBCNEPHJD = 0f;
			hNEBHCMAOAE29.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE29.IIJMLJCIJFD().NLMHKBGDKLA = 0f;
			hNEBHCMAOAE29.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE29.IIJMLJCIJFD().NEPGMKLCMFF = 3.25f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE29.INGLCFJBNOB(), hNEBHCMAOAE29);
			HNEBHCMAOAE hNEBHCMAOAE30 = new HNEBHCMAOAE();
			hNEBHCMAOAE30.FIGLEPBIEEJ(10002, "블루 캐논미니언", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Minion, HNEBHCMAOAE.HFIHMACFPMM.Range, 0u, 0u, 1, 0, "BlueMinionCannon");
			hNEBHCMAOAE30.IIJMLJCIJFD().LBJMNDBMNAE = 605u;
			hNEBHCMAOAE30.IIJMLJCIJFD().EPKGCHPIHEL = 35u;
			hNEBHCMAOAE30.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE30.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE30.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE30.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE30.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE30.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE30.IIJMLJCIJFD().IIICODNIMNN = 5f;
			hNEBHCMAOAE30.IIJMLJCIJFD().LOJEMAMKHFD = 39.5f;
			hNEBHCMAOAE30.IIJMLJCIJFD().ELDBGIKHAIO = 2.25f;
			hNEBHCMAOAE30.IIJMLJCIJFD().LNKFLFOGCCD = 1f;
			hNEBHCMAOAE30.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE30.IIJMLJCIJFD().FBEBCNEPHJD = 0f;
			hNEBHCMAOAE30.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE30.IIJMLJCIJFD().NLMHKBGDKLA = 0f;
			hNEBHCMAOAE30.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE30.IIJMLJCIJFD().NEPGMKLCMFF = 3.25f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE30.INGLCFJBNOB(), hNEBHCMAOAE30);
			HNEBHCMAOAE hNEBHCMAOAE31 = new HNEBHCMAOAE();
			hNEBHCMAOAE31.FIGLEPBIEEJ(10003, "블루 수퍼미니언", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Minion, HNEBHCMAOAE.HFIHMACFPMM.Melee, 0u, 0u, 1, 0, "BlueMinionSuper");
			hNEBHCMAOAE31.IIJMLJCIJFD().LBJMNDBMNAE = 1500u;
			hNEBHCMAOAE31.IIJMLJCIJFD().EPKGCHPIHEL = 80u;
			hNEBHCMAOAE31.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE31.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE31.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE31.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE31.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE31.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE31.IIJMLJCIJFD().IIICODNIMNN = 2f;
			hNEBHCMAOAE31.IIJMLJCIJFD().LOJEMAMKHFD = 190f;
			hNEBHCMAOAE31.IIJMLJCIJFD().ELDBGIKHAIO = 6.6f;
			hNEBHCMAOAE31.IIJMLJCIJFD().LNKFLFOGCCD = 0.694f;
			hNEBHCMAOAE31.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE31.IIJMLJCIJFD().FBEBCNEPHJD = 30f;
			hNEBHCMAOAE31.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE31.IIJMLJCIJFD().NLMHKBGDKLA = 0f;
			hNEBHCMAOAE31.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE31.IIJMLJCIJFD().NEPGMKLCMFF = 3.25f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE31.INGLCFJBNOB(), hNEBHCMAOAE31);
			HNEBHCMAOAE hNEBHCMAOAE32 = new HNEBHCMAOAE();
			hNEBHCMAOAE32.FIGLEPBIEEJ(10010, "레드 근접미니언", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Minion, HNEBHCMAOAE.HFIHMACFPMM.Melee, 0u, 0u, 1, 0, "RedMinionMelee");
			hNEBHCMAOAE32.IIJMLJCIJFD().LBJMNDBMNAE = 390u;
			hNEBHCMAOAE32.IIJMLJCIJFD().EPKGCHPIHEL = 20u;
			hNEBHCMAOAE32.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE32.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE32.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE32.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE32.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE32.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE32.IIJMLJCIJFD().IIICODNIMNN = 1.5f;
			hNEBHCMAOAE32.IIJMLJCIJFD().LOJEMAMKHFD = 12f;
			hNEBHCMAOAE32.IIJMLJCIJFD().ELDBGIKHAIO = 0.7f;
			hNEBHCMAOAE32.IIJMLJCIJFD().LNKFLFOGCCD = 1.25f;
			hNEBHCMAOAE32.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE32.IIJMLJCIJFD().FBEBCNEPHJD = 0f;
			hNEBHCMAOAE32.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE32.IIJMLJCIJFD().NLMHKBGDKLA = 0f;
			hNEBHCMAOAE32.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE32.IIJMLJCIJFD().NEPGMKLCMFF = 3.25f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE32.INGLCFJBNOB(), hNEBHCMAOAE32);
			HNEBHCMAOAE hNEBHCMAOAE33 = new HNEBHCMAOAE();
			hNEBHCMAOAE33.FIGLEPBIEEJ(10011, "레드 원거리미니언", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Minion, HNEBHCMAOAE.HFIHMACFPMM.Range, 0u, 0u, 1, 0, "RedMinionWizard");
			hNEBHCMAOAE33.IIJMLJCIJFD().LBJMNDBMNAE = 250u;
			hNEBHCMAOAE33.IIJMLJCIJFD().EPKGCHPIHEL = 10u;
			hNEBHCMAOAE33.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE33.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE33.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE33.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE33.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE33.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE33.IIJMLJCIJFD().IIICODNIMNN = 4f;
			hNEBHCMAOAE33.IIJMLJCIJFD().LOJEMAMKHFD = 23f;
			hNEBHCMAOAE33.IIJMLJCIJFD().ELDBGIKHAIO = 2.25f;
			hNEBHCMAOAE33.IIJMLJCIJFD().LNKFLFOGCCD = 0.67f;
			hNEBHCMAOAE33.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE33.IIJMLJCIJFD().FBEBCNEPHJD = 0f;
			hNEBHCMAOAE33.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE33.IIJMLJCIJFD().NLMHKBGDKLA = 0f;
			hNEBHCMAOAE33.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE33.IIJMLJCIJFD().NEPGMKLCMFF = 3.25f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE33.INGLCFJBNOB(), hNEBHCMAOAE33);
			HNEBHCMAOAE hNEBHCMAOAE34 = new HNEBHCMAOAE();
			hNEBHCMAOAE34.FIGLEPBIEEJ(10012, "레드 캐논미니언", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Minion, HNEBHCMAOAE.HFIHMACFPMM.Range, 0u, 0u, 1, 0, "RedMinionCannon");
			hNEBHCMAOAE34.IIJMLJCIJFD().LBJMNDBMNAE = 605u;
			hNEBHCMAOAE34.IIJMLJCIJFD().EPKGCHPIHEL = 35u;
			hNEBHCMAOAE34.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE34.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE34.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE34.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE34.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE34.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE34.IIJMLJCIJFD().IIICODNIMNN = 5f;
			hNEBHCMAOAE34.IIJMLJCIJFD().LOJEMAMKHFD = 39.5f;
			hNEBHCMAOAE34.IIJMLJCIJFD().ELDBGIKHAIO = 2.25f;
			hNEBHCMAOAE34.IIJMLJCIJFD().LNKFLFOGCCD = 1f;
			hNEBHCMAOAE34.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE34.IIJMLJCIJFD().FBEBCNEPHJD = 0f;
			hNEBHCMAOAE34.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE34.IIJMLJCIJFD().NLMHKBGDKLA = 0f;
			hNEBHCMAOAE34.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE34.IIJMLJCIJFD().NEPGMKLCMFF = 3.25f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE34.INGLCFJBNOB(), hNEBHCMAOAE34);
			HNEBHCMAOAE hNEBHCMAOAE35 = new HNEBHCMAOAE();
			hNEBHCMAOAE35.FIGLEPBIEEJ(10013, "레드 수퍼미니언", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Minion, HNEBHCMAOAE.HFIHMACFPMM.Melee, 0u, 0u, 1, 0, "RedMinionSuper");
			hNEBHCMAOAE35.IIJMLJCIJFD().LBJMNDBMNAE = 1500u;
			hNEBHCMAOAE35.IIJMLJCIJFD().EPKGCHPIHEL = 80u;
			hNEBHCMAOAE35.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE35.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE35.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE35.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE35.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE35.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE35.IIJMLJCIJFD().IIICODNIMNN = 2f;
			hNEBHCMAOAE35.IIJMLJCIJFD().LOJEMAMKHFD = 190f;
			hNEBHCMAOAE35.IIJMLJCIJFD().ELDBGIKHAIO = 6.6f;
			hNEBHCMAOAE35.IIJMLJCIJFD().LNKFLFOGCCD = 0.694f;
			hNEBHCMAOAE35.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE35.IIJMLJCIJFD().FBEBCNEPHJD = 30f;
			hNEBHCMAOAE35.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE35.IIJMLJCIJFD().NLMHKBGDKLA = 0f;
			hNEBHCMAOAE35.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE35.IIJMLJCIJFD().NEPGMKLCMFF = 3.25f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE35.INGLCFJBNOB(), hNEBHCMAOAE35);
			HNEBHCMAOAE hNEBHCMAOAE36 = new HNEBHCMAOAE();
			hNEBHCMAOAE36.FIGLEPBIEEJ(10100, "골드레드", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Minion, HNEBHCMAOAE.HFIHMACFPMM.Melee, 0u, 0u, 1, 0, "GoldLizardElder");
			hNEBHCMAOAE36.IIJMLJCIJFD().LBJMNDBMNAE = 3000u;
			hNEBHCMAOAE36.IIJMLJCIJFD().EPKGCHPIHEL = 20u;
			hNEBHCMAOAE36.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE36.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE36.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE36.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE36.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE36.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE36.IIJMLJCIJFD().IIICODNIMNN = 2f;
			hNEBHCMAOAE36.IIJMLJCIJFD().LOJEMAMKHFD = 60f;
			hNEBHCMAOAE36.IIJMLJCIJFD().ELDBGIKHAIO = 1f;
			hNEBHCMAOAE36.IIJMLJCIJFD().LNKFLFOGCCD = 1.5f;
			hNEBHCMAOAE36.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE36.IIJMLJCIJFD().FBEBCNEPHJD = 20f;
			hNEBHCMAOAE36.IIJMLJCIJFD().PDAOIGGBLPH = 2f;
			hNEBHCMAOAE36.IIJMLJCIJFD().NLMHKBGDKLA = 0f;
			hNEBHCMAOAE36.IIJMLJCIJFD().JFLFAKNHKNP = 1.25f;
			hNEBHCMAOAE36.IIJMLJCIJFD().NEPGMKLCMFF = 3.5f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE36.INGLCFJBNOB(), hNEBHCMAOAE36);
			HNEBHCMAOAE hNEBHCMAOAE37 = new HNEBHCMAOAE();
			hNEBHCMAOAE37.FIGLEPBIEEJ(20000, "리자드엘더", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Monster, HNEBHCMAOAE.HFIHMACFPMM.Melee, 0u, 0u, 1, 0, "LizardElder");
			hNEBHCMAOAE37.IIJMLJCIJFD().LBJMNDBMNAE = 1800u;
			hNEBHCMAOAE37.IIJMLJCIJFD().EPKGCHPIHEL = 500u;
			hNEBHCMAOAE37.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE37.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE37.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE37.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE37.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE37.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE37.IIJMLJCIJFD().IIICODNIMNN = 2f;
			hNEBHCMAOAE37.IIJMLJCIJFD().LOJEMAMKHFD = 60f;
			hNEBHCMAOAE37.IIJMLJCIJFD().ELDBGIKHAIO = 1f;
			hNEBHCMAOAE37.IIJMLJCIJFD().LNKFLFOGCCD = 0.6f;
			hNEBHCMAOAE37.IIJMLJCIJFD().FHJCBAOBGPG = 0.3f;
			hNEBHCMAOAE37.IIJMLJCIJFD().FBEBCNEPHJD = 10f;
			hNEBHCMAOAE37.IIJMLJCIJFD().PDAOIGGBLPH = 2f;
			hNEBHCMAOAE37.IIJMLJCIJFD().NLMHKBGDKLA = 0f;
			hNEBHCMAOAE37.IIJMLJCIJFD().JFLFAKNHKNP = 10f;
			hNEBHCMAOAE37.IIJMLJCIJFD().NEPGMKLCMFF = 2.5f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE37.INGLCFJBNOB(), hNEBHCMAOAE37);
			HNEBHCMAOAE hNEBHCMAOAE38 = new HNEBHCMAOAE();
			hNEBHCMAOAE38.FIGLEPBIEEJ(20001, "에이션트골렘", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Monster, HNEBHCMAOAE.HFIHMACFPMM.Melee, 0u, 0u, 1, 0, "AncientGolem");
			hNEBHCMAOAE38.IIJMLJCIJFD().LBJMNDBMNAE = 1800u;
			hNEBHCMAOAE38.IIJMLJCIJFD().EPKGCHPIHEL = 500u;
			hNEBHCMAOAE38.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE38.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE38.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE38.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE38.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE38.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE38.IIJMLJCIJFD().IIICODNIMNN = 2f;
			hNEBHCMAOAE38.IIJMLJCIJFD().LOJEMAMKHFD = 60f;
			hNEBHCMAOAE38.IIJMLJCIJFD().ELDBGIKHAIO = 1f;
			hNEBHCMAOAE38.IIJMLJCIJFD().LNKFLFOGCCD = 0.6f;
			hNEBHCMAOAE38.IIJMLJCIJFD().FHJCBAOBGPG = 0.3f;
			hNEBHCMAOAE38.IIJMLJCIJFD().FBEBCNEPHJD = 10f;
			hNEBHCMAOAE38.IIJMLJCIJFD().PDAOIGGBLPH = 10f;
			hNEBHCMAOAE38.IIJMLJCIJFD().NLMHKBGDKLA = 0f;
			hNEBHCMAOAE38.IIJMLJCIJFD().JFLFAKNHKNP = 2f;
			hNEBHCMAOAE38.IIJMLJCIJFD().NEPGMKLCMFF = 2.5f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE38.INGLCFJBNOB(), hNEBHCMAOAE38);
			HNEBHCMAOAE hNEBHCMAOAE39 = new HNEBHCMAOAE();
			hNEBHCMAOAE39.FIGLEPBIEEJ(20002, "드래곤", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Monster, HNEBHCMAOAE.HFIHMACFPMM.Melee, 0u, 0u, 1, 0, "Dragon");
			hNEBHCMAOAE39.IIJMLJCIJFD().LBJMNDBMNAE = 8940u;
			hNEBHCMAOAE39.IIJMLJCIJFD().EPKGCHPIHEL = 240u;
			hNEBHCMAOAE39.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE39.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE39.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE39.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE39.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE39.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE39.IIJMLJCIJFD().IIICODNIMNN = 3.5f;
			hNEBHCMAOAE39.IIJMLJCIJFD().LOJEMAMKHFD = 230f;
			hNEBHCMAOAE39.IIJMLJCIJFD().ELDBGIKHAIO = 0f;
			hNEBHCMAOAE39.IIJMLJCIJFD().LNKFLFOGCCD = 0.65f;
			hNEBHCMAOAE39.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE39.IIJMLJCIJFD().FBEBCNEPHJD = 50f;
			hNEBHCMAOAE39.IIJMLJCIJFD().PDAOIGGBLPH = 3.25f;
			hNEBHCMAOAE39.IIJMLJCIJFD().NLMHKBGDKLA = 30f;
			hNEBHCMAOAE39.IIJMLJCIJFD().JFLFAKNHKNP = 1.45f;
			hNEBHCMAOAE39.IIJMLJCIJFD().NEPGMKLCMFF = 3.3f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE39.INGLCFJBNOB(), hNEBHCMAOAE39);
			HNEBHCMAOAE hNEBHCMAOAE40 = new HNEBHCMAOAE();
			hNEBHCMAOAE40.FIGLEPBIEEJ(20003, "바론", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Monster, HNEBHCMAOAE.HFIHMACFPMM.Range, 0u, 0u, 1, 0, "Baron");
			hNEBHCMAOAE40.IIJMLJCIJFD().LBJMNDBMNAE = 11902u;
			hNEBHCMAOAE40.IIJMLJCIJFD().EPKGCHPIHEL = 0u;
			hNEBHCMAOAE40.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE40.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE40.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE40.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE40.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE40.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE40.IIJMLJCIJFD().IIICODNIMNN = 10f;
			hNEBHCMAOAE40.IIJMLJCIJFD().LOJEMAMKHFD = 300f;
			hNEBHCMAOAE40.IIJMLJCIJFD().ELDBGIKHAIO = 0f;
			hNEBHCMAOAE40.IIJMLJCIJFD().LNKFLFOGCCD = 0.75f;
			hNEBHCMAOAE40.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE40.IIJMLJCIJFD().FBEBCNEPHJD = 120f;
			hNEBHCMAOAE40.IIJMLJCIJFD().PDAOIGGBLPH = 3.25f;
			hNEBHCMAOAE40.IIJMLJCIJFD().NLMHKBGDKLA = 70f;
			hNEBHCMAOAE40.IIJMLJCIJFD().JFLFAKNHKNP = 1.45f;
			hNEBHCMAOAE40.IIJMLJCIJFD().NEPGMKLCMFF = 0f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE40.INGLCFJBNOB(), hNEBHCMAOAE40);
			HNEBHCMAOAE hNEBHCMAOAE41 = new HNEBHCMAOAE();
			hNEBHCMAOAE41.FIGLEPBIEEJ(20004, "고스트", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Monster, HNEBHCMAOAE.HFIHMACFPMM.Melee, 0u, 0u, 1, 0, "Ghast");
			hNEBHCMAOAE41.IIJMLJCIJFD().LBJMNDBMNAE = 420u;
			hNEBHCMAOAE41.IIJMLJCIJFD().EPKGCHPIHEL = 0u;
			hNEBHCMAOAE41.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE41.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE41.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE41.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE41.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE41.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE41.IIJMLJCIJFD().IIICODNIMNN = 1.3f;
			hNEBHCMAOAE41.IIJMLJCIJFD().LOJEMAMKHFD = 10f;
			hNEBHCMAOAE41.IIJMLJCIJFD().ELDBGIKHAIO = 0f;
			hNEBHCMAOAE41.IIJMLJCIJFD().LNKFLFOGCCD = 0.625f;
			hNEBHCMAOAE41.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE41.IIJMLJCIJFD().FBEBCNEPHJD = 6f;
			hNEBHCMAOAE41.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE41.IIJMLJCIJFD().NLMHKBGDKLA = 0f;
			hNEBHCMAOAE41.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE41.IIJMLJCIJFD().NEPGMKLCMFF = 4.43f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE41.INGLCFJBNOB(), hNEBHCMAOAE41);
			HNEBHCMAOAE hNEBHCMAOAE42 = new HNEBHCMAOAE();
			hNEBHCMAOAE42.FIGLEPBIEEJ(20005, "대형고스트", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Monster, HNEBHCMAOAE.HFIHMACFPMM.Melee, 0u, 0u, 1, 0, "GhastBig");
			hNEBHCMAOAE42.IIJMLJCIJFD().LBJMNDBMNAE = 800u;
			hNEBHCMAOAE42.IIJMLJCIJFD().EPKGCHPIHEL = 0u;
			hNEBHCMAOAE42.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE42.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE42.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE42.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE42.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE42.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE42.IIJMLJCIJFD().IIICODNIMNN = 1.5f;
			hNEBHCMAOAE42.IIJMLJCIJFD().LOJEMAMKHFD = 32f;
			hNEBHCMAOAE42.IIJMLJCIJFD().ELDBGIKHAIO = 0f;
			hNEBHCMAOAE42.IIJMLJCIJFD().LNKFLFOGCCD = 0.625f;
			hNEBHCMAOAE42.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE42.IIJMLJCIJFD().FBEBCNEPHJD = 9f;
			hNEBHCMAOAE42.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE42.IIJMLJCIJFD().NLMHKBGDKLA = 0f;
			hNEBHCMAOAE42.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE42.IIJMLJCIJFD().NEPGMKLCMFF = 4.43f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE42.INGLCFJBNOB(), hNEBHCMAOAE42);
			HNEBHCMAOAE hNEBHCMAOAE43 = new HNEBHCMAOAE();
			hNEBHCMAOAE43.FIGLEPBIEEJ(20006, "늑대", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Monster, HNEBHCMAOAE.HFIHMACFPMM.Melee, 0u, 0u, 1, 0, "Wolf");
			hNEBHCMAOAE43.IIJMLJCIJFD().LBJMNDBMNAE = 420u;
			hNEBHCMAOAE43.IIJMLJCIJFD().EPKGCHPIHEL = 0u;
			hNEBHCMAOAE43.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE43.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE43.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE43.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE43.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE43.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE43.IIJMLJCIJFD().IIICODNIMNN = 1.3f;
			hNEBHCMAOAE43.IIJMLJCIJFD().LOJEMAMKHFD = 16f;
			hNEBHCMAOAE43.IIJMLJCIJFD().ELDBGIKHAIO = 0f;
			hNEBHCMAOAE43.IIJMLJCIJFD().LNKFLFOGCCD = 0.625f;
			hNEBHCMAOAE43.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE43.IIJMLJCIJFD().FBEBCNEPHJD = 6f;
			hNEBHCMAOAE43.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE43.IIJMLJCIJFD().NLMHKBGDKLA = 0f;
			hNEBHCMAOAE43.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE43.IIJMLJCIJFD().NEPGMKLCMFF = 4.43f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE43.INGLCFJBNOB(), hNEBHCMAOAE43);
			HNEBHCMAOAE hNEBHCMAOAE44 = new HNEBHCMAOAE();
			hNEBHCMAOAE44.FIGLEPBIEEJ(20007, "대형늑대", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Monster, HNEBHCMAOAE.HFIHMACFPMM.Melee, 0u, 0u, 1, 0, "WolfBig");
			hNEBHCMAOAE44.IIJMLJCIJFD().LBJMNDBMNAE = 1000u;
			hNEBHCMAOAE44.IIJMLJCIJFD().EPKGCHPIHEL = 0u;
			hNEBHCMAOAE44.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE44.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE44.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE44.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE44.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE44.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE44.IIJMLJCIJFD().IIICODNIMNN = 1.5f;
			hNEBHCMAOAE44.IIJMLJCIJFD().LOJEMAMKHFD = 42f;
			hNEBHCMAOAE44.IIJMLJCIJFD().ELDBGIKHAIO = 0f;
			hNEBHCMAOAE44.IIJMLJCIJFD().LNKFLFOGCCD = 0.625f;
			hNEBHCMAOAE44.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE44.IIJMLJCIJFD().FBEBCNEPHJD = 9f;
			hNEBHCMAOAE44.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE44.IIJMLJCIJFD().NLMHKBGDKLA = 0f;
			hNEBHCMAOAE44.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE44.IIJMLJCIJFD().NEPGMKLCMFF = 4.43f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE44.INGLCFJBNOB(), hNEBHCMAOAE44);
			HNEBHCMAOAE hNEBHCMAOAE45 = new HNEBHCMAOAE();
			hNEBHCMAOAE45.FIGLEPBIEEJ(20008, "골렘", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Monster, HNEBHCMAOAE.HFIHMACFPMM.Melee, 0u, 0u, 1, 0, "Golem");
			hNEBHCMAOAE45.IIJMLJCIJFD().LBJMNDBMNAE = 1000u;
			hNEBHCMAOAE45.IIJMLJCIJFD().EPKGCHPIHEL = 0u;
			hNEBHCMAOAE45.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE45.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE45.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE45.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE45.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE45.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE45.IIJMLJCIJFD().IIICODNIMNN = 1.5f;
			hNEBHCMAOAE45.IIJMLJCIJFD().LOJEMAMKHFD = 35f;
			hNEBHCMAOAE45.IIJMLJCIJFD().ELDBGIKHAIO = 0f;
			hNEBHCMAOAE45.IIJMLJCIJFD().LNKFLFOGCCD = 0.613f;
			hNEBHCMAOAE45.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE45.IIJMLJCIJFD().FBEBCNEPHJD = 12f;
			hNEBHCMAOAE45.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE45.IIJMLJCIJFD().NLMHKBGDKLA = 0f;
			hNEBHCMAOAE45.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE45.IIJMLJCIJFD().NEPGMKLCMFF = 2.85f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE45.INGLCFJBNOB(), hNEBHCMAOAE45);
			HNEBHCMAOAE hNEBHCMAOAE46 = new HNEBHCMAOAE();
			hNEBHCMAOAE46.FIGLEPBIEEJ(30000, "1차타워", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Turret, HNEBHCMAOAE.HFIHMACFPMM.Range, 0u, 0u, 1, 0, "Turret");
			hNEBHCMAOAE46.IIJMLJCIJFD().LBJMNDBMNAE = 2000u;
			hNEBHCMAOAE46.IIJMLJCIJFD().EPKGCHPIHEL = 0u;
			hNEBHCMAOAE46.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE46.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE46.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE46.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE46.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE46.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE46.IIJMLJCIJFD().IIICODNIMNN = 6.5f;
			hNEBHCMAOAE46.IIJMLJCIJFD().LOJEMAMKHFD = 152f;
			hNEBHCMAOAE46.IIJMLJCIJFD().ELDBGIKHAIO = 10f;
			hNEBHCMAOAE46.IIJMLJCIJFD().LNKFLFOGCCD = 0.83f;
			hNEBHCMAOAE46.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE46.IIJMLJCIJFD().FBEBCNEPHJD = 100f;
			hNEBHCMAOAE46.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE46.IIJMLJCIJFD().NLMHKBGDKLA = 50f;
			hNEBHCMAOAE46.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE46.IIJMLJCIJFD().NEPGMKLCMFF = 0f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE46.INGLCFJBNOB(), hNEBHCMAOAE46);
			HNEBHCMAOAE hNEBHCMAOAE47 = new HNEBHCMAOAE();
			hNEBHCMAOAE47.FIGLEPBIEEJ(30001, "2차타워", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Turret, HNEBHCMAOAE.HFIHMACFPMM.Range, 0u, 0u, 1, 0, "Turret");
			hNEBHCMAOAE47.IIJMLJCIJFD().LBJMNDBMNAE = 2000u;
			hNEBHCMAOAE47.IIJMLJCIJFD().EPKGCHPIHEL = 0u;
			hNEBHCMAOAE47.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE47.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE47.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE47.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE47.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE47.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE47.IIJMLJCIJFD().IIICODNIMNN = 6.5f;
			hNEBHCMAOAE47.IIJMLJCIJFD().LOJEMAMKHFD = 170f;
			hNEBHCMAOAE47.IIJMLJCIJFD().ELDBGIKHAIO = 10f;
			hNEBHCMAOAE47.IIJMLJCIJFD().LNKFLFOGCCD = 0.83f;
			hNEBHCMAOAE47.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE47.IIJMLJCIJFD().FBEBCNEPHJD = 100f;
			hNEBHCMAOAE47.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE47.IIJMLJCIJFD().NLMHKBGDKLA = 50f;
			hNEBHCMAOAE47.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE47.IIJMLJCIJFD().NEPGMKLCMFF = 0f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE47.INGLCFJBNOB(), hNEBHCMAOAE47);
			HNEBHCMAOAE hNEBHCMAOAE48 = new HNEBHCMAOAE();
			hNEBHCMAOAE48.FIGLEPBIEEJ(30002, "3차타워", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Turret, HNEBHCMAOAE.HFIHMACFPMM.Range, 0u, 0u, 1, 0, "Turret");
			hNEBHCMAOAE48.IIJMLJCIJFD().LBJMNDBMNAE = 1800u;
			hNEBHCMAOAE48.IIJMLJCIJFD().EPKGCHPIHEL = 0u;
			hNEBHCMAOAE48.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE48.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE48.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE48.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE48.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE48.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE48.IIJMLJCIJFD().IIICODNIMNN = 6.5f;
			hNEBHCMAOAE48.IIJMLJCIJFD().LOJEMAMKHFD = 170f;
			hNEBHCMAOAE48.IIJMLJCIJFD().ELDBGIKHAIO = 10f;
			hNEBHCMAOAE48.IIJMLJCIJFD().LNKFLFOGCCD = 0.83f;
			hNEBHCMAOAE48.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE48.IIJMLJCIJFD().FBEBCNEPHJD = 100f;
			hNEBHCMAOAE48.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE48.IIJMLJCIJFD().NLMHKBGDKLA = 50f;
			hNEBHCMAOAE48.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE48.IIJMLJCIJFD().NEPGMKLCMFF = 0f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE48.INGLCFJBNOB(), hNEBHCMAOAE48);
			HNEBHCMAOAE hNEBHCMAOAE49 = new HNEBHCMAOAE();
			hNEBHCMAOAE49.FIGLEPBIEEJ(31000, "넥서스", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Turret, HNEBHCMAOAE.HFIHMACFPMM.Range, 0u, 0u, 1, 0, "Nexus");
			hNEBHCMAOAE49.IIJMLJCIJFD().LBJMNDBMNAE = 2200u;
			hNEBHCMAOAE49.IIJMLJCIJFD().EPKGCHPIHEL = 0u;
			hNEBHCMAOAE49.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE49.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE49.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE49.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE49.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE49.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE49.IIJMLJCIJFD().IIICODNIMNN = 6.5f;
			hNEBHCMAOAE49.IIJMLJCIJFD().LOJEMAMKHFD = 0f;
			hNEBHCMAOAE49.IIJMLJCIJFD().ELDBGIKHAIO = 0f;
			hNEBHCMAOAE49.IIJMLJCIJFD().LNKFLFOGCCD = 2f;
			hNEBHCMAOAE49.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE49.IIJMLJCIJFD().FBEBCNEPHJD = 100f;
			hNEBHCMAOAE49.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE49.IIJMLJCIJFD().NLMHKBGDKLA = 50f;
			hNEBHCMAOAE49.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE49.IIJMLJCIJFD().NEPGMKLCMFF = 0f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE49.INGLCFJBNOB(), hNEBHCMAOAE49);
			HNEBHCMAOAE hNEBHCMAOAE50 = new HNEBHCMAOAE();
			hNEBHCMAOAE50.FIGLEPBIEEJ(40000, "알리스타", "설명", HNEBHCMAOAE.OPKPLDIMOCL.Hero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 11000u, 0u, 0, 0, "Alistar");
			hNEBHCMAOAE50.IIJMLJCIJFD().LBJMNDBMNAE = 3000u;
			hNEBHCMAOAE50.IIJMLJCIJFD().EPKGCHPIHEL = 500u;
			hNEBHCMAOAE50.IIJMLJCIJFD().JKOEPLLJDKM = 8.675f;
			hNEBHCMAOAE50.IIJMLJCIJFD().BKOBAIPJAHP = 0.85f;
			hNEBHCMAOAE50.IIJMLJCIJFD().OCOOIOGCOEE = 278u;
			hNEBHCMAOAE50.IIJMLJCIJFD().GHCBBJBDNPH = 38u;
			hNEBHCMAOAE50.IIJMLJCIJFD().MGLIOBDEJLF = 20f;
			hNEBHCMAOAE50.IIJMLJCIJFD().GFGOPIKFOAN = 3f;
			hNEBHCMAOAE50.IIJMLJCIJFD().IIICODNIMNN = 2.2f;
			hNEBHCMAOAE50.IIJMLJCIJFD().LOJEMAMKHFD = 61.112f;
			hNEBHCMAOAE50.IIJMLJCIJFD().ELDBGIKHAIO = 3.62f;
			hNEBHCMAOAE50.IIJMLJCIJFD().LNKFLFOGCCD = 0.625f;
			hNEBHCMAOAE50.IIJMLJCIJFD().FHJCBAOBGPG = 1.125f;
			hNEBHCMAOAE50.IIJMLJCIJFD().FBEBCNEPHJD = 30.38f;
			hNEBHCMAOAE50.IIJMLJCIJFD().PDAOIGGBLPH = 3.5f;
			hNEBHCMAOAE50.IIJMLJCIJFD().NLMHKBGDKLA = 32.1f;
			hNEBHCMAOAE50.IIJMLJCIJFD().JFLFAKNHKNP = 1.25f;
			hNEBHCMAOAE50.IIJMLJCIJFD().NEPGMKLCMFF = 3.3f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE50.INGLCFJBNOB(), hNEBHCMAOAE50);
			HNEBHCMAOAE hNEBHCMAOAE51 = new HNEBHCMAOAE();
			hNEBHCMAOAE51.FIGLEPBIEEJ(50000, "티모버섯", "설명", HNEBHCMAOAE.OPKPLDIMOCL.SubHero, HNEBHCMAOAE.HFIHMACFPMM.Melee, 0u, 0u, 1, 0, "Particle/Teemo/skill3_trap");
			hNEBHCMAOAE51.IIJMLJCIJFD().LBJMNDBMNAE = 10u;
			hNEBHCMAOAE51.IIJMLJCIJFD().EPKGCHPIHEL = 0u;
			hNEBHCMAOAE51.IIJMLJCIJFD().JKOEPLLJDKM = 0f;
			hNEBHCMAOAE51.IIJMLJCIJFD().BKOBAIPJAHP = 0f;
			hNEBHCMAOAE51.IIJMLJCIJFD().OCOOIOGCOEE = 0u;
			hNEBHCMAOAE51.IIJMLJCIJFD().GHCBBJBDNPH = 0u;
			hNEBHCMAOAE51.IIJMLJCIJFD().MGLIOBDEJLF = 0f;
			hNEBHCMAOAE51.IIJMLJCIJFD().GFGOPIKFOAN = 0f;
			hNEBHCMAOAE51.IIJMLJCIJFD().IIICODNIMNN = 2f;
			hNEBHCMAOAE51.IIJMLJCIJFD().LOJEMAMKHFD = 0f;
			hNEBHCMAOAE51.IIJMLJCIJFD().ELDBGIKHAIO = 0f;
			hNEBHCMAOAE51.IIJMLJCIJFD().LNKFLFOGCCD = 0f;
			hNEBHCMAOAE51.IIJMLJCIJFD().FHJCBAOBGPG = 0f;
			hNEBHCMAOAE51.IIJMLJCIJFD().FBEBCNEPHJD = 0f;
			hNEBHCMAOAE51.IIJMLJCIJFD().PDAOIGGBLPH = 0f;
			hNEBHCMAOAE51.IIJMLJCIJFD().NLMHKBGDKLA = 0f;
			hNEBHCMAOAE51.IIJMLJCIJFD().JFLFAKNHKNP = 0f;
			hNEBHCMAOAE51.IIJMLJCIJFD().NEPGMKLCMFF = 0f;
			EPEJNKKPCCG().Add(hNEBHCMAOAE51.INGLCFJBNOB(), hNEBHCMAOAE51);
			ACIBDAANJLI(GetHashCode());
		}

		public bool AMBOPDLLCCP()
		{
			if (LJKLAIGNIKB() == GetHashCode())
			{
				return true;
			}
			return false;
		}

		public void JCOLMPJMMEB(PJEMPFEIOAK EFDLFNPAKGO)
		{
			ushort num = EFDLFNPAKGO.AJPFAAFLHEB();
			for (short num2 = 0; num2 < num; num2++)
			{
				ushort key = EFDLFNPAKGO.AJPFAAFLHEB();
				if (EPEJNKKPCCG().ContainsKey(key))
				{
					EPEJNKKPCCG()[key].JCOLMPJMMEB(EFDLFNPAKGO);
				}
				else
				{
					HNEBHCMAOAE hNEBHCMAOAE = new HNEBHCMAOAE();
					hNEBHCMAOAE.JCOLMPJMMEB(EFDLFNPAKGO);
				}
			}
			ACIBDAANJLI(GetHashCode());
		}

		public HNEBHCMAOAE DKFCIKNPJJJ(ushort OHGOBGOIECH)
		{
			HNEBHCMAOAE value;
			if (!HDCMNNCPGBH().TryGetValue(OHGOBGOIECH, out value))
			{
				return null;
			}
			return value;
		}

		protected void ACIBDAANJLI(int ICENKPDOHBK)
		{
			LFMCAMFIHEJ = ICENKPDOHBK;
		}

		public virtual int ENJBCKOPLJI()
		{
			int num = 1;
			foreach (KeyValuePair<ushort, HNEBHCMAOAE> item in EPEJNKKPCCG())
			{
				num ^= item.Value.GetHashCode();
			}
			return num;
		}

		[SpecialName]
		protected void NOMMGMBFEDI(Dictionary<ushort, HNEBHCMAOAE> ICENKPDOHBK)
		{
			ENNEEJMCHGI = ICENKPDOHBK;
		}

		public virtual int APEKPGLOLNE()
		{
			int num = 0;
			foreach (KeyValuePair<ushort, HNEBHCMAOAE> item in HDCMNNCPGBH())
			{
				num ^= item.Value.GetHashCode();
			}
			return num;
		}

		public virtual int PLNDNFDOBAA()
		{
			int num = 1;
			foreach (KeyValuePair<ushort, HNEBHCMAOAE> item in HDCMNNCPGBH())
			{
				num ^= item.Value.GetHashCode();
			}
			return num;
		}

		public bool OAHPEDHGMOP()
		{
			if (LJKLAIGNIKB() == ENJBCKOPLJI())
			{
				return false;
			}
			return true;
		}

		[SpecialName]
		protected void AOLAGOLDFGN(int ICENKPDOHBK)
		{
			LFMCAMFIHEJ = ICENKPDOHBK;
		}

		public void CFGEKKHOKKE(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC((ushort)EPEJNKKPCCG().Count);
			foreach (KeyValuePair<ushort, HNEBHCMAOAE> item in EPEJNKKPCCG())
			{
				item.Value.CFGEKKHOKKE(EFDLFNPAKGO);
			}
		}

		public void HOCIBNCFBLL(PJEMPFEIOAK EFDLFNPAKGO)
		{
			ushort num = EFDLFNPAKGO.AJPFAAFLHEB();
			for (short num2 = 1; num2 < num; num2 += 0)
			{
				ushort key = EFDLFNPAKGO.AJPFAAFLHEB();
				if (EPEJNKKPCCG().ContainsKey(key))
				{
					HDCMNNCPGBH()[key].JCOLMPJMMEB(EFDLFNPAKGO);
				}
				else
				{
					HNEBHCMAOAE hNEBHCMAOAE = new HNEBHCMAOAE();
					hNEBHCMAOAE.JCOLMPJMMEB(EFDLFNPAKGO);
				}
			}
			ACIBDAANJLI(FOJIMPLKIAI());
		}

		public override int GetHashCode()
		{
			int num = 0;
			foreach (KeyValuePair<ushort, HNEBHCMAOAE> item in EPEJNKKPCCG())
			{
				num ^= item.Value.GetHashCode();
			}
			return num;
		}

		public Dictionary<ushort, HNEBHCMAOAE> EPEJNKKPCCG()
		{
			return ENNEEJMCHGI;
		}

		public bool GOKPCMLKBHN(ushort JLPIFIJBMCD, byte MKILOIPGILH)
		{
			if (JLPIFIJBMCD == 12 && MKILOIPGILH == 3)
			{
				return true;
			}
			if (JLPIFIJBMCD == 18 && MKILOIPGILH == 3)
			{
				return true;
			}
			return false;
		}

		public EPOEICHAAKP()
		{
			JOEHMANNDJK = new object();
			HDKJGMIAOKN(new Dictionary<ushort, HNEBHCMAOAE>());
		}

		public bool MNGHKKJLBIN(ushort JLPIFIJBMCD, byte MKILOIPGILH)
		{
			if (JLPIFIJBMCD == 7 && MKILOIPGILH == 1)
			{
				return false;
			}
			if (JLPIFIJBMCD == 51 && MKILOIPGILH == 7)
			{
				return false;
			}
			return false;
		}

		public void CKBCOALJMJB(PJEMPFEIOAK EFDLFNPAKGO)
		{
			ushort num = EFDLFNPAKGO.AJPFAAFLHEB();
			for (short num2 = 1; num2 < num; num2 += 0)
			{
				ushort key = EFDLFNPAKGO.AJPFAAFLHEB();
				if (EPEJNKKPCCG().ContainsKey(key))
				{
					EPEJNKKPCCG()[key].JCOLMPJMMEB(EFDLFNPAKGO);
				}
				else
				{
					HNEBHCMAOAE hNEBHCMAOAE = new HNEBHCMAOAE();
					hNEBHCMAOAE.JCOLMPJMMEB(EFDLFNPAKGO);
				}
			}
			ACIBDAANJLI(APEKPGLOLNE());
		}

		public virtual int FOJIMPLKIAI()
		{
			int num = 1;
			foreach (KeyValuePair<ushort, HNEBHCMAOAE> item in HDCMNNCPGBH())
			{
				num ^= item.Value.GetHashCode();
			}
			return num;
		}

		[SpecialName]
		public Dictionary<ushort, HNEBHCMAOAE> HDCMNNCPGBH()
		{
			return ENNEEJMCHGI;
		}
	}
}
