using System;
using EveEngine;

namespace GameServer
{
	public class FOANFOMPBAH : EOPOBHFNFPA
	{
		public uint OHGOBGOIECH;

		public string ICCNKGPICEA;

		public string FEKLLJBGOEF;

		public string GALNKIHDMNH;

		public DateTime MBKMHBAGMHI;

		public string ANCDOGMDMKC;

		public bool HNHFOHPKCIB;

		public bool GGMNMEGDMOD;

		public bool ALMLNIDCFEK;

		public DateTime LGJILKFNKBG;

		public DateTime KBOBPMGJGIG;

		public DateTime NIGLIJJDMFO;

		public DateTime PCCLKBLODMI;

		public FOANFOMPBAH()
		{
			OHGOBGOIECH = 0u;
			ICCNKGPICEA = string.Empty;
			FEKLLJBGOEF = string.Empty;
			GALNKIHDMNH = string.Empty;
			MBKMHBAGMHI = DateTime.Now;
			ANCDOGMDMKC = string.Empty;
			HNHFOHPKCIB = false;
			GGMNMEGDMOD = false;
			ALMLNIDCFEK = false;
			LGJILKFNKBG = new DateTime(1990, 1, 1);
			KBOBPMGJGIG = new DateTime(1990, 1, 1);
			NIGLIJJDMFO = new DateTime(1990, 1, 1);
			PCCLKBLODMI = new DateTime(1990, 1, 1);
		}

		public virtual void LFBNEHNMHLL(PJEMPFEIOAK EFDLFNPAKGO)
		{
			OHGOBGOIECH = EFDLFNPAKGO.BMKOKHGAHEC();
			ICCNKGPICEA = EFDLFNPAKGO.AFPCLLNMGJP();
			FEKLLJBGOEF = EFDLFNPAKGO.AFPCLLNMGJP();
			GALNKIHDMNH = EFDLFNPAKGO.AFPCLLNMGJP();
			MBKMHBAGMHI = EFDLFNPAKGO.NOIDCBCMCMK();
			ANCDOGMDMKC = EFDLFNPAKGO.AFPCLLNMGJP();
			HNHFOHPKCIB = EFDLFNPAKGO.JCGKFEPEJPO();
			GGMNMEGDMOD = EFDLFNPAKGO.JCGKFEPEJPO();
			ALMLNIDCFEK = EFDLFNPAKGO.JCGKFEPEJPO();
			LGJILKFNKBG = EFDLFNPAKGO.NOIDCBCMCMK();
			KBOBPMGJGIG = EFDLFNPAKGO.NOIDCBCMCMK();
			NIGLIJJDMFO = EFDLFNPAKGO.NOIDCBCMCMK();
			PCCLKBLODMI = EFDLFNPAKGO.NOIDCBCMCMK();
		}

		public virtual void OBLFBODBHHK(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.BHAFGILIOCN(OHGOBGOIECH);
			EFDLFNPAKGO.GBMJNFOEACC(ICCNKGPICEA);
			EFDLFNPAKGO.GBMJNFOEACC(FEKLLJBGOEF);
			EFDLFNPAKGO.GBMJNFOEACC(GALNKIHDMNH);
			EFDLFNPAKGO.GBMJNFOEACC(MBKMHBAGMHI);
			EFDLFNPAKGO.GBMJNFOEACC(ANCDOGMDMKC);
			EFDLFNPAKGO.KHEGDBFKNMB(HNHFOHPKCIB);
			EFDLFNPAKGO.KHEGDBFKNMB(GGMNMEGDMOD);
			EFDLFNPAKGO.KHEGDBFKNMB(ALMLNIDCFEK);
			EFDLFNPAKGO.GBMJNFOEACC(LGJILKFNKBG);
			EFDLFNPAKGO.GBMJNFOEACC(KBOBPMGJGIG);
			EFDLFNPAKGO.GBMJNFOEACC(NIGLIJJDMFO);
			EFDLFNPAKGO.GBMJNFOEACC(PCCLKBLODMI);
		}

		public virtual void JHDBNOHACNB(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(OHGOBGOIECH);
			EFDLFNPAKGO.GBMJNFOEACC(ICCNKGPICEA);
			EFDLFNPAKGO.GBMJNFOEACC(FEKLLJBGOEF);
			EFDLFNPAKGO.GBMJNFOEACC(GALNKIHDMNH);
			EFDLFNPAKGO.GBMJNFOEACC(MBKMHBAGMHI);
			EFDLFNPAKGO.GBMJNFOEACC(ANCDOGMDMKC);
			EFDLFNPAKGO.GBMJNFOEACC(HNHFOHPKCIB);
			EFDLFNPAKGO.KHEGDBFKNMB(GGMNMEGDMOD);
			EFDLFNPAKGO.KHEGDBFKNMB(ALMLNIDCFEK);
			EFDLFNPAKGO.GBMJNFOEACC(LGJILKFNKBG);
			EFDLFNPAKGO.GBMJNFOEACC(KBOBPMGJGIG);
			EFDLFNPAKGO.GBMJNFOEACC(NIGLIJJDMFO);
			EFDLFNPAKGO.GBMJNFOEACC(PCCLKBLODMI);
		}

		public virtual void POIGICPGPAK(PJEMPFEIOAK EFDLFNPAKGO)
		{
			OHGOBGOIECH = EFDLFNPAKGO.BMKOKHGAHEC();
			ICCNKGPICEA = EFDLFNPAKGO.AFPCLLNMGJP();
			FEKLLJBGOEF = EFDLFNPAKGO.AFPCLLNMGJP();
			GALNKIHDMNH = EFDLFNPAKGO.AFPCLLNMGJP();
			MBKMHBAGMHI = EFDLFNPAKGO.NOIDCBCMCMK();
			ANCDOGMDMKC = EFDLFNPAKGO.AFPCLLNMGJP();
			HNHFOHPKCIB = EFDLFNPAKGO.JCGKFEPEJPO();
			GGMNMEGDMOD = EFDLFNPAKGO.JCGKFEPEJPO();
			ALMLNIDCFEK = EFDLFNPAKGO.JCGKFEPEJPO();
			LGJILKFNKBG = EFDLFNPAKGO.NOIDCBCMCMK();
			KBOBPMGJGIG = EFDLFNPAKGO.NOIDCBCMCMK();
			NIGLIJJDMFO = EFDLFNPAKGO.NOIDCBCMCMK();
			PCCLKBLODMI = EFDLFNPAKGO.NOIDCBCMCMK();
		}

		public virtual void CPPAAILEDJO(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.BHAFGILIOCN(OHGOBGOIECH);
			EFDLFNPAKGO.GBMJNFOEACC(ICCNKGPICEA);
			EFDLFNPAKGO.GBMJNFOEACC(FEKLLJBGOEF);
			EFDLFNPAKGO.GBMJNFOEACC(GALNKIHDMNH);
			EFDLFNPAKGO.GBMJNFOEACC(MBKMHBAGMHI);
			EFDLFNPAKGO.GBMJNFOEACC(ANCDOGMDMKC);
			EFDLFNPAKGO.GBMJNFOEACC(HNHFOHPKCIB);
			EFDLFNPAKGO.GBMJNFOEACC(GGMNMEGDMOD);
			EFDLFNPAKGO.KHEGDBFKNMB(ALMLNIDCFEK);
			EFDLFNPAKGO.GBMJNFOEACC(LGJILKFNKBG);
			EFDLFNPAKGO.GBMJNFOEACC(KBOBPMGJGIG);
			EFDLFNPAKGO.GBMJNFOEACC(NIGLIJJDMFO);
			EFDLFNPAKGO.GBMJNFOEACC(PCCLKBLODMI);
		}

		public virtual void JCKGMOAEJLO(PJEMPFEIOAK EFDLFNPAKGO)
		{
			OHGOBGOIECH = EFDLFNPAKGO.BMKOKHGAHEC();
			ICCNKGPICEA = EFDLFNPAKGO.AFPCLLNMGJP();
			FEKLLJBGOEF = EFDLFNPAKGO.AFPCLLNMGJP();
			GALNKIHDMNH = EFDLFNPAKGO.AFPCLLNMGJP();
			MBKMHBAGMHI = EFDLFNPAKGO.NOIDCBCMCMK();
			ANCDOGMDMKC = EFDLFNPAKGO.AFPCLLNMGJP();
			HNHFOHPKCIB = EFDLFNPAKGO.JCGKFEPEJPO();
			GGMNMEGDMOD = EFDLFNPAKGO.JCGKFEPEJPO();
			ALMLNIDCFEK = EFDLFNPAKGO.JCGKFEPEJPO();
			LGJILKFNKBG = EFDLFNPAKGO.NOIDCBCMCMK();
			KBOBPMGJGIG = EFDLFNPAKGO.NOIDCBCMCMK();
			NIGLIJJDMFO = EFDLFNPAKGO.NOIDCBCMCMK();
			PCCLKBLODMI = EFDLFNPAKGO.NOIDCBCMCMK();
		}

		public virtual void LHCEBJLJAFB(PJEMPFEIOAK EFDLFNPAKGO)
		{
			OHGOBGOIECH = EFDLFNPAKGO.BMKOKHGAHEC();
			ICCNKGPICEA = EFDLFNPAKGO.AFPCLLNMGJP();
			FEKLLJBGOEF = EFDLFNPAKGO.AFPCLLNMGJP();
			GALNKIHDMNH = EFDLFNPAKGO.AFPCLLNMGJP();
			MBKMHBAGMHI = EFDLFNPAKGO.NOIDCBCMCMK();
			ANCDOGMDMKC = EFDLFNPAKGO.AFPCLLNMGJP();
			HNHFOHPKCIB = EFDLFNPAKGO.JCGKFEPEJPO();
			GGMNMEGDMOD = EFDLFNPAKGO.JCGKFEPEJPO();
			ALMLNIDCFEK = EFDLFNPAKGO.JCGKFEPEJPO();
			LGJILKFNKBG = EFDLFNPAKGO.NOIDCBCMCMK();
			KBOBPMGJGIG = EFDLFNPAKGO.NOIDCBCMCMK();
			NIGLIJJDMFO = EFDLFNPAKGO.NOIDCBCMCMK();
			PCCLKBLODMI = EFDLFNPAKGO.NOIDCBCMCMK();
		}

		public virtual void FKCEPEBGIPO(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(OHGOBGOIECH);
			EFDLFNPAKGO.GBMJNFOEACC(ICCNKGPICEA);
			EFDLFNPAKGO.GBMJNFOEACC(FEKLLJBGOEF);
			EFDLFNPAKGO.GBMJNFOEACC(GALNKIHDMNH);
			EFDLFNPAKGO.GBMJNFOEACC(MBKMHBAGMHI);
			EFDLFNPAKGO.GBMJNFOEACC(ANCDOGMDMKC);
			EFDLFNPAKGO.GBMJNFOEACC(HNHFOHPKCIB);
			EFDLFNPAKGO.KHEGDBFKNMB(GGMNMEGDMOD);
			EFDLFNPAKGO.GBMJNFOEACC(ALMLNIDCFEK);
			EFDLFNPAKGO.GBMJNFOEACC(LGJILKFNKBG);
			EFDLFNPAKGO.GBMJNFOEACC(KBOBPMGJGIG);
			EFDLFNPAKGO.GBMJNFOEACC(NIGLIJJDMFO);
			EFDLFNPAKGO.GBMJNFOEACC(PCCLKBLODMI);
		}

		public virtual void JCOLMPJMMEB(PJEMPFEIOAK EFDLFNPAKGO)
		{
			OHGOBGOIECH = EFDLFNPAKGO.BMKOKHGAHEC();
			ICCNKGPICEA = EFDLFNPAKGO.AFPCLLNMGJP();
			FEKLLJBGOEF = EFDLFNPAKGO.AFPCLLNMGJP();
			GALNKIHDMNH = EFDLFNPAKGO.AFPCLLNMGJP();
			MBKMHBAGMHI = EFDLFNPAKGO.NOIDCBCMCMK();
			ANCDOGMDMKC = EFDLFNPAKGO.AFPCLLNMGJP();
			HNHFOHPKCIB = EFDLFNPAKGO.JCGKFEPEJPO();
			GGMNMEGDMOD = EFDLFNPAKGO.JCGKFEPEJPO();
			ALMLNIDCFEK = EFDLFNPAKGO.JCGKFEPEJPO();
			LGJILKFNKBG = EFDLFNPAKGO.NOIDCBCMCMK();
			KBOBPMGJGIG = EFDLFNPAKGO.NOIDCBCMCMK();
			NIGLIJJDMFO = EFDLFNPAKGO.NOIDCBCMCMK();
			PCCLKBLODMI = EFDLFNPAKGO.NOIDCBCMCMK();
		}

		public virtual void CFGEKKHOKKE(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(OHGOBGOIECH);
			EFDLFNPAKGO.GBMJNFOEACC(ICCNKGPICEA);
			EFDLFNPAKGO.GBMJNFOEACC(FEKLLJBGOEF);
			EFDLFNPAKGO.GBMJNFOEACC(GALNKIHDMNH);
			EFDLFNPAKGO.GBMJNFOEACC(MBKMHBAGMHI);
			EFDLFNPAKGO.GBMJNFOEACC(ANCDOGMDMKC);
			EFDLFNPAKGO.GBMJNFOEACC(HNHFOHPKCIB);
			EFDLFNPAKGO.GBMJNFOEACC(GGMNMEGDMOD);
			EFDLFNPAKGO.GBMJNFOEACC(ALMLNIDCFEK);
			EFDLFNPAKGO.GBMJNFOEACC(LGJILKFNKBG);
			EFDLFNPAKGO.GBMJNFOEACC(KBOBPMGJGIG);
			EFDLFNPAKGO.GBMJNFOEACC(NIGLIJJDMFO);
			EFDLFNPAKGO.GBMJNFOEACC(PCCLKBLODMI);
		}

		public virtual void GPBOIHMMDDD(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(OHGOBGOIECH);
			EFDLFNPAKGO.GBMJNFOEACC(ICCNKGPICEA);
			EFDLFNPAKGO.GBMJNFOEACC(FEKLLJBGOEF);
			EFDLFNPAKGO.GBMJNFOEACC(GALNKIHDMNH);
			EFDLFNPAKGO.GBMJNFOEACC(MBKMHBAGMHI);
			EFDLFNPAKGO.GBMJNFOEACC(ANCDOGMDMKC);
			EFDLFNPAKGO.KHEGDBFKNMB(HNHFOHPKCIB);
			EFDLFNPAKGO.KHEGDBFKNMB(GGMNMEGDMOD);
			EFDLFNPAKGO.GBMJNFOEACC(ALMLNIDCFEK);
			EFDLFNPAKGO.GBMJNFOEACC(LGJILKFNKBG);
			EFDLFNPAKGO.GBMJNFOEACC(KBOBPMGJGIG);
			EFDLFNPAKGO.GBMJNFOEACC(NIGLIJJDMFO);
			EFDLFNPAKGO.GBMJNFOEACC(PCCLKBLODMI);
		}

		public virtual void KIABMKGIBEP(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.BHAFGILIOCN(OHGOBGOIECH);
			EFDLFNPAKGO.GBMJNFOEACC(ICCNKGPICEA);
			EFDLFNPAKGO.GBMJNFOEACC(FEKLLJBGOEF);
			EFDLFNPAKGO.GBMJNFOEACC(GALNKIHDMNH);
			EFDLFNPAKGO.GBMJNFOEACC(MBKMHBAGMHI);
			EFDLFNPAKGO.GBMJNFOEACC(ANCDOGMDMKC);
			EFDLFNPAKGO.GBMJNFOEACC(HNHFOHPKCIB);
			EFDLFNPAKGO.KHEGDBFKNMB(GGMNMEGDMOD);
			EFDLFNPAKGO.KHEGDBFKNMB(ALMLNIDCFEK);
			EFDLFNPAKGO.GBMJNFOEACC(LGJILKFNKBG);
			EFDLFNPAKGO.GBMJNFOEACC(KBOBPMGJGIG);
			EFDLFNPAKGO.GBMJNFOEACC(NIGLIJJDMFO);
			EFDLFNPAKGO.GBMJNFOEACC(PCCLKBLODMI);
		}

		public virtual void MHBMBMMBCPK(PJEMPFEIOAK EFDLFNPAKGO)
		{
			OHGOBGOIECH = EFDLFNPAKGO.BMKOKHGAHEC();
			ICCNKGPICEA = EFDLFNPAKGO.AFPCLLNMGJP();
			FEKLLJBGOEF = EFDLFNPAKGO.AFPCLLNMGJP();
			GALNKIHDMNH = EFDLFNPAKGO.AFPCLLNMGJP();
			MBKMHBAGMHI = EFDLFNPAKGO.NOIDCBCMCMK();
			ANCDOGMDMKC = EFDLFNPAKGO.AFPCLLNMGJP();
			HNHFOHPKCIB = EFDLFNPAKGO.JCGKFEPEJPO();
			GGMNMEGDMOD = EFDLFNPAKGO.JCGKFEPEJPO();
			ALMLNIDCFEK = EFDLFNPAKGO.JCGKFEPEJPO();
			LGJILKFNKBG = EFDLFNPAKGO.NOIDCBCMCMK();
			KBOBPMGJGIG = EFDLFNPAKGO.NOIDCBCMCMK();
			NIGLIJJDMFO = EFDLFNPAKGO.NOIDCBCMCMK();
			PCCLKBLODMI = EFDLFNPAKGO.NOIDCBCMCMK();
		}

		public virtual void HOCIBNCFBLL(PJEMPFEIOAK EFDLFNPAKGO)
		{
			OHGOBGOIECH = EFDLFNPAKGO.BMKOKHGAHEC();
			ICCNKGPICEA = EFDLFNPAKGO.AFPCLLNMGJP();
			FEKLLJBGOEF = EFDLFNPAKGO.AFPCLLNMGJP();
			GALNKIHDMNH = EFDLFNPAKGO.AFPCLLNMGJP();
			MBKMHBAGMHI = EFDLFNPAKGO.NOIDCBCMCMK();
			ANCDOGMDMKC = EFDLFNPAKGO.AFPCLLNMGJP();
			HNHFOHPKCIB = EFDLFNPAKGO.JCGKFEPEJPO();
			GGMNMEGDMOD = EFDLFNPAKGO.JCGKFEPEJPO();
			ALMLNIDCFEK = EFDLFNPAKGO.JCGKFEPEJPO();
			LGJILKFNKBG = EFDLFNPAKGO.NOIDCBCMCMK();
			KBOBPMGJGIG = EFDLFNPAKGO.NOIDCBCMCMK();
			NIGLIJJDMFO = EFDLFNPAKGO.NOIDCBCMCMK();
			PCCLKBLODMI = EFDLFNPAKGO.NOIDCBCMCMK();
		}

		public virtual void AGEPBABDMDL(PJEMPFEIOAK EFDLFNPAKGO)
		{
			OHGOBGOIECH = EFDLFNPAKGO.BMKOKHGAHEC();
			ICCNKGPICEA = EFDLFNPAKGO.AFPCLLNMGJP();
			FEKLLJBGOEF = EFDLFNPAKGO.AFPCLLNMGJP();
			GALNKIHDMNH = EFDLFNPAKGO.AFPCLLNMGJP();
			MBKMHBAGMHI = EFDLFNPAKGO.NOIDCBCMCMK();
			ANCDOGMDMKC = EFDLFNPAKGO.AFPCLLNMGJP();
			HNHFOHPKCIB = EFDLFNPAKGO.JCGKFEPEJPO();
			GGMNMEGDMOD = EFDLFNPAKGO.JCGKFEPEJPO();
			ALMLNIDCFEK = EFDLFNPAKGO.JCGKFEPEJPO();
			LGJILKFNKBG = EFDLFNPAKGO.NOIDCBCMCMK();
			KBOBPMGJGIG = EFDLFNPAKGO.NOIDCBCMCMK();
			NIGLIJJDMFO = EFDLFNPAKGO.NOIDCBCMCMK();
			PCCLKBLODMI = EFDLFNPAKGO.NOIDCBCMCMK();
		}

		public virtual void MEKNGDKEKKO(PJEMPFEIOAK EFDLFNPAKGO)
		{
			OHGOBGOIECH = EFDLFNPAKGO.BMKOKHGAHEC();
			ICCNKGPICEA = EFDLFNPAKGO.AFPCLLNMGJP();
			FEKLLJBGOEF = EFDLFNPAKGO.AFPCLLNMGJP();
			GALNKIHDMNH = EFDLFNPAKGO.AFPCLLNMGJP();
			MBKMHBAGMHI = EFDLFNPAKGO.NOIDCBCMCMK();
			ANCDOGMDMKC = EFDLFNPAKGO.AFPCLLNMGJP();
			HNHFOHPKCIB = EFDLFNPAKGO.JCGKFEPEJPO();
			GGMNMEGDMOD = EFDLFNPAKGO.JCGKFEPEJPO();
			ALMLNIDCFEK = EFDLFNPAKGO.JCGKFEPEJPO();
			LGJILKFNKBG = EFDLFNPAKGO.NOIDCBCMCMK();
			KBOBPMGJGIG = EFDLFNPAKGO.NOIDCBCMCMK();
			NIGLIJJDMFO = EFDLFNPAKGO.NOIDCBCMCMK();
			PCCLKBLODMI = EFDLFNPAKGO.NOIDCBCMCMK();
		}
	}
}
