namespace GameServer
{
	public enum HGBGJMIFCEP : byte
	{
		Success = 0,
		InvalidProtocolVersion = 1,
		InvalidUserID = 2,
		InvalidNickname = 3,
		AlreadyConnect = 4,
		InvalidCharacter = 5,
		InvalidAdventure = 6,
		InvalidMission = 7,
		InvalidGuild = 8,
		NotEnoughLevel = 9,
		NotEnoughCoin = 10,
		NotEnoughCash = 11,
		NotEnoughHeart = 12,
		NotEnoughFood = 13,
		NotEnoughSkillPoint = 14,
		MaxLevel = 15,
		MaxCount = 16,
		AlreadyEnterRoom = 17,
		NotEnoughItem = 18,
		AlreadyEquipItem = 19,
		AlreadyExistHero = 20,
		AlreadyClear = 21,
		AlreadyResultChat = 22,
		AlreadyExistGuild = 23,
		BlockUser = 24,
		RankGameBlockUser = 25,
		MaxTodayRecommendCount = 26,
		MaxTotalRecommendCount = 27,
		AlreadyRecommendUser = 28,
		InvalidCoupon = 29,
		ExpireCoupon = 30,
		AlreadyUseCoupon = 31,
		AlreadyConnectAccount = 32,
		CantUseToday = 33,
		TooManyEscape = 34,
		AlreadyRequestFriend = 35,
		AlreadyFriend = 36,
		AlreadyRequestGuild = 37,
		NoPermission = 38,
		CriticalTroller = 39,
		InvalidTime = 40,
		AlreadyUse = 41,
		PossibleUse = 42,
		InvalidAdid = 43,
		AlreadyTransfer = 44,
		AlreadyReceived = 45,
		Unknown = 46
	}
}
