using EveEngine;
using MongoDB.Bson.Serialization.Attributes;

namespace GameServer
{
	[JBFHBIFPIBM]
	public class JBABEKCDKBM : EOPOBHFNFPA
	{
		public byte OIGKODPLDJA;

		public byte HMHEDBOAADF = 1;

		public int MEKAGPLGMCM;

		public uint HCECKOLDNDF;

		public uint BCBKMKDPHHF;

		public uint OFLEBCIMPMD;

		public void JANBGPFAFJF(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(OIGKODPLDJA);
			EFDLFNPAKGO.GBMJNFOEACC(HMHEDBOAADF);
			EFDLFNPAKGO.GBMJNFOEACC(MEKAGPLGMCM);
			EFDLFNPAKGO.GBMJNFOEACC(HCECKOLDNDF);
			EFDLFNPAKGO.GBMJNFOEACC(BCBKMKDPHHF);
			EFDLFNPAKGO.GBMJNFOEACC(OFLEBCIMPMD);
		}

		public void CFGEKKHOKKE(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(OIGKODPLDJA);
			EFDLFNPAKGO.GBMJNFOEACC(HMHEDBOAADF);
			EFDLFNPAKGO.GBMJNFOEACC(MEKAGPLGMCM);
			EFDLFNPAKGO.GBMJNFOEACC(HCECKOLDNDF);
			EFDLFNPAKGO.GBMJNFOEACC(BCBKMKDPHHF);
			EFDLFNPAKGO.GBMJNFOEACC(OFLEBCIMPMD);
		}

		public void DFHOLCGFPIK(PJEMPFEIOAK EFDLFNPAKGO)
		{
			EFDLFNPAKGO.CAHACMKBJMI(ref OIGKODPLDJA);
			EFDLFNPAKGO.CAHACMKBJMI(ref HMHEDBOAADF);
			EFDLFNPAKGO.CAHACMKBJMI(ref MEKAGPLGMCM);
			EFDLFNPAKGO.CAHACMKBJMI(ref HCECKOLDNDF);
			EFDLFNPAKGO.CAHACMKBJMI(ref BCBKMKDPHHF);
			EFDLFNPAKGO.CAHACMKBJMI(ref OFLEBCIMPMD);
		}

		public void JHDBNOHACNB(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(OIGKODPLDJA);
			EFDLFNPAKGO.GBMJNFOEACC(HMHEDBOAADF);
			EFDLFNPAKGO.GBMJNFOEACC(MEKAGPLGMCM);
			EFDLFNPAKGO.GBMJNFOEACC(HCECKOLDNDF);
			EFDLFNPAKGO.BHAFGILIOCN(BCBKMKDPHHF);
			EFDLFNPAKGO.GBMJNFOEACC(OFLEBCIMPMD);
		}

		public void CKBCOALJMJB(PJEMPFEIOAK EFDLFNPAKGO)
		{
			EFDLFNPAKGO.CAHACMKBJMI(ref OIGKODPLDJA);
			EFDLFNPAKGO.CAHACMKBJMI(ref HMHEDBOAADF);
			EFDLFNPAKGO.CAHACMKBJMI(ref MEKAGPLGMCM);
			EFDLFNPAKGO.CAHACMKBJMI(ref HCECKOLDNDF);
			EFDLFNPAKGO.CAHACMKBJMI(ref BCBKMKDPHHF);
			EFDLFNPAKGO.CAHACMKBJMI(ref OFLEBCIMPMD);
		}

		public void KIIHJNANIPB(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(OIGKODPLDJA);
			EFDLFNPAKGO.GBMJNFOEACC(HMHEDBOAADF);
			EFDLFNPAKGO.GBMJNFOEACC(MEKAGPLGMCM);
			EFDLFNPAKGO.BHAFGILIOCN(HCECKOLDNDF);
			EFDLFNPAKGO.GBMJNFOEACC(BCBKMKDPHHF);
			EFDLFNPAKGO.BHAFGILIOCN(OFLEBCIMPMD);
		}

		public void JKDAALCNGJE(PJEMPFEIOAK EFDLFNPAKGO)
		{
			EFDLFNPAKGO.CAHACMKBJMI(ref OIGKODPLDJA);
			EFDLFNPAKGO.CAHACMKBJMI(ref HMHEDBOAADF);
			EFDLFNPAKGO.BNLCLGMMAPD(ref MEKAGPLGMCM);
			EFDLFNPAKGO.CAHACMKBJMI(ref HCECKOLDNDF);
			EFDLFNPAKGO.CAHACMKBJMI(ref BCBKMKDPHHF);
			EFDLFNPAKGO.CAHACMKBJMI(ref OFLEBCIMPMD);
		}

		public void EIMLGHFBJAB(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(OIGKODPLDJA);
			EFDLFNPAKGO.GBMJNFOEACC(HMHEDBOAADF);
			EFDLFNPAKGO.GBMJNFOEACC(MEKAGPLGMCM);
			EFDLFNPAKGO.BHAFGILIOCN(HCECKOLDNDF);
			EFDLFNPAKGO.GBMJNFOEACC(BCBKMKDPHHF);
			EFDLFNPAKGO.BHAFGILIOCN(OFLEBCIMPMD);
		}

		public void CPPAAILEDJO(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(OIGKODPLDJA);
			EFDLFNPAKGO.GBMJNFOEACC(HMHEDBOAADF);
			EFDLFNPAKGO.GBMJNFOEACC(MEKAGPLGMCM);
			EFDLFNPAKGO.GBMJNFOEACC(HCECKOLDNDF);
			EFDLFNPAKGO.GBMJNFOEACC(BCBKMKDPHHF);
			EFDLFNPAKGO.BHAFGILIOCN(OFLEBCIMPMD);
		}

		public void JCOLMPJMMEB(PJEMPFEIOAK EFDLFNPAKGO)
		{
			EFDLFNPAKGO.CAHACMKBJMI(ref OIGKODPLDJA);
			EFDLFNPAKGO.CAHACMKBJMI(ref HMHEDBOAADF);
			EFDLFNPAKGO.CAHACMKBJMI(ref MEKAGPLGMCM);
			EFDLFNPAKGO.CAHACMKBJMI(ref HCECKOLDNDF);
			EFDLFNPAKGO.CAHACMKBJMI(ref BCBKMKDPHHF);
			EFDLFNPAKGO.CAHACMKBJMI(ref OFLEBCIMPMD);
		}
	}
}
