using EveEngine;
using MongoDB.Bson.Serialization.Attributes;

namespace GameServer
{
	[JBFHBIFPIBM]
	public class MCOBKFIDMOK : EOPOBHFNFPA
	{
		[CEJHKGLGHIN]
		public CLJOMPBCNOE.ACPICCBBPHF FBAGNJILEGD;

		[CEJHKGLGHIN]
		public byte CAIKPOKKLJD;

		public ushort IKHBHNCPDLB;

		public bool MNHIDGANMFO()
		{
			if (IKHBHNCPDLB == 0)
			{
				return true;
			}
			return false;
		}

		public void KJBADLDBAOA()
		{
			IKHBHNCPDLB = 0;
		}

		public void JCOLMPJMMEB(PJEMPFEIOAK EFDLFNPAKGO)
		{
			IKHBHNCPDLB = EFDLFNPAKGO.AJPFAAFLHEB();
		}

		public MCOBKFIDMOK()
		{
		}

		public void MHBMBMMBCPK(PJEMPFEIOAK EFDLFNPAKGO)
		{
			IKHBHNCPDLB = EFDLFNPAKGO.AJPFAAFLHEB();
		}

		public void HAKPDFMBFPE(PJEMPFEIOAK EFDLFNPAKGO)
		{
			IKHBHNCPDLB = EFDLFNPAKGO.AJPFAAFLHEB();
		}

		public void AHHKENDIBND(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.HEDNLNDFFCL(IKHBHNCPDLB);
		}

		public void CFGEKKHOKKE(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(IKHBHNCPDLB);
		}

		public MCOBKFIDMOK(CLJOMPBCNOE.ACPICCBBPHF FBAGNJILEGD, byte CAIKPOKKLJD)
		{
			this.FBAGNJILEGD = FBAGNJILEGD;
			this.CAIKPOKKLJD = CAIKPOKKLJD;
			IKHBHNCPDLB = 0;
		}

		public void LIJBCDKPJPP(ushort IKHBHNCPDLB)
		{
			this.IKHBHNCPDLB = IKHBHNCPDLB;
		}

		public CLJOMPBCNOE PEOCGJAJJBG()
		{
			return KIMJPIBNFGA.HEDJPPFKABG().HFNIECNHMFG().PFGPGGNDAAL(IKHBHNCPDLB);
		}

		public void APBPBAPJJNL(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(IKHBHNCPDLB);
		}

		public CLJOMPBCNOE IJDFGGLPNLP()
		{
			return KIMJPIBNFGA.NOLHNOGGHNA().HFNIECNHMFG().KFKMFHLOHCM(IKHBHNCPDLB);
		}

		public void BCGICPOKOHO()
		{
			IKHBHNCPDLB = 1;
		}

		public void MEKNGDKEKKO(PJEMPFEIOAK EFDLFNPAKGO)
		{
			IKHBHNCPDLB = EFDLFNPAKGO.AJPFAAFLHEB();
		}

		public CLJOMPBCNOE JJABFPALOEN()
		{
			return KIMJPIBNFGA.JJBDAOJIDAL().HFNIECNHMFG().FPICNOOFDOA(IKHBHNCPDLB);
		}

		public void AGIOLHGMNBP(ushort IKHBHNCPDLB)
		{
			this.IKHBHNCPDLB = IKHBHNCPDLB;
		}

		public void NECJDAEBLDA()
		{
			IKHBHNCPDLB = 1;
		}

		public void JCKGMOAEJLO(PJEMPFEIOAK EFDLFNPAKGO)
		{
			IKHBHNCPDLB = EFDLFNPAKGO.AJPFAAFLHEB();
		}

		public void EKIOLLKEHGM()
		{
			IKHBHNCPDLB = 0;
		}

		public void LDNEFFHJNPL()
		{
			IKHBHNCPDLB = 0;
		}

		public void HNGINOBLION(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(IKHBHNCPDLB);
		}

		public void GPBOIHMMDDD(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.HEDNLNDFFCL(IKHBHNCPDLB);
		}

		public bool AOANIHBOPHD()
		{
			if (IKHBHNCPDLB == 0)
			{
				return true;
			}
			return false;
		}
	}
}
