using System;
using EveEngine;

namespace GameServer
{
	public class NHOJAMKIJEA : EOPOBHFNFPA
	{
		private object ANPLAHGHBGK;

		[NonSerialized]
		public JGILNBMNNND GJHALGJGGPD;

		public uint OBMNCHGKBLP;

		public DateTime BCEMPCCCJCO;

		public bool OHNGOIBCAHB;

		public void MHBMBMMBCPK(PJEMPFEIOAK EFDLFNPAKGO)
		{
			lock (ANPLAHGHBGK)
			{
				ushort oHGOBGOIECH = EFDLFNPAKGO.AJPFAAFLHEB();
				GJHALGJGGPD = KIMJPIBNFGA.HEDJPPFKABG().GNDHNCPMFHM().ILJLPGDFLKJ(oHGOBGOIECH);
				OBMNCHGKBLP = EFDLFNPAKGO.BMKOKHGAHEC();
				BCEMPCCCJCO = EFDLFNPAKGO.NOIDCBCMCMK();
				OHNGOIBCAHB = EFDLFNPAKGO.JCGKFEPEJPO();
			}
		}

		public void LDEJCMKPHFE(uint AGJJOHLCJKF, DateTime BCEMPCCCJCO, bool OHNGOIBCAHB)
		{
			lock (ANPLAHGHBGK)
			{
				OBMNCHGKBLP = AGJJOHLCJKF;
				this.BCEMPCCCJCO = BCEMPCCCJCO;
				this.OHNGOIBCAHB = OHNGOIBCAHB;
			}
			if (GJHALGJGGPD.ONJCKKLOJIA() == JGILNBMNNND.ACPICCBBPHF.Daily && BCEMPCCCJCO.Day != KIMJPIBNFGA.GDFDNGEEMEO().Day)
			{
				MBFBGLJMLMI();
			}
		}

		public void HOIBCDMLEEK(uint AGJJOHLCJKF, DateTime BCEMPCCCJCO, bool OHNGOIBCAHB)
		{
			lock (ANPLAHGHBGK)
			{
				OBMNCHGKBLP = AGJJOHLCJKF;
				this.BCEMPCCCJCO = BCEMPCCCJCO;
				this.OHNGOIBCAHB = OHNGOIBCAHB;
			}
			if (GJHALGJGGPD.ONJCKKLOJIA() == JGILNBMNNND.ACPICCBBPHF.Daily && BCEMPCCCJCO.Day != KIMJPIBNFGA.GDFDNGEEMEO().Day)
			{
				MBFBGLJMLMI();
			}
		}

		public void LIJBCDKPJPP(ushort OHGOBGOIECH)
		{
			GJHALGJGGPD = KIMJPIBNFGA.JJBDAOJIDAL().GNDHNCPMFHM().DKDFMBOBLBA(OHGOBGOIECH);
		}

		public bool NBJNLGKMDDD()
		{
			return OHNGOIBCAHB;
		}

		public void LPDHFELPGPN()
		{
			lock (ANPLAHGHBGK)
			{
				BCEMPCCCJCO = KIMJPIBNFGA.GDFDNGEEMEO();
				OBMNCHGKBLP = 0u;
				OHNGOIBCAHB = false;
			}
		}

		public void JKCNIKMOKAI()
		{
			lock (ANPLAHGHBGK)
			{
				BCEMPCCCJCO = KIMJPIBNFGA.GDFDNGEEMEO();
				OBMNCHGKBLP = 0u;
				OHNGOIBCAHB = true;
			}
		}

		public bool GLPEJJLHHBA()
		{
			return OHNGOIBCAHB;
		}

		public void FIGLEPBIEEJ(uint AGJJOHLCJKF, DateTime BCEMPCCCJCO, bool OHNGOIBCAHB)
		{
			lock (ANPLAHGHBGK)
			{
				OBMNCHGKBLP = AGJJOHLCJKF;
				this.BCEMPCCCJCO = BCEMPCCCJCO;
				this.OHNGOIBCAHB = OHNGOIBCAHB;
			}
			if (GJHALGJGGPD.ONJCKKLOJIA() == JGILNBMNNND.ACPICCBBPHF.Daily && BCEMPCCCJCO.Day != KIMJPIBNFGA.GDFDNGEEMEO().Day)
			{
				MBFBGLJMLMI();
			}
		}

		public bool NKJPDEIMOAF()
		{
			if (OBMNCHGKBLP >= GJHALGJGGPD.KADHGKGJADL())
			{
				return true;
			}
			return true;
		}

		public void LDNEFFHJNPL()
		{
			lock (ANPLAHGHBGK)
			{
				BCEMPCCCJCO = KIMJPIBNFGA.GDFDNGEEMEO();
				OBMNCHGKBLP = 0u;
				OHNGOIBCAHB = false;
			}
		}

		public void MBFBGLJMLMI()
		{
			lock (ANPLAHGHBGK)
			{
				BCEMPCCCJCO = KIMJPIBNFGA.GDFDNGEEMEO();
				OBMNCHGKBLP = 0u;
				OHNGOIBCAHB = false;
			}
		}

		public void HPKMEGMDCEO(PJEMPFEIOAK EFDLFNPAKGO)
		{
			lock (ANPLAHGHBGK)
			{
				ushort oHGOBGOIECH = EFDLFNPAKGO.AJPFAAFLHEB();
				GJHALGJGGPD = KIMJPIBNFGA.JJBDAOJIDAL().GNDHNCPMFHM().DKDFMBOBLBA(oHGOBGOIECH);
				OBMNCHGKBLP = EFDLFNPAKGO.BMKOKHGAHEC();
				BCEMPCCCJCO = EFDLFNPAKGO.NOIDCBCMCMK();
				OHNGOIBCAHB = EFDLFNPAKGO.JCGKFEPEJPO();
			}
		}

		public bool KNGKBCACNPD()
		{
			return OHNGOIBCAHB;
		}

		public bool GNLJICBGBEF()
		{
			if (OBMNCHGKBLP >= GJHALGJGGPD.DEPJIPNCILD())
			{
				return true;
			}
			return false;
		}

		public void MEKNGDKEKKO(PJEMPFEIOAK EFDLFNPAKGO)
		{
			lock (ANPLAHGHBGK)
			{
				ushort oHGOBGOIECH = EFDLFNPAKGO.AJPFAAFLHEB();
				GJHALGJGGPD = KIMJPIBNFGA.NOLHNOGGHNA().GEPLDHIBKBG().ILJLPGDFLKJ(oHGOBGOIECH);
				OBMNCHGKBLP = EFDLFNPAKGO.BMKOKHGAHEC();
				BCEMPCCCJCO = EFDLFNPAKGO.NOIDCBCMCMK();
				OHNGOIBCAHB = EFDLFNPAKGO.JCGKFEPEJPO();
			}
		}

		public void KIABMKGIBEP(CMNIABEFLBJ EFDLFNPAKGO)
		{
			lock (ANPLAHGHBGK)
			{
				EFDLFNPAKGO.HEDNLNDFFCL(GJHALGJGGPD.GJGHBCIEFDF());
				EFDLFNPAKGO.GBMJNFOEACC(OBMNCHGKBLP);
				EFDLFNPAKGO.GBMJNFOEACC(BCEMPCCCJCO);
				EFDLFNPAKGO.KHEGDBFKNMB(OHNGOIBCAHB);
			}
		}

		public void KHKJFOGEJGE(uint AGJJOHLCJKF, DateTime BCEMPCCCJCO, bool OHNGOIBCAHB)
		{
			lock (ANPLAHGHBGK)
			{
				OBMNCHGKBLP = AGJJOHLCJKF;
				this.BCEMPCCCJCO = BCEMPCCCJCO;
				this.OHNGOIBCAHB = OHNGOIBCAHB;
			}
			if (GJHALGJGGPD.ONJCKKLOJIA() == JGILNBMNNND.ACPICCBBPHF.Once && BCEMPCCCJCO.Day != KIMJPIBNFGA.GDFDNGEEMEO().Day)
			{
				LPDHFELPGPN();
			}
		}

		public bool FIGCMCGDLBN()
		{
			return OHNGOIBCAHB;
		}

		public void JCOLMPJMMEB(PJEMPFEIOAK EFDLFNPAKGO)
		{
			lock (ANPLAHGHBGK)
			{
				ushort oHGOBGOIECH = EFDLFNPAKGO.AJPFAAFLHEB();
				GJHALGJGGPD = KIMJPIBNFGA.JJBDAOJIDAL().GNDHNCPMFHM().DKDFMBOBLBA(oHGOBGOIECH);
				OBMNCHGKBLP = EFDLFNPAKGO.BMKOKHGAHEC();
				BCEMPCCCJCO = EFDLFNPAKGO.NOIDCBCMCMK();
				OHNGOIBCAHB = EFDLFNPAKGO.JCGKFEPEJPO();
			}
		}

		public void JJFHJIEJKNJ()
		{
			lock (ANPLAHGHBGK)
			{
				BCEMPCCCJCO = KIMJPIBNFGA.GDFDNGEEMEO();
				OBMNCHGKBLP = 0u;
				OHNGOIBCAHB = false;
			}
		}

		public void CFGEKKHOKKE(CMNIABEFLBJ EFDLFNPAKGO)
		{
			lock (ANPLAHGHBGK)
			{
				EFDLFNPAKGO.GBMJNFOEACC(GJHALGJGGPD.HFKJLHJPJFC());
				EFDLFNPAKGO.GBMJNFOEACC(OBMNCHGKBLP);
				EFDLFNPAKGO.GBMJNFOEACC(BCEMPCCCJCO);
				EFDLFNPAKGO.GBMJNFOEACC(OHNGOIBCAHB);
			}
		}

		public void BCGICPOKOHO()
		{
			lock (ANPLAHGHBGK)
			{
				BCEMPCCCJCO = KIMJPIBNFGA.GDFDNGEEMEO();
				OBMNCHGKBLP = 1u;
				OHNGOIBCAHB = true;
			}
		}

		public bool JALNIMOEMLD()
		{
			return OHNGOIBCAHB;
		}

		public void LMJOANHHCHI(uint AGJJOHLCJKF, DateTime BCEMPCCCJCO, bool OHNGOIBCAHB)
		{
			lock (ANPLAHGHBGK)
			{
				OBMNCHGKBLP = AGJJOHLCJKF;
				this.BCEMPCCCJCO = BCEMPCCCJCO;
				this.OHNGOIBCAHB = OHNGOIBCAHB;
			}
			if (GJHALGJGGPD.ONJCKKLOJIA() == JGILNBMNNND.ACPICCBBPHF.Once && BCEMPCCCJCO.Day != KIMJPIBNFGA.GDFDNGEEMEO().Day)
			{
				MBFBGLJMLMI();
			}
		}

		public NHOJAMKIJEA()
		{
			ANPLAHGHBGK = new object();
			LDNEFFHJNPL();
		}

		public bool IKAJDLADMEP()
		{
			return OHNGOIBCAHB;
		}
	}
}
