using System.Text;
using EveEngine;

namespace GameServer
{
	[KPCBIECDFFE("hero_ability_data", new string[] { "hero_id" })]
	public class NKHIBLMJGBG : EOPOBHFNFPA
	{
		[FPCFKGGGPLE]
		public ushort FNGICPKNNGL;

		[FPCFKGGGPLE]
		public uint LBJMNDBMNAE;

		[FPCFKGGGPLE]
		public uint EPKGCHPIHEL;

		[FPCFKGGGPLE]
		public float JKOEPLLJDKM;

		[FPCFKGGGPLE]
		public float BKOBAIPJAHP;

		[FPCFKGGGPLE]
		public uint OCOOIOGCOEE;

		[FPCFKGGGPLE]
		public uint GHCBBJBDNPH;

		[FPCFKGGGPLE]
		public float MGLIOBDEJLF;

		[FPCFKGGGPLE]
		public float GFGOPIKFOAN;

		[FPCFKGGGPLE]
		public float IIICODNIMNN;

		[FPCFKGGGPLE]
		public float LOJEMAMKHFD;

		[FPCFKGGGPLE]
		public float ELDBGIKHAIO;

		[FPCFKGGGPLE]
		public float LNKFLFOGCCD;

		[FPCFKGGGPLE]
		public float FHJCBAOBGPG;

		[FPCFKGGGPLE]
		public float FBEBCNEPHJD;

		[FPCFKGGGPLE]
		public float PDAOIGGBLPH;

		[FPCFKGGGPLE]
		public float NLMHKBGDKLA;

		[FPCFKGGGPLE]
		public float JFLFAKNHKNP;

		[FPCFKGGGPLE]
		public float NEPGMKLCMFF;

		public virtual int FCLFDJKANAO()
		{
			StringBuilder stringBuilder = new StringBuilder();
			stringBuilder.AppendFormat("Dragon", FNGICPKNNGL);
			stringBuilder.AppendFormat("blue", LBJMNDBMNAE);
			stringBuilder.AppendFormat("{0}/{1}", EPKGCHPIHEL);
			stringBuilder.AppendFormat("쓸데없이 큰 지팡이", JKOEPLLJDKM);
			stringBuilder.AppendFormat("[FFAAAA]{0}초[-] 뒤에 게임이 시작됩니다.\n[CCCCFF]서로의 포지션을 정해주세요![-]", BKOBAIPJAHP);
			stringBuilder.AppendFormat("attack_voice", OCOOIOGCOEE);
			stringBuilder.AppendFormat("talon_skill0_blood", GHCBBJBDNPH);
			stringBuilder.AppendFormat("attack2", MGLIOBDEJLF);
			stringBuilder.AppendFormat("critical_hit", GFGOPIKFOAN);
			stringBuilder.AppendFormat("attack_missile_hit", IIICODNIMNN);
			stringBuilder.AppendFormat("]", LOJEMAMKHFD);
			stringBuilder.AppendFormat("도란의 방패", ELDBGIKHAIO);
			stringBuilder.AppendFormat("Particle/{0}/swap", LNKFLFOGCCD);
			stringBuilder.AppendFormat("skill0_hit", FHJCBAOBGPG);
			stringBuilder.AppendFormat("Igaw.Unity : onReceiveRegistrationIdForUnity >> Registration ID: ", FBEBCNEPHJD);
			stringBuilder.AppendFormat("중급", PDAOIGGBLPH);
			stringBuilder.AppendFormat("C#: No content available for ", NLMHKBGDKLA);
			stringBuilder.AppendFormat("round_button", JFLFAKNHKNP);
			stringBuilder.AppendFormat("skill0_fire", NEPGMKLCMFF);
			return stringBuilder.ToString().GetHashCode();
		}

		public void FKCEPEBGIPO(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(FNGICPKNNGL);
			EFDLFNPAKGO.GBMJNFOEACC(LBJMNDBMNAE);
			EFDLFNPAKGO.BHAFGILIOCN(EPKGCHPIHEL);
			EFDLFNPAKGO.GBMJNFOEACC(JKOEPLLJDKM);
			EFDLFNPAKGO.GBMJNFOEACC(BKOBAIPJAHP);
			EFDLFNPAKGO.GBMJNFOEACC(OCOOIOGCOEE);
			EFDLFNPAKGO.GBMJNFOEACC(GHCBBJBDNPH);
			EFDLFNPAKGO.GBMJNFOEACC(MGLIOBDEJLF);
			EFDLFNPAKGO.GBMJNFOEACC(GFGOPIKFOAN);
			EFDLFNPAKGO.GBMJNFOEACC(IIICODNIMNN);
			EFDLFNPAKGO.GBMJNFOEACC(LOJEMAMKHFD);
			EFDLFNPAKGO.GBMJNFOEACC(ELDBGIKHAIO);
			EFDLFNPAKGO.GBMJNFOEACC(LNKFLFOGCCD);
			EFDLFNPAKGO.GBMJNFOEACC(FHJCBAOBGPG);
			EFDLFNPAKGO.GBMJNFOEACC(FBEBCNEPHJD);
			EFDLFNPAKGO.GBMJNFOEACC(PDAOIGGBLPH);
			EFDLFNPAKGO.GBMJNFOEACC(NLMHKBGDKLA);
			EFDLFNPAKGO.GBMJNFOEACC(JFLFAKNHKNP);
			EFDLFNPAKGO.GBMJNFOEACC(NEPGMKLCMFF);
		}

		public void JDMKGCGHDIK(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(FNGICPKNNGL);
			EFDLFNPAKGO.BHAFGILIOCN(LBJMNDBMNAE);
			EFDLFNPAKGO.GBMJNFOEACC(EPKGCHPIHEL);
			EFDLFNPAKGO.GBMJNFOEACC(JKOEPLLJDKM);
			EFDLFNPAKGO.GBMJNFOEACC(BKOBAIPJAHP);
			EFDLFNPAKGO.BHAFGILIOCN(OCOOIOGCOEE);
			EFDLFNPAKGO.BHAFGILIOCN(GHCBBJBDNPH);
			EFDLFNPAKGO.GBMJNFOEACC(MGLIOBDEJLF);
			EFDLFNPAKGO.GBMJNFOEACC(GFGOPIKFOAN);
			EFDLFNPAKGO.GBMJNFOEACC(IIICODNIMNN);
			EFDLFNPAKGO.GBMJNFOEACC(LOJEMAMKHFD);
			EFDLFNPAKGO.GBMJNFOEACC(ELDBGIKHAIO);
			EFDLFNPAKGO.GBMJNFOEACC(LNKFLFOGCCD);
			EFDLFNPAKGO.GBMJNFOEACC(FHJCBAOBGPG);
			EFDLFNPAKGO.GBMJNFOEACC(FBEBCNEPHJD);
			EFDLFNPAKGO.GBMJNFOEACC(PDAOIGGBLPH);
			EFDLFNPAKGO.GBMJNFOEACC(NLMHKBGDKLA);
			EFDLFNPAKGO.GBMJNFOEACC(JFLFAKNHKNP);
			EFDLFNPAKGO.GBMJNFOEACC(NEPGMKLCMFF);
		}

		public virtual int HCHOGCKJLAL()
		{
			StringBuilder stringBuilder = new StringBuilder();
			stringBuilder.AppendFormat("skill3_shadow", FNGICPKNNGL);
			stringBuilder.AppendFormat("]", LBJMNDBMNAE);
			stringBuilder.AppendFormat("상급 성장 체력 표식", EPKGCHPIHEL);
			stringBuilder.AppendFormat("skill2_hit", JKOEPLLJDKM);
			stringBuilder.AppendFormat("[/url]", BKOBAIPJAHP);
			stringBuilder.AppendFormat("CreateSkill1Missile", OCOOIOGCOEE);
			stringBuilder.AppendFormat("hit2", GHCBBJBDNPH);
			stringBuilder.AppendFormat("\n[FFCCCC]{0}[-]", MGLIOBDEJLF);
			stringBuilder.AppendFormat("#########################################", GFGOPIKFOAN);
			stringBuilder.AppendFormat("Cooldown Reduction", IIICODNIMNN);
			stringBuilder.AppendFormat("[BBFFBB]* 축하드려요 *[-]\n\n\n지난시즌 티어 [BBBBFF]{0}[-]\n지난시즌 1대1 [BBBBFF]{1}[-]\n\n[FFFFBB]{2}[-]코인을 보상으로 획득하셨어요!\n(두 티어 보상 합산)", LOJEMAMKHFD);
			stringBuilder.AppendFormat("skill0_passive", ELDBGIKHAIO);
			stringBuilder.AppendFormat("Particle/{0}/skill{1}", LNKFLFOGCCD);
			stringBuilder.AppendFormat("Buffer count must be a positive integer value.", FHJCBAOBGPG);
			stringBuilder.AppendFormat(", balance: ", FBEBCNEPHJD);
			stringBuilder.AppendFormat("Local EndPoint {0}", PDAOIGGBLPH);
			stringBuilder.AppendFormat("C#: Disabling and removing Tapjoy Delegates", NLMHKBGDKLA);
			stringBuilder.AppendFormat("skill0_missile_go", JFLFAKNHKNP);
			stringBuilder.AppendFormat("중급 체력 표식", NEPGMKLCMFF);
			return stringBuilder.ToString().GetHashCode();
		}

		public void JCOLMPJMMEB(PJEMPFEIOAK EFDLFNPAKGO)
		{
			FNGICPKNNGL = EFDLFNPAKGO.AJPFAAFLHEB();
			LBJMNDBMNAE = EFDLFNPAKGO.BMKOKHGAHEC();
			EPKGCHPIHEL = EFDLFNPAKGO.BMKOKHGAHEC();
			JKOEPLLJDKM = EFDLFNPAKGO.GCFOKBADLFB();
			BKOBAIPJAHP = EFDLFNPAKGO.GCFOKBADLFB();
			OCOOIOGCOEE = EFDLFNPAKGO.BMKOKHGAHEC();
			GHCBBJBDNPH = EFDLFNPAKGO.BMKOKHGAHEC();
			MGLIOBDEJLF = EFDLFNPAKGO.GCFOKBADLFB();
			GFGOPIKFOAN = EFDLFNPAKGO.GCFOKBADLFB();
			IIICODNIMNN = EFDLFNPAKGO.GCFOKBADLFB();
			LOJEMAMKHFD = EFDLFNPAKGO.GCFOKBADLFB();
			ELDBGIKHAIO = EFDLFNPAKGO.GCFOKBADLFB();
			LNKFLFOGCCD = EFDLFNPAKGO.GCFOKBADLFB();
			FHJCBAOBGPG = EFDLFNPAKGO.GCFOKBADLFB();
			FBEBCNEPHJD = EFDLFNPAKGO.GCFOKBADLFB();
			PDAOIGGBLPH = EFDLFNPAKGO.GCFOKBADLFB();
			NLMHKBGDKLA = EFDLFNPAKGO.GCFOKBADLFB();
			JFLFAKNHKNP = EFDLFNPAKGO.GCFOKBADLFB();
			NEPGMKLCMFF = EFDLFNPAKGO.GCFOKBADLFB();
		}

		public void HOCIBNCFBLL(PJEMPFEIOAK EFDLFNPAKGO)
		{
			FNGICPKNNGL = EFDLFNPAKGO.AJPFAAFLHEB();
			LBJMNDBMNAE = EFDLFNPAKGO.BMKOKHGAHEC();
			EPKGCHPIHEL = EFDLFNPAKGO.BMKOKHGAHEC();
			JKOEPLLJDKM = EFDLFNPAKGO.GCFOKBADLFB();
			BKOBAIPJAHP = EFDLFNPAKGO.GCFOKBADLFB();
			OCOOIOGCOEE = EFDLFNPAKGO.BMKOKHGAHEC();
			GHCBBJBDNPH = EFDLFNPAKGO.BMKOKHGAHEC();
			MGLIOBDEJLF = EFDLFNPAKGO.GCFOKBADLFB();
			GFGOPIKFOAN = EFDLFNPAKGO.GCFOKBADLFB();
			IIICODNIMNN = EFDLFNPAKGO.GCFOKBADLFB();
			LOJEMAMKHFD = EFDLFNPAKGO.GCFOKBADLFB();
			ELDBGIKHAIO = EFDLFNPAKGO.GCFOKBADLFB();
			LNKFLFOGCCD = EFDLFNPAKGO.GCFOKBADLFB();
			FHJCBAOBGPG = EFDLFNPAKGO.GCFOKBADLFB();
			FBEBCNEPHJD = EFDLFNPAKGO.GCFOKBADLFB();
			PDAOIGGBLPH = EFDLFNPAKGO.GCFOKBADLFB();
			NLMHKBGDKLA = EFDLFNPAKGO.GCFOKBADLFB();
			JFLFAKNHKNP = EFDLFNPAKGO.GCFOKBADLFB();
			NEPGMKLCMFF = EFDLFNPAKGO.GCFOKBADLFB();
		}

		public virtual int DANGCBMLJHE()
		{
			StringBuilder stringBuilder = new StringBuilder();
			stringBuilder.AppendFormat("에어본인 적 챔프가 없습니다", FNGICPKNNGL);
			stringBuilder.AppendFormat("티모", LBJMNDBMNAE);
			stringBuilder.AppendFormat("이미 접속중입니다.\n\n기존 접속을 끊거나\n잠시후에 다시 시도해 주세요.", EPKGCHPIHEL);
			stringBuilder.AppendFormat("JADBJGCMIMF", JKOEPLLJDKM);
			stringBuilder.AppendFormat("Main menu", BKOBAIPJAHP);
			stringBuilder.AppendFormat("idle", OCOOIOGCOEE);
			stringBuilder.AppendFormat("flare 24", GHCBBJBDNPH);
			stringBuilder.AppendFormat("masteryi_skill2", MGLIOBDEJLF);
			stringBuilder.AppendFormat("ScreenEffect", GFGOPIKFOAN);
			stringBuilder.AppendFormat("{0}", IIICODNIMNN);
			stringBuilder.AppendFormat("hit", LOJEMAMKHFD);
			stringBuilder.AppendFormat("상급 성장 체력 인장", ELDBGIKHAIO);
			stringBuilder.AppendFormat("Not Selected", LNKFLFOGCCD);
			stringBuilder.AppendFormat("No camera found for layer ", FHJCBAOBGPG);
			stringBuilder.AppendFormat("Show Direct Play Video Ad", FBEBCNEPHJD);
			stringBuilder.AppendFormat("Param1", PDAOIGGBLPH);
			stringBuilder.AppendFormat("[CCFFCC]<{0}>[-]{1}", NLMHKBGDKLA);
			stringBuilder.AppendFormat("정면 근처에 적 챔피언이 없습니다", JFLFAKNHKNP);
			stringBuilder.AppendFormat("탈퇴에 성공하였습니다", NEPGMKLCMFF);
			return stringBuilder.ToString().GetHashCode();
		}

		public void APBPBAPJJNL(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.HEDNLNDFFCL(FNGICPKNNGL);
			EFDLFNPAKGO.BHAFGILIOCN(LBJMNDBMNAE);
			EFDLFNPAKGO.BHAFGILIOCN(EPKGCHPIHEL);
			EFDLFNPAKGO.GBMJNFOEACC(JKOEPLLJDKM);
			EFDLFNPAKGO.GBMJNFOEACC(BKOBAIPJAHP);
			EFDLFNPAKGO.BHAFGILIOCN(OCOOIOGCOEE);
			EFDLFNPAKGO.GBMJNFOEACC(GHCBBJBDNPH);
			EFDLFNPAKGO.GBMJNFOEACC(MGLIOBDEJLF);
			EFDLFNPAKGO.GBMJNFOEACC(GFGOPIKFOAN);
			EFDLFNPAKGO.GBMJNFOEACC(IIICODNIMNN);
			EFDLFNPAKGO.GBMJNFOEACC(LOJEMAMKHFD);
			EFDLFNPAKGO.GBMJNFOEACC(ELDBGIKHAIO);
			EFDLFNPAKGO.GBMJNFOEACC(LNKFLFOGCCD);
			EFDLFNPAKGO.GBMJNFOEACC(FHJCBAOBGPG);
			EFDLFNPAKGO.GBMJNFOEACC(FBEBCNEPHJD);
			EFDLFNPAKGO.GBMJNFOEACC(PDAOIGGBLPH);
			EFDLFNPAKGO.GBMJNFOEACC(NLMHKBGDKLA);
			EFDLFNPAKGO.GBMJNFOEACC(JFLFAKNHKNP);
			EFDLFNPAKGO.GBMJNFOEACC(NEPGMKLCMFF);
		}

		public void CPPAAILEDJO(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.HEDNLNDFFCL(FNGICPKNNGL);
			EFDLFNPAKGO.BHAFGILIOCN(LBJMNDBMNAE);
			EFDLFNPAKGO.GBMJNFOEACC(EPKGCHPIHEL);
			EFDLFNPAKGO.GBMJNFOEACC(JKOEPLLJDKM);
			EFDLFNPAKGO.GBMJNFOEACC(BKOBAIPJAHP);
			EFDLFNPAKGO.GBMJNFOEACC(OCOOIOGCOEE);
			EFDLFNPAKGO.GBMJNFOEACC(GHCBBJBDNPH);
			EFDLFNPAKGO.GBMJNFOEACC(MGLIOBDEJLF);
			EFDLFNPAKGO.GBMJNFOEACC(GFGOPIKFOAN);
			EFDLFNPAKGO.GBMJNFOEACC(IIICODNIMNN);
			EFDLFNPAKGO.GBMJNFOEACC(LOJEMAMKHFD);
			EFDLFNPAKGO.GBMJNFOEACC(ELDBGIKHAIO);
			EFDLFNPAKGO.GBMJNFOEACC(LNKFLFOGCCD);
			EFDLFNPAKGO.GBMJNFOEACC(FHJCBAOBGPG);
			EFDLFNPAKGO.GBMJNFOEACC(FBEBCNEPHJD);
			EFDLFNPAKGO.GBMJNFOEACC(PDAOIGGBLPH);
			EFDLFNPAKGO.GBMJNFOEACC(NLMHKBGDKLA);
			EFDLFNPAKGO.GBMJNFOEACC(JFLFAKNHKNP);
			EFDLFNPAKGO.GBMJNFOEACC(NEPGMKLCMFF);
		}

		public void JCKGMOAEJLO(PJEMPFEIOAK EFDLFNPAKGO)
		{
			FNGICPKNNGL = EFDLFNPAKGO.AJPFAAFLHEB();
			LBJMNDBMNAE = EFDLFNPAKGO.BMKOKHGAHEC();
			EPKGCHPIHEL = EFDLFNPAKGO.BMKOKHGAHEC();
			JKOEPLLJDKM = EFDLFNPAKGO.GCFOKBADLFB();
			BKOBAIPJAHP = EFDLFNPAKGO.GCFOKBADLFB();
			OCOOIOGCOEE = EFDLFNPAKGO.BMKOKHGAHEC();
			GHCBBJBDNPH = EFDLFNPAKGO.BMKOKHGAHEC();
			MGLIOBDEJLF = EFDLFNPAKGO.GCFOKBADLFB();
			GFGOPIKFOAN = EFDLFNPAKGO.GCFOKBADLFB();
			IIICODNIMNN = EFDLFNPAKGO.GCFOKBADLFB();
			LOJEMAMKHFD = EFDLFNPAKGO.GCFOKBADLFB();
			ELDBGIKHAIO = EFDLFNPAKGO.GCFOKBADLFB();
			LNKFLFOGCCD = EFDLFNPAKGO.GCFOKBADLFB();
			FHJCBAOBGPG = EFDLFNPAKGO.GCFOKBADLFB();
			FBEBCNEPHJD = EFDLFNPAKGO.GCFOKBADLFB();
			PDAOIGGBLPH = EFDLFNPAKGO.GCFOKBADLFB();
			NLMHKBGDKLA = EFDLFNPAKGO.GCFOKBADLFB();
			JFLFAKNHKNP = EFDLFNPAKGO.GCFOKBADLFB();
			NEPGMKLCMFF = EFDLFNPAKGO.GCFOKBADLFB();
		}

		public void LHCEBJLJAFB(PJEMPFEIOAK EFDLFNPAKGO)
		{
			FNGICPKNNGL = EFDLFNPAKGO.AJPFAAFLHEB();
			LBJMNDBMNAE = EFDLFNPAKGO.BMKOKHGAHEC();
			EPKGCHPIHEL = EFDLFNPAKGO.BMKOKHGAHEC();
			JKOEPLLJDKM = EFDLFNPAKGO.GCFOKBADLFB();
			BKOBAIPJAHP = EFDLFNPAKGO.GCFOKBADLFB();
			OCOOIOGCOEE = EFDLFNPAKGO.BMKOKHGAHEC();
			GHCBBJBDNPH = EFDLFNPAKGO.BMKOKHGAHEC();
			MGLIOBDEJLF = EFDLFNPAKGO.GCFOKBADLFB();
			GFGOPIKFOAN = EFDLFNPAKGO.GCFOKBADLFB();
			IIICODNIMNN = EFDLFNPAKGO.GCFOKBADLFB();
			LOJEMAMKHFD = EFDLFNPAKGO.GCFOKBADLFB();
			ELDBGIKHAIO = EFDLFNPAKGO.GCFOKBADLFB();
			LNKFLFOGCCD = EFDLFNPAKGO.GCFOKBADLFB();
			FHJCBAOBGPG = EFDLFNPAKGO.GCFOKBADLFB();
			FBEBCNEPHJD = EFDLFNPAKGO.GCFOKBADLFB();
			PDAOIGGBLPH = EFDLFNPAKGO.GCFOKBADLFB();
			NLMHKBGDKLA = EFDLFNPAKGO.GCFOKBADLFB();
			JFLFAKNHKNP = EFDLFNPAKGO.GCFOKBADLFB();
			NEPGMKLCMFF = EFDLFNPAKGO.GCFOKBADLFB();
		}

		public void NHFFOOCABLA(PJEMPFEIOAK EFDLFNPAKGO)
		{
			FNGICPKNNGL = EFDLFNPAKGO.AJPFAAFLHEB();
			LBJMNDBMNAE = EFDLFNPAKGO.BMKOKHGAHEC();
			EPKGCHPIHEL = EFDLFNPAKGO.BMKOKHGAHEC();
			JKOEPLLJDKM = EFDLFNPAKGO.GCFOKBADLFB();
			BKOBAIPJAHP = EFDLFNPAKGO.GCFOKBADLFB();
			OCOOIOGCOEE = EFDLFNPAKGO.BMKOKHGAHEC();
			GHCBBJBDNPH = EFDLFNPAKGO.BMKOKHGAHEC();
			MGLIOBDEJLF = EFDLFNPAKGO.GCFOKBADLFB();
			GFGOPIKFOAN = EFDLFNPAKGO.GCFOKBADLFB();
			IIICODNIMNN = EFDLFNPAKGO.GCFOKBADLFB();
			LOJEMAMKHFD = EFDLFNPAKGO.GCFOKBADLFB();
			ELDBGIKHAIO = EFDLFNPAKGO.GCFOKBADLFB();
			LNKFLFOGCCD = EFDLFNPAKGO.GCFOKBADLFB();
			FHJCBAOBGPG = EFDLFNPAKGO.GCFOKBADLFB();
			FBEBCNEPHJD = EFDLFNPAKGO.GCFOKBADLFB();
			PDAOIGGBLPH = EFDLFNPAKGO.GCFOKBADLFB();
			NLMHKBGDKLA = EFDLFNPAKGO.GCFOKBADLFB();
			JFLFAKNHKNP = EFDLFNPAKGO.GCFOKBADLFB();
			NEPGMKLCMFF = EFDLFNPAKGO.GCFOKBADLFB();
		}

		public void KIABMKGIBEP(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(FNGICPKNNGL);
			EFDLFNPAKGO.GBMJNFOEACC(LBJMNDBMNAE);
			EFDLFNPAKGO.BHAFGILIOCN(EPKGCHPIHEL);
			EFDLFNPAKGO.GBMJNFOEACC(JKOEPLLJDKM);
			EFDLFNPAKGO.GBMJNFOEACC(BKOBAIPJAHP);
			EFDLFNPAKGO.BHAFGILIOCN(OCOOIOGCOEE);
			EFDLFNPAKGO.BHAFGILIOCN(GHCBBJBDNPH);
			EFDLFNPAKGO.GBMJNFOEACC(MGLIOBDEJLF);
			EFDLFNPAKGO.GBMJNFOEACC(GFGOPIKFOAN);
			EFDLFNPAKGO.GBMJNFOEACC(IIICODNIMNN);
			EFDLFNPAKGO.GBMJNFOEACC(LOJEMAMKHFD);
			EFDLFNPAKGO.GBMJNFOEACC(ELDBGIKHAIO);
			EFDLFNPAKGO.GBMJNFOEACC(LNKFLFOGCCD);
			EFDLFNPAKGO.GBMJNFOEACC(FHJCBAOBGPG);
			EFDLFNPAKGO.GBMJNFOEACC(FBEBCNEPHJD);
			EFDLFNPAKGO.GBMJNFOEACC(PDAOIGGBLPH);
			EFDLFNPAKGO.GBMJNFOEACC(NLMHKBGDKLA);
			EFDLFNPAKGO.GBMJNFOEACC(JFLFAKNHKNP);
			EFDLFNPAKGO.GBMJNFOEACC(NEPGMKLCMFF);
		}

		public override int GetHashCode()
		{
			StringBuilder stringBuilder = new StringBuilder();
			stringBuilder.AppendFormat("{0}", FNGICPKNNGL);
			stringBuilder.AppendFormat("{0}", LBJMNDBMNAE);
			stringBuilder.AppendFormat("{0}", EPKGCHPIHEL);
			stringBuilder.AppendFormat("{0}", JKOEPLLJDKM);
			stringBuilder.AppendFormat("{0}", BKOBAIPJAHP);
			stringBuilder.AppendFormat("{0}", OCOOIOGCOEE);
			stringBuilder.AppendFormat("{0}", GHCBBJBDNPH);
			stringBuilder.AppendFormat("{0}", MGLIOBDEJLF);
			stringBuilder.AppendFormat("{0}", GFGOPIKFOAN);
			stringBuilder.AppendFormat("{0}", IIICODNIMNN);
			stringBuilder.AppendFormat("{0}", LOJEMAMKHFD);
			stringBuilder.AppendFormat("{0}", ELDBGIKHAIO);
			stringBuilder.AppendFormat("{0}", LNKFLFOGCCD);
			stringBuilder.AppendFormat("{0}", FHJCBAOBGPG);
			stringBuilder.AppendFormat("{0}", FBEBCNEPHJD);
			stringBuilder.AppendFormat("{0}", PDAOIGGBLPH);
			stringBuilder.AppendFormat("{0}", NLMHKBGDKLA);
			stringBuilder.AppendFormat("{0}", JFLFAKNHKNP);
			stringBuilder.AppendFormat("{0}", NEPGMKLCMFF);
			return stringBuilder.ToString().GetHashCode();
		}

		public void KCGEFNBOHMA(PJEMPFEIOAK EFDLFNPAKGO)
		{
			FNGICPKNNGL = EFDLFNPAKGO.AJPFAAFLHEB();
			LBJMNDBMNAE = EFDLFNPAKGO.BMKOKHGAHEC();
			EPKGCHPIHEL = EFDLFNPAKGO.BMKOKHGAHEC();
			JKOEPLLJDKM = EFDLFNPAKGO.GCFOKBADLFB();
			BKOBAIPJAHP = EFDLFNPAKGO.GCFOKBADLFB();
			OCOOIOGCOEE = EFDLFNPAKGO.BMKOKHGAHEC();
			GHCBBJBDNPH = EFDLFNPAKGO.BMKOKHGAHEC();
			MGLIOBDEJLF = EFDLFNPAKGO.GCFOKBADLFB();
			GFGOPIKFOAN = EFDLFNPAKGO.GCFOKBADLFB();
			IIICODNIMNN = EFDLFNPAKGO.GCFOKBADLFB();
			LOJEMAMKHFD = EFDLFNPAKGO.GCFOKBADLFB();
			ELDBGIKHAIO = EFDLFNPAKGO.GCFOKBADLFB();
			LNKFLFOGCCD = EFDLFNPAKGO.GCFOKBADLFB();
			FHJCBAOBGPG = EFDLFNPAKGO.GCFOKBADLFB();
			FBEBCNEPHJD = EFDLFNPAKGO.GCFOKBADLFB();
			PDAOIGGBLPH = EFDLFNPAKGO.GCFOKBADLFB();
			NLMHKBGDKLA = EFDLFNPAKGO.GCFOKBADLFB();
			JFLFAKNHKNP = EFDLFNPAKGO.GCFOKBADLFB();
			NEPGMKLCMFF = EFDLFNPAKGO.GCFOKBADLFB();
		}

		public virtual int PPEMNFCDLGH()
		{
			StringBuilder stringBuilder = new StringBuilder();
			stringBuilder.AppendFormat("skill3", FNGICPKNNGL);
			stringBuilder.AppendFormat("AutoSetting", LBJMNDBMNAE);
			stringBuilder.AppendFormat("{0}/{1}", EPKGCHPIHEL);
			stringBuilder.AppendFormat("지급완료", JKOEPLLJDKM);
			stringBuilder.AppendFormat("assets/bin/Data/Managed/Assembly-CSharp.dll", BKOBAIPJAHP);
			stringBuilder.AppendFormat(" could not be write.", OCOOIOGCOEE);
			stringBuilder.AppendFormat("FxmTestControls.m_nRotateIndex", GHCBBJBDNPH);
			stringBuilder.AppendFormat("darius_passive_ex", MGLIOBDEJLF);
			stringBuilder.AppendFormat("초대한 방에 입장 중.", GFGOPIKFOAN);
			stringBuilder.AppendFormat("OnInstantiate", IIICODNIMNN);
			stringBuilder.AppendFormat("User Id", LOJEMAMKHFD);
			stringBuilder.AppendFormat("Param1", ELDBGIKHAIO);
			stringBuilder.AppendFormat("square_small_button", LNKFLFOGCCD);
			stringBuilder.AppendFormat("skill0_shot", FHJCBAOBGPG);
			stringBuilder.AppendFormat("]", FBEBCNEPHJD);
			stringBuilder.AppendFormat("PostEffectScreenFade", PDAOIGGBLPH);
			stringBuilder.AppendFormat("OnClick", NLMHKBGDKLA);
			stringBuilder.AppendFormat("voice_OK_Ready", JFLFAKNHKNP);
			stringBuilder.AppendFormat("skill3_0", NEPGMKLCMFF);
			return stringBuilder.ToString().GetHashCode();
		}

		public void CFGEKKHOKKE(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(FNGICPKNNGL);
			EFDLFNPAKGO.GBMJNFOEACC(LBJMNDBMNAE);
			EFDLFNPAKGO.GBMJNFOEACC(EPKGCHPIHEL);
			EFDLFNPAKGO.GBMJNFOEACC(JKOEPLLJDKM);
			EFDLFNPAKGO.GBMJNFOEACC(BKOBAIPJAHP);
			EFDLFNPAKGO.GBMJNFOEACC(OCOOIOGCOEE);
			EFDLFNPAKGO.GBMJNFOEACC(GHCBBJBDNPH);
			EFDLFNPAKGO.GBMJNFOEACC(MGLIOBDEJLF);
			EFDLFNPAKGO.GBMJNFOEACC(GFGOPIKFOAN);
			EFDLFNPAKGO.GBMJNFOEACC(IIICODNIMNN);
			EFDLFNPAKGO.GBMJNFOEACC(LOJEMAMKHFD);
			EFDLFNPAKGO.GBMJNFOEACC(ELDBGIKHAIO);
			EFDLFNPAKGO.GBMJNFOEACC(LNKFLFOGCCD);
			EFDLFNPAKGO.GBMJNFOEACC(FHJCBAOBGPG);
			EFDLFNPAKGO.GBMJNFOEACC(FBEBCNEPHJD);
			EFDLFNPAKGO.GBMJNFOEACC(PDAOIGGBLPH);
			EFDLFNPAKGO.GBMJNFOEACC(NLMHKBGDKLA);
			EFDLFNPAKGO.GBMJNFOEACC(JFLFAKNHKNP);
			EFDLFNPAKGO.GBMJNFOEACC(NEPGMKLCMFF);
		}

		public void OPCIPABEGME(PJEMPFEIOAK EFDLFNPAKGO)
		{
			FNGICPKNNGL = EFDLFNPAKGO.AJPFAAFLHEB();
			LBJMNDBMNAE = EFDLFNPAKGO.BMKOKHGAHEC();
			EPKGCHPIHEL = EFDLFNPAKGO.BMKOKHGAHEC();
			JKOEPLLJDKM = EFDLFNPAKGO.GCFOKBADLFB();
			BKOBAIPJAHP = EFDLFNPAKGO.GCFOKBADLFB();
			OCOOIOGCOEE = EFDLFNPAKGO.BMKOKHGAHEC();
			GHCBBJBDNPH = EFDLFNPAKGO.BMKOKHGAHEC();
			MGLIOBDEJLF = EFDLFNPAKGO.GCFOKBADLFB();
			GFGOPIKFOAN = EFDLFNPAKGO.GCFOKBADLFB();
			IIICODNIMNN = EFDLFNPAKGO.GCFOKBADLFB();
			LOJEMAMKHFD = EFDLFNPAKGO.GCFOKBADLFB();
			ELDBGIKHAIO = EFDLFNPAKGO.GCFOKBADLFB();
			LNKFLFOGCCD = EFDLFNPAKGO.GCFOKBADLFB();
			FHJCBAOBGPG = EFDLFNPAKGO.GCFOKBADLFB();
			FBEBCNEPHJD = EFDLFNPAKGO.GCFOKBADLFB();
			PDAOIGGBLPH = EFDLFNPAKGO.GCFOKBADLFB();
			NLMHKBGDKLA = EFDLFNPAKGO.GCFOKBADLFB();
			JFLFAKNHKNP = EFDLFNPAKGO.GCFOKBADLFB();
			NEPGMKLCMFF = EFDLFNPAKGO.GCFOKBADLFB();
		}

		public virtual int IMNEMDFAINP()
		{
			StringBuilder stringBuilder = new StringBuilder();
			stringBuilder.AppendFormat("{0:+0;-0}", FNGICPKNNGL);
			stringBuilder.AppendFormat("skill1_voice", LBJMNDBMNAE);
			stringBuilder.AppendFormat("skill0_drop", EPKGCHPIHEL);
			stringBuilder.AppendFormat("skill3_voice", JKOEPLLJDKM);
			stringBuilder.AppendFormat("item_frame_{0}", BKOBAIPJAHP);
			stringBuilder.AppendFormat("상급 공격력 문양", OCOOIOGCOEE);
			stringBuilder.AppendFormat(" (SoftClip)", GHCBBJBDNPH);
			stringBuilder.AppendFormat("UpdateAnchors", MGLIOBDEJLF);
			stringBuilder.AppendFormat("JSON Parse: Quotation marks seems to be messed up.", GFGOPIKFOAN);
			stringBuilder.AppendFormat("바론", IIICODNIMNN);
			stringBuilder.AppendFormat("Particle/Fizz/skill2_explosion_s", LOJEMAMKHFD);
			stringBuilder.AppendFormat("skill0_hit", ELDBGIKHAIO);
			stringBuilder.AppendFormat("JADBJGCMIMF", LNKFLFOGCCD);
			stringBuilder.AppendFormat("상급 공격속도 정수", FHJCBAOBGPG);
			stringBuilder.AppendFormat("Constitution increases health", FBEBCNEPHJD);
			stringBuilder.AppendFormat("마나", PDAOIGGBLPH);
			stringBuilder.AppendFormat("skill1_shot", NLMHKBGDKLA);
			stringBuilder.AppendFormat("ff3d7caf", JFLFAKNHKNP);
			stringBuilder.AppendFormat("UI/Lobby/RuneData", NEPGMKLCMFF);
			return stringBuilder.ToString().GetHashCode();
		}

		public virtual int JDCJNFCDIJM()
		{
			StringBuilder stringBuilder = new StringBuilder();
			stringBuilder.AppendFormat("attack", FNGICPKNNGL);
			stringBuilder.AppendFormat("Fix", LBJMNDBMNAE);
			stringBuilder.AppendFormat("ETC", EPKGCHPIHEL);
			stringBuilder.AppendFormat("f", JKOEPLLJDKM);
			stringBuilder.AppendFormat("상급 마나 재생 정수", BKOBAIPJAHP);
			stringBuilder.AppendFormat("Searching user", OCOOIOGCOEE);
			stringBuilder.AppendFormat("챌린저", GHCBBJBDNPH);
			stringBuilder.AppendFormat("run", MGLIOBDEJLF);
			stringBuilder.AppendFormat("masteryi_skill3", GFGOPIKFOAN);
			stringBuilder.AppendFormat("Reserved", IIICODNIMNN);
			stringBuilder.AppendFormat("CreateSkill1Missile", LOJEMAMKHFD);
			stringBuilder.AppendFormat("중급 주문흡혈 정수", ELDBGIKHAIO);
			stringBuilder.AppendFormat("대전상대를 찾는 중 (매칭확장)", LNKFLFOGCCD);
			stringBuilder.AppendFormat("FxmTestControls.m_nRotateIndex", FHJCBAOBGPG);
			stringBuilder.AppendFormat("Start", FBEBCNEPHJD);
			stringBuilder.AppendFormat("skill1_voice", PDAOIGGBLPH);
			stringBuilder.AppendFormat("Inverse X axis", NLMHKBGDKLA);
			stringBuilder.AppendFormat("피즈", JFLFAKNHKNP);
			stringBuilder.AppendFormat("skill2_1", NEPGMKLCMFF);
			return stringBuilder.ToString().GetHashCode();
		}

		public void AGEPBABDMDL(PJEMPFEIOAK EFDLFNPAKGO)
		{
			FNGICPKNNGL = EFDLFNPAKGO.AJPFAAFLHEB();
			LBJMNDBMNAE = EFDLFNPAKGO.BMKOKHGAHEC();
			EPKGCHPIHEL = EFDLFNPAKGO.BMKOKHGAHEC();
			JKOEPLLJDKM = EFDLFNPAKGO.GCFOKBADLFB();
			BKOBAIPJAHP = EFDLFNPAKGO.GCFOKBADLFB();
			OCOOIOGCOEE = EFDLFNPAKGO.BMKOKHGAHEC();
			GHCBBJBDNPH = EFDLFNPAKGO.BMKOKHGAHEC();
			MGLIOBDEJLF = EFDLFNPAKGO.GCFOKBADLFB();
			GFGOPIKFOAN = EFDLFNPAKGO.GCFOKBADLFB();
			IIICODNIMNN = EFDLFNPAKGO.GCFOKBADLFB();
			LOJEMAMKHFD = EFDLFNPAKGO.GCFOKBADLFB();
			ELDBGIKHAIO = EFDLFNPAKGO.GCFOKBADLFB();
			LNKFLFOGCCD = EFDLFNPAKGO.GCFOKBADLFB();
			FHJCBAOBGPG = EFDLFNPAKGO.GCFOKBADLFB();
			FBEBCNEPHJD = EFDLFNPAKGO.GCFOKBADLFB();
			PDAOIGGBLPH = EFDLFNPAKGO.GCFOKBADLFB();
			NLMHKBGDKLA = EFDLFNPAKGO.GCFOKBADLFB();
			JFLFAKNHKNP = EFDLFNPAKGO.GCFOKBADLFB();
			NEPGMKLCMFF = EFDLFNPAKGO.GCFOKBADLFB();
		}
	}
}
