using System;
using System.Collections.Generic;
using EveEngine;
using MongoDB.Bson.Serialization.Attributes;

namespace GameServer
{
	[JBFHBIFPIBM]
	public class OBILGKHFCHO : EOPOBHFNFPA
	{
		public uint ANCDOGMDMKC;

		public DateTime HBNDHMPNCME = DateTime.Now;

		public ulong PNIMJFCJLHM;

		public int EEFMONDACJN;

		public byte DDILAEMMCAJ;

		public int JFILMHHIFGI;

		public int NMGLFEEAMOA;

		public List<ushort> EOECENOCDOG = new List<ushort>();

		public List<int> LLANMMOBEIG = new List<int>();

		public void CPPAAILEDJO(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.BHAFGILIOCN(ANCDOGMDMKC);
			EFDLFNPAKGO.GBMJNFOEACC(PNIMJFCJLHM);
			EFDLFNPAKGO.GBMJNFOEACC(EEFMONDACJN);
			EFDLFNPAKGO.GBMJNFOEACC(DDILAEMMCAJ);
			EFDLFNPAKGO.GBMJNFOEACC(JFILMHHIFGI);
			EFDLFNPAKGO.GBMJNFOEACC(NMGLFEEAMOA);
			EFDLFNPAKGO.GBMJNFOEACC(EOECENOCDOG);
			EFDLFNPAKGO.GBMJNFOEACC(LLANMMOBEIG);
			EFDLFNPAKGO.GBMJNFOEACC(HBNDHMPNCME);
		}

		public void AHHKENDIBND(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.BHAFGILIOCN(ANCDOGMDMKC);
			EFDLFNPAKGO.GBMJNFOEACC(PNIMJFCJLHM);
			EFDLFNPAKGO.GBMJNFOEACC(EEFMONDACJN);
			EFDLFNPAKGO.GBMJNFOEACC(DDILAEMMCAJ);
			EFDLFNPAKGO.GBMJNFOEACC(JFILMHHIFGI);
			EFDLFNPAKGO.GBMJNFOEACC(NMGLFEEAMOA);
			EFDLFNPAKGO.GBMJNFOEACC(EOECENOCDOG);
			EFDLFNPAKGO.GBMJNFOEACC(LLANMMOBEIG);
			EFDLFNPAKGO.GBMJNFOEACC(HBNDHMPNCME);
		}

		public void LFBNEHNMHLL(PJEMPFEIOAK EFDLFNPAKGO)
		{
			EOECENOCDOG.Clear();
			LLANMMOBEIG.Clear();
			EFDLFNPAKGO.CAHACMKBJMI(ref ANCDOGMDMKC);
			EFDLFNPAKGO.CAHACMKBJMI(ref PNIMJFCJLHM);
			EFDLFNPAKGO.BNLCLGMMAPD(ref EEFMONDACJN);
			EFDLFNPAKGO.CAHACMKBJMI(ref DDILAEMMCAJ);
			EFDLFNPAKGO.CAHACMKBJMI(ref JFILMHHIFGI);
			EFDLFNPAKGO.BNLCLGMMAPD(ref NMGLFEEAMOA);
			EFDLFNPAKGO.CAHACMKBJMI(EOECENOCDOG);
			EFDLFNPAKGO.CAHACMKBJMI(LLANMMOBEIG);
			EFDLFNPAKGO.CAHACMKBJMI(ref HBNDHMPNCME);
		}

		public void MHBMBMMBCPK(PJEMPFEIOAK EFDLFNPAKGO)
		{
			EOECENOCDOG.Clear();
			LLANMMOBEIG.Clear();
			EFDLFNPAKGO.CAHACMKBJMI(ref ANCDOGMDMKC);
			EFDLFNPAKGO.CAHACMKBJMI(ref PNIMJFCJLHM);
			EFDLFNPAKGO.CAHACMKBJMI(ref EEFMONDACJN);
			EFDLFNPAKGO.CAHACMKBJMI(ref DDILAEMMCAJ);
			EFDLFNPAKGO.CAHACMKBJMI(ref JFILMHHIFGI);
			EFDLFNPAKGO.BNLCLGMMAPD(ref NMGLFEEAMOA);
			EFDLFNPAKGO.CAHACMKBJMI(EOECENOCDOG);
			EFDLFNPAKGO.CAHACMKBJMI(LLANMMOBEIG);
			EFDLFNPAKGO.CAHACMKBJMI(ref HBNDHMPNCME);
		}

		public void HHBODHGJBNM(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.BHAFGILIOCN(ANCDOGMDMKC);
			EFDLFNPAKGO.GBMJNFOEACC(PNIMJFCJLHM);
			EFDLFNPAKGO.GBMJNFOEACC(EEFMONDACJN);
			EFDLFNPAKGO.GBMJNFOEACC(DDILAEMMCAJ);
			EFDLFNPAKGO.GBMJNFOEACC(JFILMHHIFGI);
			EFDLFNPAKGO.GBMJNFOEACC(NMGLFEEAMOA);
			EFDLFNPAKGO.GBMJNFOEACC(EOECENOCDOG);
			EFDLFNPAKGO.GBMJNFOEACC(LLANMMOBEIG);
			EFDLFNPAKGO.GBMJNFOEACC(HBNDHMPNCME);
		}

		public void HOCIBNCFBLL(PJEMPFEIOAK EFDLFNPAKGO)
		{
			EOECENOCDOG.Clear();
			LLANMMOBEIG.Clear();
			EFDLFNPAKGO.CAHACMKBJMI(ref ANCDOGMDMKC);
			EFDLFNPAKGO.CAHACMKBJMI(ref PNIMJFCJLHM);
			EFDLFNPAKGO.CAHACMKBJMI(ref EEFMONDACJN);
			EFDLFNPAKGO.CAHACMKBJMI(ref DDILAEMMCAJ);
			EFDLFNPAKGO.BNLCLGMMAPD(ref JFILMHHIFGI);
			EFDLFNPAKGO.BNLCLGMMAPD(ref NMGLFEEAMOA);
			EFDLFNPAKGO.CAHACMKBJMI(EOECENOCDOG);
			EFDLFNPAKGO.ADLGHIAPFHL(LLANMMOBEIG);
			EFDLFNPAKGO.CAHACMKBJMI(ref HBNDHMPNCME);
		}

		public void CFGEKKHOKKE(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(ANCDOGMDMKC);
			EFDLFNPAKGO.GBMJNFOEACC(PNIMJFCJLHM);
			EFDLFNPAKGO.GBMJNFOEACC(EEFMONDACJN);
			EFDLFNPAKGO.GBMJNFOEACC(DDILAEMMCAJ);
			EFDLFNPAKGO.GBMJNFOEACC(JFILMHHIFGI);
			EFDLFNPAKGO.GBMJNFOEACC(NMGLFEEAMOA);
			EFDLFNPAKGO.GBMJNFOEACC(EOECENOCDOG);
			EFDLFNPAKGO.GBMJNFOEACC(LLANMMOBEIG);
			EFDLFNPAKGO.GBMJNFOEACC(HBNDHMPNCME);
		}

		public void OBLFBODBHHK(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.BHAFGILIOCN(ANCDOGMDMKC);
			EFDLFNPAKGO.GBMJNFOEACC(PNIMJFCJLHM);
			EFDLFNPAKGO.GBMJNFOEACC(EEFMONDACJN);
			EFDLFNPAKGO.GBMJNFOEACC(DDILAEMMCAJ);
			EFDLFNPAKGO.GBMJNFOEACC(JFILMHHIFGI);
			EFDLFNPAKGO.GBMJNFOEACC(NMGLFEEAMOA);
			EFDLFNPAKGO.GBMJNFOEACC(EOECENOCDOG);
			EFDLFNPAKGO.GBMJNFOEACC(LLANMMOBEIG);
			EFDLFNPAKGO.GBMJNFOEACC(HBNDHMPNCME);
		}

		public void JCOLMPJMMEB(PJEMPFEIOAK EFDLFNPAKGO)
		{
			EOECENOCDOG.Clear();
			LLANMMOBEIG.Clear();
			EFDLFNPAKGO.CAHACMKBJMI(ref ANCDOGMDMKC);
			EFDLFNPAKGO.CAHACMKBJMI(ref PNIMJFCJLHM);
			EFDLFNPAKGO.CAHACMKBJMI(ref EEFMONDACJN);
			EFDLFNPAKGO.CAHACMKBJMI(ref DDILAEMMCAJ);
			EFDLFNPAKGO.CAHACMKBJMI(ref JFILMHHIFGI);
			EFDLFNPAKGO.CAHACMKBJMI(ref NMGLFEEAMOA);
			EFDLFNPAKGO.CAHACMKBJMI(EOECENOCDOG);
			EFDLFNPAKGO.CAHACMKBJMI(LLANMMOBEIG);
			EFDLFNPAKGO.CAHACMKBJMI(ref HBNDHMPNCME);
		}

		public void GANHNFADIJO(PJEMPFEIOAK EFDLFNPAKGO)
		{
			EOECENOCDOG.Clear();
			LLANMMOBEIG.Clear();
			EFDLFNPAKGO.CAHACMKBJMI(ref ANCDOGMDMKC);
			EFDLFNPAKGO.CAHACMKBJMI(ref PNIMJFCJLHM);
			EFDLFNPAKGO.BNLCLGMMAPD(ref EEFMONDACJN);
			EFDLFNPAKGO.CAHACMKBJMI(ref DDILAEMMCAJ);
			EFDLFNPAKGO.BNLCLGMMAPD(ref JFILMHHIFGI);
			EFDLFNPAKGO.BNLCLGMMAPD(ref NMGLFEEAMOA);
			EFDLFNPAKGO.CAHACMKBJMI(EOECENOCDOG);
			EFDLFNPAKGO.ADLGHIAPFHL(LLANMMOBEIG);
			EFDLFNPAKGO.CAHACMKBJMI(ref HBNDHMPNCME);
		}

		public void MEKNGDKEKKO(PJEMPFEIOAK EFDLFNPAKGO)
		{
			EOECENOCDOG.Clear();
			LLANMMOBEIG.Clear();
			EFDLFNPAKGO.CAHACMKBJMI(ref ANCDOGMDMKC);
			EFDLFNPAKGO.CAHACMKBJMI(ref PNIMJFCJLHM);
			EFDLFNPAKGO.CAHACMKBJMI(ref EEFMONDACJN);
			EFDLFNPAKGO.CAHACMKBJMI(ref DDILAEMMCAJ);
			EFDLFNPAKGO.CAHACMKBJMI(ref JFILMHHIFGI);
			EFDLFNPAKGO.CAHACMKBJMI(ref NMGLFEEAMOA);
			EFDLFNPAKGO.CAHACMKBJMI(EOECENOCDOG);
			EFDLFNPAKGO.ADLGHIAPFHL(LLANMMOBEIG);
			EFDLFNPAKGO.CAHACMKBJMI(ref HBNDHMPNCME);
		}

		public void GPBOIHMMDDD(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.BHAFGILIOCN(ANCDOGMDMKC);
			EFDLFNPAKGO.GBMJNFOEACC(PNIMJFCJLHM);
			EFDLFNPAKGO.GBMJNFOEACC(EEFMONDACJN);
			EFDLFNPAKGO.GBMJNFOEACC(DDILAEMMCAJ);
			EFDLFNPAKGO.GBMJNFOEACC(JFILMHHIFGI);
			EFDLFNPAKGO.GBMJNFOEACC(NMGLFEEAMOA);
			EFDLFNPAKGO.GBMJNFOEACC(EOECENOCDOG);
			EFDLFNPAKGO.GBMJNFOEACC(LLANMMOBEIG);
			EFDLFNPAKGO.GBMJNFOEACC(HBNDHMPNCME);
		}

		public void NNELCJABFPA(CMNIABEFLBJ EFDLFNPAKGO)
		{
			EFDLFNPAKGO.GBMJNFOEACC(ANCDOGMDMKC);
			EFDLFNPAKGO.GBMJNFOEACC(PNIMJFCJLHM);
			EFDLFNPAKGO.GBMJNFOEACC(EEFMONDACJN);
			EFDLFNPAKGO.GBMJNFOEACC(DDILAEMMCAJ);
			EFDLFNPAKGO.GBMJNFOEACC(JFILMHHIFGI);
			EFDLFNPAKGO.GBMJNFOEACC(NMGLFEEAMOA);
			EFDLFNPAKGO.GBMJNFOEACC(EOECENOCDOG);
			EFDLFNPAKGO.GBMJNFOEACC(LLANMMOBEIG);
			EFDLFNPAKGO.GBMJNFOEACC(HBNDHMPNCME);
		}
	}
}
