using EveEngine;
using UnityEngine;

public static class EDKNDLOFNGI
{
	public static void GBMJNFOEACC(this CMNIABEFLBJ EFDLFNPAKGO, Vector3 IHHMNIJHLNJ)
	{
		EFDLFNPAKGO.GBMJNFOEACC(IHHMNIJHLNJ.x);
		EFDLFNPAKGO.GBMJNFOEACC(IHHMNIJHLNJ.y);
		EFDLFNPAKGO.GBMJNFOEACC(IHHMNIJHLNJ.z);
	}

	public static Vector3 MCGFBNKNFJG(this PJEMPFEIOAK EFDLFNPAKGO)
	{
		Vector3 zero = Vector3.zero;
		zero.x = EFDLFNPAKGO.GCFOKBADLFB();
		zero.y = EFDLFNPAKGO.GCFOKBADLFB();
		zero.z = EFDLFNPAKGO.GCFOKBADLFB();
		return zero;
	}

	public static void GBMJNFOEACC(this CMNIABEFLBJ EFDLFNPAKGO, Quaternion HHAPHKOJIMH)
	{
		EFDLFNPAKGO.GBMJNFOEACC(HHAPHKOJIMH.x);
		EFDLFNPAKGO.GBMJNFOEACC(HHAPHKOJIMH.y);
		EFDLFNPAKGO.GBMJNFOEACC(HHAPHKOJIMH.z);
		EFDLFNPAKGO.GBMJNFOEACC(HHAPHKOJIMH.w);
	}

	public static Quaternion HLOCKIKBGOM(this PJEMPFEIOAK EFDLFNPAKGO)
	{
		Quaternion identity = Quaternion.identity;
		identity.x = EFDLFNPAKGO.GCFOKBADLFB();
		identity.y = EFDLFNPAKGO.GCFOKBADLFB();
		identity.z = EFDLFNPAKGO.GCFOKBADLFB();
		identity.w = EFDLFNPAKGO.GCFOKBADLFB();
		return identity;
	}

	public static void GBMJNFOEACC(this CMNIABEFLBJ EFDLFNPAKGO, NMAHNGDIIEF OGJFDNEEDCP)
	{
		ushort iCENKPDOHBK = (ushort)OGJFDNEEDCP.EJGJCLHFIAM();
		EFDLFNPAKGO.GBMJNFOEACC(iCENKPDOHBK);
		EFDLFNPAKGO.GBMJNFOEACC(OGJFDNEEDCP.EIMBOIKCJPE(), 0, OGJFDNEEDCP.EJGJCLHFIAM());
	}

	public static NMAHNGDIIEF NLJFHHOHAKO(this PJEMPFEIOAK EFDLFNPAKGO)
	{
		ushort aGJJOHLCJKF = EFDLFNPAKGO.AJPFAAFLHEB();
		byte[] eDMNHDBEPMC = EFDLFNPAKGO.KNGHLHCACAA(aGJJOHLCJKF);
		NMAHNGDIIEF nMAHNGDIIEF = new NMAHNGDIIEF(false, null);
		nMAHNGDIIEF.HCBNCGILGEJ(eDMNHDBEPMC, 0, aGJJOHLCJKF);
		return nMAHNGDIIEF;
	}
}
