using EveEngine;

public static class FGECEHBAIOC
{
	public static StateMachine.OEOIIKMBGAG HHBKIAJOAEG(this KCIGFAHFHCH OGJFDNEEDCP)
	{
		return (StateMachine.OEOIIKMBGAG)OGJFDNEEDCP.KFAGPDGHEBK();
	}

	public static void CAHACMKBJMI(this KCIGFAHFHCH OGJFDNEEDCP, out StateMachine.OEOIIKMBGAG ICENKPDOHBK)
	{
		ICENKPDOHBK = (StateMachine.OEOIIKMBGAG)OGJFDNEEDCP.KFAGPDGHEBK();
	}

	public static void GBMJNFOEACC(this KCIGFAHFHCH OGJFDNEEDCP, StateMachine.OEOIIKMBGAG ICENKPDOHBK)
	{
		OGJFDNEEDCP.GBMJNFOEACC((byte)ICENKPDOHBK);
	}
}
