using System.Collections.Generic;
using System.Runtime.CompilerServices;
using EveEngine;

public class HHMAFEMLHEK : EOPOBHFNFPA
{
	public int PKKDIMODALC;

	private Dictionary<ushort, PKCGCIEPDEM> AKODBJEFPII;

	public Dictionary<ushort, PKCGCIEPDEM> JNCMJIPFHEM
	{
		get
		{
			return CHLIPBJKAIE();
		}
		protected set
		{
			FJFIMJLGILA(value);
		}
	}

	[SpecialName]
	protected void CHPIBALPNHB(Dictionary<ushort, PKCGCIEPDEM> ICENKPDOHBK)
	{
		AKODBJEFPII = ICENKPDOHBK;
	}

	protected void FJFIMJLGILA(Dictionary<ushort, PKCGCIEPDEM> ICENKPDOHBK)
	{
		AKODBJEFPII = ICENKPDOHBK;
	}

	public Dictionary<ushort, PKCGCIEPDEM> CHLIPBJKAIE()
	{
		return AKODBJEFPII;
	}

	public void PEFJOMFAOJI()
	{
		PKCGCIEPDEM pKCGCIEPDEM = new PKCGCIEPDEM(1001, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM.GAFNNDHJDAE = "도란의 검";
		pKCGCIEPDEM.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM.MGGCDFHFMKK = 450;
		pKCGCIEPDEM.NCBAGGNLLLK = 80;
		pKCGCIEPDEM.LHEKBMLAJMA = 8;
		pKCGCIEPDEM.PPNKFFAHHBB = 0.03f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM.EHFEEIJKJHD(), pKCGCIEPDEM);
		PKCGCIEPDEM pKCGCIEPDEM2 = new PKCGCIEPDEM(1002, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM2.GAFNNDHJDAE = "곡괭이";
		pKCGCIEPDEM2.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM2.MGGCDFHFMKK = 875;
		pKCGCIEPDEM2.LHEKBMLAJMA = 25;
		CHLIPBJKAIE().Add(pKCGCIEPDEM2.EHFEEIJKJHD(), pKCGCIEPDEM2);
		PKCGCIEPDEM pKCGCIEPDEM3 = new PKCGCIEPDEM(1003, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM3.GAFNNDHJDAE = "BF 대검";
		pKCGCIEPDEM3.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM3.MGGCDFHFMKK = 1300;
		pKCGCIEPDEM3.LHEKBMLAJMA = 40;
		CHLIPBJKAIE().Add(pKCGCIEPDEM3.EHFEEIJKJHD(), pKCGCIEPDEM3);
		PKCGCIEPDEM pKCGCIEPDEM4 = new PKCGCIEPDEM(1004, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM4.GAFNNDHJDAE = "단검";
		pKCGCIEPDEM4.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM4.MGGCDFHFMKK = 300;
		pKCGCIEPDEM4.NMFDEKCMJAH = 0.12f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM4.EHFEEIJKJHD(), pKCGCIEPDEM4);
		PKCGCIEPDEM pKCGCIEPDEM5 = new PKCGCIEPDEM(1005, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM5.GAFNNDHJDAE = "흡혈의 낫";
		pKCGCIEPDEM5.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM5.MGGCDFHFMKK = 900;
		pKCGCIEPDEM5.LHEKBMLAJMA = 15;
		pKCGCIEPDEM5.PPNKFFAHHBB = 0.1f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM5.EHFEEIJKJHD(), pKCGCIEPDEM5);
		PKCGCIEPDEM pKCGCIEPDEM6 = new PKCGCIEPDEM(1007, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM6.GAFNNDHJDAE = "열정의 검";
		pKCGCIEPDEM6.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM6.MGGCDFHFMKK = 1200;
		pKCGCIEPDEM6.CIGEEDBPDDM = true;
		pKCGCIEPDEM6.CJALIPCFCLA = 0.15f;
		pKCGCIEPDEM6.NMFDEKCMJAH = 0.15f;
		pKCGCIEPDEM6.NEPGMKLCMFF = 0.05f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM6.EHFEEIJKJHD(), pKCGCIEPDEM6);
		PKCGCIEPDEM pKCGCIEPDEM7 = new PKCGCIEPDEM(1008, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM7.GAFNNDHJDAE = "콜필드의 전투망치";
		pKCGCIEPDEM7.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM7.MGGCDFHFMKK = 1100;
		pKCGCIEPDEM7.LHEKBMLAJMA = 25;
		pKCGCIEPDEM7.BDKLLIMAGPP = 0.07f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM7.EHFEEIJKJHD(), pKCGCIEPDEM7);
		PKCGCIEPDEM pKCGCIEPDEM8 = new PKCGCIEPDEM(1009, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM8.GAFNNDHJDAE = "탐식의 망치";
		pKCGCIEPDEM8.IJAPPEMLBBN = "기본공격적중시 잠시동안 이동속도증가. 처치시 추가증가(원거리 챔피언은 절반)";
		pKCGCIEPDEM8.MGGCDFHFMKK = 1250;
		pKCGCIEPDEM8.NCBAGGNLLLK = 200;
		pKCGCIEPDEM8.LHEKBMLAJMA = 15;
		CHLIPBJKAIE().Add(pKCGCIEPDEM8.EHFEEIJKJHD(), pKCGCIEPDEM8);
		PKCGCIEPDEM pKCGCIEPDEM9 = new PKCGCIEPDEM(1010, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM9.GAFNNDHJDAE = "주문포식자";
		pKCGCIEPDEM9.IJAPPEMLBBN = "마법피해를 받아 체력이 30%이하가 되면, 마법피해 보호막생성";
		pKCGCIEPDEM9.MGGCDFHFMKK = 1300;
		pKCGCIEPDEM9.LHEKBMLAJMA = 20;
		pKCGCIEPDEM9.NLMHKBGDKLA = 35;
		pKCGCIEPDEM9.FILHECEKNMK = 90f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM9.EHFEEIJKJHD(), pKCGCIEPDEM9);
		PKCGCIEPDEM pKCGCIEPDEM10 = new PKCGCIEPDEM(1101, PKCGCIEPDEM.ACPICCBBPHF.Active, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM10.GAFNNDHJDAE = "몰락한 왕의 검";
		pKCGCIEPDEM10.IJAPPEMLBBN = "기본공격시 대상체력6%에 해당하는 추가물리피해. 사용시 적챔피언에게 마법피해 및 이동속도감소";
		pKCGCIEPDEM10.MGGCDFHFMKK = 3300;
		pKCGCIEPDEM10.CIGEEDBPDDM = true;
		pKCGCIEPDEM10.LHEKBMLAJMA = 40;
		pKCGCIEPDEM10.NMFDEKCMJAH = 0.3f;
		pKCGCIEPDEM10.PPNKFFAHHBB = 0.1f;
		pKCGCIEPDEM10.FILHECEKNMK = 90f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM10.EHFEEIJKJHD(), pKCGCIEPDEM10);
		PKCGCIEPDEM pKCGCIEPDEM11 = new PKCGCIEPDEM(1102, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM11.GAFNNDHJDAE = "무한의 검";
		pKCGCIEPDEM11.IJAPPEMLBBN = "치명타 추가피해량 25%증가";
		pKCGCIEPDEM11.MGGCDFHFMKK = 3400;
		pKCGCIEPDEM11.CIGEEDBPDDM = true;
		pKCGCIEPDEM11.LHEKBMLAJMA = 80;
		pKCGCIEPDEM11.CJALIPCFCLA = 0.25f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM11.EHFEEIJKJHD(), pKCGCIEPDEM11);
		PKCGCIEPDEM pKCGCIEPDEM12 = new PKCGCIEPDEM(1103, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM12.GAFNNDHJDAE = "피바라기";
		pKCGCIEPDEM12.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM12.MGGCDFHFMKK = 3200;
		pKCGCIEPDEM12.CIGEEDBPDDM = true;
		pKCGCIEPDEM12.LHEKBMLAJMA = 80;
		pKCGCIEPDEM12.PPNKFFAHHBB = 0.2f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM12.EHFEEIJKJHD(), pKCGCIEPDEM12);
		PKCGCIEPDEM pKCGCIEPDEM13 = new PKCGCIEPDEM(1104, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM13.GAFNNDHJDAE = "유령무희";
		pKCGCIEPDEM13.IJAPPEMLBBN = "적 챔피언에게 기본공격시 이속증가. 피해를 받아 체력이 30%이하가 되면, 보호막생성";
		pKCGCIEPDEM13.MGGCDFHFMKK = 2800;
		pKCGCIEPDEM13.CIGEEDBPDDM = true;
		pKCGCIEPDEM13.NMFDEKCMJAH = 0.4f;
		pKCGCIEPDEM13.CJALIPCFCLA = 0.25f;
		pKCGCIEPDEM13.NEPGMKLCMFF = 0.05f;
		pKCGCIEPDEM13.FILHECEKNMK = 90f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM13.EHFEEIJKJHD(), pKCGCIEPDEM13);
		PKCGCIEPDEM pKCGCIEPDEM14 = new PKCGCIEPDEM(1105, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM14.GAFNNDHJDAE = "도미닉경의 인사";
		pKCGCIEPDEM14.IJAPPEMLBBN = "방어력 관통력 35%";
		pKCGCIEPDEM14.MGGCDFHFMKK = 2800;
		pKCGCIEPDEM14.CIGEEDBPDDM = true;
		pKCGCIEPDEM14.LHEKBMLAJMA = 45;
		CHLIPBJKAIE().Add(pKCGCIEPDEM14.EHFEEIJKJHD(), pKCGCIEPDEM14);
		PKCGCIEPDEM pKCGCIEPDEM15 = new PKCGCIEPDEM(1106, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM15.GAFNNDHJDAE = "맬모셔스의 아귀";
		pKCGCIEPDEM15.IJAPPEMLBBN = "마법피해를 받아 체력이 30%이하가 되면, 마법피해 보호막생성";
		pKCGCIEPDEM15.MGGCDFHFMKK = 3100;
		pKCGCIEPDEM15.CIGEEDBPDDM = true;
		pKCGCIEPDEM15.LHEKBMLAJMA = 50;
		pKCGCIEPDEM15.NLMHKBGDKLA = 50;
		pKCGCIEPDEM15.BDKLLIMAGPP = 0.1f;
		pKCGCIEPDEM15.FILHECEKNMK = 90f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM15.EHFEEIJKJHD(), pKCGCIEPDEM15);
		PKCGCIEPDEM pKCGCIEPDEM16 = new PKCGCIEPDEM(1107, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM16.GAFNNDHJDAE = "칠흑의 양날도끼";
		pKCGCIEPDEM16.IJAPPEMLBBN = "물리피해를 입히면, 적의 방어력을 감소(누적됨) 및 자신의 이동속도 증가(원거리 챔피언은 절반). 처치시 이동속도 추가증가";
		pKCGCIEPDEM16.MGGCDFHFMKK = 3000;
		pKCGCIEPDEM16.CIGEEDBPDDM = true;
		pKCGCIEPDEM16.LHEKBMLAJMA = 40;
		pKCGCIEPDEM16.NCBAGGNLLLK = 300;
		pKCGCIEPDEM16.BDKLLIMAGPP = 0.2f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM16.EHFEEIJKJHD(), pKCGCIEPDEM16);
		PKCGCIEPDEM pKCGCIEPDEM17 = new PKCGCIEPDEM(1108, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM17.GAFNNDHJDAE = "필멸자의 운명";
		pKCGCIEPDEM17.IJAPPEMLBBN = "방어력 25%관통. 적 챔피언에게 물리피해를 입히면 고통스러운 상처를 남김";
		pKCGCIEPDEM17.MGGCDFHFMKK = 2800;
		pKCGCIEPDEM17.CIGEEDBPDDM = true;
		pKCGCIEPDEM17.LHEKBMLAJMA = 45;
		CHLIPBJKAIE().Add(pKCGCIEPDEM17.EHFEEIJKJHD(), pKCGCIEPDEM17);
		PKCGCIEPDEM pKCGCIEPDEM18 = new PKCGCIEPDEM(1109, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM18.GAFNNDHJDAE = "스태틱의 단검";
		pKCGCIEPDEM18.IJAPPEMLBBN = "이동하거나 기본공격시 충전이 되며, 완전충전상태로 공격시 7명에게 연쇄적으로 추가마법피해를 입힘";
		pKCGCIEPDEM18.MGGCDFHFMKK = 2600;
		pKCGCIEPDEM18.CIGEEDBPDDM = true;
		pKCGCIEPDEM18.NMFDEKCMJAH = 0.4f;
		pKCGCIEPDEM18.CJALIPCFCLA = 0.25f;
		pKCGCIEPDEM18.NEPGMKLCMFF = 0.03f;
		pKCGCIEPDEM18.AMENIOICKGM = 100f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM18.EHFEEIJKJHD(), pKCGCIEPDEM18);
		PKCGCIEPDEM pKCGCIEPDEM19 = new PKCGCIEPDEM(3001, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM19.GAFNNDHJDAE = "도란의 링";
		pKCGCIEPDEM19.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM19.MGGCDFHFMKK = 400;
		pKCGCIEPDEM19.NCBAGGNLLLK = 60;
		pKCGCIEPDEM19.KBMBFHHNDPE = 15;
		pKCGCIEPDEM19.MGLIOBDEJLF = 3;
		pKCGCIEPDEM19.MOHEOOEFLNK = 0.03f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM19.EHFEEIJKJHD(), pKCGCIEPDEM19);
		PKCGCIEPDEM pKCGCIEPDEM20 = new PKCGCIEPDEM(3002, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM20.GAFNNDHJDAE = "방출의 마법봉";
		pKCGCIEPDEM20.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM20.MGGCDFHFMKK = 850;
		pKCGCIEPDEM20.KBMBFHHNDPE = 40;
		CHLIPBJKAIE().Add(pKCGCIEPDEM20.EHFEEIJKJHD(), pKCGCIEPDEM20);
		PKCGCIEPDEM pKCGCIEPDEM21 = new PKCGCIEPDEM(3003, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM21.GAFNNDHJDAE = "쓸데없이 큰 지팡이";
		pKCGCIEPDEM21.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM21.MGGCDFHFMKK = 1250;
		pKCGCIEPDEM21.KBMBFHHNDPE = 60;
		CHLIPBJKAIE().Add(pKCGCIEPDEM21.EHFEEIJKJHD(), pKCGCIEPDEM21);
		PKCGCIEPDEM pKCGCIEPDEM22 = new PKCGCIEPDEM(3004, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM22.GAFNNDHJDAE = "여신의 눈물";
		pKCGCIEPDEM22.IJAPPEMLBBN = "마나를 소모하면 소모량의 10%롤 돌려받음";
		pKCGCIEPDEM22.MGGCDFHFMKK = 850;
		pKCGCIEPDEM22.BELPBCDOPBA = 300;
		CHLIPBJKAIE().Add(pKCGCIEPDEM22.EHFEEIJKJHD(), pKCGCIEPDEM22);
		PKCGCIEPDEM pKCGCIEPDEM23 = new PKCGCIEPDEM(3005, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM23.GAFNNDHJDAE = "악마의 마법서";
		pKCGCIEPDEM23.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM23.MGGCDFHFMKK = 900;
		pKCGCIEPDEM23.KBMBFHHNDPE = 35;
		pKCGCIEPDEM23.BDKLLIMAGPP = 0.1f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM23.EHFEEIJKJHD(), pKCGCIEPDEM23);
		PKCGCIEPDEM pKCGCIEPDEM24 = new PKCGCIEPDEM(3006, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM24.GAFNNDHJDAE = "마법공학 리볼버";
		pKCGCIEPDEM24.IJAPPEMLBBN = "적 챔피언에게 기본공격을 하면 추가마법피해를 입힘";
		pKCGCIEPDEM24.MGGCDFHFMKK = 1050;
		pKCGCIEPDEM24.KBMBFHHNDPE = 40;
		pKCGCIEPDEM24.FILHECEKNMK = 40f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM24.EHFEEIJKJHD(), pKCGCIEPDEM24);
		PKCGCIEPDEM pKCGCIEPDEM25 = new PKCGCIEPDEM(3007, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM25.GAFNNDHJDAE = "기괴한 가면";
		pKCGCIEPDEM25.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM25.MGGCDFHFMKK = 1500;
		pKCGCIEPDEM25.KBMBFHHNDPE = 35;
		pKCGCIEPDEM25.NCBAGGNLLLK = 200;
		pKCGCIEPDEM25.LAAGBIKMHAE = 15;
		CHLIPBJKAIE().Add(pKCGCIEPDEM25.EHFEEIJKJHD(), pKCGCIEPDEM25);
		PKCGCIEPDEM pKCGCIEPDEM26 = new PKCGCIEPDEM(3008, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM26.GAFNNDHJDAE = "메자이의 영혼약탈자";
		pKCGCIEPDEM26.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM26.MGGCDFHFMKK = 1400;
		pKCGCIEPDEM26.KBMBFHHNDPE = 40;
		pKCGCIEPDEM26.BELPBCDOPBA = 200;
		pKCGCIEPDEM26.NEPGMKLCMFF = 0.05f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM26.EHFEEIJKJHD(), pKCGCIEPDEM26);
		PKCGCIEPDEM pKCGCIEPDEM27 = new PKCGCIEPDEM(3101, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM27.GAFNNDHJDAE = "아테나의 부정한 성배";
		pKCGCIEPDEM27.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM27.MGGCDFHFMKK = 2100;
		pKCGCIEPDEM27.CIGEEDBPDDM = true;
		pKCGCIEPDEM27.KBMBFHHNDPE = 60;
		pKCGCIEPDEM27.NLMHKBGDKLA = 30;
		pKCGCIEPDEM27.HFGCMLGPJAO = 0.5f;
		pKCGCIEPDEM27.BDKLLIMAGPP = 0.2f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM27.EHFEEIJKJHD(), pKCGCIEPDEM27);
		PKCGCIEPDEM pKCGCIEPDEM28 = new PKCGCIEPDEM(3102, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM28.GAFNNDHJDAE = "라바돈의 죽음모자";
		pKCGCIEPDEM28.IJAPPEMLBBN = "주문력 40% 증가";
		pKCGCIEPDEM28.MGGCDFHFMKK = 3600;
		pKCGCIEPDEM28.CIGEEDBPDDM = true;
		pKCGCIEPDEM28.KBMBFHHNDPE = 120;
		CHLIPBJKAIE().Add(pKCGCIEPDEM28.EHFEEIJKJHD(), pKCGCIEPDEM28);
		PKCGCIEPDEM pKCGCIEPDEM29 = new PKCGCIEPDEM(3103, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM29.GAFNNDHJDAE = "모렐로노미콘";
		pKCGCIEPDEM29.IJAPPEMLBBN = "적 챔피언에게 마법피해를 입히면 고통스러운 상처를 남김";
		pKCGCIEPDEM29.MGGCDFHFMKK = 2900;
		pKCGCIEPDEM29.CIGEEDBPDDM = true;
		pKCGCIEPDEM29.KBMBFHHNDPE = 70;
		pKCGCIEPDEM29.BELPBCDOPBA = 300;
		pKCGCIEPDEM29.LAAGBIKMHAE = 15;
		pKCGCIEPDEM29.BDKLLIMAGPP = 0.1f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM29.EHFEEIJKJHD(), pKCGCIEPDEM29);
		PKCGCIEPDEM pKCGCIEPDEM30 = new PKCGCIEPDEM(3104, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM30.GAFNNDHJDAE = "고대인의 의지";
		pKCGCIEPDEM30.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM30.MGGCDFHFMKK = 2300;
		pKCGCIEPDEM30.CIGEEDBPDDM = true;
		pKCGCIEPDEM30.KBMBFHHNDPE = 80;
		pKCGCIEPDEM30.MOHEOOEFLNK = 0.1f;
		pKCGCIEPDEM30.BDKLLIMAGPP = 0.1f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM30.EHFEEIJKJHD(), pKCGCIEPDEM30);
		PKCGCIEPDEM pKCGCIEPDEM31 = new PKCGCIEPDEM(3105, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM31.GAFNNDHJDAE = "내셔의 이빨";
		pKCGCIEPDEM31.IJAPPEMLBBN = "기본공격시 15 + 주문력의 15%에 해당하는 마법피해";
		pKCGCIEPDEM31.MGGCDFHFMKK = 3000;
		pKCGCIEPDEM31.CIGEEDBPDDM = true;
		pKCGCIEPDEM31.KBMBFHHNDPE = 80;
		pKCGCIEPDEM31.NMFDEKCMJAH = 0.5f;
		pKCGCIEPDEM31.BDKLLIMAGPP = 0.2f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM31.EHFEEIJKJHD(), pKCGCIEPDEM31);
		PKCGCIEPDEM pKCGCIEPDEM32 = new PKCGCIEPDEM(3106, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM32.GAFNNDHJDAE = "공허의 지팡이";
		pKCGCIEPDEM32.IJAPPEMLBBN = "마법 관통력 40%";
		pKCGCIEPDEM32.MGGCDFHFMKK = 2650;
		pKCGCIEPDEM32.CIGEEDBPDDM = true;
		pKCGCIEPDEM32.KBMBFHHNDPE = 70;
		pKCGCIEPDEM32.MOHEOOEFLNK = 0.1f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM32.EHFEEIJKJHD(), pKCGCIEPDEM32);
		PKCGCIEPDEM pKCGCIEPDEM33 = new PKCGCIEPDEM(3107, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM33.GAFNNDHJDAE = "라일라이의 수정홀";
		pKCGCIEPDEM33.IJAPPEMLBBN = "스킬로 피해를 입히면 대상 이동속도 감소";
		pKCGCIEPDEM33.MGGCDFHFMKK = 2600;
		pKCGCIEPDEM33.CIGEEDBPDDM = true;
		pKCGCIEPDEM33.KBMBFHHNDPE = 90;
		pKCGCIEPDEM33.NCBAGGNLLLK = 300;
		CHLIPBJKAIE().Add(pKCGCIEPDEM33.EHFEEIJKJHD(), pKCGCIEPDEM33);
		PKCGCIEPDEM pKCGCIEPDEM34 = new PKCGCIEPDEM(3108, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM34.GAFNNDHJDAE = "리안드리의 고통";
		pKCGCIEPDEM34.IJAPPEMLBBN = "스킬공격에 맞은 적에게 3초에 걸쳐 매초 현재 체력의 2% 추가마법피해. 이동방해효과에게 두배";
		pKCGCIEPDEM34.MGGCDFHFMKK = 3100;
		pKCGCIEPDEM34.CIGEEDBPDDM = true;
		pKCGCIEPDEM34.KBMBFHHNDPE = 75;
		pKCGCIEPDEM34.LAAGBIKMHAE = 15;
		pKCGCIEPDEM34.NCBAGGNLLLK = 300;
		CHLIPBJKAIE().Add(pKCGCIEPDEM34.EHFEEIJKJHD(), pKCGCIEPDEM34);
		PKCGCIEPDEM pKCGCIEPDEM35 = new PKCGCIEPDEM(3109, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM35.GAFNNDHJDAE = "대천사의 지팡이";
		pKCGCIEPDEM35.IJAPPEMLBBN = "최대마나의 3%에 해당하는 주문력 추가. 마나를 소모하면 25%를 돌려받음";
		pKCGCIEPDEM35.MGGCDFHFMKK = 3200;
		pKCGCIEPDEM35.CIGEEDBPDDM = true;
		pKCGCIEPDEM35.KBMBFHHNDPE = 50;
		pKCGCIEPDEM35.BELPBCDOPBA = 1000;
		pKCGCIEPDEM35.BDKLLIMAGPP = 0.2f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM35.EHFEEIJKJHD(), pKCGCIEPDEM35);
		PKCGCIEPDEM pKCGCIEPDEM36 = new PKCGCIEPDEM(3110, PKCGCIEPDEM.ACPICCBBPHF.Active, PKCGCIEPDEM.FPOALJHHNEK.MagAttack);
		pKCGCIEPDEM36.GAFNNDHJDAE = "존야의 모래시계";
		pKCGCIEPDEM36.IJAPPEMLBBN = "사용시 피해 보호막 생성";
		pKCGCIEPDEM36.MGGCDFHFMKK = 3000;
		pKCGCIEPDEM36.CIGEEDBPDDM = true;
		pKCGCIEPDEM36.KBMBFHHNDPE = 75;
		pKCGCIEPDEM36.FBEBCNEPHJD = 40;
		pKCGCIEPDEM36.BDKLLIMAGPP = 0.1f;
		pKCGCIEPDEM36.FILHECEKNMK = 90f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM36.EHFEEIJKJHD(), pKCGCIEPDEM36);
		PKCGCIEPDEM pKCGCIEPDEM37 = new PKCGCIEPDEM(6001, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Defence);
		pKCGCIEPDEM37.GAFNNDHJDAE = "도란의 방패";
		pKCGCIEPDEM37.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM37.MGGCDFHFMKK = 450;
		pKCGCIEPDEM37.NCBAGGNLLLK = 80;
		pKCGCIEPDEM37.JKOEPLLJDKM = 7;
		CHLIPBJKAIE().Add(pKCGCIEPDEM37.EHFEEIJKJHD(), pKCGCIEPDEM37);
		PKCGCIEPDEM pKCGCIEPDEM38 = new PKCGCIEPDEM(6002, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Defence);
		pKCGCIEPDEM38.GAFNNDHJDAE = "루비 수정";
		pKCGCIEPDEM38.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM38.MGGCDFHFMKK = 400;
		pKCGCIEPDEM38.NCBAGGNLLLK = 150;
		CHLIPBJKAIE().Add(pKCGCIEPDEM38.EHFEEIJKJHD(), pKCGCIEPDEM38);
		PKCGCIEPDEM pKCGCIEPDEM39 = new PKCGCIEPDEM(6003, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Defence);
		pKCGCIEPDEM39.GAFNNDHJDAE = "점화석";
		pKCGCIEPDEM39.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM39.MGGCDFHFMKK = 850;
		pKCGCIEPDEM39.NCBAGGNLLLK = 200;
		pKCGCIEPDEM39.BDKLLIMAGPP = 0.1f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM39.EHFEEIJKJHD(), pKCGCIEPDEM39);
		PKCGCIEPDEM pKCGCIEPDEM40 = new PKCGCIEPDEM(6004, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Defence);
		pKCGCIEPDEM40.GAFNNDHJDAE = "거인의 허리띠";
		pKCGCIEPDEM40.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM40.MGGCDFHFMKK = 1000;
		pKCGCIEPDEM40.NCBAGGNLLLK = 380;
		CHLIPBJKAIE().Add(pKCGCIEPDEM40.EHFEEIJKJHD(), pKCGCIEPDEM40);
		PKCGCIEPDEM pKCGCIEPDEM41 = new PKCGCIEPDEM(6011, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Defence);
		pKCGCIEPDEM41.GAFNNDHJDAE = "천 갑옷";
		pKCGCIEPDEM41.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM41.MGGCDFHFMKK = 300;
		pKCGCIEPDEM41.FBEBCNEPHJD = 15;
		CHLIPBJKAIE().Add(pKCGCIEPDEM41.EHFEEIJKJHD(), pKCGCIEPDEM41);
		PKCGCIEPDEM pKCGCIEPDEM42 = new PKCGCIEPDEM(6012, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Defence);
		pKCGCIEPDEM42.GAFNNDHJDAE = "쇠사슬 조끼";
		pKCGCIEPDEM42.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM42.MGGCDFHFMKK = 800;
		pKCGCIEPDEM42.FBEBCNEPHJD = 40;
		CHLIPBJKAIE().Add(pKCGCIEPDEM42.EHFEEIJKJHD(), pKCGCIEPDEM42);
		PKCGCIEPDEM pKCGCIEPDEM43 = new PKCGCIEPDEM(6013, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Defence);
		pKCGCIEPDEM43.GAFNNDHJDAE = "빙하의 장막";
		pKCGCIEPDEM43.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM43.MGGCDFHFMKK = 900;
		pKCGCIEPDEM43.FBEBCNEPHJD = 20;
		pKCGCIEPDEM43.BELPBCDOPBA = 250;
		pKCGCIEPDEM43.BDKLLIMAGPP = 0.1f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM43.EHFEEIJKJHD(), pKCGCIEPDEM43);
		PKCGCIEPDEM pKCGCIEPDEM44 = new PKCGCIEPDEM(6014, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Defence);
		pKCGCIEPDEM44.GAFNNDHJDAE = "파수꾼의 갑옷";
		pKCGCIEPDEM44.IJAPPEMLBBN = "기본공격에 맞으면 공격한 챔피언의 공격속도 감소";
		pKCGCIEPDEM44.MGGCDFHFMKK = 1000;
		pKCGCIEPDEM44.FBEBCNEPHJD = 40;
		CHLIPBJKAIE().Add(pKCGCIEPDEM44.EHFEEIJKJHD(), pKCGCIEPDEM44);
		PKCGCIEPDEM pKCGCIEPDEM45 = new PKCGCIEPDEM(6015, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Defence);
		pKCGCIEPDEM45.GAFNNDHJDAE = "군단의 방패";
		pKCGCIEPDEM45.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM45.MGGCDFHFMKK = 1100;
		pKCGCIEPDEM45.FBEBCNEPHJD = 30;
		pKCGCIEPDEM45.NLMHKBGDKLA = 30;
		CHLIPBJKAIE().Add(pKCGCIEPDEM45.EHFEEIJKJHD(), pKCGCIEPDEM45);
		PKCGCIEPDEM pKCGCIEPDEM46 = new PKCGCIEPDEM(6021, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Defence);
		pKCGCIEPDEM46.GAFNNDHJDAE = "마법무효화의 망토";
		pKCGCIEPDEM46.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM46.MGGCDFHFMKK = 450;
		pKCGCIEPDEM46.NLMHKBGDKLA = 25;
		CHLIPBJKAIE().Add(pKCGCIEPDEM46.EHFEEIJKJHD(), pKCGCIEPDEM46);
		PKCGCIEPDEM pKCGCIEPDEM47 = new PKCGCIEPDEM(6022, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Defence);
		pKCGCIEPDEM47.GAFNNDHJDAE = "음전자 망토";
		pKCGCIEPDEM47.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM47.MGGCDFHFMKK = 720;
		pKCGCIEPDEM47.NLMHKBGDKLA = 40;
		CHLIPBJKAIE().Add(pKCGCIEPDEM47.EHFEEIJKJHD(), pKCGCIEPDEM47);
		PKCGCIEPDEM pKCGCIEPDEM48 = new PKCGCIEPDEM(6101, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Defence);
		pKCGCIEPDEM48.GAFNNDHJDAE = "워모그의 갑옷";
		pKCGCIEPDEM48.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM48.MGGCDFHFMKK = 2850;
		pKCGCIEPDEM48.CIGEEDBPDDM = true;
		pKCGCIEPDEM48.NCBAGGNLLLK = 800;
		pKCGCIEPDEM48.JKOEPLLJDKM = 25;
		pKCGCIEPDEM48.BDKLLIMAGPP = 0.1f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM48.EHFEEIJKJHD(), pKCGCIEPDEM48);
		PKCGCIEPDEM pKCGCIEPDEM49 = new PKCGCIEPDEM(6102, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Defence);
		pKCGCIEPDEM49.GAFNNDHJDAE = "정령의 형상";
		pKCGCIEPDEM49.IJAPPEMLBBN = "모든 치유 효과가 20% 증가";
		pKCGCIEPDEM49.MGGCDFHFMKK = 2800;
		pKCGCIEPDEM49.CIGEEDBPDDM = true;
		pKCGCIEPDEM49.NLMHKBGDKLA = 55;
		pKCGCIEPDEM49.NCBAGGNLLLK = 450;
		pKCGCIEPDEM49.ELOOOLLHHID = 1f;
		pKCGCIEPDEM49.BDKLLIMAGPP = 0.1f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM49.EHFEEIJKJHD(), pKCGCIEPDEM49);
		PKCGCIEPDEM pKCGCIEPDEM50 = new PKCGCIEPDEM(6103, PKCGCIEPDEM.ACPICCBBPHF.Active, PKCGCIEPDEM.FPOALJHHNEK.Defence);
		pKCGCIEPDEM50.GAFNNDHJDAE = "란두인의 예언";
		pKCGCIEPDEM50.IJAPPEMLBBN = "기본공격에 맞으면,공격한 챔프는 1초간 공격속도 15%감소. 사용시 적유닛의 이동속도 둔화";
		pKCGCIEPDEM50.MGGCDFHFMKK = 2900;
		pKCGCIEPDEM50.CIGEEDBPDDM = true;
		pKCGCIEPDEM50.FBEBCNEPHJD = 70;
		pKCGCIEPDEM50.NCBAGGNLLLK = 400;
		pKCGCIEPDEM50.FILHECEKNMK = 60f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM50.EHFEEIJKJHD(), pKCGCIEPDEM50);
		PKCGCIEPDEM pKCGCIEPDEM51 = new PKCGCIEPDEM(6104, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Defence);
		pKCGCIEPDEM51.GAFNNDHJDAE = "망자의 갑옷";
		pKCGCIEPDEM51.IJAPPEMLBBN = string.Empty;
		pKCGCIEPDEM51.MGGCDFHFMKK = 2750;
		pKCGCIEPDEM51.CIGEEDBPDDM = true;
		pKCGCIEPDEM51.FBEBCNEPHJD = 50;
		pKCGCIEPDEM51.NCBAGGNLLLK = 600;
		pKCGCIEPDEM51.NEPGMKLCMFF = 0.05f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM51.EHFEEIJKJHD(), pKCGCIEPDEM51);
		PKCGCIEPDEM pKCGCIEPDEM52 = new PKCGCIEPDEM(6105, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Defence);
		pKCGCIEPDEM52.GAFNNDHJDAE = "가시 갑옷";
		pKCGCIEPDEM52.IJAPPEMLBBN = "기본공격을 받으면 적 챔피언에게 체력대비 마법피해 및 고통스러운 상처를 되돌려줌";
		pKCGCIEPDEM52.MGGCDFHFMKK = 2900;
		pKCGCIEPDEM52.CIGEEDBPDDM = true;
		pKCGCIEPDEM52.FBEBCNEPHJD = 100;
		pKCGCIEPDEM52.NCBAGGNLLLK = 250;
		CHLIPBJKAIE().Add(pKCGCIEPDEM52.EHFEEIJKJHD(), pKCGCIEPDEM52);
		PKCGCIEPDEM pKCGCIEPDEM53 = new PKCGCIEPDEM(7001, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Etc);
		pKCGCIEPDEM53.GAFNNDHJDAE = "삼위일체";
		pKCGCIEPDEM53.IJAPPEMLBBN = "기본공격적중시 잠시동안 이동속도증가. 처치시 추가증가(원거리 챔피언은 절반)";
		pKCGCIEPDEM53.MGGCDFHFMKK = 3600;
		pKCGCIEPDEM53.CIGEEDBPDDM = true;
		pKCGCIEPDEM53.LHEKBMLAJMA = 30;
		pKCGCIEPDEM53.KBMBFHHNDPE = 30;
		pKCGCIEPDEM53.NMFDEKCMJAH = 0.3f;
		pKCGCIEPDEM53.BDKLLIMAGPP = 0.2f;
		pKCGCIEPDEM53.NCBAGGNLLLK = 250;
		pKCGCIEPDEM53.BELPBCDOPBA = 250;
		pKCGCIEPDEM53.NEPGMKLCMFF = 0.08f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM53.EHFEEIJKJHD(), pKCGCIEPDEM53);
		PKCGCIEPDEM pKCGCIEPDEM54 = new PKCGCIEPDEM(8001, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.PhyAttack);
		pKCGCIEPDEM54.GAFNNDHJDAE = "사냥꾼의 마체테";
		pKCGCIEPDEM54.IJAPPEMLBBN = "몬스터 공격시 35추가피해 및 생명력흡수";
		pKCGCIEPDEM54.MGGCDFHFMKK = 350;
		pKCGCIEPDEM54.CIGEEDBPDDM = true;
		CHLIPBJKAIE().Add(pKCGCIEPDEM54.EHFEEIJKJHD(), pKCGCIEPDEM54);
		PKCGCIEPDEM pKCGCIEPDEM55 = new PKCGCIEPDEM(8011, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Etc);
		pKCGCIEPDEM55.GAFNNDHJDAE = "고대 주화";
		pKCGCIEPDEM55.IJAPPEMLBBN = "주변에서 내가 최후의 일격을 가하지 않은 미니언이 쓰러지면 4골드와 체력5를 얻습니다";
		pKCGCIEPDEM55.MGGCDFHFMKK = 365;
		pKCGCIEPDEM55.CIGEEDBPDDM = true;
		CHLIPBJKAIE().Add(pKCGCIEPDEM55.EHFEEIJKJHD(), pKCGCIEPDEM55);
		PKCGCIEPDEM pKCGCIEPDEM56 = new PKCGCIEPDEM(8012, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Etc);
		pKCGCIEPDEM56.GAFNNDHJDAE = "유목민의 메달";
		pKCGCIEPDEM56.IJAPPEMLBBN = "주변에서 내가 최후의 일격을 가하지 않은 미니언이 쓰러지면 8골드와 체력10을 얻습니다";
		pKCGCIEPDEM56.MGGCDFHFMKK = 865;
		pKCGCIEPDEM56.CIGEEDBPDDM = true;
		pKCGCIEPDEM56.ELOOOLLHHID = 0.5f;
		pKCGCIEPDEM56.HFGCMLGPJAO = 0.5f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM56.EHFEEIJKJHD(), pKCGCIEPDEM56);
		PKCGCIEPDEM pKCGCIEPDEM57 = new PKCGCIEPDEM(8013, PKCGCIEPDEM.ACPICCBBPHF.Equip, PKCGCIEPDEM.FPOALJHHNEK.Etc);
		pKCGCIEPDEM57.GAFNNDHJDAE = "오아시스의 눈";
		pKCGCIEPDEM57.IJAPPEMLBBN = "주변에서 내가 최후의 일격을 가하지 않은 미니언이 쓰러지면 9골드와 체력10을 얻습니다";
		pKCGCIEPDEM57.MGGCDFHFMKK = 2200;
		pKCGCIEPDEM57.CIGEEDBPDDM = true;
		pKCGCIEPDEM57.NCBAGGNLLLK = 200;
		pKCGCIEPDEM57.ELOOOLLHHID = 1.5f;
		pKCGCIEPDEM57.HFGCMLGPJAO = 1.5f;
		pKCGCIEPDEM57.NEPGMKLCMFF = 0.05f;
		CHLIPBJKAIE().Add(pKCGCIEPDEM57.EHFEEIJKJHD(), pKCGCIEPDEM57);
		PKCGCIEPDEM pKCGCIEPDEM58 = new PKCGCIEPDEM(9001, PKCGCIEPDEM.ACPICCBBPHF.Consume, PKCGCIEPDEM.FPOALJHHNEK.Etc);
		pKCGCIEPDEM58.GAFNNDHJDAE = "체력 물약";
		pKCGCIEPDEM58.IJAPPEMLBBN = "15초에 걸쳐 체력을 회복 (최대 5개 소지가능)";
		pKCGCIEPDEM58.MGGCDFHFMKK = 50;
		pKCGCIEPDEM58.OMPBNLBKLIM = 5;
		pKCGCIEPDEM58.FILHECEKNMK = 15f;
		pKCGCIEPDEM58.CIGEEDBPDDM = true;
		CHLIPBJKAIE().Add(pKCGCIEPDEM58.EHFEEIJKJHD(), pKCGCIEPDEM58);
		PKKDIMODALC = GetHashCode();
	}

	public bool AMBOPDLLCCP()
	{
		if (PKKDIMODALC == GetHashCode())
		{
			return true;
		}
		return false;
	}

	public void JCOLMPJMMEB(PJEMPFEIOAK EFDLFNPAKGO)
	{
		ushort num = EFDLFNPAKGO.AJPFAAFLHEB();
		for (short num2 = 0; num2 < num; num2++)
		{
			ushort key = EFDLFNPAKGO.AJPFAAFLHEB();
			if (CHLIPBJKAIE().ContainsKey(key))
			{
				CHLIPBJKAIE()[key].JCOLMPJMMEB(EFDLFNPAKGO);
			}
			else
			{
				PKCGCIEPDEM pKCGCIEPDEM = new PKCGCIEPDEM();
				pKCGCIEPDEM.JCOLMPJMMEB(EFDLFNPAKGO);
			}
		}
		PKKDIMODALC = EFDLFNPAKGO.PNBKOPGIHDI();
	}

	[SpecialName]
	public Dictionary<ushort, PKCGCIEPDEM> BCPFNFDDDFC()
	{
		return AKODBJEFPII;
	}

	public override int GetHashCode()
	{
		int num = 0;
		foreach (KeyValuePair<ushort, PKCGCIEPDEM> item in CHLIPBJKAIE())
		{
			num ^= item.Value.GetHashCode();
		}
		return num;
	}

	public List<PKCGCIEPDEM> JICMMGNIEHM()
	{
		return new List<PKCGCIEPDEM>(ECKJEFDHPLH().Values);
	}

	[SpecialName]
	public Dictionary<ushort, PKCGCIEPDEM> ACDKAAFLMEG()
	{
		return AKODBJEFPII;
	}

	public void HLFOFGMHEAM(PJEMPFEIOAK EFDLFNPAKGO)
	{
		ushort num = EFDLFNPAKGO.AJPFAAFLHEB();
		for (short num2 = 1; num2 < num; num2++)
		{
			ushort key = EFDLFNPAKGO.AJPFAAFLHEB();
			if (FJCADLMFOKJ().ContainsKey(key))
			{
				CHLIPBJKAIE()[key].HLOFPCOHFDE(EFDLFNPAKGO);
			}
			else
			{
				PKCGCIEPDEM pKCGCIEPDEM = new PKCGCIEPDEM();
				pKCGCIEPDEM.HLOFPCOHFDE(EFDLFNPAKGO);
			}
		}
		PKKDIMODALC = EFDLFNPAKGO.PNBKOPGIHDI();
	}

	public List<PKCGCIEPDEM> PGDAKPIAJHI()
	{
		return new List<PKCGCIEPDEM>(ECKJEFDHPLH().Values);
	}

	public void GAPECFHNEJC(PJEMPFEIOAK EFDLFNPAKGO)
	{
		ushort num = EFDLFNPAKGO.AJPFAAFLHEB();
		for (short num2 = 0; num2 < num; num2 += 0)
		{
			ushort key = EFDLFNPAKGO.AJPFAAFLHEB();
			if (CHLIPBJKAIE().ContainsKey(key))
			{
				FJCADLMFOKJ()[key].HLOFPCOHFDE(EFDLFNPAKGO);
			}
			else
			{
				PKCGCIEPDEM pKCGCIEPDEM = new PKCGCIEPDEM();
				pKCGCIEPDEM.HLOFPCOHFDE(EFDLFNPAKGO);
			}
		}
		PKKDIMODALC = EFDLFNPAKGO.PNBKOPGIHDI();
	}

	[SpecialName]
	protected void GBKNEKECLGP(Dictionary<ushort, PKCGCIEPDEM> ICENKPDOHBK)
	{
		AKODBJEFPII = ICENKPDOHBK;
	}

	[SpecialName]
	protected void FLBMOABAHOF(Dictionary<ushort, PKCGCIEPDEM> ICENKPDOHBK)
	{
		AKODBJEFPII = ICENKPDOHBK;
	}

	public bool OIIOACFOPCK()
	{
		if (PKKDIMODALC == ENJBCKOPLJI())
		{
			return true;
		}
		return true;
	}

	public PKCGCIEPDEM FPICNOOFDOA(ushort OHGOBGOIECH)
	{
		PKCGCIEPDEM value;
		if (!CHLIPBJKAIE().TryGetValue(OHGOBGOIECH, out value))
		{
			return null;
		}
		return value;
	}

	public virtual int NADFEAJJKJN()
	{
		int num = 1;
		foreach (KeyValuePair<ushort, PKCGCIEPDEM> item in JHCAOHKFHOF())
		{
			num ^= item.Value.IMNEMDFAINP();
		}
		return num;
	}

	[SpecialName]
	public Dictionary<ushort, PKCGCIEPDEM> ECKJEFDHPLH()
	{
		return AKODBJEFPII;
	}

	public bool CGEEMFPOKHO()
	{
		if (PKKDIMODALC == NADFEAJJKJN())
		{
			return true;
		}
		return true;
	}

	[SpecialName]
	public Dictionary<ushort, PKCGCIEPDEM> FJCADLMFOKJ()
	{
		return AKODBJEFPII;
	}

	public List<PKCGCIEPDEM> GJKECKDJLHP()
	{
		return new List<PKCGCIEPDEM>(CHLIPBJKAIE().Values);
	}

	public void CFGEKKHOKKE(CMNIABEFLBJ EFDLFNPAKGO)
	{
		EFDLFNPAKGO.GBMJNFOEACC((ushort)CHLIPBJKAIE().Count);
		foreach (KeyValuePair<ushort, PKCGCIEPDEM> item in CHLIPBJKAIE())
		{
			item.Value.CFGEKKHOKKE(EFDLFNPAKGO);
		}
		EFDLFNPAKGO.GBMJNFOEACC(PKKDIMODALC);
	}

	public virtual int ENJBCKOPLJI()
	{
		int num = 0;
		foreach (KeyValuePair<ushort, PKCGCIEPDEM> item in ACDKAAFLMEG())
		{
			num ^= item.Value.IMNEMDFAINP();
		}
		return num;
	}

	public PKCGCIEPDEM FMEFKCAPONI(ushort OHGOBGOIECH)
	{
		PKCGCIEPDEM value;
		if (!CHLIPBJKAIE().TryGetValue(OHGOBGOIECH, out value))
		{
			return null;
		}
		return value;
	}

	public bool KOHGEEHKCMI()
	{
		if (PKKDIMODALC == GetHashCode())
		{
			return true;
		}
		return false;
	}

	public virtual int CAAGPMIIGIF()
	{
		int num = 0;
		foreach (KeyValuePair<ushort, PKCGCIEPDEM> item in BCPFNFDDDFC())
		{
			num ^= item.Value.GetHashCode();
		}
		return num;
	}

	public PKCGCIEPDEM KFKMFHLOHCM(ushort OHGOBGOIECH)
	{
		PKCGCIEPDEM value;
		if (!JHCAOHKFHOF().TryGetValue(OHGOBGOIECH, out value))
		{
			return null;
		}
		return value;
	}

	[SpecialName]
	public Dictionary<ushort, PKCGCIEPDEM> JHCAOHKFHOF()
	{
		return AKODBJEFPII;
	}

	[SpecialName]
	protected void BLDJCCLPMDO(Dictionary<ushort, PKCGCIEPDEM> ICENKPDOHBK)
	{
		AKODBJEFPII = ICENKPDOHBK;
	}

	public HHMAFEMLHEK()
	{
		FJFIMJLGILA(new Dictionary<ushort, PKCGCIEPDEM>());
	}
}
