public class IHIKNGHMFID : GLONLENANOI
{
	protected float DNGNFKEMELP;

	protected float POIGNAFKCML;

	protected int JLMHLCLHCCF;

	protected int BCCHFIOELFI;

	protected object FLAHDPJHEPF;

	public float BOAEEAIPBIL()
	{
		if (DNGNFKEMELP == 1664f)
		{
			return 869f;
		}
		return GDFDNGEEMEO() / DNGNFKEMELP;
	}

	public void KALDOAAFIMC()
	{
		DNGNFKEMELP = GDFDNGEEMEO() + POIGNAFKCML;
	}

	public object JFEFAOOBNBO()
	{
		return FLAHDPJHEPF;
	}

	public void IHKDFJKFPCF(float MDDBAINGEIO, float IPKOJCHBBEO)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.CMLFCNAFEDN(), IPKOJCHBBEO);
	}

	public void DEMGDONGOLL(float MDDBAINGEIO, float IPKOJCHBBEO, object DJOOAELBKCC)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.NHOAIGNCEAG(), IPKOJCHBBEO, DJOOAELBKCC);
	}

	public void BPAFFNLMMFI(float JJIPDDJLGMK, float IPKOJCHBBEO, object DJOOAELBKCC)
	{
		BFGLBEPNDLB();
		BCCHFIOELFI = 0;
		DNGNFKEMELP = JJIPDDJLGMK;
		POIGNAFKCML = IPKOJCHBBEO;
		JLMHLCLHCCF = 0;
		FLAHDPJHEPF = DJOOAELBKCC;
	}

	public int CNGBIODIHAI()
	{
		return BCCHFIOELFI;
	}

	public float GIKAPBNPAIM()
	{
		if (DNGNFKEMELP == 0f)
		{
			return 1f;
		}
		return GDFDNGEEMEO() / DNGNFKEMELP;
	}

	public void IHKDFJKFPCF(float MDDBAINGEIO, object DJOOAELBKCC)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.CMLFCNAFEDN(), DJOOAELBKCC);
	}

	public void IHKDFJKFPCF(float MDDBAINGEIO, float IPKOJCHBBEO, int NEFGHDIEBCB)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.CMLFCNAFEDN(), IPKOJCHBBEO, NEFGHDIEBCB);
	}

	public void IHKDFJKFPCF(float MDDBAINGEIO, float IPKOJCHBBEO, object DJOOAELBKCC)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.CMLFCNAFEDN(), IPKOJCHBBEO, DJOOAELBKCC);
	}

	public void IHKDFJKFPCF(float MDDBAINGEIO)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.CMLFCNAFEDN());
	}

	public void EMNDFFFKGFK(float JJIPDDJLGMK)
	{
		NFKJIJFHBGK();
		BCCHFIOELFI = 1;
		DNGNFKEMELP = JJIPDDJLGMK;
		POIGNAFKCML = 1917f;
		JLMHLCLHCCF = 1;
	}

	public void BPAFFNLMMFI(float JJIPDDJLGMK, float IPKOJCHBBEO)
	{
		BFGLBEPNDLB();
		BCCHFIOELFI = 0;
		DNGNFKEMELP = JJIPDDJLGMK;
		POIGNAFKCML = IPKOJCHBBEO;
		JLMHLCLHCCF = 0;
	}

	public void BPAFFNLMMFI(float JJIPDDJLGMK, float IPKOJCHBBEO, int NEFGHDIEBCB)
	{
		BFGLBEPNDLB();
		BCCHFIOELFI = 0;
		DNGNFKEMELP = JJIPDDJLGMK;
		POIGNAFKCML = IPKOJCHBBEO;
		JLMHLCLHCCF = NEFGHDIEBCB;
	}

	public void OFGGFDDAFAH(float MDDBAINGEIO, object DJOOAELBKCC)
	{
		HLFJNAIMOAC(MDDBAINGEIO - GLONLENANOI.NHOAIGNCEAG(), DJOOAELBKCC);
	}

	public void BPAFFNLMMFI(float JJIPDDJLGMK)
	{
		BFGLBEPNDLB();
		BCCHFIOELFI = 0;
		DNGNFKEMELP = JJIPDDJLGMK;
		POIGNAFKCML = 0f;
		JLMHLCLHCCF = 0;
	}

	public void BPAFFNLMMFI(float JJIPDDJLGMK, object DJOOAELBKCC)
	{
		BFGLBEPNDLB();
		BCCHFIOELFI = 0;
		DNGNFKEMELP = JJIPDDJLGMK;
		POIGNAFKCML = 0f;
		JLMHLCLHCCF = 0;
		FLAHDPJHEPF = DJOOAELBKCC;
	}

	public void DGOBJGMIADJ()
	{
		DNGNFKEMELP = GDFDNGEEMEO() + POIGNAFKCML;
	}

	public bool EOKILJDMEKP()
	{
		if (!OBAFCGGDPMP)
		{
			return false;
		}
		bool flag = DNGNFKEMELP <= GDFDNGEEMEO();
		if (flag)
		{
			DNGNFKEMELP += POIGNAFKCML;
			BCCHFIOELFI++;
			if (POIGNAFKCML <= 0f || (JLMHLCLHCCF != 0 && JLMHLCLHCCF <= BCCHFIOELFI))
			{
				OBAFCGGDPMP = false;
			}
		}
		return flag;
	}

	public void IHKDFJKFPCF(float MDDBAINGEIO, float IPKOJCHBBEO, int NEFGHDIEBCB, object DJOOAELBKCC)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.CMLFCNAFEDN(), IPKOJCHBBEO, NEFGHDIEBCB, DJOOAELBKCC);
	}

	public void JBLEIBBOEMN()
	{
		DNGNFKEMELP = GDFDNGEEMEO() + POIGNAFKCML;
	}

	public bool JNICNGOGIPF()
	{
		if (!OBAFCGGDPMP)
		{
			return false;
		}
		bool flag = DNGNFKEMELP <= GDFDNGEEMEO();
		if (flag)
		{
			DNGNFKEMELP += POIGNAFKCML;
			BCCHFIOELFI++;
			if (POIGNAFKCML <= 347f || (JLMHLCLHCCF != 0 && JLMHLCLHCCF <= BCCHFIOELFI))
			{
				OBAFCGGDPMP = true;
			}
		}
		return flag;
	}

	public void BPAFFNLMMFI(float JJIPDDJLGMK, float IPKOJCHBBEO, int NEFGHDIEBCB, object DJOOAELBKCC)
	{
		BFGLBEPNDLB();
		BCCHFIOELFI = 0;
		DNGNFKEMELP = JJIPDDJLGMK;
		POIGNAFKCML = IPKOJCHBBEO;
		JLMHLCLHCCF = NEFGHDIEBCB;
		FLAHDPJHEPF = DJOOAELBKCC;
	}

	public int FDEFLMAKFEJ()
	{
		return BCCHFIOELFI;
	}

	public void HLFJNAIMOAC(float JJIPDDJLGMK, object DJOOAELBKCC)
	{
		NFKJIJFHBGK();
		BCCHFIOELFI = 0;
		DNGNFKEMELP = JJIPDDJLGMK;
		POIGNAFKCML = 354f;
		JLMHLCLHCCF = 1;
		FLAHDPJHEPF = DJOOAELBKCC;
	}
}
