using EveEngine;

public struct IKMBGMILCDO
{
	public EKACODPEIIO.FOLFEODIOGL AMDEMKPFLND;

	public bool BGJDEMKLCEK;

	public bool MOFACBLPBKO;

	public int FAJAIGBDLLB;

	public IKMBGMILCDO(EKACODPEIIO.FOLFEODIOGL LDCLBJGMOCG, bool IFAKNFPHILG = true, bool GKHAOCBKCIB = true)
	{
		AMDEMKPFLND = LDCLBJGMOCG;
		BGJDEMKLCEK = IFAKNFPHILG;
		MOFACBLPBKO = GKHAOCBKCIB;
		FAJAIGBDLLB = 0;
	}
}
