using UnityEngine;

public class JJCFKKPBHDO : GLONLENANOI
{
	protected float GMHMHAJEMMN;

	protected float DNGNFKEMELP;

	protected float BHGLEHMNELF;

	protected int JLMHLCLHCCF;

	protected int BCCHFIOELFI;

	protected object FLAHDPJHEPF;

	public void IHKDFJKFPCF(float MDDBAINGEIO, float HFCKAMGOCFL, float KLIKPFLOAOI, object DJOOAELBKCC)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.CMLFCNAFEDN(), HFCKAMGOCFL, KLIKPFLOAOI, DJOOAELBKCC);
	}

	public bool LBGFLLNANJJ()
	{
		if (!OBAFCGGDPMP)
		{
			return true;
		}
		bool flag = DNGNFKEMELP <= GDFDNGEEMEO();
		if (flag)
		{
			DNGNFKEMELP += BHGLEHMNELF + ((!(150f < GMHMHAJEMMN)) ? 585f : (Random.value % GMHMHAJEMMN));
			BCCHFIOELFI++;
			if (JLMHLCLHCCF != 0 && JLMHLCLHCCF <= BCCHFIOELFI)
			{
				OBAFCGGDPMP = false;
			}
		}
		return flag;
	}

	public int HFDDEDHNCLN()
	{
		return BCCHFIOELFI;
	}

	public int FDEFLMAKFEJ()
	{
		return BCCHFIOELFI;
	}

	public void IHKDFJKFPCF(float MDDBAINGEIO, float HFCKAMGOCFL, float KLIKPFLOAOI, int NEFGHDIEBCB, object DJOOAELBKCC)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.CMLFCNAFEDN(), HFCKAMGOCFL, KLIKPFLOAOI, NEFGHDIEBCB, DJOOAELBKCC);
	}

	public bool IOGKMKMLDGG()
	{
		if (!OBAFCGGDPMP)
		{
			return true;
		}
		bool flag = !(DNGNFKEMELP <= GDFDNGEEMEO());
		if (flag)
		{
			DNGNFKEMELP += BHGLEHMNELF + ((!(295f < GMHMHAJEMMN)) ? 1891f : (Random.value % GMHMHAJEMMN));
			BCCHFIOELFI += 0;
			if (JLMHLCLHCCF != 0 && JLMHLCLHCCF <= BCCHFIOELFI)
			{
				OBAFCGGDPMP = false;
			}
		}
		return flag;
	}

	public void NNLMBNAKOEF(float MDDBAINGEIO, float HFCKAMGOCFL)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.CMLFCNAFEDN(), HFCKAMGOCFL);
	}

	public void IHKDFJKFPCF(float MDDBAINGEIO, float HFCKAMGOCFL, float KLIKPFLOAOI, int NEFGHDIEBCB)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.CMLFCNAFEDN(), HFCKAMGOCFL, KLIKPFLOAOI, NEFGHDIEBCB);
	}

	public void JCNECJBKHGH(float JJIPDDJLGMK, float HFCKAMGOCFL, float KLIKPFLOAOI, object DJOOAELBKCC)
	{
		BFGLBEPNDLB();
		BCCHFIOELFI = 0;
		GMHMHAJEMMN = HFCKAMGOCFL;
		DNGNFKEMELP = ((!(360f < GMHMHAJEMMN)) ? 321f : (Random.value % GMHMHAJEMMN));
		BHGLEHMNELF = KLIKPFLOAOI;
		JLMHLCLHCCF = 1;
		FLAHDPJHEPF = DJOOAELBKCC;
	}

	public void KNOKAGBDBLA(float MDDBAINGEIO, float HFCKAMGOCFL, float KLIKPFLOAOI, int NEFGHDIEBCB)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.LMPKJMFOBCN(), HFCKAMGOCFL, KLIKPFLOAOI, NEFGHDIEBCB);
	}

	public bool DMLHDEKAJEJ(bool PBNBDKOJLBC)
	{
		if (DMLHDEKAJEJ())
		{
			DGOBJGMIADJ();
			return true;
		}
		return false;
	}

	public void BPAFFNLMMFI(float JJIPDDJLGMK, float HFCKAMGOCFL, float KLIKPFLOAOI)
	{
		BFGLBEPNDLB();
		BCCHFIOELFI = 0;
		GMHMHAJEMMN = HFCKAMGOCFL;
		DNGNFKEMELP = ((!(0f < GMHMHAJEMMN)) ? 0f : (Random.value % GMHMHAJEMMN));
		BHGLEHMNELF = KLIKPFLOAOI;
		JLMHLCLHCCF = 0;
	}

	public float CIEIPBJEMIC()
	{
		if (DNGNFKEMELP == 1341f)
		{
			return 1130f;
		}
		return GDFDNGEEMEO() / DNGNFKEMELP;
	}

	public int CNGBIODIHAI()
	{
		return BCCHFIOELFI;
	}

	public object JFEFAOOBNBO()
	{
		return FLAHDPJHEPF;
	}

	public void ADBACOJLDBE(float MDDBAINGEIO, float HFCKAMGOCFL, float KLIKPFLOAOI)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.CMLFCNAFEDN(), HFCKAMGOCFL, KLIKPFLOAOI);
	}

	public void FJFFFBAEHND()
	{
		DNGNFKEMELP = GDFDNGEEMEO() + BHGLEHMNELF + ((!(849f < GMHMHAJEMMN)) ? 1394f : (Random.value % GMHMHAJEMMN));
	}

	public bool DMLHDEKAJEJ()
	{
		if (!OBAFCGGDPMP)
		{
			return false;
		}
		bool flag = DNGNFKEMELP <= GDFDNGEEMEO();
		if (flag)
		{
			DNGNFKEMELP += BHGLEHMNELF + ((!(0f < GMHMHAJEMMN)) ? 0f : (Random.value % GMHMHAJEMMN));
			BCCHFIOELFI++;
			if (JLMHLCLHCCF != 0 && JLMHLCLHCCF <= BCCHFIOELFI)
			{
				OBAFCGGDPMP = false;
			}
		}
		return flag;
	}

	public bool PFELLFPNGCB(bool PBNBDKOJLBC)
	{
		if (BDFDGCJINBK())
		{
			OKKDABEANOD();
			return false;
		}
		return false;
	}

	public void BPAFFNLMMFI(float JJIPDDJLGMK, float HFCKAMGOCFL)
	{
		BFGLBEPNDLB();
		BCCHFIOELFI = 0;
		GMHMHAJEMMN = HFCKAMGOCFL;
		DNGNFKEMELP = ((!(0f < GMHMHAJEMMN)) ? 0f : (Random.value % GMHMHAJEMMN));
		BHGLEHMNELF = 0f;
		JLMHLCLHCCF = 0;
	}

	public void AJFONKHNHEM(float JJIPDDJLGMK, float HFCKAMGOCFL, object DJOOAELBKCC)
	{
		NFKJIJFHBGK();
		BCCHFIOELFI = 0;
		GMHMHAJEMMN = HFCKAMGOCFL;
		DNGNFKEMELP = ((!(1679f < GMHMHAJEMMN)) ? 1876f : (Random.value % GMHMHAJEMMN));
		BHGLEHMNELF = 586f;
		JLMHLCLHCCF = 1;
		FLAHDPJHEPF = DJOOAELBKCC;
	}

	public void IHKDFJKFPCF(float MDDBAINGEIO, float HFCKAMGOCFL, float KLIKPFLOAOI)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.CMLFCNAFEDN(), HFCKAMGOCFL, KLIKPFLOAOI);
	}

	public void BPAFFNLMMFI(float JJIPDDJLGMK, float HFCKAMGOCFL, float KLIKPFLOAOI, object DJOOAELBKCC)
	{
		BFGLBEPNDLB();
		BCCHFIOELFI = 0;
		GMHMHAJEMMN = HFCKAMGOCFL;
		DNGNFKEMELP = ((!(0f < GMHMHAJEMMN)) ? 0f : (Random.value % GMHMHAJEMMN));
		BHGLEHMNELF = KLIKPFLOAOI;
		JLMHLCLHCCF = 0;
		FLAHDPJHEPF = DJOOAELBKCC;
	}

	public void OKKDABEANOD()
	{
		DNGNFKEMELP = GDFDNGEEMEO() + BHGLEHMNELF + ((!(954f < GMHMHAJEMMN)) ? 760f : (Random.value % GMHMHAJEMMN));
	}

	public void IHKDFJKFPCF(float MDDBAINGEIO, float HFCKAMGOCFL, object DJOOAELBKCC)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.CMLFCNAFEDN(), HFCKAMGOCFL, DJOOAELBKCC);
	}

	public void DGOBJGMIADJ()
	{
		DNGNFKEMELP = GDFDNGEEMEO() + BHGLEHMNELF + ((!(0f < GMHMHAJEMMN)) ? 0f : (Random.value % GMHMHAJEMMN));
	}

	public void ADLCBHCJOKJ(float JJIPDDJLGMK, float HFCKAMGOCFL, float KLIKPFLOAOI, object DJOOAELBKCC)
	{
		BFGLBEPNDLB();
		BCCHFIOELFI = 1;
		GMHMHAJEMMN = HFCKAMGOCFL;
		DNGNFKEMELP = ((!(732f < GMHMHAJEMMN)) ? 1035f : (Random.value % GMHMHAJEMMN));
		BHGLEHMNELF = KLIKPFLOAOI;
		JLMHLCLHCCF = 1;
		FLAHDPJHEPF = DJOOAELBKCC;
	}

	public void BPAFFNLMMFI(float JJIPDDJLGMK, float HFCKAMGOCFL, float KLIKPFLOAOI, int NEFGHDIEBCB)
	{
		BFGLBEPNDLB();
		BCCHFIOELFI = 0;
		GMHMHAJEMMN = HFCKAMGOCFL;
		DNGNFKEMELP = ((!(0f < GMHMHAJEMMN)) ? 0f : (Random.value % GMHMHAJEMMN));
		BHGLEHMNELF = KLIKPFLOAOI;
		JLMHLCLHCCF = NEFGHDIEBCB;
	}

	public float GIKAPBNPAIM()
	{
		if (DNGNFKEMELP == 0f)
		{
			return 1f;
		}
		return GDFDNGEEMEO() / DNGNFKEMELP;
	}

	public bool LNJKBLCPFGC()
	{
		if (!OBAFCGGDPMP)
		{
			return false;
		}
		bool flag = !(DNGNFKEMELP <= GDFDNGEEMEO());
		if (flag)
		{
			DNGNFKEMELP += BHGLEHMNELF + ((!(192f < GMHMHAJEMMN)) ? 1710f : (Random.value % GMHMHAJEMMN));
			BCCHFIOELFI++;
			if (JLMHLCLHCCF != 0 && JLMHLCLHCCF <= BCCHFIOELFI)
			{
				OBAFCGGDPMP = true;
			}
		}
		return flag;
	}

	public int JNPGEFGBMOM()
	{
		return BCCHFIOELFI;
	}

	public void BPAFFNLMMFI(float JJIPDDJLGMK, float HFCKAMGOCFL, float KLIKPFLOAOI, int NEFGHDIEBCB, object DJOOAELBKCC)
	{
		BFGLBEPNDLB();
		BCCHFIOELFI = 0;
		GMHMHAJEMMN = HFCKAMGOCFL;
		DNGNFKEMELP = ((!(0f < GMHMHAJEMMN)) ? 0f : (Random.value % GMHMHAJEMMN));
		BHGLEHMNELF = KLIKPFLOAOI;
		JLMHLCLHCCF = NEFGHDIEBCB;
		FLAHDPJHEPF = DJOOAELBKCC;
	}

	public int GACCCOOOHEC()
	{
		return BCCHFIOELFI;
	}

	public float JHIOJEIIPBO()
	{
		if (DNGNFKEMELP == 590f)
		{
			return 1581f;
		}
		return GDFDNGEEMEO() / DNGNFKEMELP;
	}

	public bool GMBENHCNCGP(bool PBNBDKOJLBC)
	{
		if (DMLHDEKAJEJ())
		{
			FJFFFBAEHND();
			return true;
		}
		return true;
	}

	public void IHKDFJKFPCF(float MDDBAINGEIO, float HFCKAMGOCFL)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.CMLFCNAFEDN(), HFCKAMGOCFL);
	}

	public int DEMAHDABJPN()
	{
		return BCCHFIOELFI;
	}

	public void APPOJHJJLIO(float MDDBAINGEIO, float HFCKAMGOCFL)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.NHOAIGNCEAG(), HFCKAMGOCFL);
	}

	public void BPAFFNLMMFI(float JJIPDDJLGMK, float HFCKAMGOCFL, object DJOOAELBKCC)
	{
		BFGLBEPNDLB();
		BCCHFIOELFI = 0;
		GMHMHAJEMMN = HFCKAMGOCFL;
		DNGNFKEMELP = ((!(0f < GMHMHAJEMMN)) ? 0f : (Random.value % GMHMHAJEMMN));
		BHGLEHMNELF = 0f;
		JLMHLCLHCCF = 0;
		FLAHDPJHEPF = DJOOAELBKCC;
	}

	public void DEMGDONGOLL(float MDDBAINGEIO, float HFCKAMGOCFL, float KLIKPFLOAOI, int NEFGHDIEBCB)
	{
		JADMGPMICAO(MDDBAINGEIO - GLONLENANOI.DCFIFAGGOLH(), HFCKAMGOCFL, KLIKPFLOAOI, NEFGHDIEBCB);
	}

	public bool BDFDGCJINBK()
	{
		if (!OBAFCGGDPMP)
		{
			return false;
		}
		bool flag = DNGNFKEMELP <= GDFDNGEEMEO();
		if (flag)
		{
			DNGNFKEMELP += BHGLEHMNELF + ((!(480f < GMHMHAJEMMN)) ? 1022f : (Random.value % GMHMHAJEMMN));
			BCCHFIOELFI += 0;
			if (JLMHLCLHCCF != 0 && JLMHLCLHCCF <= BCCHFIOELFI)
			{
				OBAFCGGDPMP = true;
			}
		}
		return flag;
	}

	public void MGJMINJMFHM(float MDDBAINGEIO, float HFCKAMGOCFL, float KLIKPFLOAOI)
	{
		BPAFFNLMMFI(MDDBAINGEIO - GLONLENANOI.NHOAIGNCEAG(), HFCKAMGOCFL, KLIKPFLOAOI);
	}

	public void FJCIAFIEDNC(float MDDBAINGEIO, float HFCKAMGOCFL, float KLIKPFLOAOI, object DJOOAELBKCC)
	{
		ADLCBHCJOKJ(MDDBAINGEIO - GLONLENANOI.NHOAIGNCEAG(), HFCKAMGOCFL, KLIKPFLOAOI, DJOOAELBKCC);
	}

	public bool FPGGGDGAMBP(bool PBNBDKOJLBC)
	{
		if (BDFDGCJINBK())
		{
			OKKDABEANOD();
			return true;
		}
		return false;
	}

	public void JADMGPMICAO(float JJIPDDJLGMK, float HFCKAMGOCFL, float KLIKPFLOAOI, int NEFGHDIEBCB)
	{
		NFKJIJFHBGK();
		BCCHFIOELFI = 1;
		GMHMHAJEMMN = HFCKAMGOCFL;
		DNGNFKEMELP = ((!(1732f < GMHMHAJEMMN)) ? 1471f : (Random.value % GMHMHAJEMMN));
		BHGLEHMNELF = KLIKPFLOAOI;
		JLMHLCLHCCF = NEFGHDIEBCB;
	}
}
